### ISSUE TITLE
`git: tags` view

### ISSUE THREAD

**Issue by divmain** [divmain/GitSavvy#10]
- [ ] show all local tags
- [ ] add tag
- [ ] delete tag
- [ ] show tags on remote (?)
- [ ] push tags to remote

**Comment by p3lim** [comment]
I was thinking about tackling this one today, as I use tags quite a bit in my projects.

I wanted to hear with your first though, do you want it to be handled by the menus entirely, or do you want something more like the status window?
Both have their advantages and disadvantages.

**Comment by divmain** [comment]
I was thinking something similar to the status view.  I like the way I can interact with stashes in the command view, and I imagine it'd be a similar productivity boost here.  Basically `git: tag` palette command takes you to the TAGS view.  Does that sound reasonable?

**Comment by p3lim** [comment]
I agree on using a view for this, but I'm still going to implement some quick commands for the menu as well (just like with commit there is quick commit).

I don't mind the work that is required by this, I'm really enjoying Python so far, fantastic language.

**Comment by divmain** [comment]
:+1:

**Comment by divmain** [comment]
Closed by #80.
