### ISSUE TITLE
Remote branches in the branch view

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#100]
In commit 985fc6260e83b4e149ceef34286bbf9f3317580e you changed the method used to delete remote branches. Instead of deleting them on the remote, you're only allowing the user to delete the tracking of the remote branch, not actually deleting the branch.

Depending on what you'd want to do with this, you have two options:

1. If you intend to _not_ delete remote branches, don't show them at all (unless tracking).
2. If you _do_ intend to delete remote branches, revert the commit listed above and rather execute `git branch -dr remote/branch` if the `push` failed because the remote branch didn't exist.

**Comment by divmain** [comment]
I should have tested this better.  I'm going to revert to the previous behavior for now, since the user will be notified that the push failed, and they can fetch to update the branch list.

**Comment by p3lim** [comment]
The fetch command from GitSavvy doesn't prune, I suggest either adding one that does or simply add pruning to the existing one.

**Comment by p3lim** [comment]
Also, adding a fetch keybinding to the branch view wouldn't hurt :smiley:
