### ISSUE TITLE
Can't close COMMIT view

### ISSUE THREAD

**Issue by Drllap** [divmain/GitSavvy#1009]
Sublime Text V 3.1.1 Build 3176
git version 2.14.1.windows.1
Windows 10
No error in the console

1. Open Status dashboard
2. Add file to stage with "s"
3. Open COMMIT tab with "c"
4. Press "ctrl + w" to close the tab, nothing happens.

If open up the console and enable logging I can see that gs_commit_view_close is called but the view doesn't close.

This bug started after Gitsavvy was updated on my pc just now.

**Comment by randy3k** [comment]
try restarting sublime text to see if it helps.

**Comment by Drllap** [comment]
Just found this, #995. Restarted and it is fixed

**Comment by randy3k** [comment]
awesome.
