### ISSUE TITLE
Pull Current Branch

### ISSUE THREAD

**Issue by thechinnster** [divmain/GitSavvy#101]
Pulling the current branch is rather difficult now since it requires three separate steps: pull, choose remote from menu, choose branch from menu. Since the git default for Pull is to pull the current branch it would be nice to have a single command for this in GitSavvy.

**Comment by divmain** [comment]
I'd consider adding this.  The remote and branch should be preselected, which means:

1. open palette
2. start typing "git pull"
3. press enter - enter - enter

Do you find this is too much interaction anyway?

**Comment by thechinnster** [comment]
Having defaults pre-selected for origin remote and current branch would be much better and would be totally acceptable as far as I'm concerned. It was the selection of remote and branch that was making it onerous.

**Comment by divmain** [comment]
@thechinnster, I'm realizing that `origin` may not be pre-selected for remotes (I will definitely fix that), but the branch name should be pre-selected for sure.  Are you not seeing pre-selection for branch?

**Comment by divmain** [comment]
@thechinnster, a fix for this will be in the next release.  For `git: pull`, `git: fetch`, and `git: push ...` commands, the most recently used remote for that repo will be pre-selected.  If one of those commands had not previously been run (and remote selected), `origin` will be pre-selected.

**Comment by thechinnster** [comment]
I never noticed that the branch was being preselected, because it was not appearing at the top of the dropdown and the selected item background color is fairly subtle for me. Now I know this will be much easier for me to use.

**Comment by divmain** [comment]
Sounds good.  Until a recent dev release of ST3, the item would be pre-selected, but it wouldn't scroll down to the selection in the quick panel.  If you use latest ST3, that should no longer be an issue.  In any case, the behavior should be more intuitive now than it was.  Thanks for reaching out!

**Comment by Demetrio92** [comment]
Reviving an old thread. Actions has a quick "push" button with just one single key-stroke `p`. Even though, pushing in git is as complex as pulling. Why can't we have another action key for `git pull` whatever user's config would do. 

_Just in case: I'm talking about the `STATUS:` dashboard here._

**Comment by kaste** [comment]
Yeah, we're running out of keys here though.  So either we're going super-savvy for example introduce double-strokes like `[p][p] push   [p][l] for pull` (very fast, very nerdy), or we may open an additonal menu on `[enter]` similar to what we do in the `Repo History`. 🤷
