### ISSUE TITLE
`"prompt_on_abort_commit": false` broken

### ISSUE THREAD

**Issue by kaste** [divmain/GitSavvy#1055]
With the following settings

```
  "prompt_on_abort_commit": false,
  "commit_on_close": false,  # this is also the default
```

* Make a change
* Open status dashboard, `C` to commit changes

- Commit view opens with empty message
- Press `ctrl+w`, nothing happens

* Enter a message for the commit
* Press `ctrl+w`, nothing happens

Pressing the `x` button on the tab or in the sidebar works.

Regression from #970

**Comment by randy3k** [comment]
a related PR is working on this matter #1016
