### ISSUE TITLE
Performance regression for commit view

### ISSUE THREAD

**Issue by kaste** [divmain/GitSavvy#1060]
This is a typical workflow, just on a big repo. Edit file, open status dashboard, (s)tage file, enter (c)ommit view, enter message and commit. (All git status calls are super expensive, and we have probably to much of them, but #1033 reduces some of them.)

A huge problem though is the commit dry-run. I don't think this is strictly necessary, especially if we run (the much faster) git diff after that. If the diff returns empty, there is nothing staged. And we can just tell the user. 

```
 [4168ms] $ git status -b --porcelain
 [3477ms] $ git status --porcelain -z
 [ 78ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [142ms] $ git stash list
 [3473ms] $ git status -b --porcelain
 [3556ms] $ git status -b --porcelain
 [585ms] $ git add --all -- README.md                    # <= adding the file
 [3519ms] $ git status --porcelain -z
 [ 96ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [109ms] $ git stash list
 [3514ms] $ git status -b --porcelain
 [3701ms] $ git status -b --porcelain
 [10831ms] $ git commit -q --dry-run                     # <= new dry-run, why?
 [214ms] $ git diff --no-color --patch --stat --cached   # <= pretty fast diff 
 [3498ms] $ git status -b --porcelain
 [3346ms] $ git status -b --porcelain
 [ 94ms] $ git config commit.cleanup                     # ?
 [3209ms] $ git commit -q --cleanup=strip -F -           # <= actual commit
 [3477ms] $ git status --porcelain -z
 [ 93ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [125ms] $ git stash list
 [3471ms] $ git status -b --porcelain
 [3500ms] $ git status -b --porcelain
 [3555ms] $ git status --porcelain -z
 [102ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [125ms] $ git stash list
 [3372ms] $ git status -b --porcelain
 [3641ms] $ git status -b --porcelain
```

The same on the tiny GitSavvy repo.

```
 [ 97ms] $ git status -b --porcelain
 [113ms] $ git status --porcelain -z
 [ 78ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [126ms] $ git stash list
 [ 94ms] $ git status -b --porcelain
 [103ms] $ git status -b --porcelain
 [109ms] $ git add --all -- README.md                      # actual add
 [ 98ms] $ git status --porcelain -z
 [ 94ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [146ms] $ git stash list
 [ 95ms] $ git status -b --porcelain
 [109ms] $ git status -b --porcelain
 [120ms] $ git commit -q --dry-run                         # <= dry-run still slower
 [ 94ms] $ git diff --no-color --patch --stat --cached     # <= than the diff
 [100ms] $ git status -b --porcelain
 [ 94ms] $ git status -b --porcelain
 [ 94ms] $ git config commit.cleanup                       # <= too slow!
 [151ms] $ git commit -q --cleanup=strip -F -              # actual commit
 [109ms] $ git status --porcelain -z
 [ 94ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [138ms] $ git stash list
 [101ms] $ git status -b --porcelain
 [101ms] $ git status -b --porcelain
 [109ms] $ git status --porcelain -z
 [ 94ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [149ms] $ git stash list
 [104ms] $ git status -b --porcelain
 [127ms] $ git status -b --porcelain
```

Our performance budget to respond to an user action is *~100ms*. On the tiny repo, you can see that the sole `git diff` (after that the commit view is ready to type in) uses `94ms`. But with the dry-run we use more than `200ms` which is already is noticable disturbing. 

In the commit phase, the minimal necessary `git commit` takes `150ms` but if you then add the `git config` call you're at `250ms`. 

As you can see, we quickly run out of budget even with the minimal commands we have to do. If we then add calls on top of that, it begins to feel slow.

**Comment by asfaltboy** [comment]
Thanks @kaste , this ties nicely into the improvements you started in `git status`. IMHO we should make use of more memoization, e.g `git config` calls should definitely be cached in such a short interval.

Btw what OS are you on? The performance of your git calls is way slower than I expect

**Comment by kaste** [comment]
This is from a Windows laptop. What numbers do you get on the GitSavvy repo? 

I used this for logging

```diff
diff --git a/common/util/debug.py b/common/util/debug.py
index 7ba51dab..4b9f6b96 100644
--- a/common/util/debug.py
+++ b/common/util/debug.py
@@ -1,6 +1,7 @@
 import functools
 import json
 import pprint as _pprint
+from textwrap import indent
 
 from contextlib import contextmanager
 
@@ -61,6 +62,11 @@ def log_git(command, stdin, stdout, stderr, seconds):
     for field in ['stdin', 'stdout', 'stderr']:
         if isinstance(locals()[field], bytes):  # decode standard I/O bytes
             message[field] = try_to_decode(locals()[field], field)
+    print(' [{runtime:3.0f}ms] $ {cmd}\n{stdout}'.format(
+        cmd=' '.join(['git'] + [arg for arg in command if arg is not None]),
+        runtime=seconds * 1000,
+        stdout=indent(stdout.rstrip(), '  ')
+    ))
     add_to_log(message)
```

**Comment by asfaltboy** [comment]
This is my timing on my Macbook Pro, on GitSavvy (using master):
```
Entering commig:

 [ 16ms] $ git status -b --porcelain
 [ 21ms] $ git diff --no-color --patch --stat --cached
 [ 13ms] $ git status -b --porcelain
 [ 13ms] $ git status -b --porcelain

Commit DO:
 [ 19ms] $ git status -b --porcelain
 [ 40ms] $ git commit -q -F -
 [ 17ms] $ git status --porcelain -z
 [ 15ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [ 15ms] $ git status -b --porcelain
 [ 18ms] $ git status -b --porcelain
 [ 13ms] $ git status --porcelain -z
 [ 12ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [ 16ms] $ git status -b --porcelain
 [ 16ms] $ git status -b --porcelain

And here's the same Commit DO on develop branch:

 [ 14ms] $ git status -b --porcelain
 [ 11ms] $ git config commit.cleanup
 [ 42ms] $ git commit -q --cleanup=strip -F -
 [ 16ms] $ git status --porcelain -z
 [ 15ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [ 17ms] $ git status -b --porcelain
 [ 16ms] $ git status -b --porcelain
 [ 14ms] $ git status --porcelain -z
 [ 15ms] $ git log -n 1 --pretty=format:%h %s --abbrev-commit
 [ 14ms] $ git status -b --porcelain
 [ 16ms] $ git status -b --porcelain
```

Even though I don't see the `git commit -q --dry-run` call you mention, we definitely have way too many calls for seemingly just one execution command (`git commit`), and I vote we prioritise this.

I can now see why Windows users would find GitSavvy nearly unusable. Unfortunately, I'm not aware of any trick to improve git performance on Window, besides following on latest updates to Git for windows.

If performance on windows is not easily fixable with "git for windows", the next step would be to try to use a lib instead of calling processes, e.g: https://github.com/libgit2/pygit2

Refs:
- https://blogs.msdn.microsoft.com/devops/2018/01/11/microsofts-performance-contributions-to-git-in-2017/
- https://blog.praveen.science/solution-to-git-bash-is-very-slow-in-windows/
- https://blog.entelect.co.za/view/7554/speed-up-git-bash-on-windows
- https://github.com/Vigorpush/git-speedup

**Comment by kaste** [comment]
`git commit -q --dry-run` runs in the prepare phase before the view opens iirc.

**Comment by asfaltboy** [comment]
Thanks @kaste have you tried to go through the above suggested fixed for windows?

**Comment by kaste** [comment]
Most of these 'fixes' are on by default. 

This is an issue with GitSavvy. When we do a `git status` we already know if we have staged files, we don't need the dry-run. When we also run `git diff`, we really, really know that we have nothing staged if it returns empty. We could also just tell the user 'Nothing staged' instead of throwing. (We didn't throw before this summer.) I think this is bad UX. 

Also for example if we *really need* to ask `git config` (which I doubt), we could do this in the background while the user is typing the commit message.

**Comment by asfaltboy** [comment]
Thanks again Kaste! To clarify, I don't disagree that we need to stop over-calling git, and I do appreciate the work you are investing in the project! I was merely attempting to help you reduce the git call lag on windows as it seems to differ vastly from what I expected, but then again maybe that's just the best we can do?

**Comment by kaste** [comment]
Afaik we reverted most commits introducing this in 2.18.0. The too-many-`status`-calls must be tackled somewhere else.
