### ISSUE TITLE
Diff: Allow adding split hunks

### ISSUE THREAD

**Issue by nh2** [divmain/GitSavvy#1065]
Right now, the `git: diff` action allows adding whole hunks in the vain of `git add --patch`.

`git add --patch` allows splitting large hunks by pressing `s` when at the `Stage this hunk` prompt:

```
Stage this hunk [y,n,q,a,d,K,g,/,s,e,?]? ?
y - stage this hunk
n - do not stage this hunk
q - quit; do not stage this hunk or any of the remaining ones
a - stage this hunk and all later hunks in the file
d - do not stage this hunk or any of the later hunks in the file
g - select a hunk to go to
/ - search for a hunk matching the given regex
K - leave this hunk undecided, see previous hunk
s - split the current hunk into smaller hunks
e - manually edit the current hunk
? - print help
```

`s - split the current hunk into smaller hunks`.

This is possible when there are some unchanged lines between the `+`/-`-prefixed lines in a hunk. Then you can stage the two things independently.

It would be great if GitSavvy could support adding small hunks.

One may even argue that adding small hunks should be the default for an interactive tool like `git: diff`. It is simply not the default in the `git add --patch` terminal UI to make it possible to jump more quickly over things you don't want to stage. But in GitSavvy's `git: diff` view, this tradeoff isn't necessary, because we can just scroll down.

**Comment by kaste** [comment]
I actually wanted to implement line based staging/unstaging just like in git GUI. I often wish I had *wider* hunks (more context lines) though.

**Comment by stoivo** [comment]
Have you tried https://github.com/divmain/GitSavvy#highlights the inline diff. It is very good for that work.

**Comment by nh2** [comment]
> Have you tried https://github.com/divmain/GitSavvy#highlights the inline diff. It is very good for that work.

Yes, that is indeed pleasant to use, but it only shows a single file (and all of it), not all the changes across all files (and skipping unchanged bits); for that the simple `git: diff` view is _much_ faster to work with, especially because you can scroll around all changes quickly.

It'd be cool if I could just press `l` in that view to stage a `+` or `-` line, just like I can press `l` in the other view for that.

(By the way, pressing `L` to unstage doesn't seem to work for me even in the inline diff.)

**Comment by kaste** [comment]
FWIW, the non-trivial part here is to have a stable, meaningful cursor position after such a command. 

We can implement `[+]` and `[-]` to zoom. But when you get the new diff, a) the hunk count probably has changed, b) the hunk headers (`@@ 13,7...`) will change. c) Even the actual line the user was on can just disappear (e.g. the user was on a context line, and you reduce the context width).
