### ISSUE TITLE
Two navigation issues of the diff view [2.18.0]

### ISSUE THREAD

**Issue by randy3k** [divmain/GitSavvy#1074]
I have been testing with the next release (2.18.0) branch and note that there are two minor navigation issues of the new diff view.

![ezgif-1-59060baee699](https://user-images.githubusercontent.com/1690993/50496086-72dc6b00-09fb-11e9-8a24-7ed5338c89cc.gif)

1. Just note that when `cmd+enter` was hit over the first hunk, the cursor jumps to the third hunk rather to the second hunk.

2. When `tab` was hit to enter the cached diff, the cursor was not positioned at at the first hunk.

cc: @kaste

**Comment by kaste** [comment]
ACK

For 2, this is basically under-specced. Here, you switch to the 'unstaged area' for the first time, so we could at least jump to the first hunk. If you just 'tab, tab, tab' after that, it probably works already in that the cursors stays where it was before. Should it instead jump to last added hunk?

**Comment by kaste** [comment]
Close it!

**Comment by randy3k** [comment]
Thanks for the heads up.
