### ISSUE TITLE
Allow user to set a custom syntax for making commits

### ISSUE THREAD

**Issue by yyyc514** [divmain/GitSavvy#108]
This would allow a lot more flexibility and integration with packages like https://packagecontrol.io/packages/Git%20Commit%20Message%20Syntax.  We don't need to necessarily own the syntax file for making commits (unless we really want to, in which case we could merge in a more thorough syntax).

This goes right along with request #107 and relates to #41.

**Comment by yyyc514** [comment]
https://github.com/divmain/GitSavvy/pull/119

**Comment by yyyc514** [comment]
I could also break it out, but it's not much use without a more "typical" commit message (that includes summary, etc).

**Comment by divmain** [comment]
We can capture the work/issues as part of #41.  Closing.
