### ISSUE TITLE
git commit should use -a rather than calling add_all_tracked_files

### ISSUE THREAD

**Issue by yyyc514** [divmain/GitSavvy#109]
I'm not sure why we wouldn't use the built in option to `commit` to stage modified/deleted files.  Doing it manually can results in a weird error case.  If the add should happen but the commit should fail for some reason now your tree is in a state you may not expect... just passing `-a` to commit makes commit a wholly atomic operation.  It succeeds or fails completely, there is not in-between state possible.

**Comment by yyyc514** [comment]
This relate to #107 since the idea is to show what would happen... asking `git commit -a` can show us what would happen easily without the need to actually stage the files.  Of course this isn't a requirement for 107, but it's the context that caused me to stumble across this.

**Comment by yyyc514** [comment]
Adding this to #107 since it was super easy and builds on what I already started.

**Comment by yyyc514** [comment]
Sorry, I mean https://github.com/divmain/GitSavvy/pull/111

**Comment by divmain** [comment]
Can you do this as a separate PR?  There are still some things to work through for #111, and I'd like to keep it to one PR per issue (the `-a` change itself is fine, and I'll merge it as soon as the PR is ready)

**Comment by yyyc514** [comment]
#124

**Comment by yyyc514** [comment]
Closing discussion in favor of PR.

**Comment by divmain** [comment]
Closed by #124.  @yyyc514, in the future, please leave the issue open until the PR is closed.  I track all pending work in issues.

**Comment by yyyc514** [comment]
Ok.  Sorry.

**Comment by divmain** [comment]
No worries @yyyc514 :)  Just want to make sure I don't lose track of anything!
