### ISSUE TITLE
[dev] branch status badge no long is shown when there are no views

### ISSUE THREAD

**Issue by randy3k** [divmain/GitSavvy#1099]
`git bisect` reveals that the first bad commit is 41387cc069b0eb33d888564267cb73fdcf36bb61

cc @kaste

**Comment by randy3k** [comment]
master

![screen shot 2019-02-11 at 11 11 47 am](https://user-images.githubusercontent.com/1690993/52576309-d674f900-2ded-11e9-96a9-1546efd96b72.png)

dev

![screen shot 2019-02-11 at 11 12 14 am](https://user-images.githubusercontent.com/1690993/52576371-e987c900-2ded-11e9-9eb3-41304c932a0d.png)

**Comment by randy3k** [comment]
fixed by #1101

**Comment by kaste** [comment]
Do not forget that this is initially a regression from #985. #1083 is a fixup for #985. And now #1101 is a fixup for #1083.
