### ISSUE TITLE
`git: cherry pick`

### ISSUE THREAD

**Issue by divmain** [divmain/GitSavvy#11]

**Comment by yyyc514** [comment]
How would this work?  Would you get a list or be presented with a list in a view and then have to choose commits individually as a separate action?

**Comment by stoivo** [comment]
What about having it in the Branch History comparison
We can add it here. The time when I want to cherry pick is when I want only one commit from one branch over in my branch
![](http://puu.sh/iJSC2/b479d98d21.png)

**Comment by asfaltboy** [comment]
Yes please :+1: , this would be nice to have! We can add a base command that accepts a commit hash as argument, and when none provided displays commits (`log`) from all branches (`--branches`) sorted by timestamp (`--date-order`). Then we can call on this command from useful UI commands; such as branch history, mentioned above or maybe graph.

**Comment by divmain** [comment]
I like your idea @stoivo - the only thing is that commands are difficult to discover within the context of a view like this (without keymaps like in the dashboards).  I think the base case would be to prompt for the hash, as @asfaltboy said.  I'm definitely willing to entertain integrating this into the branch history view, if we can identify the right UX.

**Comment by divmain** [comment]
Alright - new idea here.  We use `CMD+Enter` / `CTRL-Enter` in lots of these views to activate special functionality.  In this case, using this key combination when a particular commit is selected would pop up a menu with the following options:

- view commit (resulting in same behavior as selection in `git: log`)
- cherry commit into current branch (new behavior)
- checkout commit (resulting in detached HEAD)

Thoughts @asfaltboy @stoivo?

**Comment by asfaltboy** [comment]
I like it! This will allow more actions on commits, or even hook into custom commands, if they (optionally) accept a commit hash as argument.


Only thing that I would consider is in a log view, where `Enter` is already mapped to log view, maybe omit view commit from context menu item?





Best regards,
Pavel Savchenko

**Comment by stoivo** [comment]
:+1:

**Comment by divmain** [comment]
@asfaltboy, I think it'd be good to include (discoverability is good!), but it can be the last option listed.  @stoivo, since you originally put together the branch history comparison view, do you want to take this on?

**Comment by stoivo** [comment]
Yes, I can do it. But I don't that much time now and the next week.

So if there are no deadline I will take this one :)

**Comment by divmain** [comment]
@stoivo, this probably went off your radar.  You still interested in adding this functionality?

**Comment by stoivo** [comment]
oh, I will do it as next task.

**Comment by divmain** [comment]
:+1:
