### ISSUE TITLE
Support git push --set-upstream

### ISSUE THREAD

**Issue by yyyc514** [divmain/GitSavvy#112]
We should support:

`git push --set-upstream origin feature/show_commit_summary`

Is there some way to do this already that I'm missing?

**Comment by yyyc514** [comment]
Maybe we could overload the remote selection by having options for both the remote and remote (set upstream)?

```
yours
upstream
yours (set upstream)
upstream (set upstream)
```

**Comment by p3lim** [comment]
Take a look at the global_flags option.

**Comment by divmain** [comment]
Thanks @p3lim.  @yyyc514, yes this is the intended use case for `global_flags`; namely, customization of frequently used Git commands that not everyone will agree on (without adding palette commands for everything).

**Comment by yyyc514** [comment]
I'm just trying to get all the way thru a full github PR workflow:

```
git co -b fix/terrible_bug
git commit
git push --set-upstream origin fix/terrible_bug
hub pull-request
```

The last part might not be really inside the scope of GitSavvy but it seems pushing with set upstream or tracking should be, no?

**Comment by yyyc514** [comment]
I guess the --set-upstream technically isn't required if you're typing it out overtime, hmmm.

**Comment by yyyc514** [comment]
How is everyone else doing this right now the first time? (to setup tracking branches properly)

**Comment by divmain** [comment]
Hmm, I'm reconsidering this now.  I don't want a ton of palette commands if we can avoid it, and the `--set-upstream` flag could have unexpected consequences if the user didn't realize that's what was happening under the hood.

Perhaps a good approach would be to add this functionality to the branch dashboard.  Right now, the `[t] configure tracking` just allows the user to select from known remote branches.  The way this works makes for great UX, except in cases where the remote branch does not yet exist.  So either:

1.  We change `[t] configure tracking` to prompt for a branch name in the quick input instead of the panel, or
2.  We add an additional command that is something explicit along the lines of `[u] push selected and set upstream`

Thoughts @yyyc514 @p3lim?

**Comment by p3lim** [comment]
I suck at UX, so I really shouldn't get a voice in this matter.

**Comment by yyyc514** [comment]
> We add an additional command that is something explicit along the lines of [u] push selected and set upstream.

Not opposed to this but why don't we consider this an error condition of a normal push and handle it well?

- "git: push" (which is what my brain wants to do anyways)
- git throws "please add upstream error"
- present a menu of choices
- abort, push to named branch, push to existing, push (--set-upstream)

Abort would stop.  The other two would call out into our existing commands... and push up-stream would try again except adding set-upstream.

**Comment by p3lim** [comment]
When using `git: push to branch name` there is an input displayed where we can enter the branch name.
What about allowing additional arguments filled in there? Would probably be the best UX implementation for power users.

**Comment by divmain** [comment]
That's a solid idea @p3lim.  So a combination of what you and @yyyc514 suggested:

- open command palette, `git: push to branch name`
- select remote
- enter branch name pre-filled with local branch name
- Yes/No dialog asking whether to set the remote branch as upstream

The first three points are already implemented - the last bullet point should be very simple to add.

**Comment by p3lim** [comment]
Make sure it only asks if the remote branch isn't already upstream tho.

**Comment by yyyc514** [comment]
> Make sure it only asks if the remote branch isn't already upstream tho.

That's why I'm interesting in just fixing "push"... I'd like to only think of push when I'm on a branch and then if an edge case comes up (first push) I'm informed and can decide what to do.

**Comment by yyyc514** [comment]
I'll play around with some things when I'm done working on some other stuff.

**Comment by divmain** [comment]
Alright, you have me convinced :)  Just added this now.  It'll be optional, for those who just want to rely on the default behavior of `git push`.  I also chose not to rely on Git's behavior when upstream is not set, as this behavior varies depending on Git version (and I'd like the GitSavvy UX to be consistent and independent of underlying Git version where possible).

**Comment by yyyc514** [comment]
Awesome.  So far this is working really well.  Now we just need PR support and I could get thru a full development cycle with GitSavvy.
