### ISSUE TITLE
NeoVintageous friendly mode not working

### ISSUE THREAD

**Issue by robbernabe** [divmain/GitSavvy#1122]
It doesn't seem that the friendly mode for NeoVintageous is working.  The following two related issues lead me to believe they should: #565 and #887.  When the status window opens, I am not dropped automatically into insert mode to type commands.

- Sublime Text version number: 3.1.1, Build 3176
- Git version number: 2.20.1
- OS type and version: macOS 10.14.3
- steps to repro: run the git status command, status window opens, I am not entered into insert mode to enter git commands automatically

**Comment by asfaltboy** [comment]
Hi @robbernabe do you have these 2 GitSavvy settings enabled?
```
    "vintageous_friendly": true,
    "vintageous_enter_insert_mode": true,
```

They're both false by default. Maybe we should consider changing the default for the benefit of vim mode users.

**Comment by robbernabe** [comment]
Thanks for the quick response.  I do have them set in my user settings:

```
	"vintageous_enter_insert_mode": true,
	"vintageous_friendly": true,
```

That's what's odd.  I tried restarting Sublime as well, no go. Any way I can debug this?

**Comment by asfaltboy** [comment]
Odd, few more questions for you:

- Which version of GitSavvy are you on? (master is on latest v2.18)
- Do you see anything in the sublime console output (<kbd>ctrl+`</kbd>) ?
- How about [the debug log][1]?

Fyi: I just tried out the functionality on dev and master branches and it works for me 😕...

[1]: https://github.com/divmain/GitSavvy/blob/master/docs/debug.md#providing-a-debug-log

**Comment by robbernabe** [comment]
Thanks for the help here @asfaltboy.  I just rebooted my Mac and now its magically working.  So sorry to waste your time.

**Comment by asfaltboy** [comment]
😮 😆 - no time wasted buddy, glad it worked !
