### ISSUE TITLE
git-lfs command not found

### ISSUE THREAD

**Issue by faelin** [divmain/GitSavvy#1123]
Opening/navigating to any file from a particular BitBucket git repo causes a Sublime console window to appear that says:
```
`/usr/local/bin/git status --porcelain -z -b` failed with following output:

git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly
```

This happens for certain repos from a BitBucket corporate accounts on local servers, from within a corporate WAN. Experimentation with PackageControl to enable/disable packages has confirmed that GitSavvy is the culprit! Additionally, I had been using GitSavvy for many months without encountering this issue.

The console window (re)appears anytime I view/open/navigate to a file from a git repo owned by this corporation, though a more recently created repo within the same BitBucket corporate domain does NOT cause the console window to trigger. However, when I manually click the "show console" button in the View menu, then a _different_ console window appears that contains no error message from GitSavvy!

NOTE: my current Sublime settings cause the file to reload whenever I change focus onto it in the Sublime UI, thus (presumably) the reappearance of the console window.

- Sublime Text version number: 3.1.1, Build 3176
- Git version number: git version 2.17.1
- OS type and version: MasOS Mojave, version 10.14.3
- Console error output: NOTHING APPEARS TO BE LOGGED IN THE CONSOLE ABOUT THIS PROBLEM
- GitSavvy Debug Log: after enabling the log, triggering the error state, and disabling the log, the log shows only the text `[]` and nothing else!

**Comment by kaste** [comment]
Already a week old so: could you solve this already?

*Just* from reading this it is unlikely to be an issue with how we do things in GitSavvy. Have you tried the above command on the command line? Is this actually a regression we introduced this year?

I would have to do a deep google search but I'm pretty sure I saw that exact error (on the CLI though) plus McMojave but ... I just don't remember anymore.

**Comment by stoivo** [comment]
https://github.com/divmain/GitSavvy/blob/master/docs/debug.md#other-tools--path-issues--different-behavior-from-terminal-and-inside-sublime

**Comment by stoivo** [comment]
Feel free to reopen
