### ISSUE TITLE
SSL certificate problem: self signed certificate

### ISSUE THREAD

**Issue by ncatenacci** [divmain/GitSavvy#1128]
Hello,

I am unable to use our on-prem Git repo with a self signed certificate with GitSavvy and Sublime Text 3.  Normally, I would ignore the certificate if running Git from the CLI:

`git -c http.sslVerify=false push origin master`

Is there an option in GitSavvy settings to configure that?

Thanks.

**Comment by kaste** [comment]
Hi @ncatenacci!

You can look at this setting

https://github.com/divmain/GitSavvy/blob/817a740bdca59923f5bf767b126c032106c4af5f/GitSavvy.sublime-settings#L208-L215

**Comment by ncatenacci** [comment]
Thank you!  That worked.
