### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by jasondmoss** [divmain/GitSavvy#1155]
Not a bug, but a noted deprecation warning from the Sublime console:

**Sublime Text:** Dev Channel, Build 3208
**Git Version:** 2.21.0
**OS:** Fedora release 30 (Thirty)
**Console:**
`... /sublime-text-3/Installed Packages/GitSavvy.sublime-package/common/util/file.py:29: YAMLLoadWarning: calling yaml.load() without Loader=`... is deprecated, as the default Loader is unsafe. Please read [https://msg.pyyaml.org/load](https://msg.pyyaml.org/load) for full details.

**Comment by kaste** [comment]
Thanks, #1152 should fix this.

**Comment by jasondmoss** [comment]
Fantastic!  Thanks for the quick response  (:
