### ISSUE TITLE
Discuss: @async decorator

### ISSUE THREAD

**Issue by yyyc514** [divmain/GitSavvy#122]
```
class GsBranchesCheckoutCommand(TextCommand, GitCommand):

    @async
    def run(self, edit):
        ...
```

```
def async(run):
    def async_run(self, *args, **kwargs):
        sublime.set_timeout_async(lambda: run(self, *args, **kwargs), 0)
    return async_run
```

Objections?  Seems like a perfect use case or am I missing something?

**Comment by divmain** [comment]
I had the same thought but deliberately kept it explicit, mostly to avoid any ambiguity regarding the life-cycle of `edit` objects.  I'll stick with the current approach for now, since it keeps things cleaner when I am running down bugs.

**Comment by yyyc514** [comment]
> I had the same thought but deliberately kept it explicit, mostly to avoid any ambiguity regarding the life-cycle of edit objects.

Huh?  In all cases where it's hard-coded now `run` always calls `async_run`... how would it not be a huge clean up to just add the decorator to make that 100% clear?  If you're debugging it's just as easy to comment one line as to comment 2 (to let the run fall thru into run_async.  Am I missing something here?
