### ISSUE TITLE
textwrap.dedent

### ISSUE THREAD

**Issue by yyyc514** [divmain/GitSavvy#125]
Use this instead of the manual dedent counts?

https://docs.python.org/2/library/textwrap.html

```
    template = """\

      BRANCH:  {branch_status}
      ROOT:    {git_root}
```

```
# inside init
        for attr in vars(self.__class__).keys():
            if attr.startswith("template"):
            	textwrap.dedent(attr)
```

With \ to auto remove the first line I think maybe that `skip_first_line` could also be tossed?

**Comment by divmain** [comment]
Good call.  I discarded `dedent` early on for some reason.  But I can't remember why, and it cleans things up very nicely.
