### ISSUE TITLE
Hide .tmLanugages

### ISSUE THREAD

**Issue by JustinAiken** [divmain/GitSavvy#134]
Sublime Text 3 3080 just came out with this new setting:
> .tmLanguage files may contain a hidden setting, to indicate they shouldn't be displayed to the user

I'm not sure if that's the same thing as the `.hidden-tmLanguage` extension it talks about [here](http://docs.sublimetext.info/en/latest/reference/syntaxdefs.html#file-format) or not, but it would be nice if pulling up the command palette and typing `GitSa` didn't pull up a bunch of stuff like `Set Syntax: GitSavvy Graph`

If possible... no biggie if not - having a few extra things in the command palette is a small price to pay for how useful this thing is! :+1:

**Comment by divmain** [comment]
Thanks for the heads-up!  I'll take a look at this...

**Comment by divmain** [comment]
Seems to work fine.  Will be in next release.

**Comment by JustinAiken** [comment]
Thanks! :+1:
