### ISSUE TITLE
How to tell GitSavvy to forget git repository?

### ISSUE THREAD

**Issue by freexo** [divmain/GitSavvy#137]
When you delete git repository (delete .git folder) GitSavvy will start bugging you with the following message:

`It looks like you haven't initialized Git in this directory.  Would you like to?`

You can't do anything until you hit "OK". I had to delete sublime text project files and create new project.

**Comment by divmain** [comment]
I see how that'd be really annoying.  Let me dig into this.  For performance reasons, GitSavvy caches information about the Git repository for a given open file / view.  That's probably what causes this issue.  I'll look into how the user can actually say "no" when the `.git` dir has been removed.

**Comment by divmain** [comment]
@freexo, a fix for this will be in the next release.
