### ISSUE TITLE
Delete untracked file/folder on discard (status: `d`)

### ISSUE THREAD

**Issue by benmosher** [divmain/GitSavvy#138]
I noticed that you mentioned the possibility of having the `d` discard action in the Status pane delete an untracked file in #17.

Discard all (`D`) appears to remove untracked files, but I get a pathspec-not-known-to-git error in the console when I try to discard a single untracked file or folder.

Console output:

```
`/usr/bin/git checkout -- WebClient/src/jsx/components/controls/test` failed with following output:

error: pathspec 'WebClient/src/jsx/components/controls/test' did not match any file(s) known to git.
```

**Comment by divmain** [comment]
As of right now, discard-all does the following:
```
git clean -df
git checkout -- .
```

The single-file discard action does this:
```
git checkout -- FILE_PATH
```

However, I've found it annoying myself that I can't discard untracked files either.  I'll add this functionality.

**Comment by divmain** [comment]
If you'd like to pull down master and confirm it behaves as expected, it is not available.  Otherwise, it'll be in the next release.
