### ISSUE TITLE
Crash when creating augmented theme

### ISSUE THREAD

**Issue by divmain** [divmain/GitSavvy#140]
Copied from #66.  /cc @dsusini

I'm having the same issue while testing on a single file with a single edit.  I followed your directions from above.  Looks like I'm getting a python crash in the console:

```
Traceback (most recent call last):
  File "C:\Users\--------\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 36, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(**kwargs), 0)
  File "C:\Users\--------\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 56, in run_async
    self.augment_color_scheme(diff_view, file_ext)
  File "C:\Users\--------\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 75, in augment_color_scheme
    themeGenerator = ThemeGenerator(original_color_scheme)
  File "C:\Users\--------\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\common\theme_generator.py", line 46, in __init__
    self.plist = ElementTree.XML(color_scheme_xml)
  File "./xml/etree/ElementTree.py", line 1356, in XML
xml.etree.ElementTree.ParseError: syntax error: line 2, column 48
```

Here is the log with private info replaced with "--------":
```json
[
  {
    "stderr": "", 
    "stdin": null, 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stdout": "## master\n M src/--------.cpp\n", 
    "type": "git"
  }, 
  {
    "stderr": "", 
    "stdin": null, 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stdout": "## master\n M src/--------.cpp\n", 
    "type": "git"
  }, 
  {
    "stderr": "", 
    "stdin": null, 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdout": "W:/Projects/--------\n", 
    "type": "git"
  }, 
  {
    "stderr": "", 
    "stdin": null, 
    "command": [
      "ls-files", 
      "-s", 
      null
    ], 
    "stdout": "100644 bb502cbea566739c4736bd63cd9860806e612eeb 0\t.gitignore\n100644 839594f987664c7538ef0f21862b772c180402d1 0\--------.sln\n100644 
```
LISTS ALL FILES IN PROJECT HERE..........

I think the below is my gitignore file contents:
```json
    "type": "git"
  }, 
  {
    "stderr": "", 
    "stdin": null, 
    "command": [
      "show", 
      "bb502cbea566739c4736bd63cd9860806e612eeb"
    ], 
    "stdout": "build/\n*.suo\n*.sublime-workspace\n", 
    "type": "git"
  }
]
```

Also, when I "Stop Logging" and "View log contents" I get a different python crash in the console:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "C:\Users\dsusini\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 127, in run
    working_tree_file_contents = self.get_file_contents(file_path)
  File "C:\Users\dsusini\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\inline_diff.py", line 193, in get_file_contents
    file_path = os.path.join(self.repo_path, file_path)
  File "./ntpath.py", line 121, in join
  File "./ntpath.py", line 102, in isabs
  File "./ntpath.py", line 208, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

**Comment by divmain** [comment]
@dsusini, I've created a new issue as I think this is unrelated to #66.  Can you do the following for me?

1. Open the Sublime console.
2. Enter `view.settings().get("color_scheme")`
3. Add a comment here with the output.

It looks like the syntax file that GitSavvy tries to augment is not valid XML (Sublime may be more forgiving than Python standard library in this regard).  What type of file are you diff'ing?

**Comment by dsusini** [comment]
Good catch.  I don't even have to run that command because I know I'm using my own custom theme and language files for c/c++.  I didn't add any bad xml, but the base file that I started with may have. Do you think that's the only issue?  If so, I'll scour the tmTheme file and see if I can figure it out.  I'll let you know what I find.

**Comment by dsusini** [comment]
Ok, thanks to you I figured it out.  I needed to make sure this line was correct at the top of my tmTheme file:

<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

**Comment by divmain** [comment]
Awesome!  Interesting that SublimeLinter didn't have an issue since I believe that's where I originally got my approach for theme handling.  Anyway, I'm going to close this out, but ping me if more needs to be addressed.
