### ISSUE TITLE
feature: possible to diff lines with changed characters and whitespace

### ISSUE THREAD

**Issue by wprater** [divmain/GitSavvy#141]
it would be nice to alternate background opacity to show the changed charters in each line for the diff view.  do you need to use a new parser?  hoping for a similar view to GitX.

**Comment by yyyc514** [comment]
Are there any git diff options that producible scanable output of the sort you're hoping for?

**Comment by yyyc514** [comment]
Maybe we should bundle `diff-highlight`? http://blogs.atlassian.com/2013/06/git-diff/

**Comment by wprater** [comment]
yeah, that perl script looks nice!  I was trying to see which GitX (rowanj) uses.

**Comment by wprater** [comment]
https://github.com/rowanj/gitx/pull/243

**Comment by yyyc514** [comment]
I'm not sure we could depend on perl for Windows... we might need a python native solution.

**Comment by wprater** [comment]
I could see about porting the [JS](http://ejohn.org/files/jsdiff.js) or [Perl](https://git.kernel.org/cgit/git/git.git/plain/contrib/diff-highlight/diff-highlight) versions to Python.

**Comment by divmain** [comment]
Hey @wprater @yyyc514, this was a bit tricky but fun to add.  Feature is now in master, so please try it out.  Along the way, I discovered what I believe is a ST3 bug, and have [filed an issue](https://github.com/SublimeTextIssues/Core/issues/766).  If the word highlighting works but only sometimes, that is probably why.

**Comment by divmain** [comment]
Oh, and you may need to delete any theme files in `Packages/User/GitSavvy` for the theme to display correctly.

**Comment by wprater** [comment]
Im not getting any diff theme at all now.  I had a few themes in there, but where did they come from ?  are they all auto-generated?

**Comment by divmain** [comment]
They are all auto-generated, yes.  Is it just rendering like plain text?  Is Sublime giving you an error?  Or a screenshot?

**Comment by wprater** [comment]
I removed them again and I've got it rendering now! Nice.

**Comment by divmain** [comment]
Awesome, thanks for letting me know!  Can you let me know if it works consistently?  On my machine, it only works as expected about 40% of the time, but I'm curious to know if the Sublime bug is restricted to OS X.

**Comment by wprater** [comment]
I'm on OS X too. but will report back to this thread.

**Comment by divmain** [comment]
Thanks!

**Comment by alextegelid** [comment]
I've been waiting for this aswell. I'll keep an eye open for bugs. Thanks @divmain!

**Comment by wprater** [comment]
this is still rather buggy, should we add a feature to disable it, so it does not confuse people?

for example I just changed `768px` to `769px` here 

![](http://cl.ly/image/1d0X43241I2q/Image%202015-04-13%20at%2011.49.24%20AM.png)

**Comment by divmain** [comment]
@wprater - you're the first that has reported this issue.  Is this happening often?  Also, do you have steps I can use to reproduce?  Its not a bad idea to add a flag to turn it off, I'll add that.

**Comment by wprater** [comment]
not all the time, but often. have not had time to look into it yet.  here is a sample diff that failed

http://cl.ly/code/0l3D2O1X0C1Y/test.diff

this was the output, where only the `2` changed to `5`
![](http://cl.ly/image/0Z101b1R0J3n/Image%202015-04-14%20at%202.58.44%20PM.png)

**Comment by divmain** [comment]
I haven't been able to reproduce this lately, and the underlying Sublime bug seems to have also been fixed.  If this turns up again, feel free to reopen, ideally with a repro I can use to help diagnose the issue.
