### ISSUE TITLE
Inline diff view for renamed file tries to diff old filename

### ISSUE THREAD

**Issue by alextegelid** [divmain/GitSavvy#149]
When I enter the inline diff view (via the command palette) for a file that I have renamed GitSavvy tries to open the diff view using the files old filename, resulting in a blank diff view.
![image](https://cloud.githubusercontent.com/assets/7058721/6868482/43e530f0-d48c-11e4-9ce5-908b6b87db24.png)

**Comment by alextegelid** [comment]
Opening the inline diff from the status dashboard works as expected

**Comment by yyyc514** [comment]
Interesting, when did you perform the rename?

**Comment by alextegelid** [comment]
I'll have to get back to you on that. I can't remember if the file was tracked or not before the rename...

**Comment by divmain** [comment]
Hmm... this may be a hard case to support.

As far as I know, Git itself doesn't know that a file has been renamed until it has been staged, or unless the file was renamed using `git mv`.  Even then, `git mv` automatically stages the file.

It might be possible to support viewing cached changes, since all the data should be there, i.e. old file name at HEAD and new file name in index.  But if nothing is staged, I'm not sure what approach to take or if similar tools support this case.

Do you know if SourceTree, GitX, et al have support for this?

**Comment by yyyc514** [comment]
> As far as I know, Git itself doesn't know that a file has been renamed until it has been staged

When I imagined solving this I imagined tackling only that single edge case (where git can tell you about the rename) - a renamed staged file...

**Comment by divmain** [comment]
Yes, that's what I meant when I said it might be possible to support viewing cached changes.  Still, it may be complex.  @alextegelid how often do you think you would rename a file, make changes, and then want to view the inline diff to back out some changes?  I think that's the edge case that it is possible to support.

**Comment by alextegelid** [comment]
It's really not a big deal for me, but I thought it was worth mentioning. I can easily make do without a fix for this, especially now that I know that it isn't really a bug in GitSavvy but a problem with git itself. 


Don't put any time on this on my account, thanks for investigating and explaining though. 👍

**Comment by divmain** [comment]
I've discovered that this is very painful to support.  In fact, I haven't found another tool that does this properly, probably due to the poor support Git actually supplies for it.  Going to close this issue as wont-fix.  Sorry @alextegelid - although I'm sure you've forgotten about it by now :)

**Comment by alextegelid** [comment]
I'd completely forgotten about it! Thanks for investigating :)
