### ISSUE TITLE
Add to `.gitignore` fails in some cases on Windows

### ISSUE THREAD

**Issue by divmain** [divmain/GitSavvy#150]
Originally mentioned here: 503ab0f579e68001b64997802f759d6bb76a8665

On Windows, when Git is configured to check out file Unix-style, `.gitignore` will add `\r` characters because of current implementation's reliance on `os.linesep`.  Instead, git config should be checked for line endings, and then cached for the remainder of the Sublime session.

/cc @p3lim

**Comment by p3lim** [comment]
:+1:

**Comment by yyyc514** [comment]
Anything we can do to make Windows less of a living hell I suppose we owe it to somebody. :smiling_imp:
