### ISSUE TITLE
Support `prepare-commit-msg` hook for messages in commit view

### ISSUE THREAD

**Issue by max-mykhailenko** [divmain/GitSavvy#156]
JIRA commit message have a next look:
`TASK-123 #time 00h 20m  commit message`
Branch name for this task will be
`TASK-123-some-cool-feature`

Add branch name to comments under commit message for autocompleting (`TASK-123`)
OR
Will be great if I can add some text to every commit dynamically by running some custom command which will insert text to commit message.

**Comment by divmain** [comment]
The first ask should be easy.  The second might be workable once #83 is ready.

**Comment by yyyc514** [comment]
Isn't this what git commit/pre-commit hooks are for?  Should we perhaps look at using those vs building out a whole new system for such things?

**Comment by yyyc514** [comment]
I think optimally if the commit view worked hand in hand with `prepare-commit-msg` we might be onto something.  Would be great to hear from more people using commit hooks along with GitSavvy to see what the thought are on how they should work together.

**Comment by max-mykhailenko** [comment]
Thanks for discussion!  Let's left only first variant. 

Add branch name to comments under commit message for autocompleting (TASK-123)
~~OR
Will be great if I can add some text to every commit dynamically by running some custom command which will insert text to commit message.~~ <-- It's must be another plugin

**Comment by max-mykhailenko** [comment]
How can I see `prepare-commit-msg` results in commit view? Is it works now?

**Comment by divmain** [comment]
@max-mykhailenko - I think the best approach here will be to expose an API where users can augment the default behavior programmatically.  I'll be thinking through what this API might look like, and where the boundary will be between configurability and "trying to do too much".

**Comment by yyyc514** [comment]
Would a patch that hooked into git's existing prepare-commit-msg hooks be accepted?

**Comment by divmain** [comment]
`prepare-commit-msg` is invoked the `git commit`, so how do you envision that working?  As it is, the GitSavvy commit view is part of a process very separate from a `git command` in the terminal.

**Comment by yyyc514** [comment]
We'd invoke it, of course. :-)  I guess it comes down to whether gitSavvy is trying to superbly enhance the git workflow or completely replace it (and rebuild a lot of it in the process)

**Comment by yyyc514** [comment]
Luckily I don't use hooks currently but if I did I would hope GitSavvy would respect them and work well with them (if possible), not require rewriting them in Python.

**Comment by divmain** [comment]
@yyyc514, after thinking about it, I've come to like the `prepare-commit-msg` approach.  I don't know how much work it'll be to truly support this in all cases, but I think it is worth taking a look.

**Comment by divmain** [comment]
Going to close this in favor of #161.  @max-mykhailenko, once the `prepare-commit-msg` hook is supported, it should be straightforward for you to add the functionality you want.

**Comment by max-mykhailenko** [comment]
Many thanks!
