### ISSUE TITLE
Setting api_tokens may import underlying unsecured issue  

### ISSUE THREAD

**Issue by kepbod** [divmain/GitSavvy#157]
Some people may upload their sublime configurations (including GitSavvy.sublime-settings) to github to synchronize, so it may be unsafe to set api_tokens in the GitSavvy.sublime-settings file. Could you add an interactive mode to let users input their api_tokens each time when needed? I think this may be more welcome. Thanks!

**Comment by yyyc514** [comment]
Or simply store them in .git/config as a git setting as I suggested elsewhere. (other tools do this)

**Comment by yyyc514** [comment]
Do people really keep tokens just laying around to paste in via some sort of interactive mode?

**Comment by divmain** [comment]
I think @yyyc514 is spot on.  We'll add functionality to store these tokens in Git config.  If we're going to prompt every time its needed, we might as well prompt for username and password - the user would be more likely to have that memorized, anyway.  Also, the lack of defined `api_tokens` only means that the module will make the HTTP request with no credentials.  For public repos, this works just fine.

**Comment by divmain** [comment]
I've looked at a number of other Sublime packages, and adding tokens and other secrets to the `User/GitSavvy.sublime-settings` seems to be the pattern used by everybody.  For that reason, closing this as wont-fix.
