### ISSUE TITLE
git pull command fails due to "--no-column" option not existing in old git versions

### ISSUE THREAD

**Issue by lmedinas** [divmain/GitSavvy#158]
when doing a git pull the output error is the following:

```
/usr/bin/git branch -r --no-color --no-column failed with following output:

error: unknown option no-column
usage: git branch [options] [-r | -a] [--merged | --no-merged]
   or: git branch [options] [-l] [-f] <branchname> [<start-point>]
   or: git branch [options] [-r] (-d | -D) <branchname>...
   or: git branch [options] (-m | -M) [<oldbranch>] <newbranch>

Generic options
    -v, --verbose         show hash and subject, give twice for upstream branch
    -t, --track           set up tracking mode (see git-pull(1))
    --set-upstream        change upstream info
    --color[=<when>]      use colored output
    -r, --remotes         act on remote-tracking branches
    --contains <commit>   print only branches that contain the commit
    --abbrev[=<n>]        use <n> digits to display SHA-1s

Specific git-branch actions:
    -a, --all             list both remote-tracking and local branches
    -d, --delete          delete fully merged branch
    -D                    delete branch (even if not merged)
    -m, --move            move/rename a branch and its reflog
    -M                    move/rename a branch, even if target exists
    --list                list branch names
    -l, --create-reflog   create the branch's reflog
    --edit-description    edit the description for the branch
    -f, --force           force creation (when already exists)
    --no-merged <commit>  print only not merged branches
    --merged <commit>     print only merged branches
```
the option "--no-column" was only implemented in git 1.7.11 and distros like Ubuntu 12.04 are still using git 1.7.9.x 

Can you please make a workaround for old git versions ? If not please at least write in the Readme the minimum version requirement for git.

**Comment by yyyc514** [comment]
I'm not sure it's possible (or advisable) to support all old versions.  I'm on 1.9.5 local (Mac OS X built-in it looks like) and see the latest is 2.3.4.  Default here seems to be no-column, but if someone has asked for columns in their git config I can see where specifying --no-column would become important.

**Comment by yyyc514** [comment]
Maybe the parsing could be changed though to support both columns and non-columns if this was important?

**Comment by lmedinas** [comment]
What if the "--no-columns" option was removed by default and add a configuration for it ? I mean it could be configurable and only enabled by default if the user wants with a warning it might not work in older versions.

**Comment by yyyc514** [comment]
I feel like it would be better to support older versions with a configuration option than newer versions... so if anything --no-columns would be the default and we'd add a special flag for really old git versions if we had to.  Honestly someone running 1.7.9 is going to have a better experience if they just upgrade.  Waiting for @divmain to weigh in on this one.

**Comment by divmain** [comment]
Here's what I'll do.  I'll remove the hard-coded `--no-columns` from the Git pull command, but I'll add a default entry for `pull` in `global_flags` (in `GitSavvy.sublime-settings`) that includes `--no-columns`.  This should result in no change of behavior for pretty much everybody, but @lmedinas you will be able to override the setting and remove `--no-columns`.

**Comment by yyyc514** [comment]
Perfect compromise.  Forgot about global_flags.

**Comment by lmedinas** [comment]
OK, let me know when it's release i will do a try but it seems a good idea.

Thanks a lot for the fast feedback

**Comment by divmain** [comment]
@lmedinas, this fix is now in master.  If you get a chance, please give it a try to confirm this resolves the issue for you.
