### ISSUE TITLE
GitSavvy: help navigation doesn't work in Ubuntu

### ISSUE THREAD

**Issue by Suor** [divmain/GitSavvy#167]
It says **Super-Enter** to open link and **SUPER-Backspace** to go back, but you can't rebind any combinations involving **Super**  in Ubuntu (at least with Unity DM, which is default). **Ctrl** variants also don't work.

**Comment by Suor** [comment]
Obviously any **Super** combinations don't work, e.g. **Super-Z** in inline diff.

**Comment by divmain** [comment]
Any recommendations for alternate key-bindings?  I haven't used Ubuntu for my daily driver for a handful of years, so my knowledge isn't up-to-date.  `CTRL` variants aren't set for Linux, but they could be used if you think it'd be a good fit.

**Comment by Suor** [comment]
You are almost always safe using same key bindings for Linux and Windows.
These also make much more sense than Super+something. It's Mac Os X that
wants special treatment, with its Cmd as primary modifier.

**Comment by divmain** [comment]
I'm surprised I haven't heard this before.  I'll switch the Linux key-bindings to match those on Windows.  Thanks!

**Comment by Suor** [comment]
These a diffstats for ST2 default key bindings:
```bash
$ diff Default\ \(Linux\).sublime-keymap Default\ \(Windows\).sublime-keymap | diffstat
 unknown |   31 +++++++++++--------------------
 1 file changed, 11 insertions(+), 20 deletions(-)

$ diff Default\ \(OSX\).sublime-keymap Default\ \(Windows\).sublime-keymap | diffstat
 unknown |  363 +++++++++++++++++++++++++++++++++-------------------------------
 1 file changed, 190 insertions(+), 173 deletions(-)
```

**Comment by Suor** [comment]
Linuxes never used custom keyboards, they used ones built for windows and still do. Hence the same combos.

**Comment by divmain** [comment]
Yeah, I'm just surprised I haven't heard from others using GitSavvy on Ubuntu before now.

**Comment by Suor** [comment]
I think it's Unity that blocks Super rebinding, so this could work in Kubuntu, Xubuntu or Lubuntu. Also, everyone is probably just using html help. I don't know why you bother at all with built-in help.

**Comment by divmain** [comment]
¯\_(ツ)_/¯

Seemed interesting, I suppose.  But there are several other places in GitSavvy that use the Super/Ctrl binding, so this should definitely be addressed.

**Comment by Suor** [comment]
Particulary weird was `Super+Z` to undo, while it is `Ctrl-Z` everywhere in Linux including Sublime Text.
