### ISSUE TITLE
Shift-H doesn't work in inline diff on linux 

### ISSUE THREAD

**Issue by Suor** [divmain/GitSavvy#168]
``` python
Traceback (most recent call last):
  File "/home/suor/.config/sublime-text-3/Packages/GitSavvy/core/commands/inline_diff.py", line 374, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(**kwargs), 0)
  File "/home/suor/.config/sublime-text-3/Packages/GitSavvy/core/commands/inline_diff.py", line 394, in run_async
    full_diff = header + diff_lines + "\n"
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by divmain** [comment]
This seems unlikely to be OS-related.  Is this broken for other actions in the inline-diff view, as well?  Have you tried this once, or is broken for any file/diff?  In any event, I should add better error handling [here](https://github.com/divmain/GitSavvy/blob/82bb849ae03d0e584923ddd09059107cbbc34cd4/core/commands/inline_diff.py#L386-L386).

**Comment by Suor** [comment]
I don't know if it's OS dependent. I tried it several times for single for with several hunks. Other shortcuts like `,`, `.` and `h` worked there.

**Comment by divmain** [comment]
Really!  It's especially surprising that `h` would work but not `H`.  I'll have to start up a Linux VM and try to reproduce this myself.  Can you tell me which version of Ubuntu you're running?

**Comment by Suor** [comment]
It's 14.10 utopic unicorn.​

**Comment by divmain** [comment]
Thx.

**Comment by divmain** [comment]
Hi @Suor - I'm unable to reproduce.  Shift-H works fine under my Ubuntu 14.10 VM.  Have you noticed if this fails across the board, or only in particular repos?

**Comment by Suor** [comment]
Happens for any repo. Here is a screencast:
![gitsavvy-opt](https://cloud.githubusercontent.com/assets/284103/7388153/e1618ff6-ee84-11e4-9f2e-cd4f277a6e58.gif)

I make a change, save, switch to inline diff. Hit "h", it works, than hit "Shift-H" twice, nothing happens. Only errors in console appear.

**Comment by stoivo** [comment]
Did you install it from the repo or the Package manager?

**Comment by Suor** [comment]
From package manager.

**Comment by stoivo** [comment]
Could you try to install it with GitHub repo?

**Comment by stoivo** [comment]
Feel free to reopen if you still have this issue
