### ISSUE TITLE
Cannot stage and commit when the repo has no commits yet.

### ISSUE THREAD

**Issue by zenoamaro** [divmain/GitSavvy#169]
When the repository has no commits yet (ie. you are about to stage and commit the first one), it's not possible to open the status page in order to do so.

The failure mode is the same as git log, in fact:

~~~
`/usr/bin/git log -n 1 --pretty=format:%h %s --abbrev-commit` failed with following output:

fatal: bad default revision 'HEAD'
~~~

The status page should still work and allow staging the initial commit, and display the fact that no commits are yet in the log. 

Apologies if this issue is a clone, but I couldn't find it elsewhere.

**Comment by divmain** [comment]
Nope, not a dupe - just hasn't come up yet.  Thanks!  A fix should be in the next release.

**Comment by edencore** [comment]
I have the same error in existing repository with commits. Is there any git command that can fix it for me ?

**Comment by zenoamaro** [comment]
@edencore, could you paste the output of `git log`?

Is it possible you're in detached head or an orphan branch?

**Comment by edencore** [comment]
@zenoamaro i don't think so. It is almost pure repository with a few commits and absolutely no branches. Btw, `git log` from GitSavvy throws the same error, but works well from the console

**Comment by zenoamaro** [comment]
@edencore, so if I'm getting it right, doing

    /usr/bin/git log -6000 --format=%h%n%H%n%s%n%an%n%at%x00

manually on the console doesn't raise errors?

Could you "GitSavvy: start logging" from the command palette, and paste the recorded log after the issue happens?

**Comment by edencore** [comment]
@zenoamaro here it is:
```
Traceback (most recent call last):
  File "/home/eden/.config/sublime-text-3/Packages/GitSavvy/common/ui.py", line 265, in run_async
    interface = InterfaceSubclass(view=self.view)
  File "/home/eden/.config/sublime-text-3/Packages/GitSavvy/common/ui.py", line 61, in __init__
    self.render(nuke_cursors=False)
  File "/home/eden/.config/sublime-text-3/Packages/GitSavvy/common/ui.py", line 90, in render
    rendered = self._render_template()
  File "/home/eden/.config/sublime-text-3/Packages/GitSavvy/common/ui.py", line 106, in _render_template
    keyed_content = self.get_keyed_content()
  File "/home/eden/.config/sublime-text-3/Packages/GitSavvy/common/ui.py", line 144, in get_keyed_content
    for key, render_fn in self.partials.items()
  File "./collections/__init__.py", line 56, in __init__
  File "./collections/abc.py", line 578, in update
  File "/home/eden/.config/sublime-text-3/Packages/GitSavvy/common/ui.py", line 144, in <genexpr>
    for key, render_fn in self.partials.items()
  File "/home/eden/.config/sublime-text-3/Packages/GitSavvy/core/interfaces/status.py", line 149, in render_head
    return self.get_latest_commit_msg_for_head()
  File "/home/eden/.config/sublime-text-3/Packages/GitSavvy/core/git_mixins/active_branch.py", line 122, in get_latest_commit_msg_for_head
    return self.git("log", "-n 1", "--pretty=format:%h %s", "--abbrev-commit").strip()
  File "/home/eden/.config/sublime-text-3/Packages/GitSavvy/core/git_command.py", line 112, in git
    command_str, stdout, stderr
  File "/home/eden/.config/sublime-text-3/Packages/GitSavvy/core/git_command.py", line 86, in raise_error
    raise GitSavvyError(msg)
GitSavvy.core.git_command.GitSavvyError: `/usr/bin/git log -n 1 --pretty=format:%h %s --abbrev-commit` failed with following output:

fatal: bad default revision 'HEAD'
```

**Comment by divmain** [comment]
@edencore, please checkout [this article](http://stackoverflow.com/questions/15628720/fatal-bad-default-revision-head).  It may help explain what you're seeing.  Especially curious is your statement that you're working with an "... almost pure repository with a few commits and absolutely no branches".  Does this include a master branch?  If you do `/usr/bin/git log -n 1 --pretty=format:%h %s --abbrev-commit` from the terminal and it fails, this is most likely due to your repo being in a strange state.

@zenoamaro, real life crept up on me.  I should get around to a fix and subsequent release in the next week or so.

**Comment by edencore** [comment]
@divmain my repo has a master branch (I wanted to say that I have no any additional branches), but it has no any remotes. Can it be the root of the problem ? 
Command that you have provided works well from the terminal.

Anyway, looks like I am the only one with this problem, so nevermind. Must be a repo's issue.

**Comment by divmain** [comment]
@edencore can you also run `which git` from the terminal?  It's strange that the same command would fail when run from GitSavvy but succeed from the terminal.

**Comment by edencore** [comment]
@divmain it returns `/usr/bin/git`
