### ISSUE TITLE
When staging a directory, ignored files are also staged.

### ISSUE THREAD

**Issue by zenoamaro** [divmain/GitSavvy#170]
The behavior when staging a directory entry from the status page differs from that of `git add <directory>`, which recursively stages the contents, but does not stage ignored files.

When staging a directory in GitSavvy's status page, ignored files get staged too. They correctly disappear from the list when unstaged.

Note that `git add` will also respect nested `.gitignore` files, scoped to their containing directory.

**Comment by divmain** [comment]
At present, GitSavvy uses the `-f` flag when staging files.  Trying to remember why this was originally.  I'll go ahead and change this in master - if nothing unexpected comes from that change, it'll be included in the next release.

**Comment by zenoamaro** [comment]
Seems the only use of `-f` is being able to add ignored files. I can see cases where this would be useful, but I remember being able to stage the file simply invoking "Git: add" from the command palette in SublimeGit, which worked well considering how rarely I had needed to do that. So that may still warrant the `-f` flag, I think?

Anyway, thanks a lot for the fix!

**Comment by zenoamaro** [comment]
Worked perfectly, thanks!
