### ISSUE TITLE
Line unstage undo not working properly

### ISSUE THREAD

**Issue by aristidesfl** [divmain/GitSavvy#176]
1. Open diff view current file (cached)
2. Unstage a line from the **middle** of the hunk with `l`
3. Press `super+z` to undo

The line seems to be inserted on top of the hunk, instead of in its original place.

**Comment by divmain** [comment]
Meh, this one is going to be tedious to fix.  But its a reasonable ask, so this is in my queue.

**Comment by stoivo** [comment]
I think this is same issue as #187.
