### ISSUE TITLE
Add git graph all to command palette

### ISSUE THREAD

**Issue by steverandy** [divmain/GitSavvy#179]
I think the default `git graph` command should not have `--all` arg applied.
I would prefer to have a new command `git graph all` to view all refs.

**Comment by divmain** [comment]
I'll make this globally configurable.  In the future, the graph view will be more interactive and allow the user to open and/or view selected commits and branches.  For that reason, the default will remain as-is.  But if you're willing to sacrifice that functionality, there's no reason why this can't be configurable on a per-user basis.

**Comment by steverandy** [comment]
Thanks for clarifying!

**Comment by stoivo** [comment]
This is done, can we close this one, @divmain?

**Comment by divmain** [comment]
Good point.  Thanks @stoivo!
