### ISSUE TITLE
How can I do merge without --log param?

### ISSUE THREAD

**Issue by max-mykhailenko** [divmain/GitSavvy#183]
How I can disable default `--log` param?
https://github.com/divmain/GitSavvy/blob/master/core/commands/merge.py#L49

Trying to use this config
```
{
"global_flags": {
        "merge": ["--no-log"]
    }
}
```

But seems that `--no-log` is placed before default `--log` (according to 
https://github.com/divmain/GitSavvy/blob/1394489e1fa042996d9ba20817c0e8e4d45dcbb0/core/git_command.py#L245)

**Comment by max-mykhailenko** [comment]
Why this important? Because people who use JIRA smart commits for logging time include time record to commits messages. Merge with --log provoke logging time twice for every commit

Example commit messages:
 - simple commit message
`KATA-964 #time 0h 54m immutable tips`

- merge commit message
```
Merge branch 'KATA-958-manage-notices-as-administrator' into dev

* KATA-958-manage-notices-as-administrator: (23 commits)
KATA-964 #time 0h 54m immutable tips
KATA-964 #time 0h 4m Fix some
KATA-964 #time 0h 4m just time log
...
```

**Comment by divmain** [comment]
This should be an easy fix - will include in the next release @max-mykhailenko.

**Comment by max-mykhailenko** [comment]
Sent pull request for that https://github.com/divmain/GitSavvy/pull/188

**Comment by max-mykhailenko** [comment]
I have this error again, probably because commands order in line
https://github.com/divmain/GitSavvy/blob/master/core/git_command.py#L265

@divmain please, check it, we have big problems with that

**Comment by max-mykhailenko** [comment]
In my previous pull request it was changed to
```
if global_flags and git_cmd in global_flags:
-            args = [git_cmd] + global_flags[git_cmd] + addl_args
+            args = [git_cmd] + addl_args + global_flags[git_cmd]
 ```

**Comment by divmain** [comment]
Hey @max-mykhailenko, unfortunately that broke several other cases and we had to revert.  I think the simplest approach here will be to make that `--log` param optional.  Just pushed a commit, let me know if it works for you.
