### ISSUE TITLE
Help command for all views

### ISSUE THREAD

**Issue by stoivo** [divmain/GitSavvy#184]
I was thinking that is might be good to have easy-access-help for all views.
by pressing "?" to toggle a write-only quick panel. 
for diff, inline diff, blame, etc?
This will make the docs easy to access.

I started to read all keybindings-file for find new functions.
What do you think about this?

**Comment by divmain** [comment]
There is a `GitSavvy: help` command in the Sublime palette.  This will give users access to either general, wiki-style help, or bring them to a specific page when in certain views.  Do you have something in mind other than this?

**Comment by stoivo** [comment]
I was thinking something like this ![screenshot 2015-05-16 04 20 41](https://cloud.githubusercontent.com/assets/3492040/7666489/921877d2-fbe7-11e4-8280-af4241dce860.png)

and some color highlighting. But I do not know who to do it.

**Comment by divmain** [comment]
It is a neat idea, but I think having two live-help systems is unnecessary.  Also, highlighting in views could be difficult if you wanted control over the colors used.  It would be possible to underline, etc, without any issues but that might be confused for plugins that show errors.

**Comment by stoivo** [comment]
Yes, I totally agree with you that is is unnecessary,  but it will only contain shortcuts for each view.
it is easy to add custom colouring in the quick panel. Like this(Just some silly ruby code)
![screen shot 2015-05-19 at 21 53 38](https://cloud.githubusercontent.com/assets/3492040/7712648/c3eb64ee-fe72-11e4-9b48-f02ac94ac581.png)
)

code snippet to do it 
```
class ShowHelpView( sublime_plugin.TextCommand):
    def run( self, edit ):
        other_string = """\
class Foo
  def ee
    3
  end
end"""
        string = """\
inline diff help

[,] previous hunk
[.] next hunk

[h] stage hunk         [H] discard hunk
[l] stage line         [L] discard line

[r] refresh view

{} """

        if (sublime.platform() == "Windows"):
            undo_command = "[CTRL-z] on Windows    "
        else:
            undo_command = "[SUPER-z] on Linux/OSX "

        self.output_view = self.view.window().create_output_panel("inline-diff-help")
        self.output_view.set_read_only(False)
        # self.output_view.insert(edit, 0, string.format(undo_command))
        self.output_view.insert(edit, 0, other_string)
        self.output_view.set_syntax_file("Packages/Ruby/Ruby.tmLanguage")
        self.output_view.set_read_only(True)
        self.view.window().run_command("show_panel", {"panel": "output.inline-diff-help"})
```

**Comment by stoivo** [comment]
If you want it, I will create it :)

**Comment by divmain** [comment]
Let me think about this. I don't like the idea of having two help systems, but I do like the idea of contextual help.

**Comment by divmain** [comment]
For the sake of simplicity, I'm going to pass on this feature.  `GitSavvy: help` provides more help than most plugins do, and a `?`-shortcut would be 1) not discoverable, and 2) not always available (in normal views, for example).
