### ISSUE TITLE
Line unstage is re-adding it in a different place

### ISSUE THREAD

**Issue by hanoii** [divmain/GitSavvy#187]
I have a file in which I have a line removed, but when I unstage the line, instead of being added to the same line it was, it's being added on a different place (a few lines above) ending with a removal/addition in the wrong place.

**Comment by hanoii** [comment]
I just realized this happens if there's also an addition above the line that's being removed.

**Comment by divmain** [comment]
Hi @hanoii, there still seem to be a handful of quirks with the line stage/unstage.  I'm planning to try to squash all these bugs at one time.  Could you help me out by taking screenshots of each stage of the repro process?

**Comment by hanoii** [comment]
Sure thing.

This one's pretty easy to reproduce. I just cloned this project, edited CONTRIBUTE.md and added a new line and below I removed another one, see:

![screenshot 2015-06-10 10 41 38](https://cloud.githubusercontent.com/assets/677879/8083773/74114136-0f5d-11e5-8191-e83bb5c78c03.png)

I them attempted to unstage the removal the line, see below what happens:

![screenshot 2015-06-10 10 41 49](https://cloud.githubusercontent.com/assets/677879/8083786/8a71d558-0f5d-11e5-9ea7-f462e71cb854.png)

Trying to unstage it again adds the same line again:

![screenshot 2015-06-10 10 41 58](https://cloud.githubusercontent.com/assets/677879/8083799/96ecc25c-0f5d-11e5-8035-8f331c9d8531.png)

**Comment by stoivo** [comment]
I will try to fix this.

**Comment by stoivo** [comment]
I found the issue. When we create the diff we use to apply single line or hunk.
We create
```diff
diff --git a/docs/debug.md b/docs/debug.md
index 55bacd9..19a4a6c 100644
--- a/docs/debug.md
+++ b/docs/debug.md
@@ -16 +24,0 @@ This command will only have an effect if `dev_mode` is set to `true` in `Package
-This will start tracking the inputs and outputs of all Git commands that are running under the hood.  Aggregating this data can be useful for those wanting to learn how GitSavvy wo
````

We should
```diff
diff --git a/docs/debug.md b/docs/debug.md
index 55bacd9..19a4a6c 100644
--- a/docs/debug.md
+++ b/docs/debug.md
@@ -16 +27,0 @@ This command will only have an effect if `dev_mode` is set to `true` in `Package
-This will start tracking the inputs and outputs of all Git commands that are running under the hood.  Aggregating this data can be useful for those wanting to learn how GitSavvy wo
````

mark the difference is in this line 
```
@@ -16 +27,0 @@
```
Instead of 24 we use 27, it is `line nr` pluss `other lines added earlier`minus `lines deleted earlier` in this file. I am not 100% sure, but closer than ever.

I just want you to know that it is in progress :)
