### ISSUE TITLE
Wrong help in commit's view

### ISSUE THREAD

**Issue by edencore** [divmain/GitSavvy#190]
As I can see from [this file](https://github.com/divmain/GitSavvy/blob/master/Default%20(Linux).sublime-keymap) I should use `Ctrl`+`Enter` to make a commit, but on the commit's view page I see a following message:
```
## To make a commit, type your commit message and press SUPER-ENTER. To cancel
## the commit, close the window. To sign off the commit press SUPER-S.
```

**Comment by divmain** [comment]
Thanks @ddevlin for the fix.
