### ISSUE TITLE
Implement and add plugin tests

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#195]
We can do this using [one](https://github.com/randy3k/UnitTesting) of the [sublime](https://github.com/twolfson/sublime-plugin-tests) [testing](https://bitbucket.org/klorenz/sublimepluginunittestharness) [frameworks](https://github.com/guillermooo/AAAPT) out there (sorted by update date descending).

**Comment by divmain** [comment]
I've decided not to pursue unit testing for GitSavvy at this time.

The first of the frameworks that was linked shows some promise, but upon making at attempt, it appears that GitSavvy is considerably more complex than the framework can accommodate in a straightforward way.  In particular, there doesn't appear to be a way to make assertions about asynchronous behavior (`set_timeout_async`).  The other frameworks aren't maintained, nor do they seem any better.

I could roll my own testing solution, like Vintageous does.  But considering that regressions have rarely occurred for the life of the project, and the additional barrier for potential contributors (when there haven't been consistent contributors besides myself), this doesn't seem like the right path.

If a great testing framework shows up on the scene, I will absolutely reconsider.

**Comment by randy3k** [comment]
@asfaltboy brought me here. Actually, UnitTesting has a deferrable TestCase which could be used to test async commands. 

Given that I am the author of UnitTesitng, I am quite positive to enhance the functionality of UnitTesting to fit the GitSavvy use case.

**Comment by stoivo** [comment]
I am all for including test but I somehow I dont want to send my next 10h on figuring out how to writ specs. If you could create the first spec that would be nice.

**Comment by divmain** [comment]
Thanks @randy3k!
