### ISSUE TITLE
[request] Rename commands for logging

### ISSUE THREAD

**Issue by pradyunsg** [divmain/GitSavvy#198]
Currently, if one types "git st" in the Command Pallete, the suggested commands begin with "GitSavvy: start logging".

This is very unlikely to be what the user wants in nearly all cases. The user is most likely to be expecting "git: status" to be the first suggested command. Also, since "git st" and "git s" are very often git aliases for status, this is the expected behaviour.

So, my suggested fix is:
Please rename "GitSavvy: start logging" and "GitSavvy: stop logging" to "GitSavvy: enable logging" and "GitSavvy: disable logging".

I don't think such a change will negatively anyone's workflow but will improve the UX for some others by making "git: status" on the command palette accessible with the same command as on the command line.

**Comment by divmain** [comment]
Seems like a reasonable request.  I've found that Sublime learns pretty quick what I actually want, since it re-orders the displayed options based on previous selections.  However, no need to make this more difficult than it needs to be.
