### ISSUE TITLE
‘M’ in Status and Rebase doesn’t launch merge tool (Kaleidoscope)

### ISSUE THREAD

**Issue by sentience** [divmain/GitSavvy#199]
I have Kaleidoscope set up as my Git merge tool. I’m able to launch it on a conflicted repo with `git merge tool` from a Terminal prompt.

Hitting ‘M’ (Shift-m) in a GitSavvy Status or Rebase view does not do anything. No messages appear in the Sublime console.

Sublime Text 3 (r3092) running on OS X 10.10.

**Comment by divmain** [comment]
Sorry it has taken me a bit to get to this.  Could you post the pertinent section from your git config?  Also, what is the output of `git config merge.tool` ?

**Comment by sentience** [comment]
Here’s everything from my Git config that looks relevant:
```
[mergetool]
        keepBackup = true
        prompt = false
[difftool "Kaleidoscope"]
        cmd = ksdiff --partial-changeset --relative-path \"$MERGED\" -- \"$LOCAL\" \"$REMOTE\"
[diff]
        tool = Kaleidoscope
[difftool]
        prompt = false
[mergetool "Kaleidoscope"]
        cmd = ksdiff --merge --output \"$MERGED\" --base \"$BASE\" -- \"$LOCAL\" --snapshot \"$REMOTE\" --snapshot
        trustExitCode = true
[merge]
        tool = Kaleidoscope
```

And the output of  the command you requested:
```
> git config merge.tool
Kaleidoscope
```

**Comment by divmain** [comment]
Hm, that looks reasonable.  Can you do a couple more things?

#### 1)

In the terminal, show me the output of the following:
```
git config mergetool.Kaleidoscope.cmd
```

#### 2)
- open Sublime
- open Status dashboard
- put repo in condition where merge conflict needs to be resolved
- place cursor over conflict-file in dashboard
- run command `GitSavvy: enable logging`
- press `M` to activate the merge tool
- run command `GitSavvy: view recorded log`
- run command `GitSavvy: disable logging`

Give me the output of the recorded log here.  If we get nothing from the log, maybe we're dealing with a selector problem... so:

#### 3)
- open Sublime
- open Status dashboard
- put repo in condition where merge conflict needs to be resolved
- place cursor over conflict-file in dashboard
- open console and enter `view.run_command("gs_status_launch_merge_tool")`
- see what happens

Let's hope one of these gives us something to go on!

**Comment by sentience** [comment]
### 1)

```
> git config mergetool.Kaleidoscope.cmd
ksdiff --merge --output "$MERGED" --base "$BASE" -- "$LOCAL" --snapshot "$REMOTE" --snapshot
```

### 2)

How odd! When I tried to complete these steps, Kaleidoscope opened just fine! Indeed, I am no longer able to reproduce this bug.

I have just upgraded from OS X Yosemite to OS X El Capitan GM Seed, so perhaps something in that upgrade made the difference!

Perhaps close this for now, and I can reopen if I experience the issue again.

### 3)

Ditto. Works perfectly now.

**Comment by divmain** [comment]
Heh.  There be gremlins.  OK, I'm glad it is working for you.  Please do let me know if it comes up again!
