### ISSUE TITLE
Color scheme fails to load for git diff (windows)

### ISSUE THREAD

**Issue by ethanbustad** [divmain/GitSavvy#2]
I get the attached error message, the color scheme defaults to white with black text, and the changed hunks are unclear (in cached mode it seems like the changed hunks aren't shown at all, in uncached mode the hunks are shown as white text on black but it isn't clear what was removed, changed, added).
![gitsavvy-error](https://cloud.githubusercontent.com/assets/2229593/6158607/bab0b32a-b200-11e4-8e4a-7abd83f87db6.png)

**Comment by ethanbustad** [comment]
:+1: thanks! Works great now :)

**Comment by divmain** [comment]
Thanks for letting me know!

**Comment by p3lim** [comment]
Sorry for the necrobump, but I keep getting this every single time I diff a file with the latest releases of GitSavvy. When I diff a file I get the default scheme with white background and black text like described, and that error popup. I then have to accept the error, close the diff and re-open it, then it works.
