### ISSUE TITLE
When commit messages had dots in message, branches disapper from the main branch screen

### ISSUE THREAD

**Issue by jordic** [divmain/GitSavvy#204]

**Comment by stoivo** [comment]
Hey, 
I tried to reproduce it but did not manage. @jordic, can you look [here](http://recordit.co/owGtHBvgg0) and say what I did wrong.

**Comment by divmain** [comment]
@jordic, I was able to reproduce - I will have this fixed in the next day or two.

**Comment by jordic** [comment]
Sorry.. @stoivo.. Perhaps because im on linux.. Same you do on the video on mine the branch disappears..

**Comment by jordic** [comment]
Thank you! 
Works perfect!
