### ISSUE TITLE
Support `git pull --rebase`

### ISSUE THREAD

**Issue by sentience** [divmain/GitSavvy#207]
In order to avoid creating unwanted merges, I usually pull with `--rebase`:

```
git pull --rebase origin master
```

I’d like to be able to do this with Git Savvy. At first glance, you’d expect to be able to do this with the `global_flags` setting, but adding `"pull": ["--rebase"]` to this produces the following command:

```
git pull origin master --rebase
```

…which is an invalid command.

Can `global_flags` be adjusted to place its flags before the remote and branch ref in a `git pull`? Alternatively, can you offer a `git: pull (rebase)` command?

**Comment by divmain** [comment]
I'll going to scope this ticket to address the strange placement of the flag.  The pull-rebase command can be accomplished once #83 is implemented.  If I hear back from enough folks that it would be useful, I may add it as a command down the line.

**Comment by sentience** [comment]
:+1:

**Comment by divmain** [comment]
@sentience sorry for the wait.  Both changes are now in master.  Hit me up here or on Gitter if either one looks problematic.
