### ISSUE TITLE
Diff all files opens a new tab every time

### ISSUE THREAD

**Issue by dufferzafar** [divmain/GitSavvy#213]
I am not sure if this is expected but the diff all files action (from the Status Dashboard) opens a new tab everytime I press `f`. I expect it to just focus to the already open tab.

When I open the status dashboard (if it is already open) it doesn't create a new tab and just focuses the existing one. This should be done for Diffs too, IMO.

![Multiple instances of the same diff opens rather than focusing the existing tab](https://cloud.githubusercontent.com/assets/1449512/8505338/abcdb180-2200-11e5-89eb-041c6d059ec5.png)

**Comment by divmain** [comment]
This is a known issue, and should be resolved when the diff view is refactored using the interface base class (like the various dashboards).  This is a minor annoyance, though, so it will isn't on the top of my list.  I'd be happy to provide direction if you or someone else would like to take a look themselves.

**Comment by dufferzafar** [comment]
This is not only for Diff All Files but for any Diff view!

**Comment by dufferzafar** [comment]
Thanks @divmain
