### ISSUE TITLE
Rebase doesn't work if no master branch

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#217]
I tried `git rebase` in a repository with no `master` (it only has `gh-pages` and forks from that):

```
`/usr/bin/git merge-base HEAD master` failed with following output:

fatal: Not a valid object name master
```

**Comment by ddevlin** [comment]
Hi @stevage, you can change the default base branch by adding the following to your `.sublime-project` file:
```json
{
    "settings": {
        "rebase_default_base_ref": "gh-pages"
    }
}

It might be nice to handle the absence of a master branch more gracefully, I think the difficulty would be determining which of the other branches is the main branch.

**Comment by stevage** [comment]
A per-project setting doesn't really help me as I work on too many projects too fleetingly.

I don't know exactly how the rebase UI is supposed to work, but maybe you could simply present a list of all available branches? Probably some more sophisticated approach to finding likely rebase candidates, but my git-fu is insufficient...

**Comment by divmain** [comment]
@stevage, @ddevlin just took care of this with PR #221.  The fix is in master, and will be included in the next release.

**Comment by stevage** [comment]
Hooray, thanks!
