### ISSUE TITLE
"Squash commit with previous" action in rebase view

### ISSUE THREAD

**Issue by ptomato** [divmain/GitSavvy#220]
We have "Squash commit with next", but I'd really like an equivalent of "fixup" from Git's interactive rebase mode — e.g., for squashing a small amendment into a large commit. Usually it's not possible to move the small commit up above the large one because the small commit may be fixing something that doesn't exist yet. And if we squash the large commit into the small one, we lose the large commit's commit message.

**Comment by divmain** [comment]
Hi @ptomato - if you use the rebase dashboard's `squash commit with next`, the two commit messages will be concatenated.  So you can `squash commit with next` and then `edit commit message` to get the effect you're looking for.  However, if there's a compelling reason, I'm open to adding something like Git's fixup - I just personally found it to be redundant given the combination of functionalities already present in the dashboard.

**Comment by ptomato** [comment]
@divmain That worked for me, thanks. It's a couple steps more than "fixup" but no big deal.

**Comment by divmain** [comment]
Great - if someone else happens upon this ticket and makes the same request, I'll put time into thinking through an alternative.

**Comment by maethu** [comment]
I would ❤️  to habe the `fixup` command from interactive rebase console.

**Comment by divmain** [comment]
Alright, seems like this is a reasonably popular idea, so I'm reopening.  Two thoughts:

- `fixup` would be identical in behavior to squash, except that the more recent commit's message would disappear
- `fixup from staged` would basically give you the ability to edit a commit in place.  Any changes currently staged would be automatically rolled into the selected commit.  That way you can avoid creating the temporary commit, moving it into place, and squashing.

I think the second option would have to include some rigorous protections, since we could have the equivalent of a merge conflict if a subsequent commit made changes in the same place later.  But I think just trying to `git apply` with enough hunk context would help considerably.

Thoughts?

**Comment by sentience** [comment]
I’d be happy with the simple `fixup` as a first step. I do the squash-and-then-edit-commit-message dance on a daily basis, and it’s gotten annoying enough that I often switch to another client (GitUp) to perform these.

`Fixup from staged` would be an amazing power-user feature, but like yourself I fear it would cause a subsequent commit to fail with a merge conflict in many cases, so you’d need to handle that. I’d say it should drop the Rebase dashboard into its interactive merge conflict resolution state on the subsequent commit. This sounds pretty tricky to implement, however, so in the meantime I’d vote for adding the simple ‘fixup’ command (which probably will require remapping the ‘define base ref’ shortcut to free up F).

**Comment by stoivo** [comment]
@sentience, I have a similar flow but uses some other commands. When you have staged files and do git amend previous commit the staged file will be added to the commit.

The rebase can be improved but the functionality is there.

**Comment by maethu** [comment]
> fixup would be identical in behavior to squash, except that the more recent commit's message would disappear

I'll use this often, it would be great to have this feature in gitsavvy

**Comment by sentience** [comment]
@stovio That works if the commit you wish to fix up is the most recent on your branch, but Fixup (like Squash) would be for when you are fixing an issue in an earlier commit, something I do frequently during code review of a branch.

**Comment by stoivo** [comment]
ahhh,

**Comment by asfaltboy** [comment]
By the way, not sure if anyone noticed this, but I sneaked in both `fixup` and `rebase-with-autosquash` into [the custom commands documentation][1]. 

[1]: https://github.com/divmain/GitSavvy/blob/master/docs/custom.md#examples

**Comment by sentience** [comment]
Nice one, @asfaltboy! I had to read up on `--autosquash` ([recommended reading here](https://robots.thoughtbot.com/autosquashing-git-commits)), but this is definitely an improvement for me!

**Comment by randy3k** [comment]
I have been experimenting the following command which does fixup and rebase with autosquash 
https://gist.github.com/randy3k/b70eedffb6a638b4299a05adeeed2c5d
