### ISSUE TITLE
Key bindings

### ISSUE THREAD

**Issue by andersennl** [divmain/GitSavvy#222]
Hi, I'm wondering if it is possible to bind the package's commands to keybindings? I couldn't find the typical sublime key bindings submenu for the package where I would normally find the available shortcuts, only the `git: xxx` commands in the command palette. Thanks.

**Comment by divmain** [comment]
Hi @andersennl, you should be able to create a `Default.sublime-keymap` file in your `User` package directory.  Most of the commands in GitSavvy's [default keymap](https://github.com/divmain/GitSavvy/blob/master/Default.sublime-keymap) are limited in scope to dashboards and the like.  But we leave it very open for users to add entries to their individual keymap files.  Does that answer your question, or are you looking for something more/different?

**Comment by andersennl** [comment]
Hi @divmain, thanks for the fast answer. And sorry, I just realized that my question wasn't clear enough. What I'm looking for is a way to open the (for example) 'git: status' dashboard via keyboard shortcut. Currently I would open the command palette via 'cmd + p' and then enter 'git: status' so that the status dashboard opens. This action I want to bind to a key.

**Comment by divmain** [comment]
The entry in your `User/Default.sublime-keymap` file would have an entry something like the following - replacing, of course, whatever key-binding you prefer.

```json
[
  { "keys": ["ctrl+shift+d"], "command": "gs_show_status" }
]
```

Under the hood, Sublime registers all `WindowCommand`s from every plugin globally.  This means that you can search the GitSavvy codebase for the functionality you like, and translate any `CamelCaseCommand` that you find (that inherits from `WindowCommand`) into `camel_case`.

However, most of the commands you'll be interested in are already [here](https://github.com/divmain/GitSavvy/blob/master/Default.sublime-commands) in the command-palette.  So search for the palette command you want to assign a key-binding to, find its `command` value, and create the corresponding entry in the `Default.sublime-keymap` file.

**Comment by divmain** [comment]
And if you still get stuck, feel free to reach out on the [Gitter channel](https://gitter.im/divmain/GitSavvy).  I'm not always online, but there are a handful of other GitSavvy users that may be able to help you.

**Comment by andersennl** [comment]
Thank you so much @divmain, this was exactly what I was looking for. And thanks a lot as well for the explanation regarding the `WindowCommands`, I always wondered how exactly that works.

**Comment by divmain** [comment]
Awesome, glad to help. :+1:

**Comment by max-mykhailenko** [comment]
@andersennl look at my config
```
{
    "keys": ["alt+shift+a"],
    "command" : "gs_commit",
    "args" : {
      "amend": true
    }
  },
  {
    "keys": ["shift+super+s"],
    "command" : "gs_show_status"
  },
  {
    "keys": ["shift+super+b"],
    "command" : "gs_show_branch"
  },
  {
    "keys": ["shift+super+c"],
    "command": "gs_commit", 
    "args": {
      "include_unstaged": true
    }
  }
```

**Comment by andersennl** [comment]
Thanks a lot @max-mykhailenko, here is the config I currently have:
```
  { "keys": ["alt+s"], "command": "gs_show_status" },
  { "keys": ["alt+d"], "command": "gs_inline_diff" },
  { "keys": ["alt+b"], "command": "gs_show_branch" },
  { "keys": ["alt+r"], "command": "gs_show_rebase" },
  { "keys": ["alt+g"], "command": "gs_log_graph" },
  { "keys": ["alt+h"], "command": "gs_log_graph", "args": { "all_branches": true } },
```
