### ISSUE TITLE
Warn when using `git: push (force)`

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#225]
Because of the way Sublime handles keyboard shortcuts through the shift-cmd-P menu, you can get this:

1. I want to force push. I type <kbd>Shift-Cmd-P</kbd>, `gpushf`, `<enter>` <kbd>enter</kbd>
2. Some time later, I want to do a normal push. I reflexively type <kbd>Shift-Cmd-P</kbd>, `gpush`, <kbd>enter</kbd>
3. Result: another force push, with no warning, no chance to abort.

Suggest having a confirmation. Force pushing is a rare event, and can be nasty, and is worth an extra click to confirm.

**Comment by stevage** [comment]
Nice one! Btw are you taking donations anywhere?

**Comment by divmain** [comment]
No, but thank you for the thought :)

**Comment by benmosher** [comment]
Man, this just bit me, too. Looking forward to the update. 😅

**Comment by divmain** [comment]
Sorry for the delay - next patch-version just went out.
