### ISSUE TITLE
Show Diff in a Panel (optionally)

### ISSUE THREAD

**Issue by pradyunsg** [divmain/GitSavvy#234]
It would be nice the git diff could be shown in a panel (like Unsaved Changes) instead of another view.

Also, possibly, this could be done for all commands, as in ST3 (to my not-so-vast knowledge) panels are very much like views except for close events which can be emulated by an event-listener listening for show_panel and hide_panel and maintaining a state.

Obviously, this introduces a new setting... `show_diff_panel` or even `use_panel_for` if used in a generic case.

**Comment by divmain** [comment]
Is this primarily a preference thing, or is there a demonstrable use case where this is better than the current behavior?  I'm not opposed to the idea, but this is far enough down in the list of priorities that it is unlikely to happen unless someone submits a PR.  And even then, I may not go for it if it adds measurable complexity to the codebase.  However, if you can think of situations where this is important, that might make a difference.

**Comment by pradyunsg** [comment]
Well, it's main "advantage" is that on (almost?) all split/non-split view configurations, the user will be able to see code along with the diff. While this should be trivial to do for output-only commands, the input only one will need some effort.

That PR could come from me if I get the time. :smiley:

**Comment by divmain** [comment]
Fair enough.  Just be sure that:

- [ ] it does not add significant complexity, and
- [ ] the default behavior remains the same

My only reason for the blatant word of caution is because I'd hate for you to put in a ton of effort just to have it shot down.  But if you have some time and want to give it a try as an experiment, I'd be glad to take a look through the PR and entertain the idea.

**Comment by pradyunsg** [comment]
Ok! Will try if I get the time...

**Comment by stoivo** [comment]
@pradyunsg, any progress? Or should we close the issue?

**Comment by pradyunsg** [comment]
Nope. I couldn't get the time. 

If someone else takes this on, I won't mind. But I'm don't thing I'm going to get around doing this anytime before May. Just a lot of studies have been piled up. :stuck_out_tongue:

**Comment by pradyunsg** [comment]
I'm not gonna come around to do this. So, if you feel like it, do close this. :)
