### ISSUE TITLE
external diff

### ISSUE THREAD

**Issue by cvogt** [divmain/GitSavvy#235]
would be nice to be able to call external diff programs. The build-in diff of GitSavvy can only do so much, external tools that focus on diff exclusively have more time to nail that, e.g. show which parts of a line changed like kdiff3.

**Comment by divmain** [comment]
GitSavvy actually does display which parts of the line changed, when you use the `inline diff` view.  There is, however, an outstanding bug in Sublime Text 3 that prevents it from being displayed correctly on a Mac.

Adding specific functionality to call an outside diff program is out of scope for GitSavvy.  On the other hand, it should be simple enough for you to add a [custom command](https://github.com/divmain/GitSavvy/blob/95d8d8818b9c42e998ea8eb2586cd4dd7834ee6d/docs/README.md#custom-commands) to accomplish what you're looking for.

**Comment by stoivo** [comment]
I think we we create some kind of diff toggle quite easy since git have a flagg called `--word-diff`
example 

```
$ git diff file
diff --git a/file b/file
index dd72235..a89dec4 100644
--- a/file
+++ b/file
@@ -1,6 +1,6 @@
 set :stage, :production
 set :rails_env, 'xxx'
-set :branch, 'live'
+set :branch, 'tmp_live'
 set :domain, 'xxxx.no'

$ git diff --word-diff file
diff --git a/file b/file
index dd72235..a89dec4 100644
--- a/file
+++ b/file
@@ -1,6 +1,6 @@
set :stage, :xxx
set :rails_env, 'xxx'
set :branch, [-'live'-]{+'tmp_live'+}
set :domain, 'xxx.no'
```

maybe we can press W in a diff-"view". Not only diffs but commits too. than toggle `--word-diff`

**Comment by divmain** [comment]
@stoivo, we're already displaying bolded sections where a word was added/removed/changed.  The limitation is a bug in Sublime itself.

**Comment by stoivo** [comment]
yeah, in inline diff. This could be adding this for a normal diff view and commit view.
