### ISSUE TITLE
When viewing inline-diff, shortcut to open the file at specific line

### ISSUE THREAD

**Issue by guncha** [divmain/GitSavvy#236]
First of all, thank you for all of your work on GitSavvy! It's been an amazing boost to my productivity. Here's a feature request that I think many would appreciate:

Before every commit, I always review all the changes using the inline-diff view and the stage/unstage hunk shorcuts are great for this. Sometimes though the change needs some extra attention and I really wish there was a way to open the file in question at the specific line using the same open shortcut as on the status page.

Thoughts?

**Comment by divmain** [comment]
Agreed, that's a good idea.

**Comment by stoivo** [comment]
:+1: I thought about adding it myself but did't get the time yet, would you like to add it?

**Comment by stoivo** [comment]
t thought about `e` for edit.

**Comment by ddevlin** [comment]
`o` for open would be more consistent with Status and Rebase views.

**Comment by guncha** [comment]
:+1: for `o`

**Comment by stoivo** [comment]
I made it, It is working good for me :smile:

**Comment by divmain** [comment]
Thanks @stoivo!  I made a few changes, so now any cursor position is supported.

**Comment by ddevlin** [comment]
Thanks @guncha for suggesting this, and @stoivo and @divmain for the implementation, just tried it, it's a great addition!

**Comment by stoivo** [comment]
:sparkles:
