### ISSUE TITLE
git status picking up wrong repository when using npm link

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#239]
Here's my setup:

* `.../nationalmap/terriajs` is my main repo
* `.../nationalmap/cesium` is a submodule
* `.../nationalmap/terriajs/node_modules/terriajs-cesium` is npm-linked back to `.../nationalmap/cesium` (via two symlinks)

In Sublime I:

1. I opened `.../nationalmap/terriajs`. 
2. I navigate to `.../nationalmap/terriajs/node_modules/terriajs-cesium/Source/Scene/WebMapServiceImageryProvider.js`. 
3. I make changes to this file. 
4. I go (via the cmd+shift-P menu) to "git status".
5. It brings up a status page for `.../nationalmap/terriajs` (which shows no changes, because `node_modules/...` is ignored).

Expected: Brings up status page for `.../nationalmap/cesium`.

To be clear, this works as expected on the command line:

```
.../nationalmap/terriajs/node_modules/terriajs-cesium $ git status
On branch terriajs
Your branch is up-to-date with 'origin/terriajs'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Source/Scene/WebMapServiceImageryProvider.js
```

**Comment by divmain** [comment]
Interesting.  I've seen strangeness with symlinked directories as well.  Try this for me:

1. Open `.../nationalmap/terriajs/node_modules/terriajs-cesium/Source/Scene/WebMapServiceImageryProvider.js`
2. Open the Sublime console and type `view.file_name()`
3. What path is given?

To determine the repo path, GitSavvy first checks the `file_path` of the open view.  If that fails for some reason, it falls back to the first of any folders added to the project.  If that fails, the following error is thrown: `ValueError("Unable to determine Git repo path.")`.  Barring any bugs, if the path used is incorrect, Sublime is probably providing something unexpected.

I've noticed this on occasion in my own use, usually with symlinked directories.

**Comment by stevage** [comment]
Hmm, my directory structure has changed a bit since filing, and I don't seem to be able to reproduce it. It's possible I made a mistake in reporting. I'll definitely check that value and report if I can make this happen again.

**Comment by divmain** [comment]
That _also_ doesn't surprise me, as the problem occurred intermittently for me.  As in, Sublime would sometimes give me the symlinked path, and sometimes the real path.  To keep things tidy, I'm going to close this issue - _however_, if this occurs again, please see if you can get the view's `file_name`.  That should help determine whether this is truly a Sublime issue.
