### ISSUE TITLE
next/previous file shortcuts in Status view not highlighted correctly

### ISSUE THREAD

**Issue by sentience** [divmain/GitSavvy#245]
The Status view’s keyboard reference contains entries for the new next/previous file shortcuts:

```
  [.] move cursor to next file
  [,] move cursor to previous file
```

Unfortunately, the syntax highlighting doesn’t recognise the `.` and `,` characters, so they are not highlighted as the other shortcuts are.

**Comment by divmain** [comment]
Hmm - this is unexpected.  1) what version of GitSavvy are you using?  This should have been fixed/added with [this change](https://github.com/divmain/GitSavvy/commit/8f71d24b94f225d569aaf18b7dcdd1b9e2da6413).

**Comment by sentience** [comment]
Ah! I’m using the latest release, and it seems like this fix just hasn’t been released yet. Thanks!
