### ISSUE TITLE
pull non-tracking branch: `Invalid refspec 'HEAD -> origin/master'`

### ISSUE THREAD

**Issue by benmosher** [divmain/GitSavvy#246]
I have a `develop` branch that is not tracking any origin branch.

![screen shot 2015-09-29 at 11 39 06 am](https://cloud.githubusercontent.com/assets/3709196/10169364/b5c0ad40-669e-11e5-82dc-d4fa54ab3b4c.png)

When I try to get it up to date with `origin/master` using the `origin/HEAD -> origin/master` option via the `git: pull` action (after selecting `origin`), I get this in the console:
```
`/usr/local/bin/git pull origin HEAD -> origin/master` failed with following output:

fatal: Invalid refspec 'HEAD -> origin/master'
```

I would expect the behavior to be the same as selecting `origin/master`.

**Comment by divmain** [comment]
I have never seen the `origin/HEAD -> origin/master` option show up before.  This was definitely not accounted for.  Can you take a log of all the operations and post it here?

- `GitSavvy: enable logging`
- `GitSavvy: view recorded log`
- `GitSavvy: disable logging`

**Comment by benmosher** [comment]
I see it when I use `git branch -r` in a terminal:

```
➜  eslint-plugin-import git:(master) git branch -r     
  import-core/common-interop
  import-core/import.resolve
  import-core/master
  origin/HEAD -> origin/master
  origin/bugfix/windows-case-sensitivity
  origin/master
  origin/no-unused
```

I thought it might be a weird BitBucket thing, but this output is from one of my GitHub-hosted projects.

I will grab logs as you have directed, at some point.

In case it's relevant: `git --version` := 2.2.0, on OSX.

**Comment by benmosher** [comment]
I think this is the relevant log output:

```json
  {
    "type": "git", 
    "stdout": "  origin/HEAD -> origin/master\n  origin/auto-incremental\n  origin/byod\n  origin/concept_modal\n  origin/feature/cloudconnect\n  origin/feature/fastgrid\n  origin/feature/suggestion-types\n  origin/feature/test-resurrection\n  origin/feature/transforms2\n  origin/feature/viz\n  origin/master\n  origin/preview\n  origin/rql-sandbox\n  origin/salesforceCC\n", 
    "stderr": "", 
    "stdin": null, 
    "command": [
      "branch", 
      "-r", 
      "--no-color"
    ]
  }
```
Something about my `git` installation or repo is returning that `origin/HEAD -> origin/master` line.

(I'd include the rest but I'd need to sanitize it first)

**Comment by benmosher** [comment]
I can't find any evidence of a flag to prevent that pointer from being printed, but 
```
git branch -r | grep -v "\->" 
```
seems to work by suppressing it. (pretty hacky, though.)

**Comment by divmain** [comment]
Very interesting!  I have not run across this before.  But it should be a straightforward fix!
