### ISSUE TITLE
User settings: inline_diff colors not parsing correctly

### ISSUE THREAD

**Issue by rpbaptist** [divmain/GitSavvy#249]
This package is really awesome. Thank you so much.

I have a problem setting the inline diff colors. I added this to my GitSavvy user settings:
```json
  "colors": {
      "inline_diff": {
          "add_foreground": "#61C95B",
          "add_background": "#232323",
          "add_foreground_bold": "#61C95B",
          "add_background_bold": "#232323",
          "remove_foreground": "#DE5151",
          "remove_background": "#232323",
          "remove_foreground_bold": "#DE5151",
          "remove_background_bold": "#232323"
      }
  }
```

What happens is that the foreground colors are used as background. The actual foreground color is my default foreground color.

It seems that the colors I set for foreground are used for background and the colors I set in background are simply ignored.

**Comment by stoivo** [comment]
We think there is a bug in Sublime core when it comes to these inline_diff colors. The bug is about nesting colors inside others. 

So we can't really help you :cry:

**Comment by rpbaptist** [comment]
Thanks for your response. I managed to work around it, I noticed when I installed the former Git package I used for ST3 the highlighting was working as expected. I simply copied the syntax highlighting files from that package into my own directory and then removed the package.
