### ISSUE TITLE
Feature request: keyboard shortcuts to jump between status,branch,tags,graph

### ISSUE THREAD

**Issue by burbanczyk** [divmain/GitSavvy#261]
Hi
I'm using GitSavvy in my sublime workflow and I think it would be very handy to be able to jump between git:status git:branch git:tags git:graph either using keys like 1 2 3 4 or(and) TAB.
The main benefit would be less open tabs and a lot less keystrokes to jump from status to graph or branch.

**Comment by max-mykhailenko** [comment]
Good idea! It will be dashboard page with one hotkey.

**Comment by stoivo** [comment]
I think we have decided not to add have to many global keystrokes, since than you may have some conflicts with other packages. But you are free to add you own keystrokes:

if you do to `Preferences` > `Key bindings - User` 
and add the following.
```json
[
  { "keys": ["control+1"], "command": "gs_show_status" },
  { "keys": ["control+2"], "command": "gs_show_branch" },
  { "keys": ["control+3"], "command": "gs_show_tags" },
  { "keys": ["control+4"], "command": "gs_log_graph" },
  { "keys": ["control+5"], "command": "gs_show_tags", "args": { "all_branches": true } },
]
```
or you may like to have it on F2 ..
```json
[
  { "keys": ["F2"], "command": "gs_show_status" },
  { "keys": ["F3"], "command": "gs_show_branch" },
  { "keys": ["F4"], "command": "gs_show_tags" },
  { "keys": ["F5"], "command": "gs_log_graph" },
  { "keys": ["F6"], "command": "gs_show_tags", "args": { "all_branches": true } },
]
```

**Comment by burbanczyk** [comment]
Yes I know I can do that in preferences but, that's not exactly what I meant. 
Adding key bindings would open new tab each time and it's still a two key combination.

What I'm proposing is that 1 2 3 4 keys wouldn't be global - they would work only on GitSavvy. This way you would utilize only one tab in sublime and have everything you need one keystroke away.

**Comment by stoivo** [comment]
So you want to switch from status to branch on the same tab with one keystroke?

If we just close status view and open branch view? Than you get the behavior you want?

**Comment by burbanczyk** [comment]
Pretty much, if the tab and focus stays in place then yes.
I'm imagining workflow like this: 
I'm on git:status, i use (A) to add files, then (c) to commit, (ctrl+enter) to submit that commit. Next i want to jump to git:graph I use (4),  Everything is fine so I use (2) to jump to git:branch next i choose a branch and hit (c) to checkout.
That's approx. 6 keystrokes Instead of:
(A), (c), (ctrl+enter), (ctrl+shift+p) (git gra...+enter), (ctrl+shift+p) (git bra...+enter), (up, down), (c)

**Comment by stoivo** [comment]
Let's see what @divmain have to say.

**Comment by alextegelid** [comment]
I second this idea! With GitSavvy growing and the number of views increasing with it, it'd be like a general GitSavvy dashboard that one could switch views within. 

The switch action could be prefixed like the stash commands are. 
Spacebar for example:

`[spacebar]+1` => Status view 
`[spacebar]+2` => Branch view 
`[spacebar]+3` => Rebase view 
And so on

**Comment by divmain** [comment]
Alrighty, you can now `TAB` between interfaces.  As it is, the `git: tags` and `git: graph` views are not true interfaces, so they're not included in this enhancement.  However, I've added the necessary subtasks to the related tickets - when that gets done, you'll be able to tab to them also.

If you prefer to explicitly open a particular dashboard, you can add a setting to your user key-bindings like so:

```json
{
    "keys": ["spacebar", "1"],
    "command": "gs_show_branch",
    "args": { "commandeer_active_view": true },
    "context": [
        { "key": "setting.git_savvy.is_interface", "operator": "equal", "operand": true }
    ]
}
```

**Comment by sentience** [comment]
Having a play with this, and it’s really lovely. Thanks so much!

**Comment by burbanczyk** [comment]
Yeah, thanks guys! hoping to be able to switch to tags and graph any time soon!

**Comment by divmain** [comment]
I've ported over tags dashboard to interface pattern, and you can now `Tab` between status, branches, rebase, and tags.  The graph view is used much less often than these dashboards, so I'm not making it tab-able.  Hopefully this is still considerably cleaned-up for you @burbanczyk!

**Comment by burbanczyk** [comment]
Great thanks! Sorry to hear you won't be adding graph support. Is it your personal experience that graph is used less, or do you have GitSavvy statistics? For example I use status and graph all the time, graph very often, tags from time to time and rebase much less. Unfortunately I don't know python so I can only hope you'll change your mind :)

**Comment by stoivo** [comment]
I don't like using  tab circle, since If pas the one I have to circle around again.

I think a good solution is to use numbers to switch. And have this a setting
```json 
{
  "quick_switch_from_interfaces":{
}

}

**Comment by divmain** [comment]
Alrighty, I've added some configurability that should satisfy the concerns.  The tab cycle now includes the graph view @burbanczyk.  The order and inclusion of the tab cycle is also now configurable, using the `tab_order` sublime setting.  You can include/exclude and reorder to fit your preference.

@stoivo, I won't be adding global number key-bindings because **1)** I don't want hidden key-bindings in the dashboards, and **2)** adding reference for each of those numbers would add a lot of noise to accommodate an edge case.

_However._  @stoivo @alextegelid, it is setup so that users can create key-bindings themselves.  You can use `1` for status dashboard, and so on, in your local config.  It should look like this:

```json
{
    {
        "keys": ["1"],
        "command": "gs_tab_cycle",
        "args": { "target": "status" },
        "context": [
            { "key": "setting.git_savvy.tabbable", "operator": "equal", "operand": true }
        ]
    },
    {
        "keys": ["2"],
        "command": "gs_tab_cycle",
        "args": { "target": "branch" },
        "context": [
            { "key": "setting.git_savvy.tabbable", "operator": "equal", "operand": true }
        ]
    },
    {
        "keys": ["3"],
        "command": "gs_tab_cycle",
        "args": { "target": "rebase" },
        "context": [
            { "key": "setting.git_savvy.tabbable", "operator": "equal", "operand": true }
        ]
    },
    {
        "keys": ["4"],
        "command": "gs_tab_cycle",
        "args": { "target": "tags" },
        "context": [
            { "key": "setting.git_savvy.tabbable", "operator": "equal", "operand": true }
        ]
    },
    {
        "keys": ["5"],
        "command": "gs_tab_cycle",
        "args": { "target": "graph" },
        "context": [
            { "key": "setting.git_savvy.tabbable", "operator": "equal", "operand": true }
        ]
    }
}
```

**Comment by stoivo** [comment]
Thx, I was probably explaining myself bad. I don't want you to add a global key-binding. The reason I wanted to have this as  settings is so we can add something like this for all the views that have this feature. 
```
  ###################             
  ## SWITCH ACTION ##             
  ###################             

  [1] Status                      
  [2] Branch
  [3] rebase
  [4] Tag 
  [5] Graph
```
And than this section will be generated so it fit the user. 

If anything is unclear than ask, sry for my bad explanation before

**Comment by divmain** [comment]
No problem, I understood :)

I don't want to add key-bindings to all of those views - and key-binding menus for those actions - for the reasons I stated above.  If users would like to use these (or other) keybindings, instead of the customized `Tab` cycling, it is a natural fit for `User/Default.sublime-keybindings`.

That's the strength of Sublime, from my perspective - plugins can provide sane defaults, but allow the user to flexibly customize their setup to suit how they work.

**Comment by stoivo** [comment]
I agree. :sparkles: Than I think tab-ing is done. 
One thing I notice is if I have  open a Status view and one Branch view. Open and start tabbing. I am going to end up merging those two into one single view. It is not an issue, but now you know about it.

![http://g.recordit.co/u9eB60Uspn.gif](http://g.recordit.co/u9eB60Uspn.gif)

**Comment by divmain** [comment]
Yeah I noticed that too.  Can't think of a fantastic alternative - we definitely only want on STATUS view for a particular repo at one time.  So tabbing into STATUS from wherever else should result in only one STATUS dashboard.

I guess we will see if anybody cares, and if they can think of a better alternative.

**Comment by stoivo** [comment]
Yes  :+1:

**Comment by burbanczyk** [comment]
@divmain tabing works great now. Adding configuration is definitely a good move. Now working with GitSavvy is awesome.
Although I personally think configurable key bindings (1,2,3,4,5) by default would be handy because cycling can be sometimes but that's not a problem - I can configure that on my own. Maybe an example should be added to the documentation in case other users would like to have shortcuts too.
Again many thanks!
