### ISSUE TITLE
feature github open repo and repo issues in browser

### ISSUE THREAD

**Issue by atomi** [divmain/GitSavvy#264]
Small feature request. Can we get a
```github: open repo on remote``` 
and
 ```github: open issues on remote```

**Comment by stoivo** [comment]
`github: open repo on remote` would open a list where you could choose remote and then these urls will be opened in browser?
    Github        -> https://github.com/divmain/GitSavvy
    Bickbucket -> https://bitbucket.org/<username>/<packagename>/overview

and similar to  issues?

**Comment by atomi** [comment]
Yeah

**Comment by atomi** [comment]
Also as you know ```.git/config``` file has an entry for ```url``` under ```[remote "origin"]```.

**Comment by stoivo** [comment]
url = https://github.com/divmain/GitSavvy.git
url = git@github.com:divmain/GitSavvy.git

**Comment by stoivo** [comment]
i think we can use this and get a good result
```
$ git remote -vv
ddevlin	git@github.com:ddevlin/GitSavvy.git (fetch)
ddevlin	git@github.com:ddevlin/GitSavvy.git (push)
origin	git@github.com:stoivo/GitSavvy.git (fetch)
origin	git@github.com:stoivo/GitSavvy.git (push)
upstream	https://github.com/divmain/GitSavvy (fetch)
upstream	https://github.com/divmain/GitSavvy (push)
```

**Comment by atomi** [comment]
Yeah the idea is for it to work similar to Github's hub [browse command](https://github.com/github/hub/tree/d45511c7aaca000c49ac1a2ef1a162a6153b0c44#git-browse) But it looks like they build the web url from params https://github.com/github/hub/blob/aa63aa67f2375f552d19cd715016570f3d044edf/github/project.g#L30 
I think in this case  ```git remote - vv``` is the easiest and safest way to get the web url.

**Comment by divmain** [comment]
The codebase already includes functionality to determine the URL, so this will be pretty straightforward.  I should have time to add this later today.

**Comment by stoivo** [comment]
Note: We should have support for Github.com, GitLab.com and bitbucket.org and flash a note the user if the repo in note hosted on any of these servers.

**Comment by divmain** [comment]
@stoivo, GitLab and BitBucket are not yet supported.  That is tracked in #40.
