### ISSUE TITLE
Babun/Cygwin w/ subl - [WinError 267] The directory name is invalid

### ISSUE THREAD

**Issue by atomi** [divmain/GitSavvy#270]
If I use ```subl mygitrepo``` to open ```mygitrepo``` in Sublime from Babun/Cygwin I get the error:
```[WinError 267] The directory name is invalid```

But if I add the folder using drag and drop or through the menu, GitSavvy works fine.

It appears that it might be an issue with using ```subl.exe``` or using ```subl.exe``` from a ```mintty``` prompt is returning a Cygwin style directory path and GitSavvy is unable to find it.

I tested with both the official Git for Windows installation and the Cygwin git.exe in bin path. Both produce the same error.

**Comment by atomi** [comment]
I just tested this with ```sublime_text.exe``` as well and it causes the same problem if executed from Cygwin.

**Comment by divmain** [comment]
Hey @atomi.  Can you paste the full error (including call stack if available)?  Also, can you open the Sublime terminal (`CTRL-~`) and show me the output of `window.folders()`?  It should looks something like this:

```
>>> window.folders()
['/Users/daleb/Library/Application Support/Sublime Text 3/Packages/GitSavvy']
```

It may be necessary for me to dive a little deeper, if neither of these results in something useful.  In case that's the way things go, can you give me details about your computer configuration so I can try to reproduce?  Should include

- type of machine (real or VM)
- Windows version
- Sublime version
- GitSavvy version
- *nix emulation configuration (vanilla Cygwin from the site? packaged up somehow?)
- terminal configuration (same questions as above)

Thanks!

**Comment by divmain** [comment]
Don't have what I need to reproduce this, so closing.  Feel free to re-open if you are still experiencing issues.  Thanks!
