### ISSUE TITLE
Feature request: blame current line

### ISSUE THREAD

**Issue by ptomato** [divmain/GitSavvy#271]
It would be nice to have a command to show the commit (commit message and diff) that was responsible for the current line according to `git blame`.

**Comment by stoivo** [comment]
https://github.com/divmain/GitSavvy/blob/master/docs/history.md#git-blame-current-file
I you are in Git Blame and press `SUPER-Enter` (`CTRL-Enter` in Windows)  you will open the commit

**Comment by stoivo** [comment]
![http://g.recordit.co/6ZzrXwnccA.gif](http://g.recordit.co/6ZzrXwnccA.gif)

**Comment by stoivo** [comment]
close this one? @divmain
