### ISSUE TITLE
Missing argument for git flow feature finish

### ISSUE THREAD

**Issue by hectorsq** [divmain/GitSavvy#272]
When I select **flow: feature finish**  from the command palette GitSavvy asks me for confirmation showing correctly the branch name, selecting Yes fails with the following message:

```
/usr/bin/git flow feature finish` failed with following output:
usage: git flow feature [list] [-v]
       git flow feature start [-F] <name> [<base>]
       git flow feature finish [-rFk] <name|nameprefix>
       git flow feature publish <name>
       git flow feature track <name>
       git flow feature diff [<name|nameprefix>]
       git flow feature rebase [-i] [<name|nameprefix>]
       git flow feature checkout [<name|nameprefix>]
       git flow feature pull <remote> [<name>]

Missing argument <name>
``` 

However **flow: feature start** works fine

**Comment by asfaltboy** [comment]
Kindly provide some details:

Your environment configuration
```bash
$ git config -l | grep flow
gitflow.origin=asfaltboy
gitflow.branch.master=master
gitflow.branch.develop=develop
gitflow.prefix.feature=feature/
gitflow.prefix.release=release/
gitflow.prefix.hotfix=hotfix/
gitflow.prefix.support=support/
gitflow.prefix.versiontag=v
```

And your feature branch name, for example:
```bash
$ git branch -va | grep feature
  feature/more-unmerged-options                   c08dc81 Fix: display all types of unmerged conflicts
  remotes/asfaltboy/feature/more-unmerged-options c08dc81 Fix: display all types of unmerged conflicts
```

**Comment by hectorsq** [comment]
```
$ git config -l | grep flow
gitflow.branch.master=master
gitflow.branch.develop=develop
gitflow.prefix.feature=feature/
gitflow.prefix.release=release/
gitflow.prefix.hotfix=hotfix/
gitflow.prefix.support=support/
gitflow.prefix.versiontag=
```

```
$ git branch -va | grep feature
* develop                                           a22b42d Merge branch 'feature/rename-folders' into develop
  feature/fix_demo_data                             d9269d4 Add agenda_id to tasks.
  feature/indications                               59d5875 Add description and generic name to medicament data
  feature/peoplesoft                                b80619b Simple and complex examples
  feature/rails-4.2                                 e93b513 First attempt to migrate to Rails 4.2.0
  remotes/origin/develop                            a22b42d Merge branch 'feature/rename-folders' into develop
  remotes/origin/feature/aseguradoras               b1276f7 Data added for facturation perform
  remotes/origin/feature/clean_views                46a3131 Added "values" to Glasgow scale
  remotes/origin/feature/create-task-with-resources b22b5d7 Remove unused variable.
  remotes/origin/feature/edit                       6359639 Fix file name
  remotes/origin/feature/maintenance                d43b54e Add expediente and erase lugar of nota_urgencia
  remotes/origin/feature/new_notes                  896efff Add base.pdf to hoja_alergias
  remotes/origin/feature/paper_views                00b894b Fix views to work with the printed
  remotes/origin/feature/pdf_socioeconomico         4246238 Change pdf structure and fix print.yml
  remotes/origin/feature/signatures                 b6135cc Create sign_document
```

The feature branch that I could not finish inside the editor was feature/rename-folders, however I could finish the feature in the terminal without any problem.

It seems to me that GitSavvy is not passing the branch name to git.

**Comment by asfaltboy** [comment]
Sorry, I see the problem now; [the code](https://github.com/divmain/GitSavvy/blob/12738af4b993fea0d5ea993195a6f7c845845331/core/commands/flow.py#L229) currently assumes you have latest [`git-flow`](https://github.com/nvie/gitflow), where [feature name is optional]((https://github.com/nvie/gitflow/blob/develop/git-flow-feature#L49)), and does not pass a feature name when a feature branch is currently checked out; nor does it on a release, support or hotfix branch for that matter.

A possible fix could be to enforce passing the current branch name (sans-prefix) in all finish cases. A pull request is of course appreciated.

Meanwhile, as a workaround, you could upgrade to latest gitflow. You'll also enjoy some [other new features](https://github.com/nvie/gitflow/blob/develop/Changes.mdown#042) (many more unfortunatley are undocumented).

**Comment by divmain** [comment]
@asfaltboy, we'll either need to explicitly define the minimum-supported git-flow version, or make sure older versions of git-flow are supported.  I'm fine with either one - gitflow is not something I use, but I imagine it is relatively simple to upgrade?

**Comment by asfaltboy** [comment]
I believe their [install script](https://github.com/nvie/gitflow/wiki/Mac-OS-X#curl) pulls HEAD from repo and [copies each required file](https://github.com/nvie/gitflow/blob/develop/contrib/gitflow-installer.sh#L71) to destination (using [install](http://linux.die.net/man/1/install)).

**Comment by hectorsq** [comment]
Confirmed, I removed a homebrew based installation (version is 0.4.1)  and installed git flow manually.
Now it works fine.

**Comment by divmain** [comment]
Alright, so this ticket should be:

- [ ] make `0.4.1` the minimum supported version, since it is the latest released version
- [ ] fix `git flow feature finish` to operate correctly under `0.4.1`

I'm not comfortable forcing users to circumvent their package control system (brew, or whatever else) so that git flow operates correctly under GitSavvy.
