### ISSUE TITLE
Rewrite to Interface

### ISSUE THREAD

**Issue by stoivo** [divmain/GitSavvy#275]
Rewrite view to be 'interface'-style 
- [ ] Tags
- [ ] Graph
- [ ] Commit

Also remember to add `TAB`-ing between them #261  
I can't remember if there is some other that should be change to 'Interface'-style

**Comment by divmain** [comment]
Tag dashboard changes are tracked in #88.  Commit view port is tracked in #50.  I'm not convinced Graph view should be ported to interface, but open to hearing if there are good reasons.

**Comment by stoivo** [comment]
The only reason I have to port Graph is if we want to have it in the `TAB`-sircle.

**Comment by divmain** [comment]
Hey @stoivo, I mentioned [here](https://github.com/divmain/GitSavvy/issues/261#issuecomment-152043341) that I don't think the Graph view is used often enough to warrant `TAB` functionality.  The `TAB` becomes less useful the longer it takes for you to cycle to the view you're looking for.
