### ISSUE TITLE
Add `git: add and commit` command

### ISSUE THREAD

**Issue by aarohmankad** [divmain/GitSavvy#278]
This command seems more intuitive to type than `git: commit including unstaged files`. The functionality is there, just a different alias.

I currently have a custom command set to this alias.

**Comment by divmain** [comment]
If this changed, would likely change to `git : quick stage all files and commit` to match existing `git : quick stage current file and commit`.  Will wait to see if anyone chimes in on this.

**Comment by divmain** [comment]
Haven't seen any other feedback, so I think I'm going to close this.  I don't really have a preference - one of the alternatives may be better, actually.  However, the project is old enough at this point that making changes may interrupt users' dev flow.
