### ISSUE TITLE
Edit Commit Message in Rebase Mangles Title Line

### ISSUE THREAD

**Issue by utahmike** [divmain/GitSavvy#284]
The title line is not properly modified when changed during Edit Commit Message during interactive rebase. Typical behavior is to ignore all edits to the title line. Running GitSavvy v2.7.1 on Sublime Text Build 3083.

**Comment by divmain** [comment]
Hi @utahmike.  Can you give me an example?  I regularly use that feature and am not sure what you're describing.

**Comment by utahmike** [comment]
Sure. Will screen shots suffice?

**Comment by divmain** [comment]
Absolutely, thanks!

**Comment by utahmike** [comment]
Here you go. I hope this is helpful.

— Mike

**Comment by utahmike** [comment]
I can send you the repo if that would help.

**Comment by stoivo** [comment]
I can not see any screenshot, maybe it don't work to send it on mail?

**Comment by utahmike** [comment]
Here you go, I put it on my web server: http://www.aspengrove.com/gitsavvy.zip <http://www.aspengrove.com/gitsavvy.zip>

**Comment by utahmike** [comment]
I also just noticed that assuming you don’t call your own special version of git, I am using the version that come with OS X Yosemite:

/Applications/Xcode.app/Contents/Developer/usr/bin/git
git version 2.4.9 (Apple Git-60)

— Mike

**Comment by divmain** [comment]
Converted screenshots to PNG:

![00-forgot-to-capitalize](https://cloud.githubusercontent.com/assets/5016978/13312671/5ed2ad70-db4d-11e5-9a0c-c7363a57da12.png)
![01-edit-to-capitalize](https://cloud.githubusercontent.com/assets/5016978/13312672/6028b7d2-db4d-11e5-9da3-2cf4ce79babd.png)
![02-ok -good-changes](https://cloud.githubusercontent.com/assets/5016978/13312674/62787fe0-db4d-11e5-993a-da22ac385591.png)
![03-hit-super-ret-what_s-with-my-title_](https://cloud.githubusercontent.com/assets/5016978/13312676/648273b8-db4d-11e5-93d4-e0cba0f60a29.jpg)
![04-let_s-look-again -where-is-the-_f__](https://cloud.githubusercontent.com/assets/5016978/13312677/65d7e1f8-db4d-11e5-847e-3b1294d761f2.jpg)

**Comment by divmain** [comment]
This must have been resolved as part of an unlinked ticket.  I remember fixing this awhile back.  Closing, but please re-open if it continues to be a problem.
