### ISSUE TITLE
Feature: Support rebase onto current branch

### ISSUE THREAD

**Issue by alextegelid** [divmain/GitSavvy#286]
Often I find myself rebasing onto the current branch using `git rebase -i HEAD~<n>` to modify the `<n>` previous commits. 

I think this would be an awesome feature. Is it doable in the rebase dashboard?

**Comment by asfaltboy** [comment]
I believe the rebase dashboard tries to accomplish common scenarios that you would usually accomplish in an interactive `git rebase` (squashing a commit with next commit, squashing all visible commits, rewording a commit message and change order of commits).


While it also lets you choose a "base ref" for a commit (sort of like the `HEAD~[n]` in your example above only using a branch as the starting point), it does not currently allow to pick a base using an arbitrary hash, nor from <n> commits from tip (aka `~`).

I also think it would be a nice idea to add this functionality.

**Comment by divmain** [comment]
Give it a try and let me know how you like it.  It should support arbitrary refs - commits, `HEAD~5`, tags, branches, etc.

**Comment by alextegelid** [comment]
I'll try it out next week when I'm back at the office, hard at work :) Thanks so far!

**Comment by asfaltboy** [comment]
Sweet! Works very nice for me.

<img width="500" alt="screen shot 2015-11-13 at 9 51 51 pm" src="https://cloud.githubusercontent.com/assets/321520/11157318/0985f4f0-8a51-11e5-9791-51e960e81589.png">
