### ISSUE TITLE
Can't open the status interface. "NoneType is not iterable"

### ISSUE THREAD

**Issue by alextegelid** [divmain/GitSavvy#289]
When I select `git: status`from the palette, nothing visibly happens and this is output in the console:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "/Users/alextegelid/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/interfaces/status.py", line 19, in run
    StatusInterface(repo_path=self.repo_path)
  File "/Users/alextegelid/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 194, in repo_path
    return self._repo_path()
  File "/Users/alextegelid/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 234, in _repo_path
    throw_on_stderr=throw_on_stderr
  File "/Users/alextegelid/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/git_command.py", line 90, in git
    if args[0] in close_panel_for:
TypeError: argument of type 'NoneType' is not iterable
```

I've just cloned a fresh copy of master onto my new laptop, and that's when this started happening.

Might be similar to this:
https://github.com/divmain/GitSavvy/issues/128
And possibly fixed like this:
https://github.com/divmain/GitSavvy/pull/130
https://github.com/divmain/GitSavvy/commit/36119c98c98127b7c55abc43e1403248385be015

**Comment by alextegelid** [comment]
I don't know if this might be related, but whenever I open the command palette this is output to the console:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 463, in is_visible_
    raise ValueError("is_visible must return a bool", self)
ValueError: ('is_visible must return a bool', <GitSavvy.core.commands.flow.GsGitFlowFeatureFinishCommand object at 0x11204b510>)
```
14 times with different memory locations, if that's what's right at the end: `object at 0xXXXXXXXX`.
I'm guessing it's one for every GitSavvy command in the palette.
```

**Comment by divmain** [comment]
Yikes, okay I'll take a look!

**Comment by divmain** [comment]
Re: the first problem, do you have [this line](https://github.com/divmain/GitSavvy/blob/a20dd69fe19d7a37e09f061e0325bd0f8a5a5d96/GitSavvy.sublime-settings#L84-L84) in your settings file?  It should be in the master settings file - only case I can think of that would result in it _not_ being there is if 1) you pulled from master, 2) you had edited the `GitSavvy.sublime-settings` in the package instead of in `User/`, and 3) you resolved any conflicts by using your local version.

If there's some other condition that would result in this happening, I'm very eager to learn about it.  In any case, I can add a little more safety to the relevant piece of code so that this doesn't error out if the setting is missing.

**Comment by divmain** [comment]
The second problem looks very similar - your settings file must be missing [this entry](https://github.com/divmain/GitSavvy/blob/81bf7e2047ee5e44bd6be5a785bc129d76368c61/GitSavvy.sublime-settings#L170-L170).

There's a fix for both of these now in master, so feel free to pull it down.  But I am still very interested to know how your machine ended up with this configuration.

**Comment by alextegelid** [comment]
Firstly, the fix works. Thanks!

It's fairly simple to explain how this happened.

I bought a new laptop a few days ago, installed Sublime Text and symlinked /User to my backed up copy in Dropbox. In that backup, my `GitSavvy.sublime-settings` says (and have been saying for a long while):
```

{
    "prompt_before_destructive_action": true,
    "dev_mode": false,

    "show_commit_diff": true,

    "show_panel_for": [ "push", "pull" ]
}
```

I've been using the latest version from master lately and have never changed the default `GitSavvy.sublime-settings` (never encountered any conflicts while pulling). 
I then started noticing these problems right from the initial setup on the new laptop.

Having checked the default `GitSavvy.sublime-settings` just now I can confirm that both settings you mention is in there.

Let me know if you need something else :)

**Comment by divmain** [comment]
That works - thanks for letting me know!  Sounds like it isn't something that'll likely occur again, and the safeguards should prevent an issue otherwise.
