### ISSUE TITLE
git: log not working, on selection of a commit nothing happens

### ISSUE THREAD

**Issue by laggingreflex** [divmain/GitSavvy#292]
The git:log option shows commits but selecting them (hitting enter) does nothing, the menu just disappears. And if at the same time I have the console panel opened up it logs "Quick panel unavailable". Enabled debug logging and here's the generated log json: http://pastebin.com/RtuM3iP1

Windows 8, Sublime text 3, already tried with a fresh install of everything, and on different repositories.

(love it btw)

**Comment by divmain** [comment]
Whoa, that's very strange.  In doing a quick search, it sounds like this was an expected issue with Sublime Text 2, but I didn't find anything recent.  Have you noticed similar problems when a second quick panel is supposed to open immediately after a first?  I have a potential fix in mind, but want to understand the scope of the problem.

**Comment by laggingreflex** [comment]
I've only just installed it so I don't know much. What other command are supposed to bring up a second quick panel?
I'm also not very well versed in Python or Sublime dev, so please bear with me. Is command pallet a quick panel? If so, then the only other command that I can think of that brings up another panel right afterwards is the Package manager, with list/install/disaable packages commands, and no, there's no issue there.

**Comment by divmain** [comment]
Fair enough - and thanks for the detailed information.  If I put up a branch with a potential fix, would you be able to pull it down and test it?  I'm not able to reproduce the issue on any of my environments (including Windows 8), so confirmation would be good before merging into master.

**Comment by laggingreflex** [comment]
Absolutely

**Comment by laggingreflex** [comment]
I was still on build 3065, and updating to the latest fixed this. 

Really sorry for the trouble, I know I should be using the latest anyway, but I was really waiting for [this](https://github.com/SublimeTextIssues/Core/issues/913) to be fixed.

In the changelog I see that they fixed something related to quick_panel in build 3080: "API: Window.show_quick_panel() will now scroll to the selected item when shown", so maybe that was probably causing this.

**Comment by divmain** [comment]
Gotcha - glad this is working for you.  Really had me baffled :)
