### ISSUE TITLE
"commit_on_close" not working

### ISSUE THREAD

**Issue by laggingreflex** [divmain/GitSavvy#293]
Regular commit works with ctrl+enter but when I activate the `"commit_on_close": true` option and close the commit window (with a commit message written) it fails to commit. 

Console panel logs the following:

    Traceback (most recent call last):
      File "core.commands.commit in C:\Program Files\Sublime Text\Data\Installed Packages\GitSavvy.sublime-package", line 131, in run_async
    IndexError: list index out of range

**Comment by laggingreflex** [comment]
I changed the contents of the file `core/commands/commit.py` line 131: 

        # commit_message = view_text.split(help_text)[0]
        commit_message = "view_text"

Essentially I hardcoded the commit message to a simple text "view_text". It gave this error:

    `C:\Program Files\Git\bin\git.EXE commit -q -F -` failed with following output:
    On branch master
    Changes not staged for commit:
        modified:   a.txt

    no changes added to commit

It seems the commit message just isn't going through. It should've been appended after `-F -`
Could it be getting lost due the the tab being closed?
(with the ctrl-enter it just works, it makes a commit with "view_text" message)

**Comment by laggingreflex** [comment]
I see that there's a different class `GsCommitViewCloseCommand` (same file core\commands\commit.py:176) for performing commit on close, but all of above is being executed in the class `GsCommitViewDoCommitCommand`. 

Could it be some setting configured incorrectly somewhere that's actually supposed to link this (the second class) with the close_tab command?

**Comment by divmain** [comment]
Hey @laggingreflex - I'll take a look at this tonight.  Strange that you're running into so many problems that haven't come up for anyone else.  You're using ST3 on Window 8, correct?  In any case, I'll look into this.  Thanks for reporting!

**Comment by laggingreflex** [comment]
So yeah you were right about finding it strange, the other issue was due to me using an older build, sorry about that! 

But this issue still seems to be present. ST 3 build 3083 (win 8.1). Same error, and I did all above debugging again with same results.
