### ISSUE TITLE
Move cursor when commit is moved in rebase dashboard

### ISSUE THREAD

**Issue by divmain** [divmain/GitSavvy#296]

**Comment by HughMacdonald** [comment]
This would mean that moving a commit up, say, 5 commits would just be a matter of tapping "u" 5 times. In conjunction with #208, this would hopefully be very responsive.

**Comment by divmain** [comment]
@HughMacdonald sorry for the wait on this - both this and #208 should be good to go.  Give it a try and let me know if you run into any issues.
