### ISSUE TITLE
Queue up actions in Rebase dashboard

### ISSUE THREAD

**Issue by divmain** [divmain/GitSavvy#297]

**Comment by divmain** [comment]
**Possible alternative:** Add functionality to move commits as a block - this should introduce fewer edge cases, and the result of the action should be reversible if any of the Git operations fail.

**Comment by HughMacdonald** [comment]
I do like the alternative of being able to move a block.

I was thinking that it would be nice to be able to mark one or more contiguous commits and have them highlighted to flag which ones are marked. Then "u" and "d" would move these, and, in addition, maybe a "move" command where you move the cursor to a point between two other commits and in one command move the whole block without having to go a commit at a time.

This matches up with my `vim` process, which currently involves moving individual commits around using `dd` and `P`. Except this would allow doing multiple commits at once, which would be even better!
