### ISSUE TITLE
Endless loop: "GitSavvy was unable to parse Git output as UTF-8"

### ISSUE THREAD

**Issue by alextegelid** [divmain/GitSavvy#300]
I accidentally pressed `e` (diff) on a GNU MO file in the status view. That seems to have started som kind of endless loop of popups saying:
```
GitSavvy was unable to parse Git output as UTF-8. Would you like to use the fallback encoding specified in GitSavvy settings? Text may not appear as expected.
```
It doesn't matter whether I press `Cancel` or `Fallback?`. 

_Edit:_ Force quitting Sublime Text and restarting helped.

The popup:
<img width="555" alt="endless" src="https://cloud.githubusercontent.com/assets/7058721/11502759/fb441d96-983c-11e5-90f8-1f1375eb0e35.png">

In exposé:
<img width="835" alt="all of them" src="https://cloud.githubusercontent.com/assets/7058721/11502758/fb43a988-983c-11e5-85fb-921c816e94f7.png">
Yes, I might have gone on a clicking frenzy 😅

**Comment by divmain** [comment]
Whoa.  That... is not correct.  Thanks for reporting!

**Comment by asfaltboy** [comment]
Since [gettext MO files are binary](http://www.gnu.org/software/gettext/manual/gettext.html#Binaries), by default `git diff` should produce output such as:

```diff
diff --git a/django.mo b/django.mo
new file mode 100644
index 0000000..166f912
Binary files /dev/null and b/django.mo differ
```

However, I could reproduce this behavior by explicitly requesting a binary file to be diffed as test:

    # .gitattributes
    *.jpg diff

@alextegelid regardless of issue, you should probably check if you have set *.mo file to be diffed as text anywhere in git settings (.gitattributes, repo config or global). If you did, you probably don't want to do that like that.

**Comment by alextegelid** [comment]
I can't remember having set anything like that, but I'll definitely check it out. Thanks @asfaltboy

**Comment by divmain** [comment]
Looks like whenever you close the error modal by clicking `OK`, the diff view regains focus and tries to refresh.  When it does that, the offending git command runs again, and you are again prompted.  Boo.

A universal solution to this is not occurring to me at the moment, so for now I've added a somewhat inelegant but otherwise acceptable fix.

**Comment by alextegelid** [comment]
(A well commented fix at that 😂)

Oddly enough when trying to intentionally diff an mo-file (namely the exact same file as the initial post) I'm getting this output, similar to what @asfaltboy mentioned:
```
diff --git a/language/sv_SE.mo b/language/sv_SE.mo
index deb8117..2201654 100644
Binary files a/language/sv_SE.mo and b/language/sv_SE.mo differ
```
By manual override in `.gitattributes` ( `*.mo diff` ) I can confirm that the popups does indeed stop after clicking OK in the second dialog. Good job!

**Comment by divmain** [comment]
Thanks for checking!

**Comment by alextegelid** [comment]
Just want to nudge this since I'm experiencing it again. I'm at the latest commit in master as usual.

**Comment by divmain** [comment]
Sorry to hear that.  Re-opening, and I'll take a look!

**Comment by divmain** [comment]
@alextegelid is there a public repo I could pull down to test this?  I've been playing around with it and cannot reproduce.

**Comment by alextegelid** [comment]
I'll look into that. Unfortunately the one in question is work for a client
of mine.

fre 22 jan. 2016 kl. 10:55 skrev Dale Bustad <notifications@github.com>:

> @alextegelid <https://github.com/alextegelid> is there a public repo I
> could pull down to test this? I've been playing around with it and cannot
> reproduce.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/divmain/GitSavvy/issues/300#issuecomment-173865019>.
>
-- 
Alexander Tegelid
070-508 49 90

**Comment by alextegelid** [comment]
No matter how hard I try I can't reproduce this either... I must've done something really stupid when this reappeared. Sorry for cluttering the issue tracker, feel free to close this again 😅

**Comment by divmain** [comment]
No worries!  Text encoding is a messy business, and hard to handle all possible cases.  If you do notice something reproducible, please reopen, as it is probably effecting others users too!

**Comment by stoivo** [comment]
Try  https://github.com/stoivo/sublime_bug_demo/. 
Clone, edit 'encoding'(yes, the file is called encoding) and try to open inline diff.

**Comment by alextegelid** [comment]
For me that works according to the solution @divmain introduced. Upon clicking `Cancel` a panel pops up with this message `'utf-8' codec can't decode byte 0xe5 in position 112: invalid continuation byte`.
