### ISSUE TITLE
Rebase : "Squash commit with next" doesn't match "git rebase -i" functionality

### ISSUE THREAD

**Issue by HughMacdonald** [divmain/GitSavvy#301]
Currently, it feels to me that combining commits in GitSavvy doesn't act in quite the same way as doing it using `git rebase -i`

Using `git rebase -i`, commits are always considered to be combined with a previous commit (using `squash` or `fixup`, so the first commit is considered the master.

Initial git repository setup

    git init
    touch master
    git add master
    git commit -m "master"
    git checkout -b rebase_test
    touch a
    git add a
    git commit -m "A"
    touch b
    git add b
    git commit -m "B"
    git rebase -i master

Standard `git rebase -i` workflow

The rebase will give you

    pick 324c79e A
    pick 72ac10f B

To squash the B commit into the A commit, change this to

    pick 324c79e A
    s 72ac10f B

The suggested commit message is then:

    # This is a combination of 2 commits.
    # The first commit's message is:
    
    A
    
    # This is the 2nd commit message:
    
    B

Ad the end of this, you'll be left with one commit, with the commit message

    A
    B

And with metadata based on the original `A` commit, including author and date/time.

If I do the same thing in GitSavvy, your initial rebase page looks like this:

    REBASE:  rebase_test --> master (aa88cb5)
    STATUS:  Ready.

    ┳ (aa88cb5)
    ┃
    ·  513d7b0  A
    ┃
    ·  f90a87c  B
    ┃
    ┻

If I go to the "A" commit and press "q", it'll squash it into the following commit.

After this, the commit message of the new commit is:

    B
    A

(the opposite order to before)

And the metadata (author and date/time) are from the B commit rather than the A commit.

I would suggest changing functionality to be "Squash into previous" and also add "Fixup into previous", which will ignore the current commit's message and just use the previous commit. Personally, my workflow is to give the first commit in a branch for a class a decent commit message, and later commits, as I know they'll be rebased later, will just get a message like "MyClass : Update", and then when I rebase to move the commits together and use `fixup` to combine them, it'll drop all of the later commit messages and just use the first one.

I hope this all makes sense - please let me know if you're not sure about anything I've written.

Cheers

**Comment by divmain** [comment]
@HughMacdonald, I've been polishing the rebase dashboard a bit.

- `squash into next` has become `squash into previous`
- commit meta-data uses the destination commit rather than the source commit
- commit message ordering is consistent with `git rebase -i` behavior
- cursor moves to the new, squashed commit

Let me know if you run into any problems.
