### ISSUE TITLE
Rebase : doesn't work if there isn't a project

### ISSUE THREAD

**Issue by HughMacdonald** [divmain/GitSavvy#302]
When working through the steps of an issue on Git Rebase that I was writing, I discovered something slightly odd.

While `git status` works fine if I haven't created a Project (does it look at the path for the current file, maybe?), `git rebase` gives me a blank page until I actually have a project.

This really confused me for a while - it'd be nice for it to make the same assumption as `git status` for which repository we're in.

**Comment by divmain** [comment]
Hmm, you'll have to include more repro steps for this one.  There's only a single mechanism for detecting which git repository to talk to, so I'm not sure what you're describing.

**Comment by HughMacdonald** [comment]
Here you go - this just worked for me:

    > mkdir git_test
    > cd git_test
    > git init
    > touch a
    > git add a
    > git commit -m "A"
    > touch b

    Open 'b' in Sublime Text
    Command Palette -> "git status"

<img width="755" alt="screen shot 2015-12-04 at 14 49 09" src="https://cloud.githubusercontent.com/assets/625512/11592415/444b814a-9a96-11e5-82fa-cfe04dba9925.png">

    Close Status tab
    Command Palette -> "git rebase"

<img width="755" alt="screen shot 2015-12-04 at 14 49 18" src="https://cloud.githubusercontent.com/assets/625512/11592431/510051b8-9a96-11e5-8672-7a9681535a1f.png">

    Close Rebase tab
    Project -> Save Project As -> "git_test/git_test.sublime-project"
    Command Palette -> "git rebase"

<img width="755" alt="screen shot 2015-12-04 at 14 49 31" src="https://cloud.githubusercontent.com/assets/625512/11592442/619cf0bc-9a96-11e5-9b65-2af7c9c5421f.png">

**Comment by HughMacdonald** [comment]
BTW - this is all on OSX 10.10.5 using git version 2.4.9 (Apple Git-60)

**Comment by divmain** [comment]
_Weird._  Thank you, I'll take a look.
