### ISSUE TITLE
reset --hard?

### ISSUE THREAD

**Issue by aristidesfl** [divmain/GitSavvy#304]
How to to do reset --hard?

**Comment by ddevlin** [comment]
The default reset mode used by GitSavvy is `--mixed` ([see here for more info](https://git-scm.com/docs/git-reset)). 

You can get the same result as `reset --hard` by first doing `git: reset` or `git: reset (reflog)` and then pressing `D` on the GitSavvy status dashboard to discard all unstaged changes.

@divmain: I'm considering adding the reset mode as a configuration option (defaulting to --mixed), but in the case of `--hard` we will want to dynamically wrap the call to git with @util.actions.destructive, something like this:

```python
class GsResetCommand(GsLogCommand):

    def on_hash_selection(self, index):
        if index == -1:
            return
        if index == self._limit:
            self._pagination += self._limit
            sublime.set_timeout_async(lambda: self.run_async(), 1)
            return

        gitsavvy_settings = sublime.load_settings("GitSavvy.sublime-settings")
        reset_mode = gitsavvy_settings.get("reset_mode") or "--mixed"

        def do_reset():
            self.git("reset", reset_mode, self._hashes[index])

        if reset_mode == "--hard":
            do_reset = util.actions.destructive("perform a hard reset")(do_reset)

        do_reset()
```

From my reading of https://git-scm.com/docs/git-reset, `--hard` is the only destructive mode. What do you think?

**Comment by aristidesfl** [comment]
I would not expect the reset to be --hard by default, but a separate reset --hard command?

**Comment by ddevlin** [comment]
How about something like this?

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/912471/11570068/1e891fc0-99ed-11e5-88be-a84f5212be1d.gif)

I'd probably add a setting to enable this extra step, and retain `--mixed` as the default to keep things simple for users who aren't familiar with reset modes.

**Comment by aristidesfl** [comment]
looks very good

**Comment by divmain** [comment]
@ddevlin, I like it - push that up as a PR, and I'll merge!
