### ISSUE TITLE
Status view not updated after commit

### ISSUE THREAD

**Issue by aristidesfl** [divmain/GitSavvy#314]
After making a commit starting from the status view, the staged list doesn't disappear, even after pressing `r` to refresh. Only after evoking the command palette the view gets updated.
I have set `"commit_on_close": true` in the user preferences, don't know if this is relevant to the problem.

**Comment by divmain** [comment]
Can you check in the console to see if any errors are present?  The `commit_on_close` setting is very likely involved somehow.

**Comment by aristidesfl** [comment]
```
NpmRunArbitraryWorker on_close
closed view not in list
NpmRunArbitraryWorker on_close
closed view not in list
Traceback (most recent call last):
  File "core.commands.commit in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 147, in run_async
AttributeError: 'NoneType' object has no attribute 'focus_view'
```

**Comment by aristidesfl** [comment]
Before that I also had a problem where de commit did not succeed:

```
NpmRunArbitraryWorker on_close
closed view not in list
NpmRunArbitraryWorker on_close
closed view not in list
Traceback (most recent call last):
  File "core.commands.commit in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 131, in run_async
IndexError: list index out of range
```

**Comment by divmain** [comment]
@asfaltboy, do you have time to take a look at this?

**Comment by asfaltboy** [comment]
I've mentioned this in [a comment to #298](https://github.com/divmain/GitSavvy/pull/298#issuecomment-161556346), i.e the  event listener behavior of a window closed by user seems broken. I'll try to debug in the weekend.

**Comment by divmain** [comment]
Ended up being relatively straightforward.  @aristidesfl, can you pull down the latest to confirm this is now working?

**Comment by aristidesfl** [comment]
Seems to be working, thank you :)
