### ISSUE TITLE
Dashboard keyboard shortcuts

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#315]
Only recently discovered that you can Tab through dashboards. There are quite a few (and that may grow), so how about keyboard shortcuts that work on any dashboard to consistently get to the same other one. As a simple idea, just pressing <kbd>1</kbd> etc:

* 1: status
* 2: branches
* 3: graph
* 4: rebase
* 5: tags

(Yes, I'm also voting for rejigging the current order).

**Comment by divmain** [comment]
See #261 for previous discussion.  Most likely of interest to you, take a look at the `tab_order` option in `GitSavvy.sublime-settings`.  And if you want specific key-bindings so you don't have to rotate through, see how in [this comment](https://github.com/divmain/GitSavvy/issues/261#issuecomment-152301061).

The focus was on adding as much flexibility as possible without re-inventing what Sublime gives us for free.
