### ISSUE TITLE
Help at top of Graph page

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#316]
Are there operations you can perform on the Graph view? How about a short summary of the keyboard shortcuts available at the top? I see that <kbd>,</kbd> and <kbd>.</kbd> navigate commits, but guessing there are other things you can do here - and now way to discover them. (Obvious things to want to do are diff, checkout, reset...)

**Comment by asfaltboy** [comment]
If you open gitsavvy help while in the Graph view it will show contextual information (somewhat), at the bottom of that help page you can see the section on "Graph" which lists the available shortcuts.

There was [some discussion in the past](https://github.com/divmain/GitSavvy/issues/184) on showing more contextual help in some views.

А possible solution would be to somehow add a reminder that contextual help is available for pages where keyboard shortcuts aren't listed by default.

**Comment by stevage** [comment]
Hmm. I did spend a few moments looking to see if there was some help somewhere - didn't occur to me to do Cmd-P "gitsavvy help" though. (And even after reading your tip above, I still didn't twig for a while that the results of "gitsavvy help" are dependent on the current view you're in - very unintuitive IMHO).

One of the things I love about GitSavvy (and why I despise Git) is it gives you easy prompts to what to do next, without having to think a lot. 

Is there particular resistance to the idea of a brief summary of the available commands? Something like:

```
[,], [.]   navigate commits                  [m] toggle commit info
[enter] view commit                          [cmd-enter] checkout commit
```

**Comment by divmain** [comment]
I'm open to the idea.  In some of the views (like inline-diff) it is difficult to add extra content.  However, that's not really the case here, if we use regions correctly.  Is there anything beyond what's in the text snippet above that you'd find useful?

**Comment by stevage** [comment]
Oh, cool. Well, I'm not aware of anything else you can do on that screen - but if there is, then yes. :) Oh, and probably Tab/Shift-Tab.

**Comment by stevage** [comment]
Ok, I now discover (by looking at the source) that there is both a single-branch and all-branch mode, and that the view you get by cycling dashboards is single-branch. So I'd probably suggest including that information in the header, possibly with a keystroke to switch:


```
SHOWING: current branch (master)
[,], [.]   navigate commits                  [m] toggle commit info
[enter] view commit                          [cmd-enter] checkout commit
[b] alternate current/all branches
```

**Comment by stevage** [comment]
Some tentative work here: https://github.com/divmain/GitSavvy/compare/master...stevage:316-graph-ui?expand=1

Suspect that it should be refactored as a UI class.

**Comment by divmain** [comment]
Yes, would like this to be a UI subclass.  But this initial work is good.  Would you like to keep at it, or should I put it into my own queue?

**Comment by stevage** [comment]
​Realistically, I won't get to this again until January, so very happy for
you to take it over before then.

**Comment by stoivo** [comment]
@stevage, this probably went off your radar. You still interested in adding this functionality?

**Comment by stevage** [comment]
Yeah, sorry about that. I'm pretty terrible at picking things back up once I put them down. I'm about to head off for another 5 weeks of inactivity, so if someone else is willing to take this over, that would be better.

**Comment by stoivo** [comment]
Than we will keep the issue open, we will look at this issue later.

**Comment by aziz** [comment]
I'm on it.
