### ISSUE TITLE
"Open a pull request" feature

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#318]
After pushing a branch, my current workflow is to then open a browser window, navigate to the Github repo, then click the "Compare & pull request" link when it pops up.

It looks like the URL is pretty simple: 

`https://github.com/ORGANISATION/REPO/compare/BRANCHNAME?expand=1`

Maybe we should even automatically offer to do this when pushing a branch for the first time:

1. "No upstream branch set, want to set one?"
2. Yes, push...
3. "Want to open a pull request?"

**Comment by asfaltboy** [comment]
I'm not sure I want to be asked this every time I push a branch to remote, as most of my time is spent outside of github.

I do however consider "open pull request" as a valid feature idea. My current flow is to either navigate via browser, or use [`git pull-request`](https://github.com/github/hub#git-pull-request) to open a PR on github from terminal.

**Comment by stevage** [comment]
Ok, good to know (and thanks for the link to hub - didn't know that existed!). Maybe a slightly different approach would be to have "Open pull request" start by pushing. (Would you ever *not* to want to push your latest changes before opening the pull request?) Then your flow would look something like

1. commit
2. "github: open pull request"
3. "No upstream defined, where do you want to push to?" > origin/myrepo
4. Pushing...
5. Pull request browser window opens.

**Comment by stoivo** [comment]
I think that we should create GitHubSavvy where we can create all kind of views that is related to GitHub. Maybe a `GitHub: pull request`-interface, where we can open diff, write comments, etc ... 


Also there are many user that don't use Github. There are many users that like GitLab, BitBucket or just a git server(no GUI).

**Comment by stevage** [comment]
Well, all the Github commands are already quite well segregated in the
interface and in the code - no reason there couldn't be GitLab, BitBucket
etc features also included.

Also, GitSavvy can tell by looking at the remotes which tools are
applicable - no need to propose a Github pull request for a remote which is
hosted on GitLab?

The problem with separating things out into separate plugins is
discoverability - most users will probably have no idea that there even is
a GithubSavvy, and won't think to search for one.

**Comment by stoivo** [comment]
We can recommend installing one of these in [messages/install.txt](https://github.com/divmain/GitSavvy/blob/fe2457fce846857bd846a7b76ffe95d50b0b93ed/messages/install.txt). This file is we be opened when someone install GitSavvy

**Comment by divmain** [comment]
Awhile ago, we were throwing around ideas for high-level GitHub integration - things like managing issues from Sublime, and opening and commenting on PRs - stuff like that.  After exploring the possibilities for awhile, I ultimately realized that I was trying to re-invent GitHub.  And unfortunately, it seemed that the UX would inevitably be worse.

The current strategy is to focus on the local dev experience, and let GitHub be GitHub (BitBucket and GitLab is still on the list to be added).  Asking _"Does GitHub do this already?"_ can serve as a litmus test for whether an integration feature adds value or not.  Also, not everybody uses GitHub, so I've intentionally left those commands separate from the core `git: ...` commands.

As far as this ticket is concerned, here's what makes the most sense to me:

1. user opens command palette and types `github: open pull request`
2. if an upstream is not configured, prompt to configure
3. if the local branch is ahead of the upstream, prompt to push
4. open the browser

**Comment by stevage** [comment]
Yep, I'm pretty happy with the "launch a Github browser window" approach.

To spell out what about GitSavvy gives me the most value: reducing the friction of interacting with each project's Github repo. In particular:

- doing everything I need to do from within my editor, using the keyboard
- getting rich context about the current situation to increase confidence I'm doing the right thing
- predictable keystroke combinations for standard tasks to minimise cognitive load
- hints and prompts as to what I probably want to do next

So this approach meets most of those needs pretty well.

(And of course someone can still write a Github plugin that moves that support directly into Sublime if they want...)

**Comment by randy3k** [comment]
https://github.com/temochka/sublime-text-2-github-tools has a similar feature. It should be great to implement something similar.

**Comment by divmain** [comment]
Alrighty, this seems like a good way forward.  @randy3k, feel free to open a ticket (or a PR) for the other feature.  I'd prefer the more explicit `github: show history for current file`.

**Comment by randy3k** [comment]
Now, it is easy to create simple pull requests in Sublime Text in 4 steps.

1. `git: checkout new branch` for the pull request
2. `git: quick stage and commit current file` and type the commit
3. `git: push` and choose the upstream (assume that the remote is set)
4. `github: create pull request` and submit the PR via the browser


PS: There is a related feature that we are still missing: the ability to fork a repo, something similar to [git fork](https://github.com/github/hub#git-fork).

**Comment by divmain** [comment]
@stevage, is the `github: create pull request` feature that @randy3k introduced good enough for your purposes?  Or would you like a little more polish somewhere before this ticket is closed out?

**Comment by stevage** [comment]
Oh! Sorry I didn't see this earlier. Just tested now and it works well.

I guess the only other useful "polish" would be a choice of where to PR to, but you can make those choices through the Github UI, so it's really fine as is. Thanks!
