### ISSUE TITLE
Pushing a single tag does not work

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#319]
The tag dashboard has 2 commands `[p] push to remote` and `[P] push all tags to remote`.

I assume the first command is intended to push a specified tag; however invoking it seems to perform `git push origin` and this fails (unless we had the tag checked out).

"Branch interface" has a similar behavior, but I think it uses the branch from the line the cursor is currently on, and "Tag interface" should attempt to do the same.

**Comment by divmain** [comment]
Fixed, thanks for the report!
