### ISSUE TITLE
git: 'flow' is not a git command

### ISSUE THREAD

**Issue by rimmer333** [divmain/GitSavvy#321]
I have a strange issue with git flow commands in GitSavvy. I have git-flow installed (on a Mac from Homebrew), and I use it from command line all the time. I have enabled flow commands in GitSavvy, but whenever I call one of those from command drawer in Sublime upon an already flow-enabled repo, it ends up with this in a popping console on the bottom:
```
`/usr/bin/git flow version` failed with following output:

git: 'flow' is not a git command. See 'git --help'.

Did you mean one of these?
	reflog
	show

```
, as if I didn't have git-flow. Calling this same `/usr/bin/git flow version` from command line results in a perfectly legit
```
0.4.1
```

I don't run Sublime as a different user or root, I am a single user on this Macbook. `ls -lha /usr/local/bin/git-flow` results in a very usual
```
lrwxr-xr-x  1 myusername  admin    37B 23 июл  2014 /usr/local/bin/git-flow -> ../Cellar/git-flow/0.4.1/bin/git-flow
```

So, I'm clueless as to what could be wrong here.

**Comment by divmain** [comment]
Have you installed a new version of `git` with Homebrew?  If so, it is likely that Sublime is using the Git packaged with OS X, whereas git flow is setup for the Git installed by Homebrew.  The easiest way to resolve this is to modify the `git_path` in `GitSavvy.sublime-settings`.  Give this a try, and let me know what happens.

**Comment by rimmer333** [comment]
Man, you're quick to react! Unfortunately, that is not the case. I don't have git installed as a Homebrew package, and I always had the system git path set in my settings:

```
Last login: Sun Dec 13 21:15:06 on console
~ » which git
/usr/bin/git
~ » brew list
ansible			curlftpfs		ffmpeg			gettext			haxe			jpeg			libgpg-error		libtool			multimarkdown		objective-caml		pcre			rbenv			tmux			x264
autoconf		elixir			fontconfig		git-flow		help2man		lame			libimobiledevice	libusb			mysql			openssl			phantomjs		readline		tor			xvid
automake		eot-utils		fontforge		glib			hub			legit			libplist		libxml2			neko			ossp-uuid		pidof			ruby-build		unixodbc		xz
bdw-gc			erlang			freetype		gmp			icu4c			libevent		libpng			libyaml			nettle			osxfuse			pixman			spidermonkey		usbmuxd			yasm
cairo			f3			fuse4x			gnupg			imagemagick		libffi			libtasn1		memcached		nspr			p11-kit			pkg-config		sshfs			wget
cmake			faac			fuse4x-kext		gnutls			ios-webkit-debug-proxy	libgcrypt		libtiff			mercurial		ntfs-3g			passenger		postgresql		texi2html		wxmac
~ » cat ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/GitSavvy.sublime-settings
{
	"show_git_flow_commands": true,
	"git_path": "/usr/bin/git",
	"show_commit_diff": true,
    "inline_diff_auto_scoll": true,
    "commit_on_close": true
}
```

**Comment by divmain** [comment]
Only thing I can think of here is that `/usr/local/bin/` is not in your `PATH` for dock apps.  This is separate from your path in the terminal.  OS X has changed the way you set the global path with basically every version that's been released.

I'm on Yosemite, and you can set a global path (for all apps and all users) by running `sudo launchctl config user path <my path setting>` and restarting the machine.  I don't think finder respects `~/.profile` or `/etc/paths` anymore, although you could try editing them just to make sure.

Finally, you might also look at [Fix Mac Path](https://github.com/int3h/SublimeFixMacPath), a plugin that ensures the Sublime run context matches whatever you'd have in your bash terminal.  I think the only downside there is that it may add start-up time to Sublime - I haven't tried it, so I'm not sure.

**Comment by asfaltboy** [comment]
confirmed this is required it seems:

```bash
PATH="" /usr/bin/git flow
git: 'flow' is not a git command. See 'git --help'.

Did you mean one of these?
	reflog
	show
```

**Comment by divmain** [comment]
@rimmer333, I'm going to close this one out.  Let me know if tweaking your path doesn't resolve.

**Comment by rimmer333** [comment]
Yup, Fix Mac Path seems to do it, flow commands are now perfectly fine. Thanks!
