### ISSUE TITLE
Eight-character SHAs not properly highlighted in UI views

### ISSUE THREAD

**Issue by sentience** [divmain/GitSavvy#323]
Occasionally, a Git SHA is displayed with eight characters instead of seven. For example, in the Rebase view:

![rebase__murmur_ _culture_amp](https://cloud.githubusercontent.com/assets/89772/11801833/bb320928-a33d-11e5-8c0f-af3a66b74be3.png)

I’m not sure if the bug is the length of the SHA or the lack of highlighting for the extra character, but there’s obviously something wrong.

**Comment by ddevlin** [comment]
Hi @sentience, Git short refs are the shortest unambiguous prefix of the full 40 character SHA1 ref of a commit, with a minimum length of 7. Seeing a longer one here isn't a git bug, it means you have two or more refs starting with `49090f1`. The fact that it isn't syntax highlighted correctly is a GitSavvy bug.
