### ISSUE TITLE
Navigating past the end of git: graph crashes plugin_host

### ISSUE THREAD

**Issue by txtsd** [divmain/GitSavvy#334]
![Screenshot of error](http://i.imgur.com/AxYCfmU.png)
```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 372, in on_text_command
    v = sublime.View(view_id)
RuntimeError: maximum recursion depth exceeded while calling a Python object
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```
Perhaps this is because the graph file has a blank line at the end? I have my ST3 set so all files have an empty line at the end on save.

OS: Archlinux
ST3: 3095
GitSavvy: 2.8.1 from Package Control

**Comment by stoivo** [comment]
Hmm, I can not reproduce it. 
Can you send me the steps you use to reproduce this? or make a screen recording?

**Comment by divmain** [comment]
I've been unable to reproduce this also.  Please re-open the issue if you can provide us with repro steps.  I don't mind throwing together an ArchLinux VM either, if that's necessary.

**Comment by txtsd** [comment]
@divmain @stoivo 
1. Open `git: graph` (current or all branches, doesn't matter)
2. Use `,` and `.` to navigate
3. Go past the last entry to the blank line
4. plugin_host will crash

**Comment by divmain** [comment]
Hey @txtsd, I misunderstood.  Thanks for the repro steps, a fix is now in master.

**Comment by txtsd** [comment]
Thanks for the speedy fix :)
