### ISSUE TITLE
Show status.

### ISSUE THREAD

**Issue by wilsonmiz** [divmain/GitSavvy#34]
Can we have a new feature that show repo status in bottom left-hand corner of Sublime Text Window?

**Comment by divmain** [comment]
I don't see why not.  @wilsonmiz, do you have anything particular in mind beyond branch name and ahead/behind?

**Comment by benregn** [comment]
I'd vote for something similar to [Git-StatusBar](https://github.com/randy3k/Git-StatusBar) which is a reduction of what [Git](https://github.com/kemayo/sublime-text-git) shows.

**Comment by wilsonmiz** [comment]
This is what I wanted, thank you @benregn ! But wish it to be able to integrate into GitSavvy. @divmain

**Comment by p3lim** [comment]
Would it be (technically) possible to move this to the right instead?

The left is already cluttered by output and other information about the view, and without the capabilities of icons like in Atom (atleast I don't think there is a way of adding icons to the status bar), it's a bit messy.

**Comment by divmain** [comment]
@p3lim - as far as I know, this is not supported.  See `set_status(key, value)` [here](https://www.sublimetext.com/docs/3/api_reference.html#sublime.View).

**Comment by p3lim** [comment]
In that case, please make the status feature optional.

**Comment by divmain** [comment]
Can do.
