### ISSUE TITLE
Package Control

### ISSUE THREAD

**Issue by JamesJosephFinn** [divmain/GitSavvy#343]
Weird. "gitsavvy" is not reachable via package control. I do:
```
Command Palette >> Package Control: Install Package >> 
```
and begin typing "gitsavvy", but fuzzy searching returns nothing.

**Comment by JamesJosephFinn** [comment]
Sorry, I installed it last week, and forgot all about it. doh! it's been a long week.

**Comment by divmain** [comment]
No problem!  Let me know if anything comes up.
