### ISSUE TITLE
git push resulting in "fatal: could not read Username"...

### ISSUE THREAD

**Issue by cvax** [divmain/GitSavvy#346]
When I try to do a git push I get this error
```fatal: could not read Username for 'https://github.com': Invalid argument```

Here is the full message:
```
`c:\program files\git\cmd\git.EXE push` failed with following output:

bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument
```

**Comment by cvax** [comment]
Figured it out. Had to save a credential to git for gitsavvy to work.

**Comment by stoivo** [comment]
Glad you made it and come back if there are anything we can help with.

**Comment by hnbeck** [comment]
Hi cvax
what exactly you have done by "saving git credentials" ? I've the same problem although I have an valid git API token configured in user settings

Cheers

Hans

**Comment by stoivo** [comment]
Hi, @hnbeck please open an issue with your problem.

And add the details for os and what you want to accomplish. 

git API token? Github personal token?
