### ISSUE TITLE
Manage remotes

### ISSUE THREAD

**Issue by wldcordeiro** [divmain/GitSavvy#347]
It would be nice to be able to add, remove and manage remotes from the branch view.

**Comment by stoivo** [comment]
Would you like to have a own small interface or have a toggle option in branch interface? like toggle remotes.

**Comment by wldcordeiro** [comment]
I think toggling would be useful, especially if you could toggle some remotes to show and others not (use case: in my team we add each other's forks as remotes and one team mate doesn't prune his branches so the branch view for me is a list of 300+ branches)

**Comment by stoivo** [comment]
ok, I think we can make a option to toggle all remotes. I may look at this tomorrow. No promises.

**Comment by divmain** [comment]
I've been thinking about it, and I don't want to add remote config to the branch dashboard.  There are a couple of reasons for that:

1) it will add significant clutter to the branch dashboard, in or to accommodate tasks that do not happen often
2) the way remotes are populated in the branch dashboard is distinct from what remotes are defined (for example, if you add a remote but haven't fetched yet, that remote will not appear in the branch dashboard).

Instead, I'd like to add palette commands: `git: remote add` and `git: remote remove`.  @wldcordeiro, will this solve the use cases you have in mind?

**Comment by wldcordeiro** [comment]
@divmain For managing remotes? Yes. I'd like to also get the toggle of displaying remotes to be on a remote by remote basis on the Branches dashboard.

**Comment by divmain** [comment]
We've been talking about it this in the Gitter channel.  I don't want to add per-remote visibility toggling to the Branches dashboard.  The UX would be subpar (given the constraints) and the implementation would add significant complexity to how the branches dashboard's render works now.

However, I'm trying to think through other options.  One might be to "forget" all the branches a particular remote.  For example, when you initially add a new remote, it doesn't know what refs/branches/tags are available at that remote.  Once you `fetch`, that information is populated.  I'm imagining something like the inverse of this process, to revert knowledge of that branch to the pre-fetch state.

This way you don't have to remove the remote will all the dead branches, and then re-add it when you happen to need it.  Instead, you would "forget" the refs, and simply fetch from that remote once you care about it again.

Does that seem reasonable?

**Comment by stoivo** [comment]
We should be able to add both with (username and password) and ssh keys
This is the two different ways we can add them. Do any of you who about more? 
```
[remote "stoivo"]
       url = https://github.com/stoivo/Packages.git
       fetch = +refs/heads/*:refs/remotes/stoivo/*
[remote "stoivo"]
        url = git@github.com:stoivo/Packages.git
        fetch = +refs/heads/*:refs/remotes/stoivo/*
```
