### ISSUE TITLE
GitSavvy: help - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by webbydoug** [divmain/GitSavvy#350]
"If you're a new user and you find yourself asking, _"Can GitSavvy do X?"_, there are two places to look.  First, open your command palette and type `GitSavvy: help`.  This will take you to the offline wiki-style documentation."

control + ` to open console.

When I followed instructions, I got this error:

>>> GitSavvy: help
  File "<string>", line 1
    GitSavvy: help
            ^
SyntaxError: invalid syntax

**Comment by stoivo** [comment]
Could you provide additional information about the version you are running?
And your steps to reproduce this?

**Comment by webbydoug** [comment]
http://recordit.co/gGco7tmjOc

**Comment by webbydoug** [comment]
I see where the issue was. In your opening instructions, you mention opeing console using control + ` keyboard shortcut; then typing GitSavvy: Help.

On https://github.com/divmain/GitSavvy you state, "Feature documentation can be found here. It can also be accessed from within Sublime by opening the command palette and typing GitSavvy: help."

So, this command/instruction was for command palette and not for console?

**Comment by divmain** [comment]
Hi @webbydoug - I think you may have misread?  [Here](https://github.com/divmain/GitSavvy/blob/master/messages/install.txt#L5) is the message you see when you first install GitSavvy.  Both here and in the README, it says to open the command palette and not the console.  I just did a quick search of the codebase to make sure there wasn't a typo somewhere, but I didn't find anything.  If you do find something, let me know and we'll fix it straight away!

**Comment by webbydoug** [comment]
You are so right @divmain And I am soooo sorry for wasting your time.

Thank you for quality utility. I found this via Ryan Irelan's Lesson on Sublime & Git: https://mijingo.com/lessons/using-git-in-sublime-text/

Have a good one!

**Comment by divmain** [comment]
No problem @webbydoug, glad you reached out!

**Comment by stoivo** [comment]
:sparkles:
