### ISSUE TITLE
Detect semvar tags and sort accordingly

### ISSUE THREAD

**Issue by mreq** [divmain/GitSavvy#352]
I'll try to make a PR soon.

![1455372821](https://cloud.githubusercontent.com/assets/1286942/13028084/785b4186-d264-11e5-9c4e-1303cacd2fc5.png)

**Comment by divmain** [comment]
If you get a chance to push up a PR, I'd be glad to merge it in!  Depending on my availability over the next couple of weeks, I may get to this before you :)

**Comment by stoivo** [comment]
@mreq, still interested in putting up a PR?

**Comment by mreq** [comment]
@stoivo thanks for reminding me

#418
