### ISSUE TITLE
Goto Symbol in Project matches with DIFF windows

### ISSUE THREAD

**Issue by jipumarino** [divmain/GitSavvy#355]
When using Goto Symbol in Project, besides matching with symbols in the actual project files, it also matches symbols with all open DIFF windows. Since there can be multiple DIFF windows for a single file (which might be a separate issue on its own), it often happens that, after selecting the symbol in Goto Symbol in Project, one has to select the actual file among a long list of DIFFs.

**Comment by divmain** [comment]
Interesting - I haven't run into that before.  Unfortunately, setting `index_files` on the view doesn't change the indexing behavior for that view (which drives Goto Symbol), and there is no other mechanism exposed by the Sublime API to disable that feature for a given view.

Unfortunately, there is no way I can see to change this behavior.

**Comment by jipumarino** [comment]
Thank you for the reply @divmain. Besides this particular issue (which can't be solved without more help from the Sublime API), is the multiple DIFF windows for the same file an actual issue? Should I look into it?

**Comment by divmain** [comment]
That one is tracked in #213.  Since I don't have as much time to work on it as I did, it hasn't been a high priority.  But since there are multiple users now who have made the same request, that'll push it closer to the top of my queue.
