### ISSUE TITLE
Trying to `git status`,  getting `git.exe stash list` error

### ISSUE THREAD

**Issue by vongoh** [divmain/GitSavvy#360]
Ive been using GitSavvy with no problems for a few months now.  I just did a clean install of all of my ST3 plugins (to address a different issue).   When I reinstalled  GitSavvy - I get the following whenever I try and run `git status`:

1)  Windows error dialogue `sh.exe has stopped working.  A problem cause the program to stop working correctly` etc.  I click `Close program` button ..

2) The 'STATUS' tab for GitSavvy comes up blank.  This is the error at the ST3 console:

```
`C:\Program Files (x86)\Git\cmd\git.EXE stash list` failed with following output:

      0 [main] sh 12060 open_stackdumpfile: Dumping stack trace to sh.exe.stackdump
      0 [main] sh.exe" 2736 sync_with_child: child 12060(0x134) died before initialization with status code 0xC0000005
     18 [main] sh.exe" 2736 sync_with_child: *** child state waiting for longjmp
C:\Program Files (x86)\Git/libexec/git-core\git-stash: fork: Resource temporarily unavailable
```
A couple of things to note:

- Running a `git branch` in GitSavvy works fine.  The issue is with the `git status` command only so far that I have seen, and

- Running `git status` for the same repo at my Win command prompt, this also works fine.  The process is only crashing in GitSavvy.

I also rebooted my machine a couple of times .. uninstalled reinstalled GitSavvy .. no change ..
thanks

**Comment by divmain** [comment]
Weird!  To start, double check that both GitSavvy and your command line are using the same `git` binary.  After a cursory search, it seems like some issues can arise if you 1) have Cygwin installed with Git, 2) msysgit installed, and 3) both are simultaneously listed in the `PATH`.

If you find that you're using different binaries, remove one, and set the `git_path` in `GitSavvy.sublime-settings` to be doubly-sure.  Let me know if any of that helps.

Pasting a couple of links here for further investigation in case the issue remains:
- http://stackoverflow.com/questions/12042363/cygwin-git-fork-error-on-pull
- https://groups.google.com/forum/#!topic/msysgit/M2pkd1AXV9Q

**Comment by vongoh** [comment]
@divmain - Well, as I am not so git 'savvy'  :) about the differences between Cygwin and msysgit, I am not positive but it looks like I only have one of them on my machine - msysgit.   

The only Git install I can find is at 'C:/Program Files (x86)/Git/cmd'.  The release notes in that directory state that I am using Git-1.9.0-preview20140217.

I tried setting '"git_path": "C:/Program Files (x86)/Git/cmd"' in GitSavvy user settings, I get the same error and issue.

I checked the Windows path and the only Git path I see is the one to that directory.

**Comment by divmain** [comment]
Shoot - this may be difficult for me to troubleshoot remotely...  Is this the same Git that you had installed previously, or did you reinstall other things besides your Sublime plugins?  I can't think of a reason why reinstalling Sublime or plugins only would result in such significant breakage.

**Comment by divmain** [comment]
This appears to be related:
https://groups.google.com/forum/#!topic/msysgit/EafhNNATV_4

**Comment by vongoh** [comment]
If by fast ring for updates you mean 'insider preview' (thats what they call it?) builds - no I am not on that.  Apparently I'm in for their standard 'opt out' upgrades where they do it behind the scenes without notifying you.   

I am running version 1511 (OS Build 10586.71).   

The most promising thing from the links you posted was this:
https://twitter.com/onovotny/status/692538905539780609

So I upgraded my Git for Windows to 2.6.1 as recommended, even though my Windows build does not match the build they are claiming has these issues.  Did not help.

Just before trying this upgrade - I tried a `git stash list` at my command prompt and got this error:

```
git stash list
      0 [main] sh 11132 open_stackdumpfile: Dumping stack trace to sh.exe.stackdump
      0 [main] sh.exe" 8164 sync_with_child: child 11132(0x150) died before initialization with status code 0xC000
0005
    116 [main] sh.exe" 8164 sync_with_child: *** child state waiting for longjmp
C:\Program Files (x86)\Git/libexec/git-core\git-stash: fork: Resource temporarily unavailable
```
The upgrade did not help that either.   A bit more info - when I said I did a clean install of all of my plugins,  this is what I did -- http://www.sublimetext.com/docs/3/revert.html

I do see there at the bottom of that page a note about the ST3 cache in Windows -- "In Windows, cache files are stored in a separate location, %LOCALAPPDATA%\Sublime Text 3".   The instructions do not say to clear any of that, so I didn't.

There is a GitSavvy directory there at `C:\Users\[USER]\AppData\Local\Sublime Text 3\Cache\GitSavvy`.    Should I clear that cache?   Dont want to touch it at this point unless you say so

**Comment by divmain** [comment]
Removing the cache won't hurt anything, but I don't think it'll help either.

This is definitely an issue with your system.  It seems like this error or similar problems have popped up at various times, and have been attributed to:

- graphics driver incompatibilities
- bad `msys-1.0.dll`
- recent windows build weirdness

The only things left I can recommend you try:
- Remove Git completely, and remove any traces of msys or Cygwin left on the system.  Then re-install, and if you've been using the 32-bit build, maybe try the 64-bit build (or vice-versa, if that's the case).  From your path, it does look like you're using the 32-bit build.
- Remove Git, install [Cygwin](https://www.cygwin.com/), include Git from there, and set `git_path` in `GitSavvy.sublime-settings` to point to the new git executable path.

Since you saw this error from the command line, it suggests that there is an underlying problem that is revealed in certain circumstances - and somehow GitSavvy is hitting that circumstance every time.  Some of it might be process environment variables, it might be how the output is piped to another process instead of stdout.  It is really difficult to say for sure.

I'm sorry I can't help more.

**Comment by vongoh** [comment]
"Remove Git completely, and remove any traces of msys or Cygwin left on the system. Then re-install, and if you've been using the 32-bit build, maybe try the 64-bit build"

This did the trick,  I completely removed Git for Windows from my machine,  installed the latest 64bit copy 2.7.2.windows.1,  the commands that were failing in both the command prompt and GitSavvy now seem to be working fine.   Thanks again for the attention to this issue!

**Comment by divmain** [comment]
That's great to hear!
