### ISSUE TITLE
Unicode support when trying to merge with kdiff3?

### ISSUE THREAD

**Issue by allen-zeng** [divmain/GitSavvy#366]
Sometimes when I try to launch kdiff3 from the STATUS dashboard (typing <kbd>M</kbd> ), I get an error in the console that says
> Traceback (most recent call last):
>  File "core.interfaces.status in /Users/allen.zeng/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 760, in <lambda>
>  File "core.git_mixins.merge in /Users/allen.zeng/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 57, in launch_tool_for_file
>  File "core.git_mixins.merge in /Users/allen.zeng/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 36, in launch_tool_for_file
> UnicodeEncodeError: 'ascii' codec can't encode character '\u2022' in position xxxxx: ordinal not in range(128)

The error is straight forward enough to work out, but it's really annoying, and there's no way to get GitSavvy to bring up the merge tool for this file.

**Comment by divmain** [comment]
Hey @allen-zeng, thanks for filing an issue.  It may be that we can work around this - would you please:

- Open the command palette (either `Cmd-Shift-P` or `Ctrl-Shift-P`) and enter `GitSavvy: enable logging`
- Reproduce the error that you've described above.
- Open the command palette again and enter `GitSavvy: disable logging`.
- Open the command palette a final time and enter `GitSavvy: view recorded log`.
- Copy the log output and included it in this ticket (inside triple-backticks - ```` ``` ````).

That, along with the stack-trace you've already provided, should give me enough information to determine if this is something we can work around.

**Comment by allen-zeng** [comment]
Sorry I should have mentioned - the file does contain a character \u2022, it's causing the crash.

I've looked through the logs and everything seems correct. I'm reluctant to post the actual log messages that contain all the source code though :)

**Comment by stoivo** [comment]
What type of encoding is the file saved with?
I think it shows it by default in right bottom corner on the status bar. If not you can change this by setting `show_encoding_on_status_bar` to true in user preferebces.

**Comment by allen-zeng** [comment]
The file is encoded in UTF-8.

**Comment by allen-zeng** [comment]
The unicode character is a bullet, used in comments:
```
//
  • blah blah blah
  • other stuff
//
```

**Comment by divmain** [comment]
Oh, strange.  That's definitely something we should be able to fix.

**Comment by divmain** [comment]
@allen-zeng, I just pushed a change that should resolve this issue.  Could you pull down latest master and let me know if this is resolved for you?

**Comment by allen-zeng** [comment]
Works perfectly! Thanks for fixing it so quickly too!

**Comment by divmain** [comment]
Glad to hear it!
