### ISSUE TITLE
Issue autocomplete does not work

### ISSUE THREAD

**Issue by sindrig** [divmain/GitSavvy#370]
All of a sudden, autocomplete on issues in the commit window does not work. When I type in "#" and press TAB, nothing happens.

This is printed in the dev console:

```
Traceback (most recent call last):
  File "github.commands.commit in /home/sindri/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 36, in <lambda>
  File "github.commands.commit in /home/sindri/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 51, in run_async
  File "github.github in /home/sindri/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 117, in query_github
  File "common.interwebs in /home/sindri/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 30, in request
AttributeError: 'module' object has no attribute 'HTTPSConnection'
```

**Comment by stoivo** [comment]
GitSavvy version?
OS?
Sublime version?

**Comment by sindrig** [comment]
GitSavvy version 2.9.1
Manjaro 15.12
Sublime build 3103

**Comment by sindrig** [comment]
>>> import sys
>>> sys.path
['/home/sindri/.config/sublime-text-3/Packages/Python PEP8 Autoformat/libs/py33', '/home/sindri/.config/sublime-text-3/Packages/Python PEP8 Autoformat/libs', '/opt/sublime_text_3', '/opt/sublime_text_3/python3.3.zip', '/home/sindri/.config/sublime-text-3/Packages', '/home/sindri/.config/sublime-text-3/Packages/bz2/st3_linux_x64', '/home/sindri/.config/sublime-text-3/Packages/pyyaml/st3', '/home/sindri/.config/sublime-text-3/Installed Packages/Emmet.sublime-package', '/home/sindri/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet_completions', '/home/sindri/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet', '/home/sindri/.config/sublime-text-3/Packages/isort', '/home/sindri/.config/sublime-text-3/Packages/isort', '/home/sindri/.config/sublime-text-3/Installed Packages/PyV8', '/home/sindri/.config/sublime-text-3/Installed Packages/PyV8/linux64-p3', '/home/sindri/.config/sublime-text-3/Installed Packages/PyV8/pyv8-linux64-p3']
>>> sys.version_info
sys.version_info(major=3, minor=3, micro=3, releaselevel='final', serial=0)
>>> import http.client
>>> http.client.HTTPSConnection
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'HTTPSConnection'

The symptoms seem to be the same as in https://github.com/pypa/pip/issues/833. I'll post back here if I find a fix for this...

**Comment by sindrig** [comment]
This is probably related to a recent update of OpenSSL on Arch (https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/openssl&id=4b82ed4285c7cb76caf6d75a015c5a7542c625d1). It's up to you if you want this issue to remain open as it has little to do with GitSavvy, but either way I'll be back if I find a way to fix this.

**Comment by divmain** [comment]
Yeah, I haven't done much work with the Sublime-bundled Python on Linux.  I did come across [this](https://github.com/codexns/sublime-ssl-linux) that may provide some help.  Would be glad if you could post anything you come up back here for other Arch Linux users.

**Comment by divmain** [comment]
@sindrig, ST3 build 3109 may help with this.  From the release notes: `API: Updated to Python 3.3.6, and now includes the _ssl module on Linux, plus sqlite3 and bz2 on all platforms.`

**Comment by sindrig** [comment]
ST3 build 3109 fixed this. Thanks @divmain

**Comment by divmain** [comment]
Great to hear!
