### ISSUE TITLE
Combine "git checkout branch" and "git checkout remote branch as local"

### ISSUE THREAD

**Issue by stevage** [divmain/GitSavvy#371]
I find this split a little bit clumsy and counterintuitive. Why not just list all remote branches below local ones:

```
foo
blah
origin/foo
origin/bar
mine/blah
```

In particular this would remove the confusing error that happens when you try to "checkout remote branch as local" a branch that you have previously checked out.

**Comment by divmain** [comment]
Agreed, these don't need to be separate, especially since the second command doesn't prompt for a local branch name.  We'll be doing a 3.0 release which includes breaking changes, so I'll try to include this change with the rest of it.
