### ISSUE TITLE
Git Diff against Specific Commit

### ISSUE THREAD

**Issue by MichaelOhlrogge** [divmain/GitSavvy#373]
Maybe I am just missing something obvious, but is there a way to view the differences against a specific commit, rather than just the most recent one?

**Comment by divmain** [comment]
Oddly enough, that hasn't come up before.  It should be simple enough to add, however.  How would you prefer it work?  We could introduce a new command `git: diff...` that takes the user through a series of prompts, like - diff against working directory or index - diff against ancestor (git-log like prompt appears) - etc.

**Comment by aireties** [comment]
Great! I think what would be most useful would be to get a list of commits by their dates and commit messages and then be able to either scroll down through that list or filter it by typing in characters which match to commit messages.  Right now I use GitSavvy for basically all of my sublime git needs, but I need to go to the GitGutter package to get this comparison ability (which is enabled there).  But, I much prefer the nice ways that GitSavvy displays the comparisons, as compared to GitGutter, and so it'd be nice to have the feature in GitSavvy, and also so I could have everything in a nice single package.  Thanks!

**Comment by divmain** [comment]
Oh, you know what.  This is already there, I just don't find myself using it often.

- `git: log` (or variant)
- select the commit you care about
- `Compare commit against index` or `Compare commit against working directory`

**Comment by aireties** [comment]
Hmmm, maybe I'm just not doing this right, I can get that feature to work, but it just seems to give the log comparisons.  If I then call the git diff operation, it still seems to be comparing against the most recent commit.  I'm relatively new though to git and GitSavvy, so it's possible I'm just not using things correctly.

**Comment by divmain** [comment]
Ah, so are you talking about `git: diff current file inline`, where the changes are file is displayed, added lines are green, removed are red, etc?

That functionality does not currently exist - and is unfortunately very difficult to implement.  We've been talking about doing an inline-diff rewrite that would provide a bit more complexity, but it hasn't been a top priority.  That's partially tracked as #102.

**Comment by aireties** [comment]
Yeah, basically it would be the equivalent of 

`git diff <commit> <commit> `

from the command line.  But, if it would be prohibitive to implement, I totally understand.  Thanks for the great package, it's still very useful!

**Comment by divmain** [comment]
Going to re-open this for further consideration.  If all you want is a command where you can compare the working directory against a given commit, that should be achievable.  If it is closer to what is described in #102, we can close this again.

**Comment by aireties** [comment]
Yeah, comparing working directory against a given commit sounds great to me.  Thanks!

**Comment by grrowl** [comment]
I'd love to use this for code reviews — typically we review the branch diff in a github PR, or through `git: branch > select developbranch > diff against active`, but when we need to see it in the context of the whole file, it'd be great to browse the diff between `featurebranch` and `developbranch` inline.

**Comment by randy3k** [comment]
I also found that the commands `git: log` -> select commit -> `Compare commit against working directory` are not very useful. 

It would be much useful to do something like

`git: log` -> select commit -> `Compare against ...` -> select another commit to compare
