### ISSUE TITLE
New Feature: porting to Atom

### ISSUE THREAD

**Issue by fracarma** [divmain/GitSavvy#376]
It would be great to port this Package to Atom editor: for me, the "git status" pages are fundamental in my work and I miss it a lot on Atom.
Is a porting already studied?

**Comment by divmain** [comment]
Hey @fracarma - I've had a handful of discussions about this, but I don't have great news for you.

This would be less of a port and more of a completely new project.  Atom uses 1) JavaScript for plug-ins, and 2) a very different plug-in architecture.  I looked at creating a JavaScript-to-Python bridge and Sublime/Atom plugin compatibility layer, and it just looked like too much work.

On top of that, I don't use Atom, so there would be very little personal motivation.  If I were to move to a new editor, it would probably be VS Code, for performance reasons.

Anyway, not what you were looking for, I'm sure.  Sorry I can't accommodate!

**Comment by fracarma** [comment]
Thank you very much for the answer!

**Comment by halvardos** [comment]
@divmain I recently made the move to VS code from Sublime and found this old issue. Have you put any more consideration into a version for VS code?

The only thing worse with using vs code for me is the git integration compared to Gitsavvy.

Thanks for creating an awesome tool!

**Comment by jeongl** [comment]
I recently switched to VSCode, but can't give up sublime because I need this plugin. It really is amazing. Still hoping for a vscode port.

**Comment by 3v1n0** [comment]
Another one in the list :).

Indeed it's another project, but I'm trying to move to VSCode, but living without GitSavvy is quite impossible to me (so that I basically only use sublime for git management now :)).

However, probably we could setup some discussion in order to start re-implement this in a new extension?

**Comment by tevren** [comment]
https://atom.io/packages/atomatigit provides most of the functionality of GitSavvy, but it needs a maintainer :(
