### ISSUE TITLE
Add folding to Gitsavvy Branch View

### ISSUE THREAD

**Issue by wldcordeiro** [divmain/GitSavvy#381]
Based on ScopeHunter output, we could tell Sublime that the headings for remotes are foldable points. This could also be used in other views as well on other `keyword.other.git-savvy.section-header` scopes too.

```
Scope:                         git-savvy.branch
                               meta.git-savvy.status.section
                               keyword.other.git-savvy.section-header
```

**Comment by stoivo** [comment]
Like where?

**Comment by wldcordeiro** [comment]
![selection_012](https://cloud.githubusercontent.com/assets/580982/14261206/cd251766-fa6c-11e5-9315-bb158bd24f06.png)

Ideally line 44 would have the ST code folding indicator and let me fold up the branch list under the remote name.

**Comment by stoivo** [comment]
Oh, we have it on master branch, but we just need to make the release. 
it looks like 
![screen shot 2016-04-04 at 21 57 15](https://cloud.githubusercontent.com/assets/3492040/14261299/423f1e64-fab0-11e5-9968-f6cc48b85fc7.png)

Is there some other places where this should be added?

**Comment by wldcordeiro** [comment]
Can't think of any places off the top of my head. The scope for the syntax seems pretty generic so it should be in most places now. :)

**Comment by wldcordeiro** [comment]
If we get a new release @stoivo  you could close this issue and #380 together. :+1:

**Comment by stoivo** [comment]
> If we get a new release @stoivo you could close this issue and #380 together.

I agree, I am checking with @divmain.
