### ISSUE TITLE
Git Savvy no longer working after force quit of sublime.

### ISSUE THREAD

**Issue by utahmike** [divmain/GitSavvy#382]
I encountered the same problem as described here:

https://github.com/divmain/GitSavvy/issues/300

And was forced to "Force Quit" sublime.

Upon restart, Git Savvy commands are no longer available in the Command Palette. I've tried removing and re-installing the package. Restarting the computer. Restarting sublime. Nothing will restore the commands to the Palette.

**Comment by divmain** [comment]
@utahmike, can you check the Sublime console to see if any errors are reported?  This sort of problem usually happens if the plugin is not initialized correctly.

**Comment by dominiquedutra** [comment]
Hello,

I too have the same problem this morning and I dont remember force-quitting sublime yesterday. Last thing I did as always was push my code and close everything up.

[sublimeConsoleOutput.txt](https://github.com/divmain/GitSavvy/files/206350/sublimeConsoleOutput.txt)

**Comment by KenzR** [comment]
Me too, from this morning my git savvy does not exist anywhere. I tried reinstalling it, reinstalling sublime, deleting packages. Nothing helps, also my branch that i was on yesterday is lost. Yesterday everything was okay.

**Comment by dominiquedutra** [comment]
@KenzR @utahmike please attach your console output to help the developers.

**Comment by utahmike** [comment]
Here is my console output. Definitely problems loading the package.
[SublimeStartup.txt](https://github.com/divmain/GitSavvy/files/206426/SublimeStartup.txt)

**Comment by tcrockett1138** [comment]
I've also hit this issue, specifically when I updated to 2.10.0.  I've attached a snip of the console log.  I'm running ST3 on Windows7.
[SublimeGitSavvy210Error.txt](https://github.com/divmain/GitSavvy/files/206891/SublimeGitSavvy210Error.txt)

**Comment by stoivo** [comment]
I am working on a fix.

**Comment by divmain** [comment]
@utahmike @dominiquedutra @KenzR @tcrockett1138 I just pushed out an update that will disable the offending code as a temporary work-around.  Syntax highlighting will disabled in inline-diff views, but we'll address that regression separately.  If you see this in the next few minutes, it would be super helpful if you could pull down master and confirm that things are working for you.  Please ping me on Gitter if there are still issues - and sorry for the bad update!

**Comment by utahmike** [comment]
All is working again, thank you for your quick response.

**Comment by tcrockett1138** [comment]
Looks good, all fixed.  And the remote add/remove work great also. :-)

**Comment by KenzR** [comment]
It's working :D

**Comment by stoivo** [comment]
:1+:

**Comment by dominiquedutra** [comment]
Working. Thanks!

**Comment by akwiczola** [comment]
It happened to me too today. Reinstalled it, still not showing the commands
