### ISSUE TITLE
GitSavvy doesn't work after installed GitGutter

### ISSUE THREAD

**Issue by bank32** [divmain/GitSavvy#384]
After installed GitGutter my Sublime can't use GitSavvy anymore. It was not found on my command palette. So, I tried to remove GitGutter and reinstall GitSavvy but it still doesn't work.

Please help me as soon as possible, GitSavvy is a part of my life now.

**Comment by rmnbrd** [comment]
Same issue here, GitSavvy is totally absent from the command palette since the last update :disappointed:

**Comment by stoivo** [comment]
There is some major bug now, I am working on fixing it now.

**Comment by divmain** [comment]
@bank32 @rmnbrd, I just pushed out an update that will disable the offending code as a temporary work-around.  Syntax highlighting will disabled in inline-diff views, but we'll address that regression separately.  If you see this in the next few minutes, it would be super helpful if you could pull down master and confirm that things are working for you.  Sorry for the bad update!

**Comment by bank32** [comment]
fixed it. Thanks a lot.

**Comment by bank32** [comment]
@divmain I have another question. now I fixed it by less simple method but I wanna know when we can install latest version via Sublime package control ?

**Comment by divmain** [comment]
@bank32 it should be going out now.  You may need to either 1) restart Sublime, or 2) run `Package Control: Upgrade Package` in the command palette.  There is a delay between when I push a new tag in my Git repo and when `packagecontrol.io` picks up that changes and starts pushing it out to clients.

**Comment by rmnbrd** [comment]
It's working like a charm now.
Thank you guys for your great reactivity! You rock! :+1:
