### ISSUE TITLE
Lost syntax highlighting in diff view

### ISSUE THREAD

**Issue by nightmarebadger** [divmain/GitSavvy#386]
From yesterday my diff view lost all syntax highlighting for some reason. I can still manually check the correct syntax and it works, but I have to do it every time I close and re-open a diff. The green/red highlights from GitSavvy still work, but it always sees the diffs as `Plain Text`, no matter what file I open. 

I have tried a complete removal of GitSavvy (removing and even manually deleting the `/User/GitSavvy` folder) but it didn't seem to do much good. I did not install/remove/enable/disable any new packages (but I guess something might have been updated). 

As a test I tried to copy over one of the other `.tmTheme` files into the `/User/GitSavvy` folder but it seems to be overwritten every time I open a diff view. 

Anyone experiencing something similar?

**Comment by divmain** [comment]
Hey @nightmarebadger.  This is a known issue.  There was a pretty significant bug that disabled GitSavvy for some users with the `2.10.0` release.  As a workaround, we have temporarily disabled syntax highlighting in the inline diff views with `2.10.1`.  We'll be releasing `2.10.2` within the next day or so to restore the disabled behavior.

**Comment by nightmarebadger** [comment]
Thanks @divmain, I did not see that anywhere when I searched. 

Will leave this in and open until it is fixed for other people searching for the same thing.

**Comment by p3lim** [comment]
Sorry for the necrobump, but I have this issue with the latest release of GitSavvy on ST 3189.
