### ISSUE TITLE
Help doesn't work

### ISSUE THREAD

**Issue by DanielKeep** [divmain/GitSavvy#389]
I opened the GitSavvy help from the command palette, and got the "GITSAVVY HELP" file.

The advice about following links to other pages simply *does not work*.  I've tried Ctrl+Enter, Enter, Shift+Enter, Alt+Enter, Ctrl+Alt+Enter, Ctrl+Shift+Enter, Win+Enter, ], >, f... nothing works to follow links.  I can't open the files manually, since File > Open just shows my project's folder, and I have no idea where these files are.

So, GitSavvy is basically useless because I can't look up how to do anything with it.

I'm running ST3, Stable build 3103.  I've attached my package list and the contents of the console after startup.

* [gitsavvy-console-log.txt](https://github.com/divmain/GitSavvy/files/218425/gitsavvy-console-log.txt)
* [Package Control.sublime-settings.txt](https://github.com/divmain/GitSavvy/files/218427/Package.Control.sublime-settings.txt)

**Comment by stoivo** [comment]
We have some trouble with the new syntax format (.sublime_syntax). We are working on a fix. If you set the syntax to markdown and then press `Ctrl+Enter` it will work.

I hope we can make a release with a fix next two weeks.

**Comment by divmain** [comment]
@DanielKeep, that was an unexpected side-effect of the syntax changes.  As @stoivo mentioned, we should have a fix shortly.  In the meantime, you can look through the same documentation [here](https://github.com/divmain/GitSavvy/blob/master/docs/README.md).  I'll leave this open until we have a fix for docs in place.

**Comment by DanielKeep** [comment]
Switching to "Syntax: Markdown Extended" does appear to work.  Incidentally, and just to clarify: I had the same problem *prior* to updating to the latest build of ST3 with `.sublime_syntax` support.  Don't know if that's relevant, but just thought I'd mention it.

**Comment by divmain** [comment]
Thanks!  We made changes in GitSavvy to accommodate the syntax changes going on in ST3.  That led to a serious regression, and we pushed out a temporary fix that included disabling some of the features that rely on syntax.

If you have time and inclination, could you pull down the latest version of GitSavvy directly from the repo (instead of through the package manager)?  I re-enabled some of the syntax features, and wonder if that has addressed your issue here.

If it has not, we may need to dig deeper.

**Comment by DanielKeep** [comment]
I just followed the instructions for installing the package through a Git clone, and got the following in the console:

```
Traceback (most recent call last):
  File "F:\Programs\Sublime Text 3\sublime_plugin.py", line 162, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\drk\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\git_savvy.py", line 9, in plugin_loaded
    from .common import util
ImportError: cannot import name util
```

A quick look in the `common` folder shows no `__init__.py`; was it accidentally not checked in?
