### ISSUE TITLE
Customized git log (graph)

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#39]
Basically the option to customize this line: https://github.com/divmain/GitSavvy/blob/83a486eaad8aac982160caabeb7099052da5e462/core/commands/log_graph.py#L29

**Comment by divmain** [comment]
Are you looking for direct customization (enter any flags you want), or something more specific?  My intention here is to add interaction to the view, where `Super+Enter` on a commit would open that commit, `Super+Enter` on a branch would prompt you to check it out, etc.  Too much customization here might make this a more difficult task.

**Comment by p3lim** [comment]
Custom flags, like adding committer, email, tags etc.

This is what I use normally in bash, and I'd love something like it for this. Not sure if you plan on supporting colors though.
`git log --graph --pretty=format:'%Cred%h%Creset %s%Cgreen%d %C(yellow)(%cr) %Cblue[%an]%Creset' --abbrev-commit --date=relative --all`

**Comment by divmain** [comment]
Relates to #13.
