### ISSUE TITLE
blame current file: remember last blame mode

### ISSUE THREAD

**Issue by benmosher** [divmain/GitSavvy#394]
I always use the last blame mode (detect moved or copied across all commits). Would be handy if it was auto-selected every time.

Many of the sub-menus remember the last position, so I suspect this is low-hanging and generally desirable. 

For your consideration. Thanks for all your work so far! 😄

**Comment by stoivo** [comment]
It makes a lot of sense to me to autoselect the one you last used.

**Comment by stoivo** [comment]
@benmosher, If you installed GitSavvy by pulling down master branch, you can pull now and it will work. We are trying to keep master stable. 😄
