### ISSUE TITLE
Show file at commit when folders are symlinked

### ISSUE THREAD

**Issue by stoivo** [divmain/GitSavvy#399]
These lines of code is not working when folders are symlinked
[core/commands/show_file_at_commit.py#L29-L31](https://github.com/divmain/GitSavvy/blob/3d89abab3f3304120549176a461c816837278321/core/commands/show_file_at_commit.py#L29-L31)

**Comment by divmain** [comment]
I know :(

Using [`os.path.realpath`](https://docs.python.org/3/library/os.path.html#os.path.realpath) everywhere might help in this regard, but the trick is finding all the places it might be needed.

**Comment by stoivo** [comment]
Anyway it better to start somewhere than nowhere. And thank I did not know of `os.path.realpath`.

**Comment by stoivo** [comment]
This exact issue is fixed in https://github.com/divmain/GitSavvy/pull/481/commits/264b0299d6b9ee52106835a5120738eb20d9f6ea
