### ISSUE TITLE
Diff syntax highlight in the commit message file

### ISSUE THREAD

**Issue by dufferzafar** [divmain/GitSavvy#405]
The diff that gets displayed in the commit window isn't highlighted.

I think `git-savvy.make-commit` & `git-savvy.diff` should be merged somehow, so that the diff can be properly highlighted during commits.

**Comment by stoivo** [comment]
This can be fix with including the diff in make-commit.

**Comment by stoivo** [comment]
I look like you studied it, Would you like to make a Pull Request on this?
https://www.sublimetext.com/docs/3/syntax.html look under section `Include Patterns`.

**Comment by stoivo** [comment]
I can not see that this PR is making any difference. Could you add two screenshots of before and after?

**Comment by dufferzafar** [comment]
Here you go:

## Before:

![before](https://cloud.githubusercontent.com/assets/1449512/15119584/33fffb12-162f-11e6-875b-062bcc9a02bf.png)

## After:

![after](https://cloud.githubusercontent.com/assets/1449512/15119590/39507eb6-162f-11e6-8eaa-c662eb4f83be.png)

**Comment by stoivo** [comment]
I am on git version 2.8.2 and my diff looks like this
```diff


## To make a commit, type your commit message and press SUPER-ENTER. To cancel
## the commit, close the window. To sign off on the commit, press SUPER-S.

## You may also reference or close a GitHub issue with this commit.  To do so,
## type `#` followed by the `tab` key.  You will be shown a list of issues
## related to the current repo.  You may also type `owner/repo#` plus the `tab`
## key to reference an issue in a different GitHub repo.

diff --git a/core/commands/inline_diff.py b/core/commands/inline_diff.py
index 4ff181c..0896e6e 100644
--- a/core/commands/inline_diff.py
+++ b/core/commands/inline_diff.py
```

Can you check your git version? `$ git --version`

**Comment by dufferzafar** [comment]
I am on 2.8.1

**Comment by dufferzafar** [comment]
I knew it was some custom setting that I had. Turns out there is a setting in git config called `noprefix` which removes those a, b characters.

Though I think that GitSavvy should handle both these cases.

**Comment by stoivo** [comment]
Sure, I agree
