### ISSUE TITLE
Pedantic commit messages

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#41]
Add a distinct style guide for the commit messages:
- First line should be max 50 characters
- Second line should be empty
- Any subsequent lines should be max 72 characters

Coloring the background of any characters that exceed limits is ideal, only warning the user.

This should be optional, of course.

References:
http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
https://github.com/blog/926-shiny-new-commit-styles

**Comment by yyyc514** [comment]
See #119.  Someone just needs to make a kick-butt syntax for commits in general.

**Comment by yyyc514** [comment]
Related: https://github.com/adambullmer/sublime_git_commit_syntax/pull/2

Spent a little time on this.  If I can't get it back it mainline I'll probably create a whole new repository and package.  Still tweaking the styles.

**Comment by yyyc514** [comment]
![screen shot 2015-03-21 at 6 26 41 am](https://cloud.githubusercontent.com/assets/6473/6764679/607ce3a0-cf93-11e4-9549-ccb05da0a4f3.png)

**Comment by yyyc514** [comment]
@divmain Would you like this kind of thing in GitSavvy proper?

**Comment by yyyc514** [comment]
Having multiple syntax files for different modes gets messy at some point (though it might be ok for only two options).

**Comment by divmain** [comment]
Please see my comment in #119.  I'm not averse to including a "pedantic commit message syntax" in GitSavvy proper - it can be commented out as an alternative in the default `GitSavvy.sublime-settings` file.

**Comment by divmain** [comment]
For anyone interested, @yyyc514 may have a custom syntax definition for commit views that you can use.  However, as I commented in #119, I'm not 100% I can preserve this new behavior while moving the commit view to being more interface-like.

I'll leave this open until the feature is officially announced as part of a changelog.

**Comment by stoivo** [comment]
hey, @yyyc514!
How did you make the commit view look like this?
I cloned https://github.com/adambullmer/sublime_git_commit_syntax
now when I open Commit view and  run in console 
```
>>> view.settings().get('syntax')
'Packages/sublime_git_commit_syntax/commit-message.tmLanguage'
```

And my diff look really boring. Now there are no color at all

**Comment by yyyc514** [comment]
Try my fork:

https://github.com/yyyc514/sublime_git_commit_syntax

**Comment by stoivo** [comment]
Still, not working. What theme are you using?

**Comment by yyyc514** [comment]
A custom one, but the syntax just uses common things like "Entity", etc.

**Comment by stoivo** [comment]
Can you share it on a gist?

**Comment by yyyc514** [comment]
http://runningblind.com/post/778165402/sunburst-josh-final

**Comment by stoivo** [comment]
Now it looks like 
http://puu.sh/iQhji/4960f86afd.png
and the syntax I use is 
https://gist.github.com/stoivo/e6fde1f18fd804e0cbfd

**Comment by yyyc514** [comment]
Dunno what to tell you... something is going wrong.

**Comment by stoivo** [comment]
anyway, thx. I will tell you 'when' I found a solution .

**Comment by aristidesfl** [comment]
@yyyc514 tried your fork but seems to be a bit strange. Is this how it is supposed to work? The color scheme I'm using is `Flatland_Dark (SL)`: 

![gitsavvy](https://cloud.githubusercontent.com/assets/208149/14591775/3d875bc2-0517-11e6-9971-963eec0517be.gif)

**Comment by stoivo** [comment]
If any of you are running on `dev` branch what do you think
