### ISSUE TITLE
'SELECTED FILE' hot keys dead when cursor is at the end of the line

### ISSUE THREAD

**Issue by rkpatel33** [divmain/GitSavvy#414]
When my cursor is at the end of a file name line, seems all my 'SELECTED FILE' keys are dead. When I bring the cursor onto the line or at the BOL, they work. Small but seems to be a reset issue.

![image](https://cloud.githubusercontent.com/assets/3799489/15616613/ff18660e-2412-11e6-8a71-94bf08e1710a.png)

**Comment by divmain** [comment]
This'll be included in the next release (or you can pull down master if you don't want to wait).  Thanks for the bug report!

**Comment by rkpatel33** [comment]
Great, thanks!

______________________________________
Rishi K. Patel
​, ​
Founder
​,
www.docnavapp.com
*​*
​
rishi@docnavlab.com
​,
917-647-0892​
LinkedIn <https://www.linkedin.com/in/rkpatel33>, @docnavlab
<https://twitter.com/docnavlab>
