### ISSUE TITLE
add `git add --edit` equivalent

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#42]
There's no easy way of telling which hunks or lines are actually staged in the inline diff.
Consider adding a background color to these (e.g. yellow) to distinguish them.

This would be especially useful with #35.

**Comment by divmain** [comment]
I thought about this, but I wasn't sure how to deliver a consistent experience.  A color could be shown for added lines, but not sure how to represent lines that have been removed.  You _are_ able to view an inline-diff of the file in the index, and un-stage lines and hunks there.  That seemed to mostly solve my personal use case.

With #35, I envision situations where I mistakenly revert a hunk (not stage it) and immediately realize I nuked something I didn't mean to.  An undo feature would protect me against myself in situations like that, and make it more likely I'd be willing to use the revert feature in my daily flow.

Interested to hear more from you on this, though.  Maybe the same thing could be accomplished by an easier way to switch between `inline diff` and `inline diff (cached)` views of a file?

**Comment by p3lim** [comment]
Honestly, I really prefer the look and usability of patch files, basically what you'd get from running `git add -e`.

I'm not entirely sure how I'd properly support that feature entirely in the current design, that would be entirely up to you. For now I've just added the aforementioned command as a keybind to the status window for my own needs.

**Comment by divmain** [comment]
I've never used `git add -e` before, myself.  That's something I'll take a look at to identify if similar functionality can be incorporated into the inline diff or into a separate feature.

**Comment by divmain** [comment]
Leaving a note for myself: this feature will present a view similar to `git: diff`, but will allow user to edit the diff at their own peril.  Upon submission, that diff will be applied to the index.
