### ISSUE TITLE
Multi-merging in branch view

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#420]
The <kbd>m</kbd> key states "merge selected into active branch", but it only does one at a time.
I would like to see the ability to select multiple (either text selection or multiple cursors if possible) branches to merge from.

**Comment by stoivo** [comment]
Do you know if there is one command to merge multiple branches at once. 

Can we just do 
`git merge b1 b2 b3 b4`

**Comment by p3lim** [comment]
You can, it's called octopus merging.

**Comment by stoivo** [comment]
I know, just googled it 😉

**Comment by stoivo** [comment]
I made it work for multiple selections, this will be added in next release.
