### ISSUE TITLE
Commit message: Visually represent first line limit of 50 characters

### ISSUE THREAD

**Issue by FichteFoll** [divmain/GitSavvy#423]
It is common practice to have the first line of a commit not exceed 50 characters. Currenty, GitSavvy does not "endorse" this because it only displays a ruler at column 80 for the entire message.
I have a a few ideas on how this could be implemented:
1. Show two rulers, one at 50 and one at 80. People that know about this convention will understand.
2. Adjust the ruler setting based on which line the caret is in (using `on_selection_modified`).
3. Only show ruler at 80 but make the syntax definition apply a different scope to any character past 50 in the first line.

All of these are feasable and comparatively easy to implement (especially 2.). However, 3. additionally has the downside of being rather obstrusive towards users that don't care about this convention.
2. has the advantage of wrap commands usually automatically adjusting to the first ruler in the view, which would be at 80 for the detailed message (and 50 when 1. is implemented). As such, 2. is highly preferred.

[Some recommend 72](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) as max-width for the message (for a console width of 80 with 4 characters padding on each side), so it makes sense to make this configurable imo. Setting to `80|80` would consequently disable this feature.
Related SO discussion: http://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting
[According to Linus](https://github.com/torvalds/linux/pull/17#issuecomment-5661185), this style is also used in the Linux kernel.

**Comment by stoivo** [comment]
This issue is kind of linked https://github.com/divmain/GitSavvy/issues/41

**Comment by asfaltboy** [comment]
How about we allow customisation of the value in settings, perhaps defaulting to the current 80?

**Comment by maximd** [comment]
@asfaltboy: having a default of 50 seems to be the best default according to [How to Write a Git Commit Message](http://chris.beams.io/posts/git-commit/) and [Git documentation's Commit Guidelines](https://git-scm.com/book/ch5-2.html#Commit-Guidelines)

**Comment by stoivo** [comment]
If any of you are running on `dev` branch what do you think
