### ISSUE TITLE
Add command palette entries for editing settings (user and default)

### ISSUE THREAD

**Issue by FichteFoll** [divmain/GitSavvy#424]
Some packages (not enough) have started to adapt adding shortcuts to their configuration files to the command palette. The naming scheme is as follows:

```
Preferences: <Package Name> Settings - <User|Default>
```
([example](https://github.com/FichteFoll/CSScheme/blob/adf06b51176b7b7ab7edf587da30bb03bcf78a0c/Package/Default.sublime-commands#L17-L32))

Please also add some bindings for this package. I hate having to crawl through 3 sub-menus.

**Comment by ddevlin** [comment]
@FichteFoll you should look at [Preference Helper](https://packagecontrol.io/packages/Preference%20Helper). In addition to the hotkeys described in the package page, it exposes a command palette option:

<img width="555" alt="screen shot 2016-06-02 at 00 08 00" src="https://cloud.githubusercontent.com/assets/912471/15727388/58511a3a-2856-11e6-9b9f-c2597cfc3014.png">

Which displays a list of all `sublime-settings` files:

<img width="589" alt="screen shot 2016-06-02 at 00 08 59" src="https://cloud.githubusercontent.com/assets/912471/15727410/737846b2-2856-11e6-9b6c-a72c6cb35e51.png">

You can also use a command palette option or a hotkey to switch from Default to User settings (creating the User setting file automatically if it didn't exist):

<img width="561" alt="screen shot 2016-06-02 at 00 09 28" src="https://cloud.githubusercontent.com/assets/912471/15727424/a5059914-2856-11e6-8b80-38eaef8fd774.png">

**Comment by FichteFoll** [comment]
@ddevlin, thanks for the pointer. I'm using [Edit Preferences](https://packagecontrol.io/packages/Edit%20Preferences) for this purpose normally, but that only opens existing files, i.e. the default preferences file.
