### ISSUE TITLE
Automatically move to next hunk after adding this one

### ISSUE THREAD

**Issue by dufferzafar** [divmain/GitSavvy#427]
In the "Diff File Inline" view, `.` is used to move to next hunk, where as `h` is used to add this one.

But, upon pressing `h`, the cursor stays at the current hunk location. Is this by design?

A better alternative would be to move on to the next hunk after adding this one.

**Comment by dufferzafar** [comment]
Moreover, how can I change these hotkeys? I'm not really a vim-er so, `h`, `,`, `.` seem a bit odd to me.

**Comment by stoivo** [comment]
We used `,` and `.` through the whole package. 
The 'h' is for Hunk and `H` is for unstage Hunk.
The 'l' is for Line and `L` is for unstage Line.

To change this you need to add the highlighted section in the link to you  sublime-keymap file.https://github.com/divmain/GitSavvy/blob/675ad2ec3f77ace31c3a3a30b8dd027c61e59e86/Default.sublime-keymap#L50-64. This will not replace `,` and `.` but add one more key-binding.

@divmain, What do you think of doing to next hunk when staging or reverting a hunk? We should have the same behaviour in staging revertion lines

**Comment by divmain** [comment]
Rolling this into #446.  Please leave feedback there regarding the use cases you have in mind and any thoughts you might have on implementation.
