### ISSUE TITLE
Autocomplete Git commit messages from history

### ISSUE THREAD

**Issue by dufferzafar** [divmain/GitSavvy#428]
Just had this idea now, and am not sure if it's a nice one, but it's definitely food for thought.

I make a lot of commits, that have similar words/phrases in their title & messages. So I think it might be nice to add words from past commit messages to the Sublime auto-complete.

**Comment by stoivo** [comment]
@dufferzafar, do you know if auto complete can autocomplete whole lines?

**Comment by dufferzafar** [comment]
I don't think it can.

**Comment by stoivo** [comment]
Me too, then I don't really understand what you want.

Is there word you use in you commit messages you want to auto to have autocomplete on?

**Comment by dufferzafar** [comment]
Yeah, I want words (& not entire lines) used in previous commit messages to be visible in autocomplete selector.

**Comment by stoivo** [comment]
I will spend some time to see if that is doable. 
I dont this it is a smart idea to add all word used in all commit in the whole history.  How many commit should we take text from? it would take time to iterate over 100 000 of commits.

**Comment by dufferzafar** [comment]
Um, we could filter commits for a particular user? and just keep around 100 or so commits?

**Comment by stoivo** [comment]
DUNNO.
This should be doable, there is one example here https://github.com/alienhard/SublimeAllAutocomplete/blob/master/all_views_completions.py#L19-47.

**Comment by stoivo** [comment]
Would you like you try to make this? I  would like if you could try 😄  I have other issues to fix too.

**Comment by divmain** [comment]
There would be a lot of moving parts for this one, with minimal benefit.  If this is something you'd personally use @dufferzafar, it'd probably even be easier to write a one-off plugin that does this when the commit view is detected, pre-populated with the words that you find yourself using often.

Because there seems to be a minimal benefit + significant complexity, I'm going to close this as `won't fix`.
