### ISSUE TITLE
Jump to line when launching diff file inline

### ISSUE THREAD

**Issue by dufferzafar** [divmain/GitSavvy#433]
When I launch diff file inline from a particular file, it'd be nice if the inline diff view could jump to the exact line I was on rather than opening at the beginning of the file.

This would allow us to jump to diff view, add hunk, go back quickly!

**Comment by dufferzafar** [comment]
Wow, I just realized that this might not be as straightforward as I originally thought since there are many new lines added to the diff view. :disappointed:

**Comment by divmain** [comment]
Rolling this into #446.

**Comment by kaste** [comment]
This has been implemented via https://github.com/timbrel/GitSavvy/pull/1137
