### ISSUE TITLE
Allow staging of a region in inline diff view

### ISSUE THREAD

**Issue by dufferzafar** [divmain/GitSavvy#434]
Suppose I want to stage 5 lines, I have to press 10 keys. `l` 5 times - along with down arrow 5 times to move to the next line. 

I think we should allow users to select a bunch of lines (forming a continous region) and then stage that. Preferably with `l` key itself.

**Comment by stoivo** [comment]
Yes, we could the each line in selection.

**Comment by divmain** [comment]
This is actually very difficult to accomplish, and I'm inclined to say "no".  There would have to be a lot of specialized logic surrounding what sorts of selections could occur - entire `+` hunks, parts of `+` hunks, whole hunks and parts of others, etc.

Most folks would ultimately use their keyboards to select and then stage, since the mouse would be clumsy in this case, so we wouldn't be saving a ton of keystrokes either.

I'm willing to hear a case for it (and please say so if you think I'm missing something), but for now I'm going to close as `wont-fix`.

**Comment by sentience** [comment]
What if the ‘l’ shortcut moved the cursor to the next line after staging the current line? That way you could tap your way through a series of adjacent lines just by hitting the ‘l’ key repeatedly.

**Comment by divmain** [comment]
That's much more doable.  I find myself pressing `l.l..l.l.l` to scroll through a diff and incrementally stage.  Do you find that cumbersome @sentience?  I'm open to making this configurable: `auto-scroll-after-stage` or some such.

**Comment by sentience** [comment]
I don’t think implicitly scrolling to the next changed line is necessarily desirable. After staging a line I usually like to see the same view, just with the highlighting updated, as clear confirmation that the action I requested has been performed.

I think simply moving the cursor to the next line after staging a line would be a nice middle-ground, where it would enable l-l-l’ing through a series of adjacent lines (saving the ‘.’ keystrokes in your workflow), without potentially shifting the view to a change much later in the file and losing the user’s sense of place.

**Comment by dufferzafar** [comment]
I'd actually created another issue #427 for tracking this moving to next hunk (or next line.) So yeah having a setting for that would be great!

**Comment by stoivo** [comment]
That is a much easier to implement the the making a selection and stage that section. We will make it this new setting. This should not be difficult to make compare to staging selections.

**Comment by divmain** [comment]
Perhaps surprisingly, there's still a bit of work to do to move to the next line after pressing `L`.  For example, if you staged a red line, you probably don't want to move to the next line - you'd wan to stay on the same one.

In any case, I think we have a number of possible ways to change how auto-scroll works in the inline-diff views.  Please leave feedback in #446 regarding the use cases you have in mind and any thoughts you might have on implementation.
