### ISSUE TITLE
Output to panels

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#44]
Most of the outputs in this plugin is done to the status bar.
I would like to see an option to output to panels, especially for certain actions like commit or push where you'd want to see the output, like a response from the server(s).

**Comment by jbrooksuk** [comment]
:+1: for showing the push output in a panel.

This is especially useful when pushing to Dokku or Heroku for example, where the buildstep progress is long.

**Comment by divmain** [comment]
In `GitSavvy.sublime-settings`:
```json
  "show_panel": ["push"]
```

**Comment by p3lim** [comment]
As far as I understood it, this is how you'd create and output to a panel in ST3:
```Python
window = sublime.active_window()
output = window.get_output_panel("name_of_panel")
window.run_command("show_panel", {"panel": "output.name_of_panel"})
output.set_read_only(False)
output.run_command("append", {"characters": "Hello world!"})
output.set_read_only(True)
```
Documentation is not that good, so this might save you some time.

**Comment by divmain** [comment]
Thanks @p3lim.  I'll pick this up early this upcoming week.  GitSavvy displays panel output for failed Git commands, so additional conditions is a simple add.  I'll make this opt-in, where you can configure panel output using `show_panel` as seen in my above comment.
