### ISSUE TITLE
Link navigation in GitSavvy help is broken

### ISSUE THREAD

**Issue by sentience** [divmain/GitSavvy#440]
The GitSavvy Help introduction instructs the user to follow Markdown links with ⌘Enter; however, this keystroke is bound to **Edit > Text > Insert Line After** in Sublime Text 3 by default. Users are therefore unable to follow the links in GitSavvy’s help as instructed.

**Comment by stoivo** [comment]
Do you have any other suggestions?

**Comment by divmain** [comment]
Hmm this is working for me.  What is your OS and Sublime version, @sentience?  If the behavior is non-deterministic, we may just end up changing the key bindings.

**Comment by sentience** [comment]
OS X 10.11.5, Sublime Text 3 v3117.

**Comment by sentience** [comment]
I note that when I open GitSavvy Help, the syntax used is ‘Plain Text’. Didn’t GitSavvy used to have a specific syntax definition for its help? At the very least I’d expect it to be displayed as Markdown.

**Comment by sentience** [comment]
I can confirm that if I switch the syntax to Markdown manually, the links work.

**Comment by divmain** [comment]
Ah that makes sense, actually - although I'll still look into why the Markdown syntax might not be applied.  The help system uses a [markdown syntax selector](https://github.com/divmain/GitSavvy/blob/aa95250489eab71c463ebcba030c04c638434ee4/common/commands/help.py#L139) to identify all links on the page, and whether the user's cursor is contained by one.

**Comment by tollus** [comment]
hey @divmain I was able to see the same problem, however the problem only happens for me when I install via the package manager. When I manually installed via `git clone` the markdown highlighting was automatically selected.

(OSX 10.10.5, Sublime Text 3114)

**Comment by asfaltboy** [comment]
I believe we refactored the syntax files a while back, please reopen if this still happens to you and provide more information (which syntax is selected instead of markdown, etc)
