### ISSUE TITLE
Rebase moving without action

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#452]
When I want to move commits around I only have the option to move them up/down one at a time.
Sometimes I need to move certain commits to a certain place, or squash with a certain commit, and moving them one position at a time can yield conflicts.

Adding an option to select a commit (or multiple) for any action before commiting (basically queuing) them would be nice.

For displaying this, you could use a different color for the ref, and/or indent them further, just thoughts.

**Comment by divmain** [comment]
Can you give me an example of a time when moving a commit several places would not result in a merge conflict, but moving one spot at a time would result in a merge conflict?  I assume it'd be something you changed and then changed back in the context of your branch?

We've thrown around a queuing mechanism before, and while it sounds like a useful feature, I'm not really sure how it would function in the context of the dashboard.  It might be worth building something closer to `git rebase -i`, or maybe even providing a shortcut to use `git rebase -i` itself.

**Comment by p3lim** [comment]
When there are hunks close to each other would be a good example.

**Comment by divmain** [comment]
Ah that's an irritatingly solid example.  OK.  How do you feel about farming this work out to `git rebase -i`?  That may be hard to integrate well with GitSavvy/Sublime - Git makes certain assumptions about how that workflow should happen (namely, you're doing it on the terminal and it will open a text editor in your terminal, full stop).

We could try to create some sort of "stage changes" mode, where you move commits around, drop commits, etc, but they won't take effect until you accept all of the changes (with an option to abort).  It would add significant complexity to the rebase dashboard, which is a downside, and would also diverge from the real-time behavior, which is also a downside (unless we dump realtime behavior altogether).

In any case, this will be a largish task.  If you have UX ideas, or anything that might make for a good middle-ground, I'm all ears!

**Comment by p3lim** [comment]
> (namely, you're doing it on the terminal and it will open a text editor in your terminal, full stop)

Setting the gitconfig flag `core.editor` to `subl -nw` works fine, it's what I've used on Windows forever, and it is something you can do on a non-global basis, as long as you have SublimeText as part of the path (or just use the full path).

> We could try to create some sort of "stage changes" mode, where you move commits around, drop commits, etc, but they won't take effect until you accept all of the changes (with an option to abort).

Sounds perfect to me, the dashboard has the (UX) potential of normal `rebase -i` operation.

I would help on the matter, but I've fallen behind on the packages internals, and don't have much time to work on such a large task in the foreseeable future.

**Comment by divmain** [comment]
Alright, I'll pick this up when I can.  Agree that this isn't ideal.  A smaller change that might help with your particular use-case is fixing up commits directly from staged changes.  This may provide more flexility to make small changes to earlier commits, that you currently can't edit because of intermediate commits that happen in the same file...
