### ISSUE TITLE
Merge resolve default commit message

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#458]
Default behavior in git is to automatically supply a commit message for merging, formatted as such:
`Merge branch 'from-branch-name' into to-branch-name`

When resolving a conflict from the status dashboard however, committing the merge has no commit message.

Not sure if this is a bug, but if not, consider it a missing feature.

**Comment by randy3k** [comment]
relatd to #426

**Comment by randy3k** [comment]
I do have the merge message.
![untitled 1](https://cloud.githubusercontent.com/assets/1690993/16996911/409677ae-4e81-11e6-8207-775aa93fb534.gif)

**Comment by stoivo** [comment]
@p3lim, can you supply with which commands you are using to find this behavior?

**Comment by p3lim** [comment]
1. I merge a branch into another branch on the branch dashboard.
2. There's a conflict, I go back to the status dashboard
3. I resolve the conflicts in the file(s)
4. I stage the files
5. I press <kbd>C</kbd> to commit

At which point the commit view is empty (except for the help text and the commit diff below).

**Comment by divmain** [comment]
Can you also include Sublime version, Git version, OS version?

**Comment by p3lim** [comment]
SublimeText build 3120  
Git 2.9.2  
Windows 10 Pro x64

**Comment by sentience** [comment]
I was seeing this behaviour as well with Git 2.6.2. Upgraded to Git 2.10.1 and I’m no longer having a problem.

**Comment by p3lim** [comment]
Can confirm, can't reproduce with 2.10.1, closing this issue.
