### ISSUE TITLE
Is it possible to have the git push panel shown during the push and not when finished?

### ISSUE THREAD

**Issue by hanoii** [divmain/GitSavvy#476]
I found about 

`"show_panel_for": []`

but I would like to see the output of the push while it happens, not just in the end, is that possible.

**Comment by stoivo** [comment]
Just to open it and leave it blank(or the command currently executing) until the command is done?

**Comment by hanoii** [comment]
Well, I am on a project that does a few things when you git push (deploy an environment and builds a few things, and while that happens, which can takes up to a few minutes, it's showing output. I would like to see this output as it happens, not all at once at the end.

**Comment by stoivo** [comment]
How is this set up? with git hooks?

Is is possible that you can share who it is set up, so I can see what I can do about it?

You probably want to change all that is related to your project with some dummy values.

**Comment by hanoii** [comment]
I assume it is with git hooks, it's not me that's doing it.

It comes from https://platform.sh/

This is some of the output I get, but not all at once.

```
$ git push
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 396 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)

Validating submodules.
Validating configuration files.
Processing activity: **yyy** pushed to **Master**
    Found 1 new commit.

    Building application 'php' (runtime type: php:5.6, tree: c51185d)
      Slug already built for this tree id, skipping.

    W: Route 'www.{default}' doesn't map to a domain of the project, mangling the route.
    W: Route '{default}' doesn't map to a domain of the project, mangling the route.

    Re-deploying environment neek54wncnlig-master.
      Environment configuration:
        php (type: php:5.6, size: L, disk: 10240)
        mysql (type: mysql:10.0, size: XL, disk: 4096)
        redis (type: redis:3.0, size: M)

      Environment routes:
        

To xxx@git.eu.platform.xxx.git
   cc53780..35c417c  master -> master
```

**Comment by divmain** [comment]
Unfortunately, this isn't possible with our current architecture.  Python doesn't do async very well at all, and that includes interactions with subprocesses.

I've looked into a subprocess construct that gives iterative output - something similar to what `SublimeRepl` does ([link](https://github.com/wuub/SublimeREPL/blob/master/sublimerepl.py#L60-L74)).  The concept itself is relatively simple, but it would mean significant changes to the entire codebase to work with the change.  So far we've only found some very small use cases that don't seem worth the effort required to get us there.

It's obviously not ideal, and I may revisit when I have a bit more time to spend on it.  But for now, I'd say your best bet is to push from the terminal.

**Comment by stoivo** [comment]
I will try to up some git hooks that take time but I am not sure if we can read the STDout before all is printed. 

I will give it a try.

**Comment by hanoii** [comment]
I wonder if this is still a won't fix or there's anything looking easier at the moment?

**Comment by stoivo** [comment]
The current structure does not allow for that.  If/when we make it possible  this would be really cool.
