### ISSUE TITLE
Commit: Need easy access to previous commit messages

### ISSUE THREAD

**Issue by tomngo** [divmain/GitSavvy#492]
I've migrated almost completely over to GitSavvy commit, but I keep going back to other interfaces for access to previous commit messages. If others agree, here are three possible solutions.

1. Put previous commit messages in the comments below

1. Add a `<tab>` command to iterate through previous commit messages

1. At least turn the Rebase dashboard upside down (right side up) so that the most recent commits are at the top. Right now, one of my workarounds is to invoke that dashboard, scroll to the bottom, and copy to clipboard.

**Comment by divmain** [comment]
Let's combine this with #488, and come up with a config option to enable any number of useful bits of information in the commit view.
