### ISSUE TITLE
How to use with BashOnWindows's Git?

### ISSUE THREAD

**Issue by laggingreflex** [divmain/GitSavvy#493]
Since [Windows 10 now has Ubuntu Bash](https://github.com/Microsoft/BashOnWindows), one can easily install Git on it with `apt-get` and even use it from `cmd.exe` as `bash -lic git ...`. So I'm using the setting: 

    "git_path": "bash -lic git"

but it's showing error: "[WinError 2] The system cannot find the file specified"

It would be incredible to be able to use this in GitSavvy... is it possible?

**Comment by laggingreflex** [comment]
I tried a workaround, I created a `git.cmd` with `bash -lic git %@` and tried to use it as the `git_path`, but now getting error like this:
![`git.cmd rev-parse --show-toplevel` failed with following output:
E<NULL>r<NULL>r...`](http://i.imgur.com/SUWmek0.png)

**Comment by laggingreflex** [comment]
I guess there would be another issue even if that did work. The status tab in GitSavvy requests repository directory name which would be something like `/mnt/c/project/...` returned from BashOnWindows environment and that wouldn't work, right?

**Comment by stoivo** [comment]
Hello, I am sorry for late response.

I would like to give you the answer to your question, but I don't know. I don't have any machine to test BashOnWindows. 

I wonder, where is bash located on Windows drive? You can find it with `$ which bash`. You might want to try 

```
"git_path": "C:/Program Files/??/bash -lic git"
```
or 
https://github.com/divmain/GitSavvy/blob/7654de2a5ac0b857b85c9ee78d4706c44076f44d/GitSavvy.sublime-settings#L15-L21

**Comment by laggingreflex** [comment]
It's in `C:\\Windows\\sysnative\\bash.exe` or `C:\\Windows\\System32\\bash.exe` and I tried them but same error.

Is it that `git_path` expects an EXE and only that, not any arguments etc? Maybe it's trying to take the whole string "bash -lic git" as a file path?

But like I said, I tried a workaround, created a `git.cmd` with `bash -lic "git %*"` and tried to use it as the `git_path`, which worked in the sense that I'm at least not getting "[WinError 2] The system cannot find the file specified", but now getting error like this:
![`git.cmd rev-parse --show-toplevel` failed with following output:
E<NULL>r<NULL>r...`](http://i.imgur.com/SUWmek0.png)

I also see my `git.cmd`'s batch file text contents as well, which you normally don't if you're just executing the file. I'm not well versed in python but is there a difference between executing a binary and a batch file in windows though python, especially in the way it expects their output in a certain way or executes them a bit differently?

**Comment by laggingreflex** [comment]
Also, like I said, even if all above did work as expected I suspect another issue. GitSavvy requests the path of the repository directory which if returned from Windows Bash's `git` would be something like `/mnt/c/project/...` but since GitSavvy is in Windows environment it would expect something like `c:\project...`, so it might not actually work...

**Comment by stoivo** [comment]
cc @divmain

**Comment by stoivo** [comment]
> Microsoft/BashOnWindows#2
Issue there exactly is the problem at hand here. Once that is fixed, so will this error. bash.exe cannot use pipes properly.

RaphaelArkadyMeyer from SublimeTextIssues/Core#1346

This is the make problem, so there is nothing I can do about it now.

**Comment by stoivo** [comment]
Hello again, 

It looks like it is fixed in BashOnWindows but waiting for a major release. I think I would just install git on the Windows the old way. 

Or maybe you have found another solution.

**Comment by laggingreflex** [comment]
This might complicate things even if it did work (the /mnt/c path issues as I said above), so I'll probably stick to git on windows. Thanks for looking into it.
