### ISSUE TITLE
STATUS: commands don't work if cursor at end of line

### ISSUE THREAD

**Issue by aristidesfl** [divmain/GitSavvy#497]
On the STATUS: view, if the cursor happens to be at the very end of the line which represents a file, the commands don't work.

**Comment by randy3k** [comment]
I fixed it at be6d404085402892ee1810689d03ce34f4c5c2ea already.

**Comment by stoivo** [comment]
Thats right.
I will close this one. Feel free to reopen.

**Comment by aristidesfl** [comment]
Thanks 👍
