### ISSUE TITLE
Improve detection of root commit for branches when opening Rebase dashboard

### ISSUE THREAD

**Issue by sentience** [divmain/GitSavvy#499]
We use a Git Flow-esque branching structure. Consequently, most of my branches are rooted on the `develop` branch; however, the Rebase dashboard always seems to guess I want to use `master` as the base ref. It would seem the logic for detecting the root commit of a branch could use some work.

The `"rebase_default_base_ref"` preference is useful for relieving the pain of this in most cases; however, the branches that _are_ rooted on `master` are then incorrectly compared to `develop` when I open the Rebase dashboard.

**Comment by randy3k** [comment]
It was addressed long ago.
