### ISSUE TITLE
[M] fetch and merge into active branch

### ISSUE THREAD

**Issue by airtonix** [divmain/GitSavvy#500]
```
`/usr/bin/git merge o r i g i n / d e v e l o p` failed with following output:

merge: o r i g i n / d e v e l o p - not something we can merge
```

![peek 2016-09-12 11-43](https://cloud.githubusercontent.com/assets/61225/18422807/2c0fa882-78de-11e6-94ff-6013051d8b8d.gif)

**Comment by stoivo** [comment]
Can you make a log with where commands 
https://github.com/divmain/GitSavvy/blob/master/docs/debug.md#gitsavvy-start-logging
