### ISSUE TITLE
No pull support in STATUS view

### ISSUE THREAD

**Issue by rchl** [divmain/GitSavvy#501]
The plugin has a `git: Pull` command in the command palette but it doesn't seem to provide equivalent functionality in STATUS view. If the branch is tracking remote branch, I think it makes sense to support `pull` from that view.

Current solution is to either use command palette or:
 - go to BRANCHES view
 - press h to fetch remote branches
 - either show remote branches, find one that we are tracking and use merge
 - or go to REBASE view and press r to rebase on top of tracked branch

First option lacks visual feedback and second is too cumbersome.

**Comment by stoivo** [comment]
https://github.com/divmain/GitSavvy/issues/379

I am using the first alternative with command palette. Have you looked at the setting called "show_panel_for"? It will make a visual feedback.
https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L83-L87

**Comment by divmain** [comment]
Yep, and there are definitely ways you can add this yourself without too much trouble.  #379 has details.
