### ISSUE TITLE
Support for creating fixup commits

### ISSUE THREAD

**Issue by rchl** [divmain/GitSavvy#503]
It would be useful to have support for creating the fixup commits (`git commit --fixup sha`). The UI could work by providing a list of commits in the command palette.

Questions:
 - How many commits should command palette show (should it determine the base same way as rebase view)?
 - How to determine which commits to show? Any commits that already start with [squash|fixup]! could probably be skipped as creating a commit that has two of those is in theory invalid. At least in the sense that it would make git rebase --interactive not recognize those as proper fixups.
 - Should `fixup! <sha>` or `fixup! <summary>` be created and should it be configurable? `fixup! <summary>` is preferable IMO as it's more resilient to partial rebases.

Of course GitSavvy wouldn't need to use `git commit --fixup` internally but rather just open commit view with pre-populated, valid fixup/squash summary. That would allow adding description to the commit in addition to the summary.

**Comment by randy3k** [comment]
👍 for this, fixing up commits is the only thing that I still rely on Terminal.

**Comment by sentience** [comment]
See https://github.com/divmain/GitSavvy/issues/220#issuecomment-255411405 for a method for doing fixups in GitSavvy using custom commands.
