### ISSUE TITLE
Consider using 'u' for both staging and unstaging

### ISSUE THREAD

**Issue by rchl** [divmain/GitSavvy#504]
Currently there is 's' for staging and 'u' for unstaging in status view. Both actions are exclusive and triggered in different contexts so both could just work using the same key. Preferably 'u' as that's the shortcut `tig` uses for example.

That would free up 's' for doing other stuff. Maybe showing/hiding stashes.

**Comment by stoivo** [comment]
I would prefer to keep it the same. 

Thought, if you would like to use 'u' for staging and unstaging you can set it in you'r sublime-keymap file. 
You would need to add with different shortcuts 
https://github.com/divmain/GitSavvy/blob/master/Default.sublime-keymap#L87-L104

**Comment by divmain** [comment]
I agree with @stoivo on this one.  There needs to be a compelling reason to change this, since its been there from the beginning.
