### ISSUE TITLE
Vim friendly mode breaks "skip commit during rebase" shortcut

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#507]
The shortcut `[k] skip commit during rebase` is not usable in vim friendly mode, since <kbd>k</kbd> is already used as the "up" shortcut.

**Comment by divmain** [comment]
Can you suggest a remedy?  We could remap the command to a different key, or we could suggest users add a second key-binding if they're Vintageous users.

**Comment by asfaltboy** [comment]
Can we remap skip to uppercase k (K) ?

**Comment by stoivo** [comment]
Only for skip commit during rebase? is there any other shortcuts we should make vim friendly?

**Comment by stoivo** [comment]
I push one commit on master can you check that it works?

**Comment by asfaltboy** [comment]
I think just conflicting keys with j/k have caused me trouble.  I can
recall nothing else at the moment

**Comment by stoivo** [comment]
Can you check if it works with uppercase k (K)?

**Comment by asfaltboy** [comment]
Thanks @stoivo ! Uppercase K works great.
