### ISSUE TITLE
Update exclude content behavior in commit view

### ISSUE THREAD

**Issue by divmain** [divmain/GitSavvy#51]
Currently just removes everything including and after the `COMMIT_HELP_TEXT`.  Instead, add a canonical separator below which all content will be excluded.  Follow-up to #45.

**Comment by yyyc514** [comment]
I saw this. Why not just pass the full thing to git?  It's going to ignore the comments.  That's how the existing git edit workflow works if you let git drive the process.

**Comment by yyyc514** [comment]
Ah, this is because of showing a full diff...

**Comment by yyyc514** [comment]
Can we control the view layout?  Sure seems like this would make a lot more sense with commit on top and actual diff (in it's own view) on bottom.

**Comment by yyyc514** [comment]
Splitting, syntax coloring, etc...

**Comment by divmain** [comment]
Yes, I plan to significantly refactor using Sublime regions, which will help with cleanly partitioning the content, as well as nested syntax definitions.

**Comment by divmain** [comment]
Closing in favor of #50.
