### ISSUE TITLE
Not picking up `typechange`

### ISSUE THREAD

**Issue by allen-zeng** [divmain/GitSavvy#510]
Gitsavvy isn't picking up the type changes in the status dashboard.

Steps to reproduce:
- create a symlink for a file
- commit the file
- delete the symlink and add a file (not a symlink) with the same name back in

After these steps, Gitsavvy reports that the directory is clean, whereas running `git status` reports that there is a `typechange` (as opposed to `modified` and others).

**Comment by stoivo** [comment]
Confirmed, it is a bug. I will look at it.

**Comment by stoivo** [comment]
Thanks for reporting.
Sorry for late reply

**Comment by allen-zeng** [comment]
No problems - thanks for looking into it! :)

**Comment by stoivo** [comment]
Do we need to have some special indicator to status view if it is typechange?

**Comment by allen-zeng** [comment]
It wouldn't hurt, but obviously depends on how much work :)

**Comment by stoivo** [comment]
We have a '- filename' for deleted, maybe add 't filename' for typechange? That is less than a minute fix. But the throwback is that it is not self explaining.

Any idea?

**Comment by allen-zeng** [comment]
Yeah if we want a single letter denoting type changes then we may have to add a legend of some sort.

GitHub pull request emails have statuses before each file, most obviously "M" for modified, "A" for added. Don't know what they use for type change though. Consistency with that might make the adoption easier

**Comment by stoivo** [comment]
Do you have one example of how github sends it on email?

**Comment by stoivo** [comment]
ping @allen-zeng

**Comment by allen-zeng** [comment]
Sorry about the delay. I managed to find [some documentation](https://git-scm.com/docs/git-status) on the statuses (scroll down to the section called "OUTPUT").
>- M = modified
- A = added
- D = deleted
- R = renamed
- C = copied
- U = updated but unmerged

Unfortunately we don't know what a `typechange` type is abbreviated to, my assumption is "T", but to be sure, we'd have to manufacture a pull request for it. I've forked this repo and created (a branch called `typechange`](https://github.com/allen-zeng/GitSavvy/tree/typechange). Can you make a type change to the symlink file and send me a pull request? I should get an email then.

**Comment by stoivo** [comment]
Here is you very first PR allen-zeng/GitSavvy#1

**Comment by allen-zeng** [comment]
lol I'm so excited!

But unfortunately this is all I get:
![image](https://cloud.githubusercontent.com/assets/7380931/19611420/62d7b10c-982d-11e6-8678-9af742b24831.png)

So I guess given how relatively rare this is, we may be able to get away appending the file name with a "(typechange)" in grey, similar to the remote tracking branch name on the branches dashboard

**Comment by stoivo** [comment]
there is  problem with that since what if someone call there file for  `I like so change packages (typechange)` also that means at every command reading that line will have to parse away ` (typechange)`. 

So my goto is to not add anything to it. It is not the greatest. I would say that if someone change this that are aware of it and there is no problems. This is also how github does it.

**Comment by allen-zeng** [comment]
Yeah good point. What we want to achieve is so that it is reported, and more importantly that we can stage the change. With those in mind, adding the rarity of this type of change, I think it's ok to not have to have an indicator at all.

**Comment by stoivo** [comment]
Added PR for it, not many character changes :)

**Comment by allen-zeng** [comment]
Wooo!! Thanks @stoivo for fixing it so quickly!
