### ISSUE TITLE
all option for "git log" and "git graph" 

### ISSUE THREAD

**Issue by don-harden** [divmain/GitSavvy#523]
First off, major kudos for GitSavvy!!! I've now switched from the Git plugin.
Have you considered adding an **All** option to display **git log** and **git graph** for all branches?

**Comment by randy3k** [comment]
Oh, it used to have an all option in `git: graph`, but it is lost under the latest refactoring. We shall add it back.

**Comment by randy3k** [comment]
perhaps we should track this issue at #486.

**Comment by asfaltboy** [comment]
@randy3k can you point us to the location where this feature was removed?

**Comment by divmain** [comment]
Yeah @randy3k, for regressions, we definitely don't want to roll into a separate ticket.  Reopening this.

**Comment by randy3k** [comment]
I am working to bring it back.

**Comment by divmain** [comment]
Thanks again!
