### ISSUE TITLE
Rebase view: editing a merge commit fails

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#524]
I often edit commits in the rebase view by pressing <kbd>e</kbd>). However, merge commits fail to be edited, and the following error is displayed:

```
`/usr/local/bin/git cherry-pick --allow-empty --allow-empty-message --no-commit 7035574424b1e8a668820ece6d401d1e731ee4e0` failed with following output:

error: Commit 7035574424b1e8a668820ece6d401d1e731ee4e0 is a merge but no -m option was given.
fatal: cherry-pick failed
```

Not sure if we simply use `-m` option here.

related to #426

**Comment by randy3k** [comment]
The same bug also occurs when moving/ squshing (revoking `rewrite_active_branch`) if there is a merge commit.

The current implementation of `rewrite_active_branch` does not handle merge commits correctly.

**Comment by randy3k** [comment]
Just gave it a thought, it is difficult to fix. We cannot just use the `-m` option, as it will convert the merge commit to a normal single-parent commit...

**Comment by asfaltboy** [comment]
If I read [`git-rebase` code here][1] and [also here][2] correctly, we should fork on whether this is a merge commit and use either `cherry-pick `or `git-merge` (passing in a list of parents and the new commit message) accordingly.

[1]: https://github.com/git/git/blob/master/git-rebase--interactive.sh#L1160-L1180
[2]: https://github.com/git/git/blob/master/git-rebase--interactive.sh#L386-L387

**Comment by randy3k** [comment]
Sounds like right. It is basically a rewrite of `rebase -i -p`. 

related to #297, #452

**Comment by divmain** [comment]
Merge commits have historically been really difficult to manage properly in the rebase dashboard.  Would love to see this addressed, but want to avoid adding the functionality at the cost of greatly increased implementation complexity.

**Comment by asfaltboy** [comment]
I'm not sure we can (or even want) to allow every action for a merge commit, but editing commit message should be possible, I do it myself a lot.

But I can't imagine how, for example, one could move a merge commit up/down .. unless the whole sub-tree is moved with it. 

In any case, I think merge commits are pretty simple to preserve, we simply need to detect it's a merge (get multiple parents) and redo the merge, instead of the cherry pick. Here's a list of relevant actions and what I suggest we do with merge commits:

- [ ] <kbd>q</kbd> squash commit with previous -- _remove  merge commit_
- [ ] <kbd>Q</kbd> squash all commits -- _remove merge commit_
- [ ] <kbd>e</kbd> edit commit message -- _redo merge commit with new message_
- [ ] <kbd>p</kbd> drop commit -- _remove merge commit_
- [ ] <kbd>d</kbd> move commit down (after next)  -- _show warning_
- [ ] <kbd>u</kbd> move commit up (before previous)  -- _show warning_
- [ ] <kbd>r</kbd> rebase branch on top of...  -- _cherry pick normal commits + redo merge commits_
- [ ] <kbd>K</kbd> skip commit during rebase  -- _remove merge commit_

**Comment by randy3k** [comment]
For `rebase branch on top of`, the current implementation of using `git rebase -p` should work fine.
The purpose of `rewrite_active_branch` is to gimmick the interactive rebase `git rebase -i -p`.

**Comment by randy3k** [comment]
@asfaltboy If you are not working on it, I could try to address this.

**Comment by asfaltboy** [comment]
I am not, please assign at will :)
