### ISSUE TITLE
Add fork as remote does not include all forks

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#528]
For large projects, like GitSavvy, only the first few forks (one page?) are shown. If you're looking for a specific fork, which is often the case, you may have trouble finding it.

I suggest keeping the list short, and adding 2 options: _"Next page"_ and _"Custom"_, to allow manually entering a `<user>/<repo>` formatted fork label.

**Comment by divmain** [comment]
Surprised to hear this, since the API docs don't mention that this endpoint returns paginated data.  Definitely seems to be a bug if not all forks are listed.

**Comment by asfaltboy** [comment]
Seems it's a generalized feature, across all resources, as [explained here][1] and in [more detail here][2]. 

[1]: https://developer.github.com/v3/#pagination
[2]: https://developer.github.com/guides/traversing-with-pagination/

**Comment by randy3k** [comment]
#540 adds [show_paginated_panel](1), which may be useful for address this issue.


[1]: https://github.com/randy3k/GitSavvy/blob/6ec048118d2a3a6f7359b4d229d8ec6d2361a196/common/quick_panel.py#L5
