### ISSUE TITLE
I can't seem to find git graph ALL anymore.

### ISSUE THREAD

**Issue by mkstix6** [divmain/GitSavvy#537]
As recently as last week I had a command that was called something like 'git graph all' which showed the git tree/graph-thing for all the branches and remotes simultaneously. Even if they weren't associated or if they were ahead. By recently I mean I had it at some time on Friday but it was gone on Saturday.

I could be mistaken but I thought this command came from gitsavvy. Forgive me if I'm wrong.

This command provides a fantastic overview of the branches without iterating through them all individually. It can really be helpful when trying to keep a handle on what other members of the team are up to. I feel quite a bit slower without it 😞.

**Comment by asfaltboy** [comment]
This dupes #523, but we should definitely bump up this regression.

**Comment by mkstix6** [comment]
Apologies. I must had a Monday morning search fail. I'll close this one.
