### ISSUE TITLE
Can't view commits from Graph view

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#543]
Got this error:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
TypeError: run() missing 1 required positional argument: 'action'
```

When pressing <kbd>Enter</kbd> on a commit in the Graph view.

**Comment by randy3k** [comment]
I cannot reproduce, what is you GitSavvy version?

**Comment by p3lim** [comment]
2.13.0

**Comment by randy3k** [comment]
Could you restart Sublime Text and try again, I suspect it was caused by the automatic upgrade and Sublime Text was not restarted.

**Comment by p3lim** [comment]
You are correct, works fine after a restart, I see new functionality on the commit selection and I guess ST didn't unbind the previous shortcut assignment when the new one was added.
