### ISSUE TITLE
Branch prompts are not consistent

### ISSUE THREAD

**Issue by randy3k** [divmain/GitSavvy#546]
There are many commands which require a branch prompt. For example 
- `git: cherry-pick`
- `git: pull`
- `git: log` -> `Filtered by branch`
- `git: merge` etc

However, the ways that branches are displayed are not consistent. Some commands ask for a remote first then branch, some commands ask to choose `remote/branch`.  I guess it would be more consistent to replace the prompts with a function. Maybe something like,

```python
branch_prompt(on_done, selected_branch=None, ask_remote_first=True)
```

- How do you guys think? @divmain @stoivo @asfaltboy 

- A related question is: where should the function `branch_prompt` be placed? It is a UI related function but also very git related. There is no home for such functions currently. There are quite a few functions/classes in `common` which fall into this category, e.g. `common.quick_panel.show_log_panel`. 

- Similarly, there is a need for remote prompt.

- Also related to #371

**Comment by asfaltboy** [comment]
This refactoring sounds great, we'll definitely clean up the code with this. Some commands may want to prompt for local branches only ([`git: flow init`][1] is the only one I can come up with right now that does that).

We should have common UI mixins/helpers. To be available to all commands. Stuff like "get selected branch/es / commit/s" helpers, as [mentioned in this review comment][2], can also go in here, as well as the mentioned "remote prompt".

[1]: https://github.com/divmain/GitSavvy/blob/master/docs/flow.md#flow-init
[2]: https://github.com/divmain/GitSavvy/pull/535#discussion_r86278276

**Comment by divmain** [comment]
I'm in favor of removing the prompt for remote when it isn't necessary.  If you're used to the command line, you'll type something like `git pull origin master`.  If you type `origin master` in the command palette, that'll select `origin/master`.  I don't know why I originally added the intermediate step of prompting for the remote, but I'm definitely in favor of removing it and making the prompts consistent.

I'm fine with doing this as one of a set of git-and-UI-related helper functions.  That seems a reasonable abstraction given the direction things are going.
