### ISSUE TITLE
GitSavvy makes Sublime unusable when git is not installed

### ISSUE THREAD

**Issue by firelizzard18** [divmain/GitSavvy#551]
I installed sublime on a new machine. I copied AppData/Roaming/Sublime Text 3. When I try to do anything, GitSavvy absolutely blasts me with messages that git can't be found. It has made sublime utterly unusable. I can't even disable the package, because trying to open the command window triggers another message.

FOR THE LOVE OF GOD, ADD AN OPTION FOR "SHUT THE F*** UP! I KNOW I DON'T HAVE GIT INSTALLED YET!"

**Comment by firelizzard18** [comment]
Thanks for the rapid response!

**Comment by asfaltboy** [comment]
No problem, I feel your pain! Hope you worked around this meanwhile and this can wait until next release

**Comment by firelizzard18** [comment]
I copied `git_command.py` into `%appdata%/Roaming/Sublime Text 3/Packages/GitSavvy/core/`. [Package control](https://packagecontrol.io/docs/customizing_packages) indicates that this should overwrite the file in the packed package. It may have just broken GitSavvy. But that's OK, because now sublime isn't broken, and I'll remove the file once I have git installed.
