### ISSUE TITLE
GitSavvy reporting `Permission denied (publickey)` after updating ssh key

### ISSUE THREAD

**Issue by rkpatel33** [divmain/GitSavvy#559]
I just updated my Github SSH key using by my git bash and not when I try to pull from GitSavvy in Sublime, I get the follow error:

```
`/usr/local/bin/git pull origin master` failed with following output:

ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have made no other changes to my system. If I start Sublime from the terminal with `subl` everything works fine.

I ran `which git` and `echo $PATH` tow commands from terminal and the ST3 console (per this issue https://github.com/divmain/GitSavvy/issues/243) and got the following output. It seem to look fine to me. Anything look amiss here?  

```
⇒  echo $PATH 
/opt/local/bin:/opt/local/sbin:/Users/rishi/.virtualenvs/global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/rishi/.fzf/bin

⇒  which git                                                                                                                                                                                        (env: global) 
/usr/local/bin/git
```

Console output:

```
>>> import os; os.environ.get('PATH')
'/usr/local/lib:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin'

>>> import shutil; shutil.which("git")
'/usr/local/bin/git'
```

Thx.

**Comment by stoivo** [comment]
If you run  `/usr/local/bin/git pull origin master` from the terminal, does that work?

**Comment by rkpatel33** [comment]
Yes, that works fine:

```
⇒  /usr/local/bin/git pull origin master                                                                                                                                                             (env: global) 
From github.com:meetalbert/albert
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```

**Comment by divmain** [comment]
It sounds like you've added a password-encrypted SSH key.  Git is prompting you for your password, but this does not work in a non-Terminal environment.  You can try installing [mac-ssh-keypass](https://github.com/markcarver/mac-ssh-askpass).

**Comment by rkpatel33** [comment]
Ah, I see. I just blew out the old key and created one with no password. Thank you for the quick response!

**Comment by H4rsh4nk** [comment]
i'm on kali linux, i have setup SSH key. Now git push works with command line but it says '_sign_and_send_pubkey: signing failed for RSA "/root/.ssh/id_rsa" from agent: agent refused operation
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository_.' 
when pushed with Savvy

**Comment by kaste** [comment]
There is no easy tip here.  It could be that Sublime uses a different environment than your Terminal.  Or you changed stuff in the Terminal but did not persist.  Try opening the console in Sublime.  There you have a python REPL.

```
>>> from subprocess import getoutput
>>> getoutput("git push -v")
```

This is a bit simplified.  Make sure to start Sublime from the Terminal from the correct working dir.  If that just succeeds, try the more involved, but realistic, command:

```
>>> from subprocess import Popen, PIPE, STDOUT
>>> print(Popen(["git", "push", "-v"], stdout=PIPE, stderr=STDOUT).communicate()[0].decode().replace("\\n", "\n"))
```

Now, `push -v` should be verbose already.  You can run `ssh-add -l` etc in the same way.
