### ISSUE TITLE
Rebase: status incorrect after failure

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#560]
Trying to perform a change that fails, e.g because it causes a conflict, results in a SUCCESS message even though the change failed.

Reproduction steps:
1. Commit a change
2. Commit another change in closely related line.
3. Try moving the second commit "UP" by hitting <kbd>u</kbd>
4. "STATUS" should not change, but it shows e.g:
    > Successfully moved 6435b68 up. Undo available.
5. Nothing else (hash/order) seems to change.

[error-log.json.zip](https://github.com/divmain/GitSavvy/files/578721/error-log.json.zip)

**Comment by randy3k** [comment]
Could you check if #534 has the same issue?

**Comment by asfaltboy** [comment]
Not in the same manner, see the branch I just pushed: https://github.com/divmain/GitSavvy/tree/pull-request-534-with-560

**Comment by randy3k** [comment]
I can reproduce it. I thought about how to resolve conflicts when manipulating commits, but it requires a lot of work.

**Comment by randy3k** [comment]
I have updated #534, 4095e85 should fix this.

**Comment by asfaltboy** [comment]
I think rebase view originally allowed conflict resolution, maybe only for
some commands.

Need to test this

**Comment by randy3k** [comment]
Only the [r] key rebase supports resolving conflicts. All other manipulations does not.
