### ISSUE TITLE
Rebase: moving 1st commit down always fails; the reverse works

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#561]
Reproduction steps:

1. Commit a change
2. Commit another change in different (non-conflicting) line.
3. Try moving the first commit "DOWN" by hitting <kbd>d</kbd>
4. Nothing else (hash/order) seems to change.
5. Assert moving second commit "UP" with <kbd>u</kbd> works fine and switches the two commits around.

[error-log.json.zip](https://github.com/divmain/GitSavvy/files/578730/error-log.json.zip)

**Comment by randy3k** [comment]
It is fixed in #534
