### ISSUE TITLE
git rev-parse failed

### ISSUE THREAD

**Issue by eden-lane** [divmain/GitSavvy#563]
Since this morning I get this:
```
`/usr/bin/git rev-parse --show-toplevel` failed with following output:

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
```
What could be wrong?

**Comment by eden-lane** [comment]
Sorry, it was really silly question. I just had no idea that Sublime could somehow connected to XCode. So I just started XCode and agreed to license

**Comment by stoivo** [comment]
Sublime does not speak with Xcode, but git is installed with Xcode. Every time you update xcode you need to accept the license again, until you accept it git doesn't allow any operations.

**Comment by eden-lane** [comment]
@stoivo thanks a lot for this explanation!
