### ISSUE TITLE
Feature request: jump to first line diff in inline diff view

### ISSUE THREAD

**Issue by 9thbit** [divmain/GitSavvy#564]
When opening an inline diff, where the change may be off screen, it would be nice if the view would automatically jump or start at the first diff.

It would also be cool if you could navigate between the line diffs within the file from the keyboard.

**Comment by asfaltboy** [comment]
You can navigate between the "diff hunks" by using <kbd>.</kbd> and <kbd>,</kbd>. Not sure about the "jump to first hunk", this may be a nice feature.

**Comment by stoivo** [comment]
It exits, check setting inline_diff_auto_scroll
https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L54-L58

**Comment by 9thbit** [comment]
Great, thanks @asfaltboy and @stoivo ! 👍
