### ISSUE TITLE
Would it be possible to disable vintageous in the git savvy views by default

### ISSUE THREAD

**Issue by docsteveharris** [divmain/GitSavvy#565]
It would save having to switch to insert mode to use your keybindings.

e.g. view.settings().set('__vi_external_disable', True)

see https://github.com/guillermooo/Vintageous/wiki/Disabling

and implemented here for sublime git

SublimeGit/SublimeGit@3832541

**Comment by asfaltboy** [comment]
There is already [the `vintageous_enter_insert_mode ` toggle setting][1] which, when enabled, "puts" you into insert mode by default in GitSavvy interfaces. Simply set your user settings to:

>     /*
>         When set to `true`, GitSavvy will become Vintagoues friendly.
>         You might need to restart Sublime in order to get this working.
>      */
>     "vintageous_friendly": true,
> 
> 
>     /*
>         When set to `true`, all views will start in INSERT mode.
>         Ignored if `vintageous_friendly` is `false`.
>      */
>     "vintageous_enter_insert_mode": true,

[1]: https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L286-L289

**Comment by divmain** [comment]
@docsteveharris if this does not address your question, please feel free to reopen.

**Comment by docsteveharris** [comment]
Awesome. Thanks - I had missed that.
