### ISSUE TITLE
STATUS dashboard: "Push current branch"

### ISSUE THREAD

**Issue by allen-zeng** [divmain/GitSavvy#566]
I think the action might not be what it's meant to be. I found it surprising when it pushed more than just my "current" branch, which I took to mean the very branch I was on, not all the other ones that are configured to track a remote branch with the same name.

Example: I'm on `master`, tracking remote `master`, and I also have a local branch `develop` tracking remote `develop`. When I'm on the status dashboard, hitting P (push current branch) also tries to push `develop`, which may or may not be the intention (it certainly wasn't mine).

Having viewed the logs via "GitSavvy: enable logging", then "GitSavvy: view recorded log", the command is simply `git push`. I think it should be `git push <remote> master`.

`git push` is definitely useful, but there is already a corresponding action on the branches dashboard: `[P] push all branches to remote`, which has a much clearer message.

**Comment by asfaltboy** [comment]
Are you pressing upper or lower case `p`? The branch interface says:

    [p] push selected to remote

Notice, the lower case <kbd>p</kbd> is what you ought to be pressing to push the selected branch.

**Comment by allen-zeng** [comment]
@asfaltboy I'm talking about the status dashboard, not the branches dashboard.

There is only capital P on the status dashboard.

**Comment by randy3k** [comment]
[P] triggers `gs_push` and
the related [code](https://github.com/divmain/GitSavvy/blob/2d41dec240e07434502206407373a9425a3c3631/core/commands/push.py#L57) does not set `branch`.

**Comment by asfaltboy** [comment]
My bad, sorry. The behavior you are describing is indeed odd, does this reproduce every time and only at the "STATUS" dashboard?

Please note that the [`git push` docs][1] mention that

> When neither the command-line nor the configuration specify what to push, the default behavior is used, which corresponds to the simple value for push.default: the current branch is pushed to the corresponding upstream branch.

Did you perhaps configure your global/repo git config's `push.default` key, and if so is it something other than "simple"?

Perhaps we should make the command lowercase [p] to avoid mistakenly pressing the same in branch dashboard?

[1]: https://git-scm.com/docs/git-push#_description

**Comment by allen-zeng** [comment]
Nice find! My setting is `matching`, which according to the docs, pushes _all_ matching branches with matching names on both ends.

Given the current messaging, I think the command should still be `git push <remote> master` instead of simply `git push`, to cater for the possibility of this setting. It's probably easier than displaying different task names depending on the setting.

The suggestion to make the key lowercase in the branch dashboard is a good one. The only concern is the change in behaviour that people might have got used to.

**Comment by asfaltboy** [comment]
I would argue that the dashboard should retain its  simple/default commands. Users may need to customise their default behaviour, and using a config would cover both command line and sublime use case.

If you need different behaviour for this command only in sublime, GitSavvy has a setting to append  arguments for each command. You can add the following to your user settings:

    "global_flags": {
        "push": ["origin", "HEAD"]
    }

**Comment by randy3k** [comment]
I think we should make the branch and status board consistent.

**Comment by allen-zeng** [comment]
@asfaltboy I think you have a good point there, but I think if we are going to stick with that behavior, we need to at least change the message label on the status dashboard. Even something like "git push" is better than "push current branch" which seems to imply an explicit command to push a single branch only.

I would prefer that the message stays the way it is and the action specifies a branch. But I'm not that fussed. :)

**Comment by divmain** [comment]
The `push.default` setting changed between Git version 1.x and 2.x.  For recent versions of Git, this command works correctly - so this was a simple oversight.

The behavior and/or description should definitely be brought into alignment and, since most users are unaware of the default `git push` semantics, we should change the behavior here and not the description.

So: Pressing `[P]` in the status dashboard should result in `git push REMOTE CURRENT_BRANCH`, where `REMOTE` is either the remote for the configured tracking branch or the default remote.

**Comment by asfaltboy** [comment]
@divmain agreed, how about updating default shortcut to lowercase `[p]` ?

**Comment by allen-zeng** [comment]
Thanks guys for working on this - with the latest version the shortcut is changed to `p`, but the status dashboard still says that the shortcut is `[P]`, I think a fix for that is in order :)

![image](https://cloud.githubusercontent.com/assets/7380931/23679794/1cc7dec8-03dd-11e7-87e7-92fdcf257294.png)

**Comment by allen-zeng** [comment]
I should add - `P` doesn't work, `p` does. I took me quite a bit to realise the change :/

**Comment by asfaltboy** [comment]
That's weird, both commits from pull #569 are missing from commit history. Did someone force pushed a rebased history on master?

**Comment by asfaltboy** [comment]
@allen-zeng wait that doesn't make sense. Do you have the last version from packagecontrol? Or have you checked out the project locally? Try running `git branch -vva` in your GitSavvy directory.

**Comment by allen-zeng** [comment]
@asfaltboy I did have an old version of GitSavvy in my `Packages/User` folder, my bad!

Deleted it and reinstalled GitSavvy and all is well!

Thanks for looking into this 🙏

**Comment by stoivo** [comment]
Good.
