### ISSUE TITLE
Branches dashboard: "[o] checkout remote as local" fails when there are no local branches

### ISSUE THREAD

**Issue by allen-zeng** [divmain/GitSavvy#567]
When there are no local branches, trying to create a branch by hitting `[o]` does nothing. The console shows the error message:

>Traceback (most recent call last):
  File "core.interfaces.branch in /Users/Allen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 218, in run_async
IndexError: list index out of range

**Comment by asfaltboy** [comment]
Thank you @allen-zeng for the report! This should be fixed by next release.
