### ISSUE TITLE
Warning before discarding changes, dangerous status view key bindings

### ISSUE THREAD

**Issue by JonnieCache** [divmain/GitSavvy#58]
I'm used to using SublimeGit, but this looks better so I disable that and install this instead. Bring up the status page, everything looks good. I want to check out the inline diffs, they sound very useful, so I move to a file with some changes and reflexively hit `d` which stands for diff in sublimegit. I'm sure you've worked out the punchline: the first thing I did with gitsavvy was discard a bunch of work. Hey, at least `c` is bound to commit and not checkout :)

I'm proposing that we should at least have a warning before discarding changes. Also I'd personally like to see the key for discard changed to `backspace` and diff moved to `d` but I understand that's just me privileging my own muscle memory.

Either way, irrevocably deleting work with a single idle keystroke is not a good first experience with a version control tool.

**Comment by ddevlin** [comment]
Firstly, thank you for this project, the current features are excellent, and I was really excited to see some of the additional functionality you have planned. 

Like @JonnieCache, I also got caught out by SublimeGit muscle memory when switching to GitSavvy. I will eventually get used to it, but if you do decide to change the interaction I think a modifier key (e.g. Super+d) or a key sequence like you use for the stash controls would be preferable to a confirmation dialog.

**Comment by divmain** [comment]
I'd like to find a way to address this - I agree, that's not the best first experience.  @JonnieCache @ddevlin, how do you feel about prompting for confirmation the first time the user ever discards?  After that, the experience would continue as it does now.

Basically, I'd like to avoid exactly what you experienced.  But I also appreciate single-key shortcuts for my own workflow, or if multi-key shortcuts are necessary, to have them grouped into logical categories.

I'll think about this a bit more and consider switching to `backspace` for discards.  I think I won't switch diffs to `d`, because that would cause the same problem for those expecting it to show them a diff.

**Comment by alextegelid** [comment]
How about a setting, something like "prompt_before_discard", that defaults to true for new users? That way new users won't risk deleting uncommitted work and experienced users can easily turn those warnings off. 




I experienced the same muscle memory mishap (from SublimeGit), luckily I was only testing GitSavvy on dummy files and didn't loose any actual work. 



—
Alexander Tegelid
070-508 49 90
alex@tegelid.se
—

**Comment by JonnieCache** [comment]
prompting the first time would work. Instinctively I'd prompt the user every time they do anything irreversible to a whole file like that, and let them turn off the prompt in the settings file.

**Comment by divmain** [comment]
That seems reasonable.  I'll include this in the bug-fix release sometime today.

**Comment by dflock** [comment]
Argh! just done this too :(

**Comment by hanoii** [comment]
I just upgraded and for some reason I am not being prompted for anything, I can see the new setting.

**Comment by divmain** [comment]
@hanoii, I took another look and there was an issue with reading the settings in certain environments (but not on my dev machine, which is why I missed it).  Just pushed v1.1.1, which should be picked up by package control in the next while.
