### ISSUE TITLE
Rebase view: Error when moving a commit up/down

### ISSUE THREAD

**Issue by gwenzek** [divmain/GitSavvy#593]
When in the rebase view I try to move up/down a commit I got the following error:
```
  File "core.interfaces.rebase in /.../.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 451, in get_idx_entry_and_prev
UnboundLocalError: local variable 'selected_idx' referenced before assignment.
```

By looking at the definition of  [get_idx_entry_and_prev](https://github.com/divmain/GitSavvy/blob/becc7ab6c97a4c64f48b0ea63324c28d08756965/core/interfaces/rebase.py#L483) that would mean that the selected hash isn't found in the entries list but I'm not sure why.

Anyway I can't move commits up and down anymore.

**Comment by stoivo** [comment]
Hmm, it work for me. I think is is related to commit sha matching. 
Does any of you commits start with the same 7 characters?

**Comment by divmain** [comment]
Going to close this until we get more information.  Please reopen @gwenzek if you can provide some repro steps or more information.
