### ISSUE TITLE
git: clone freezes Sublime

### ISSUE THREAD

**Issue by tailsu** [divmain/GitSavvy#598]
git: clone does indeed clone the given repository, but Sublime becomes completely unresponsive while the cloning is taking place.

It would be nice to show the cloning progress instead and not freeze. It would also be nice if a new Sublime window opens with the cloned folder. It would also (final one, I promise) be nice if the suggested checkout folder isn't a subdirectory in the current project, but rather the first folder up the chain of folders starting from the current project that is not a git repo. In other words, that the cloned repo goes into a folder that is a sibling of the currently opened git repo.

**Comment by stoivo** [comment]
Thanks for reporting, I havn't taken a look at the code. But here is some comments.
1. The It should be quite easy to add a async block around `git: clone` to stop it from running in that main thread and run in a background thread . The way git savvy is built we can't fix the progress bar :( , or we could , it just require more time then want I have free. 
2. When selecting a git root, [this](https://github.com/divmain/GitSavvy/blob/6d26efd1a62b69d04b9f739d55bac5581d1da54a/core/commands/init.py#L102-L112) is the function which create a proposal for path. It should use the open folder path as root is if it's not a repo. If it is a repo the take the parent folder as root.

**Comment by tailsu** [comment]
All of that sounds reasonable.

I also checked the Sublime API - unfortunately it appears to be impossible to open a new sublime window with a given folder name through the API. Maybe directly through the executable? `subprocess.Popen('subl ' + cloned_git_folder, ...)` ?

**Comment by stoivo** [comment]
@tailsu, Now it will open the newly cloned project in a new window.

**Comment by stoivo** [comment]
I created a PR, I will see if any of the other contributes want to comment before I merge.
We should probably create a release soon.
