### ISSUE TITLE
Handle branch names with slashes

### ISSUE THREAD

**Issue by arubis** [divmain/GitSavvy#60]
Git branch names are allowed to have slashes in them; however, GitSavvy status shows only the branch name up until the first slash.

eg. in console:
```
➜  infra git:(dylan/terraform/add-utility-instances) ✗ gst
On branch dylan/terraform/add-utility-instances
Your branch is up-to-date with 'origin/dylan/terraform/add-utility-instances'.
```

...but in GitSavvy:

![status__infra_ _infra](https://cloud.githubusercontent.com/assets/19107/6561642/738f5f7a-c658-11e4-9c25-8de04105bd94.png)

**Comment by divmain** [comment]
Hey @arubis - this was reported as #52, and a fix is in master.  Should be pushed out to package control users sometime this evening.

**Comment by arubis** [comment]
Great, thanks! Sorry I missed seeing that on scanning through in the first place :)
