### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by ramiel** [divmain/GitSavvy#604]
It looks like a lot (lot) of fixes have been made since the latest release (2.13.0). When will be released a new version?
Thanks for the amazing great job you do!

**Comment by stoivo** [comment]
We will have a release in couple of weeks, I am working on a majore issue

**Comment by ramiel** [comment]
Ok, great!

**Comment by divmain** [comment]
@stoivo I just pushed out 2.14.0.  Should the release be halted?

**Comment by divmain** [comment]
Also, thanks!  You've and the others have been doing a fantastic job managing GitSavvy!

**Comment by stoivo** [comment]
Patch release sounds good.
