### ISSUE TITLE
Feature Request: Select branch when adding new branch

### ISSUE THREAD

**Issue by tollus** [divmain/GitSavvy#608]
When I create a branch through the branch view, it does a `git checkout` but I need to highlight the branch name manually to use 'Edit Description'. Is it possible to highlight the newly created branch?

Thanks!

**Comment by stoivo** [comment]
You would like to move the cursor to the newly created branch, right?

**Comment by tollus** [comment]
Yes, exactly.

**Comment by stoivo** [comment]
I have other issues on my priority list. Would you like to try to implement it?

**Comment by tollus** [comment]
I had looked at it briefly, but have a very brief knowledge in python, so I couldn't find what I needed to change.

It's definitely not a priority to have this done, it's a "nice to have" but I can easily just move my cursor to the branch.
