### ISSUE TITLE
inline-diff newline change ambiguity

### ISSUE THREAD

**Issue by ethanbustad** [divmain/GitSavvy#61]
This code

    Line 1 content
    // comment
    Line 3 content

and this code

    Line 1 content
    
    // comment
    Line 3 content

generate the same inline diff:

    Line 1 content
    
    // comment  <--- (green text)
    Line 3 content

There's no indication of whether I've added a newline or not.

If I simply add or remove a newline, the diff acts as expected. It's only when I add text to a previously blank line that this ambiguity shows up.

Obviously this isn't a huge deal, as I know where I've added newlines and where I haven't, and these comments aren't generally things I'll be committing; it's just a little bit unexpected behavior.

**Comment by divmain** [comment]
I'm surprised I haven't noticed this before.  Can you post a screenshot?
