### ISSUE TITLE
Feature Request: Add a quick way to "git show HEAD"

### ISSUE THREAD

**Issue by SujayKrishna** [divmain/GitSavvy#610]
I know that we can do a `git: log` then choose a commit and then choose `Show commit` to get to this. But `git log` is sometimes not fast enough and so a shorthand for `git show X` would be good.

**Comment by divmain** [comment]
Hi @SujayKrishna!

This is unlikely to become a standard feature - everybody has their own niche commands, and it would be untenable to support all of them explicitly.

However, we have supported a couple of methods to add your own simple features.  One of those ways is via [custom commands](https://github.com/divmain/GitSavvy/blob/master/docs/custom.md).

Another option might be something like adding the following to a `.sublime-commands` file in your `User` package, which would open an actual commit view:
```json
    {
        "caption": "git: show HEAD",
        "command": "gs_show_commit",
        "args": {
            "commit_hash": "HEAD"
        }
    },
```

Does that adequately address your needs?

**Comment by stoivo** [comment]
Custom command could look like 
```
    {
        "caption": "git: show X",
        "command": "gs_custom",
        "args": {
            "args": ["show", "{PROMPT_ARG}"],
            "prompt_msg": "sha"
        }
    }
```

**Comment by SujayKrishna** [comment]
Cool! Makes sense!

Thank you!

**Comment by SujayKrishna** [comment]
@stoivo The custom command doesn't end up showing a ST3 tab though. 
I could see the output only by using `output_to_panel: true`.

Is there a flag I could use to open it as a new ST3 tab?

**Comment by stoivo** [comment]
I added it now. Will be on master in a day or two.

**Comment by SujayKrishna** [comment]
Thanks @stoivo
