### ISSUE TITLE
Unable to create pull request

### ISSUE THREAD

**Issue by aristidesfl** [divmain/GitSavvy#612]
Github command not working.

Sublime 3126

**Comment by stoivo** [comment]
I don't know. I works perfectly for me.
Could you try to install GitSavvy the less simple way? https://github.com/divmain/GitSavvy#less-simple

**Comment by aristidesfl** [comment]
@stoivo are you on mac and have commit signing on by default?

**Comment by aristidesfl** [comment]
@stoivo Just did, same thing. turns out the connection errors were from something else. 
No errors, only when `create pull request`:
```py
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/GitSavvy/github/commands/pull_request.py", line 177, in run_async
    owner = github.parse_remote(self.get_remotes()[remote_branch.remote]).owner
AttributeError: 'NoneType' object has no attribute 'owner'
```

**Comment by stoivo** [comment]
ok, can you run and post the output here
- git --version
- git remote -v
- git rev-parse --abbrev-ref --symbolic-full-name @{u}
- git branch -a -vv --no-abbrev

**Comment by divmain** [comment]
Are you working behind a firewall of some kind, or on a spotty internet connection?  `Connection refused` errors typically result from connectivity issues.

**Comment by aristidesfl** [comment]
@stoivo 

```bash
$ git --version
git version 2.12.0
hub version 2.2.9

$ git remote -v
origin	git@github.com:divmain/GitSavvy.git (fetch)
origin	git@github.com:divmain/GitSavvy.git (push)

$ git rev-parse --abbrev-ref --symbolic-full-name '@{u}'
origin/master

$ git branch -a -vv --no-abbrev
* master                                           ed1c70c4205fbd00f3f53b549ebeeb6dd0b6e781 [origin/master] Allow user to stash only changes that have been staged.
  remotes/origin/HEAD                              -> origin/master
  remotes/origin/encoding_inlinediff               78632c3b14b33c47b7856ff3bc0ffb632541563d Merge branch 'encoding_inlinediff' of https://github.com/divmain/GitSavvy into encoding_inlinediff
  remotes/origin/feature/better-base-ref-detection c5e13d467989a2d6a60aed575bfba25335ed00a4 Add more debugging and avoid infinite loop
  remotes/origin/gitlab-support                    8189f46a533f6958881caa2cd72c48b8e6b19b62 GitLab placeholder.
  remotes/origin/master                            ed1c70c4205fbd00f3f53b549ebeeb6dd0b6e781 Allow user to stash only changes that have been staged.
```

**Comment by aristidesfl** [comment]
@divmain no firewall, different networks, those errors were from another package.

**Comment by divmain** [comment]
Sorry, I had missed that.  This is definitely a bizarre bug.  For this error to occur, `parse_remote` would have to return `None` either [here](https://github.com/divmain/GitSavvy/blob/ed1c70c4205fbd00f3f53b549ebeeb6dd0b6e781/github/github.py#L32) or [here](https://github.com/divmain/GitSavvy/blob/ed1c70c4205fbd00f3f53b549ebeeb6dd0b6e781/github/github.py#L37).  Based on the output of the Git commands @stoivo asked for, I don't see how either of those is possible.  Because you're using `divmain/GitSavvy` as the example here, I stepped through the individual git commands to see where an issue might manifest, and I couldn't find anything.  One more question, and I'll have to think about this a bit... Do you have a `git_path` specified in your `GitSavvy.sublime-settings`?

**Comment by stoivo** [comment]
I added a branch called (issue612)[https://github.com/divmain/GitSavvy/tree/issue612] which add 3 print statements which could help.

**Comment by aristidesfl** [comment]
@stoivo It works on the GitSavvy project for example. On hammerspoon/hammerspoon doesn't work at all, and nothing appears on the console.

**Comment by aristidesfl** [comment]
```
$ ll
total 200
drwxr-xr-x   8 user  staff   272B Mar  2 19:27 scripts
-rw-r--r--   1 user  staff    24B Mar  2 19:27 requirements.txt
drwxr-xr-x  78 user  staff   2.6K Mar  2 19:27 extensions
-rw-r--r--   1 user  staff   147B Mar  2 19:27 codecov.yml
-rw-r--r--   1 user  staff    32K Mar  2 19:27 appcast.xml
-rw-r--r--   1 user  staff   2.4K Mar  2 19:27 README.md
drwxr-xr-x  14 user  staff   476B Mar  2 19:27 Pods
-rw-r--r--   1 user  staff   1.5K Mar  2 19:27 Podfile.lock
-rw-r--r--   1 user  staff   426B Mar  2 19:27 Podfile
-rw-r--r--   1 user  staff   1.9K Mar  2 19:27 Makefile
drwxr-xr-x   6 user  staff   204B Mar  2 19:27 LuaSkin
-rw-r--r--   1 user  staff   1.1K Mar  2 19:27 LICENSE
drwxr-xr-x   5 user  staff   170B Mar  2 19:27 HammerspoonUITests
drwxr-xr-x   4 user  staff   136B Mar  2 19:27 Hammerspoon.xcworkspace
drwxr-xr-x   4 user  staff   136B Mar  2 19:27 Hammerspoon.xcodeproj
drwxr-xr-x  22 user  staff   748B Mar  2 19:27 Hammerspoon Tests
drwxr-xr-x  39 user  staff   1.3K Mar  2 19:27 Hammerspoon
-rw-r--r--   1 user  staff   471B Mar  2 19:27 CREDITS.md
-rw-r--r--   1 user  staff   2.3K Mar  2 19:27 CODE_OF_CONDUCT.md
-rw-r--r--   1 user  staff   1.3K Mar  2 19:27 .travis.yml
-rw-r--r--   1 user  staff    42B Mar  2 19:27 .syntastic_objc_config
-rw-r--r--   1 user  staff    31B Mar  2 19:27 .luacheckrc
-rw-r--r--   1 user  staff   707B Mar  2 19:27 .gitignore
drwxr-xr-x   3 user  staff   102B Mar  2 19:27 .fauxpas
-rw-r--r--   1 user  staff    12K Mar  3 00:32 CONTRIBUTING.md
drwxr-xr-x  12 user  staff   408B Mar  4 02:27 .git

user at unknown in ~/Work/hammerspoon on master
$ remote -v
origin	git://github.com/Hammerspoon/hammerspoon.git (fetch)
origin	git://github.com/Hammerspoon/hammerspoon.git (push)
```

**Comment by divmain** [comment]
Oh!  So it did work with the GitSavvy repo?  I'll take a look at `hammerspoon`.

**Comment by asfaltboy** [comment]
From the git remote printout, we may be looking at fixing the parse_remote
method

**Comment by divmain** [comment]
I'm unable to reproduce in the `hammerspoon` repo either.  @aristidesfl, can you pull down @stoivo's `issue612` branch, run GitSavvy off that, and report back on output in the terminal when running `github: create pull request` command?

**Comment by aristidesfl** [comment]
@divmain 

On GitSavvy it works fine, but on hammerspoon:
```bash
remote_branch.remote origin
self.get_remotes() OrderedDict([('origin', 'git://github.com/Hammerspoon/hammerspoon.git')])
github.parse_remote(self.get_remotes()[remote_branch.remote]) None
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/GitSavvy/github/commands/pull_request.py", line 180, in run_async
    owner = github.parse_remote(self.get_remotes()[remote_branch.remote]).owner
AttributeError: 'NoneType' object has no attribute 'owner'
```

**Comment by asfaltboy** [comment]
The usual syntax offered by github when cloning is "git@github.com:Hammerspoon/hammerspoon.git", `parse_remote` supports this or "http" prefix.  

We can add it, but question if there are any other syntax we're missing, I'll add a PR meanwhile

**Comment by aristidesfl** [comment]
@asfaltboy it makes sense now. I used https://github.com/github/hub to clone that repository.
