### ISSUE TITLE
"Select commit as base ref"  in the rebase screen

### ISSUE THREAD

**Issue by mnieber** [divmain/GitSavvy#620]
I think that for rebasing the first K commits it would be handy if the commit under the cursor can be selected as the base ref.

**Comment by mnieber** [comment]
I can easily do this by copying the ref and using "define base ref", so no real need.

**Comment by divmain** [comment]
I actually really like this idea, and would find it to be a convenience myself.  So I'm going to re-open :)

**Comment by randy3k** [comment]
It was implemented.
