### ISSUE TITLE
Allow HEAD@{1} in `git reset`

### ISSUE THREAD

**Issue by mnieber** [divmain/GitSavvy#622]
To undo a previous `git reset` you can do `git reset HEAD@{1}` (http://stackoverflow.com/questions/2510276/undoing-git-reset)

However, the `git reset` command of GitSavvy does not accept this term.

**Comment by asfaltboy** [comment]
Have you tried using [the `git: reset (reflog)` command][1]?

[1]: https://github.com/divmain/GitSavvy/blob/master/docs/misc.md#git-reset-reflog

**Comment by mnieber** [comment]
Sorry, I overlooked that option :-).
