### ISSUE TITLE
Show inline diff for commit in the GRAPH tab

### ISSUE THREAD

**Issue by mnieber** [divmain/GitSavvy#623]
The `Show commit` option in the GRAPH tab shows the normal diff, but usually I prefer to see the inline diff.

**Comment by asfaltboy** [comment]
I may be wrong, but I believe the inline diff is currently only reserved to staged/unindexed changed, at least the commands it supports (staging/unstaging hunks or lines, etc).

If you're looking for the nice word-diff coloring, there's another feature request for that (#527) which discusses just this.

**Comment by mnieber** [comment]
You're right, cool, I will start following that other thread then.
