### ISSUE TITLE
Commands to manipulate the stash

### ISSUE THREAD

**Issue by aristidesfl** [divmain/GitSavvy#628]
There are no commands in the palette to pop and add to the stash.
Any objection to adding those?

**Comment by randy3k** [comment]
Before it is addressed, you could use the custom command for the purpose. https://github.com/divmain/GitSavvy/blob/master/docs/README.md#custom-commands

**Comment by reagle** [comment]
Yes, this would be nice to have.  It's awkward to want to put into another branch presently as you must stash and checkout branch.

**Comment by aristidesfl** [comment]
Should i submit a PR or would someone already familiar with the codebase like to do it?

**Comment by stoivo** [comment]
You are very welcome to open a PR.

**Comment by aristidesfl** [comment]
I doesn't looks as simple as adding custom commands

**Comment by aristidesfl** [comment]
Also it would be nice to have stash shortcuts in the branch view, since checkout is often not possible without stashing first.

**Comment by stoivo** [comment]
In https://github.com/divmain/GitSavvy/pull/744 we will add these commands to the Command panel. If you want to have a single key combination to create stash you can add it yourself to you `User.sublime-keymap` 
```
    {
        "keys": ["t", "c"],
        "command": "gs_create_stash",
        "context": [
            { "key": "setting.command_mode", "operator": "equal", "operand": false },
            { "key": "setting.git_savvy.branch_view", "operator": "equal", "operand": true }
        ]
    },
```
