### ISSUE TITLE
git fetch --prune

### ISSUE THREAD

**Issue by zakpatterson** [divmain/GitSavvy#630]
Pruning remote branches is the greatest. When your feature branch grows up and becomes one with master, and that feature branch goes away. Ah it's so good.

Suggest we add

```
[H] fetch remote branches and prune
```

To the branches dashboard,

and `git fetch --prune` to the ^ P menu, similar to `git push --force`

I've never dug into the code for this module, but i'm happy to give it a try.

**Comment by stoivo** [comment]
GitSavvys fetch does prune 
If you would like to see the code look here https://github.com/divmain/GitSavvy/blob/master/core/git_mixins/remotes.py

**Comment by zakpatterson** [comment]
Ah, I did miss that, don't know how i got out of sync somehow. Thanks!

**Comment by stoivo** [comment]
Feel free to reopen when you find out how that happened :)
