### ISSUE TITLE
no commit history available in rebase dashboard

### ISSUE THREAD

**Issue by reagle** [divmain/GitSavvy#638]
As you can see, I have a new repo and I'd like to squash the last two commits (added a line of a's and b's). The commit history shows up in log, but not in the rebase dashboard. Am I doing something wrong?

<img width="875" alt="screen shot 2017-04-21 at 5 38 22 pm" src="https://cloud.githubusercontent.com/assets/596814/25297044/7d7125e6-26b9-11e7-967e-54d3eedd1383.png">

**Comment by randy3k** [comment]
You will need to define the rebase base by pressing the `f` key.

**Comment by reagle** [comment]
When I try `f` and I use `ref as base` it would be nice if it offered me a selection. Even so, I enter "c246ac8" it complains about unclean state because I have two files not staged (I'm not tracking them). After, I delete them, I can then see the two subsequent commits. But when I try to squash I get an error.

```
`/usr/local/bin/git log -1 --format=%h%n%H%n%s%n%an%n%ae%n%at%x00%B%x00%x00%n c246ac87417c5e71aaca26f4c3ee8481daffdef6~1..c246ac87417c5e71aaca26f4c3ee8481daffdef6` failed with following output:

fatal: ambiguous argument 'c246ac87417c5e71aaca26f4c3ee8481daffdef6~1..c246ac87417c5e71aaca26f4c3ee8481daffdef6': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by randy3k** [comment]
Ai...you cannot use the first commit as the base. We should make it clear though...

**Comment by reagle** [comment]
Okay, what about:
1. easy way to select base commit
2. complaints about unclean state because of unstaged files?

**Comment by randy3k** [comment]
1. #532 is working on it.
2. You need to stash or stage the changes before any rebase actions. It is of no difference to the regular git routine. But however, we can make it more automatous by stashing the changes and poping it after the rebase action.

**Comment by reagle** [comment]
Okay, thanks.
