### ISSUE TITLE
git: add error

### ISSUE THREAD

**Issue by trevans24** [divmain/GitSavvy#645]
I am having issues with the git add not working in sublime. this is the error that populates:

`/usr/local/bin/git apply --cached -` failed with following output:

fatal: unrecognized input

I was able to git add and commit just fine last night but now this morning there is this error. I have not seen any documentation on this issue for fixes.

**Comment by stoivo** [comment]
Do you have the exact steps you did? There is many ways to add in gitsavvy.

**Comment by trevans24** [comment]
I am adding via git: add in the command + shift + p
then when it says use super enter it gives me the error message, but it worked just fine yesterday

**Comment by trevans24** [comment]
Having funky issue in my git repo, working now after change....thanks anyways

**Comment by stoivo** [comment]
Good, feel free to reopen.
