### ISSUE TITLE
Rebase conflicts cause endless dialog fail

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#646]
So this started happening, and I'm not able to close dialogs (i.e they open infinitely).

![screen shot 2017-05-12 at 11 43 41](https://cloud.githubusercontent.com/assets/321520/25992882/51166c04-3708-11e7-90a0-e42844b29909.png)

My GitSavvy was on commit 5631c53 and also continued when I checked out latest 8b3d313. So this is a recent regression.

I'm not sure which of the changes did it, I can try to bisect later if want.

**Comment by stoivo** [comment]
Can you try [rebase_rewrite_dialog](https://github.com/divmain/GitSavvy/tree/rebase_rewrite_dialog)

**Comment by asfaltboy** [comment]
Didn't really work unfortunately. This may have to do with this "re-raise" that occurs when we call [`rewrite_active_branch ` in `make_changes`][1]. This call eventually calls the `rebase_rewritten` that was patched in 0480911

https://github.com/divmain/GitSavvy/blob/master/core/interfaces/rebase.py#L519-L527

**Comment by randy3k** [comment]
The error complains that `rebase-apply` directory is not found, so I have fixed up @stoivo's patch at https://github.com/divmain/GitSavvy/commit/67f05a9272d2a67ed0af24c8d6bf6c0e88169435.

**Comment by randy3k** [comment]
Actually, I argue that we should just use `open` instead of `safe_open` since this function should not be invoked by users directly.

**Comment by stoivo** [comment]
I think that's better @randy3k. I had that as a though when I made the branch.

**Comment by asfaltboy** [comment]
Looks to be ok now, hopefully this is the only location where we depend on the exception to be raised if open fails.
