### ISSUE TITLE
Commands that opens in a Browser is not opening the OS default browser

### ISSUE THREAD

**Issue by danillos** [divmain/GitSavvy#651]
I'm using Chrome as default browser on MacOS and Sublime 3.

**Comment by asfaltboy** [comment]
@danillos thank you for reporting, are there any errors logged in a panel or your sublime log console (<kbd>cmd</kbd>+<kbd>~</kbd>) ?

**Comment by danillos** [comment]
@asfaltboy no, I didn't see any log there when I run the command.

My default browser is Chrome, it was opening on Firefox, I removed the Firefox App and now it is opening on Safari.

**Comment by danillos** [comment]
Some weeks ago it was working without issues, but I can't tell you the exactly day, I saw it since the last week I guess.

**Comment by asfaltboy** [comment]
I'm sorry I didn't understand the issue properly before, I now do.

We had a similar issue / request in #629. We use Python's built-in webbrowser package to open a URL in the default browser. It determines the default browser on a given OS, see the full documentation here: 

https://docs.python.org/3/library/webbrowser.html

The docs mention you can override this default by setting the `BROWSER` variable in the environment sublime is running in.

**Comment by danillos** [comment]
I did a test setting the `BROWSER` variable in the environment and doesn't work.

Here is what I found:

```bash
~ $ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import webbrowser
>>> webbrowser.open('https://google.com')
0:34: execution error: "https://google.com" doesn’t understand the “open location” message. (-1708)
70:78: execution error: Can’t get application "firefox". (-1728)
True
>>> webbrowser.get().name
'chrome'
```

**Comment by asfaltboy** [comment]
Looks to be more of OS/Python issue than anything else, here is a blog post from someone with a similar issue to yours: http://www.andrewjaffe.net/blog/2017/05/python-bug-hunt.html

And the issue he filed for python bug tracker: http://bugs.python.org/issue30392

Seems we have an issue with `open location` in MacOS Sierra 10.12.5, this seems to be one among many other bugs, as noted in this list:

https://eclecticlight.co/2017/05/17/known-bugs-in-macos-sierra-10-12-5-an-incomplete-summary/

I can also confirm that on my system (El Capitan), this works fine:

    # python
    Python 2.7.13 (default, May 22 2017, 20:50:44)
    [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import webbrowser
    >>> webbrowser.open('https://google.com')
    True
    >>> vars(webbrowser.get())
    {'_name': 'default'}
    >>>

**Comment by danillos** [comment]
Sure, thank you @asfaltboy.
