### ISSUE TITLE
git: blame current file - ignore uncommitted changes

### ISSUE THREAD

**Issue by vegar** [divmain/GitSavvy#654]
One scenario that I frequently end up in, is that I start to edit some code, then realize that I need to understand the origin of the code better, so I do a git blame to find out who was there before me, and what issue they were working on. 

At this point, though, git blame will include my local changes, and therefore tell me that I was the one touching the code last.

Is it possible to get an option to ignore uncommitted changes when doing the blame?
Would it even be possible to have a 'history walker' so that we could blame the same file, but the previous version of it? 

Another option would be to have 'blame' as an option when selecting a version from the log.

`git: log current file` -> `[select a version]` -> `blame`

**Comment by stoivo** [comment]
Totalt irrelevant. 

Hei hei nordman :)
