### ISSUE TITLE
"Open File on remote" no longer respects default browser on Mac

### ISSUE THREAD

**Issue by RS-David** [divmain/GitSavvy#657]
Sublime Text 3, build 3131
Git version 2.13.0

I believe this has changed in the last month, but selecting "Open File on remote" now no longer opens in my default browser (Chrome), instead always opening in Safari (Leading to 404's on private repositories since I don't use Safari).
I haven't found an option in the settings to modify this.

Reproduction:
1. Have GitSavvy authed with Github
2. Open a file corresponding to a repository
3. In the Command Window, select `github: open file on remote`

**Comment by asfaltboy** [comment]
Are you using MacOs Sierra ? If so this may be dupe of #651. If you are which version of MacOs you're on?

**Comment by RS-David** [comment]
Ack. On Sierra, yes. My apologies, I didn't notice that one as overlapping. Duplicate then, I'll close this up.
