### ISSUE TITLE
Allow me to disable the "initialize repository" prompt

### ISSUE THREAD

**Issue by firelizzard18** [divmain/GitSavvy#664]
I do not ever use GitSavvy to create repos. I will not ever. I manually create or clone every repo. If I were to use GitSavvy for this, I would do it manually. The initialize repository prompt is obnoxious and serves absolutely no purpose for me.

Please give me the option of disabling this 'feature'!

**Comment by stoivo** [comment]
I have it on my todo list, it will be in the next release.
