### ISSUE TITLE
Feature request: Git add --patch / --interactive

### ISSUE THREAD

**Issue by ChainsawBaby** [divmain/GitSavvy#667]
I recently learned about the `git add --patch` feature of git, and since then I'm a frequent user of it.
I'd love it this became possible in GitSavvy too.
Being able to "cherry pick" which lines to add to a commit

**Comment by ChainsawBaby** [comment]
Some info about patch and interactive
https://git-scm.com/book/en/v2/Git-Tools-Interactive-Staging

http://nuclearsquid.com/writings/git-add/

**Comment by stoivo** [comment]
Have you seen inline diff?
https://github.com/divmain/GitSavvy/blob/master/docs/staging.md#git-diff-current-file-inline

There you can stage hunks or commits.

**Comment by ChainsawBaby** [comment]
Ah, I had not seen there were functions with the inline diff, since there were no help menu visible.
Just toggled the help menu manually, and I see the functions.

So this is already implemented

**Comment by stoivo** [comment]
You have this view, right?
![2017-06-13_14-13-56_status repo repo user](https://user-images.githubusercontent.com/3492040/27081929-f83e5750-5042-11e7-84c5-2d5baca038a4.png)

**Comment by ChainsawBaby** [comment]
Yeah, I have the one open.
But I didn't see any help window for `diff file inline`.
Just thought it was another version of `diff file`

**Comment by stoivo** [comment]
A couple of views like Inline diff, graph, blame (soon), has a keyboard shortcut `?` to open a window with some extra details. And there is a command called `GitSavvy: help` with extensive details about different commands.

Where would we need to put this information so that you would find it?

**Comment by ChainsawBaby** [comment]
Well, if you could just commit it straight into my brain, I'd be very happy

**Comment by stoivo** [comment]
Haha.

🇳🇴  Hei, morro å se nordmen rundt

**Comment by ChainsawBaby** [comment]
🇳🇴  Vi prøver å erobre verden, igjen

**Comment by reagle** [comment]
I always forget where to find this myself. Maybe after "diff inline" it could say "(interactive patch)." I love that GitSavvy supports patches to stage/index and cherry-picks in the repo, I just have to remember the difference and where to find them.
