### ISSUE TITLE
Add support to (un)staging hunks when using git: diff (with the same shortcuts)

### ISSUE THREAD

**Issue by 3v1n0** [divmain/GitSavvy#669]
When using the `git: diff current file inline` I can stage/unstage hunks by using `h` / `H`, I was expecting to be able to do the same when just using `git: diff` (and `git: diff current file`), hunk by hunk (no support for line adding of course in this case).

**Comment by stoivo** [comment]
If you `?` you can see all commands for views like these. This should be a cool addon. Probably we just need to pass a `--reset` to apply if this is the case.

Is `super+shift+ENTER` a good key? 

Would you like to open a PR?

**Comment by 3v1n0** [comment]
I'd just stay consistent using `h`/`H` as it happens in inline mode... 

Asl `Ctrl+Enter` already does it.

**Comment by stoivo** [comment]
@divmain, @randy3k, @asfaltboy. Is it too mush to have the keyboard shortcut from `super+enter` to `h` for it to have the same key binding as in the inline diff? 
The view is read-only so the user shouldn't want to type `h` anyway. 

Or maybe keep `super+enter` and then `h`and `H`.

**Comment by 3v1n0** [comment]
Yah, I'd keep `Super/Ctrl+enter` around... While adding `h`/`H` as alias.

I think those views should be consistent in keybinding, so if the views do the same things, they should use the same values.

**Comment by randy3k** [comment]
I prefer using h/l/H/L keybinds.

**Comment by divmain** [comment]
Adding key aliases could make things messy pretty quick - the keybindings file is already pretty massive!  However, I do like keeping `Super+Enter` for this use case, while it also completely makes sense to use H and L.  So maybe we can make an exception for aliasing here.  I'm fine adding the functionality, and adding h/l/H/L keybindings in the same PR.
