### ISSUE TITLE
Discarding accidentally, too easy

### ISSUE THREAD

**Issue by hanoii** [divmain/GitSavvy#67]
I really like this plugin, however, since I installed it this weekend, I accidentally discarded two files. I know this is more an error from me than the plugin, but it's just to easy to type 'd' and discard it. The first time I was trying to discard a stash, but somehow, as I didn't had the cursor on the stash, typing [t][d] on a file actually discarded the file.

Today I hit d thinking of diff, and again!

I don't know, it should be more difficult to discard a file. Maybe asking for a confirmation in a window, or at least making this confirmation configurable.

On thing is to type git checkout to discard and another is hitting 'd'.

**Comment by divmain** [comment]
Hey @hanoii.  Sorry you ran into this.  This was brought up and fixed in #58.  I just rolled out the change in 1.1.0, which should be picked up by package control the next time you upgrade.
