### ISSUE TITLE
j/k selectors don't work in vintageous_friendly with diff and show-commit views

### ISSUE THREAD

**Issue by 3v1n0** [divmain/GitSavvy#670]
Enabling `vintageous_friendly` allows to properly move in GitSavvy views including branch, status, inline-diff-view.

But it doesn't in `git: diff` or when showing a commit from `git: log` or `git: graph`.

I've tested this in a new installation with only GitSavvy installed.

**Comment by asfaltboy** [comment]
Just to clarify, @3v1n0 when you mean it doesn't work in show-commit views, you mean that it is expected that the j/k shortcuts would "jump between hunks" like <kbd>.</kbd> & <kbd>,</kbd> do?

**Comment by 3v1n0** [comment]
@asfaltboy yes... I see it defined properly in the sources, but it doesn't work either in a brand new sublime installation.

**Comment by randy3k** [comment]
I guess we should keep j and k to moving between lines instead of moving between hunks.

**Comment by stoivo** [comment]
, and . Jumps between hunks and i think thats good. 

J and k shoulddo the same
