### ISSUE TITLE
Show messages from remote when pushing

### ISSUE THREAD

**Issue by ibobo** [divmain/GitSavvy#675]
In `push to deploy` solutions it would be useful to allow seeing messages from the server while the deploy is in progress.

I see two solutions here:

* add a switch in the configuration file or the like (better on a project per project basis) to always show output of push command while pushing;
* if the output of the push command contains the `remote:` string at the beginning of a line, output that line in a console like view.

I would love to see this feature.

**Comment by asfaltboy** [comment]
Hi  @ibobo , have you tried the [toggle setting for output panel feature][1] yet? In your user GitSavvy settings set:

    {
        "show_panel_for": ["push"],
    }

[1]: https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L83-L87

**Comment by ibobo** [comment]
Hi @asfaltboy, I tried changing the config as you said, and that's better than before, but I wanted to see the output *live* as it comes from the server; the whole process for the deploy takes about a minute and seeing nothing happen on the screen for that long always makes me nervous.

Thanks!

**Comment by divmain** [comment]
@ibobo, our current architecture doesn't allow for live output from the git commands.  Python isn't great at async, and there are extra constraints in the Sublime context.  I'm going to close this as wont-fix, since `show_panel_for` is the closest we'll get to supporting this (barring a significant rewrite).
