### ISSUE TITLE
`github: open file on remote` opens URL in Firefox even though it is not the default browser

### ISSUE THREAD

**Issue by ottumm** [divmain/GitSavvy#678]
Is there a preference option or something that controls which browser GitSavvy opens web URLs in? In any case, it seems better to use the default browser.

**Comment by stoivo** [comment]
Maybe duplication of #651 ?

**Comment by asfaltboy** [comment]
yes @stoivo, either this or #629 . This can be confirmed if @ottumm would confirm that he's using MacOS Sierra 10.12.5. The bug would be fixed in upcoming 10.12.6 (currently in beta 4).

**Comment by ottumm** [comment]
Confirmed, I am using MacOS Sierra 10.12.5

**Comment by ottumm** [comment]
Glad to hear this will be fixed when I upgrade MacOS! I'm curious as to why this is the case (I read the linked issues but couldn't find the answer). Is it a MacOS bug?

**Comment by stoivo** [comment]
Yes, it is a MacOS bug.
