### ISSUE TITLE
Amending the very first commit of a repo fails

### ISSUE THREAD

**Issue by 3v1n0** [divmain/GitSavvy#679]
It's classic, you fail your first commit of a new repo... :-D

But amending crashes:
```
`/usr/bin/git diff --no-color --cached HEAD^` failed with following output:

fatal: ambiguous argument 'HEAD^': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by asfaltboy** [comment]
This (and other oddities) were reported by myself a while back, in #557 . Unfortunately, no one has yet to tackle these yet.

**Comment by stoivo** [comment]
Since it is a duplicate we will close this issue.
