### ISSUE TITLE
Launch external merge tool for conflict - No such file or directory: '--verbose'

### ISSUE THREAD

**Issue by oddysee** [divmain/GitSavvy#681]
Sublime Text version number: Dev channel, Build 3139

Git version number: 2.13.0 (Apple Git-88)

OS type and version: macOS Sierra, 10.12.5

Console error output: 
```
>>> view.run_command("gs_status_launch_merge_tool")
Traceback (most recent call last):
  File "core.interfaces.status in /Users/sumanjay/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 802, in <lambda>
IndexError: tuple index out of range
```
A description of the problem:
On attempting to launch an external merge tool to resolve a conflict, nothing happens. 
Inspecting the console shows this -
```
  File "core.interfaces.status in /Users/sumanjay/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 802, in <lambda>
  File "core.git_mixins.merge in /Users/sumanjay/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 88, in launch_tool_for_file
  File "core.git_mixins.merge in /Users/sumanjay/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 68, in launch_tool_for_file
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '--verbose'
```

Relevant section of my gitconfig file:
```
[difftool "sourcetree"]
	cmd = /Applications/DiffMerge.app/Contents/MacOS/DiffMerge --nosplash \"$LOCAL\" \"$REMOTE\"
	path = 
[mergetool "sourcetree"]
	cmd = /Applications/DiffMerge.app/Contents/MacOS/DiffMerge --merge --result=\"$MERGED\" \"$LOCAL\" \"$BASE\" \"$REMOTE\"
	trustExitCode = true
[diff]
	tool = diffmerge
[merge]
	tool = diffmerge
[difftool "diffmerge"]
	cmd = diffmerge
[mergetool "diffmerge"]
	trustExitCode = true
	cmd = diffmerge --merge --result=\"$MERGED\" \"$LOCAL\" \"$BASE\" \"$REMOTE\"
```

Output of `git config merge.tool` is `diffmerge`.

Output of `git config mergetool.diffmerge.cmd` is - `diffmerge --merge --result="$MERGED" "$LOCAL" "$BASE" "$REMOTE"`

Steps to reproduce, if possible: I'm not entirely sure, I switched back to using my older Mac after encountering this issue on my current one. Very similar setup with just a difference in hardware (2015 vs 2013).

**Comment by asfaltboy** [comment]
Hi @oddysee , thank you for reporting the issue! Kindly help us with a few more details:

* Output of `git config -l | grep merge`
* Result of running `git mergetool` on it's own in a shell
* If the above still doesn't provide enough information, please record and attach a debug log like so:

   1. Open sublime, and get to the state of conflict just prior to running the merge command
   2. Open command palette, and run the command "GitSavvy: enable logging"
   3. Perform the failing "Launch external merge tool" command.
   4. Run the command "GitSavvy: disable logging"
   5. Run the command "GitSavvy: view recorded log", save the file and attach it here. Take care to remove any sensitive information that may be recorded in GitSavvy.

**Comment by thezimmee** [comment]
I am seeing the same issue on one of my machines but not another. I do have a different mergetool than the OP. Here is the info you asked for:

- **Output of `git config -l | grep merge`:
```bash
merge.tool=sublimerge
mergetool.sublimerge.cmd=subl -n --wait "$REMOTE" "$BASE" "$LOCAL" "$MERGED" --command "sublimerge_diff_views"
mergetool.sublimerge.trustexitcode=false
diff.tool=sublimerge
difftool.sublimerge.cmd=subl -n --wait "$REMOTE" "$LOCAL" --command "sublimerge_diff_views {\"left_read_only\": true, \"right_read_only\": true}"
branch.widget-migration.merge=refs/heads/widget-migration
branch.dev.merge=refs/heads/dev
branch.production.merge=refs/heads/production
branch.team-dash--35429.merge=refs/heads/team-dash--35429
branch.fed-bugs-for-client-launches.merge=refs/heads/fed-bugs-for-client-launches
branch.panels-layered--56935.merge=refs/heads/panels-layered--56935
```
- **Result of `git mergetool`:** Mergetool correctly opens up and works as expected.
- **Result of GitSavvy debug log attached**.

As noted, running `git mergetool` works just fine, so it's not a major issue; but I can't figure out why one of my machines works and another doesn't when I hit `M` from the status screen to run the mergetool. Both machines have the same config. Any help would be appreciated.

**Thank you** for all your work on GitSaavy... it's a great tool that I use every day and sure appreciate it!!

**Comment by stoivo** [comment]
> Result of GitSavvy debug log attached.
Where is it?

**Comment by thezimmee** [comment]
> Where is it?

Sorry, not sure what happened. I updated the comment with the attached log.

**Comment by stoivo** [comment]
@theiviaxx 
Can you inspect the console and see if it prints an error? maybe there is a problem with the path

**Comment by asfaltboy** [comment]
@thezimmee are you sure  that the issue occurred in the attached log? There doesn't seem that there is `--verbose` anywhere in the merge command to be executed.

If you still have the issue, I have created a branch that adds a bit more logging about executed command over here: [feature/add-process-debug-log][1]

Please try it out and add the new output here.

[1]: https://github.com/asfaltboy/GitSavvy/tree/feature/add-process-debug-log

**Comment by oddysee** [comment]
@asfaltboy OP here, I discovered that a botched install of a Git client (SourceTree) had mangled the gitconfig, which was resulting in the `--verbose` merge tool command.

Apologies for the confusion and thanks for all the assistance. Leaving this open for @thezimmee, though I'd suggest his issue is different and he'd be better off opening a separate issue.

**Comment by thezimmee** [comment]
I recently installed the dev build of Sublime, and for whatever reason that seemed to resolve the issue for me. Thanks for your help guys, I will let you know if I see it again.
