### ISSUE TITLE
Command not found in custom `commit-msg` git hook

### ISSUE THREAD

**Issue by TheRealJoeLinux** [divmain/GitSavvy#684]
### Sublime Text version number:
- Build 3126

### Git version number:
- 2.7.4

### OS type and version:
- Ubuntu 16.04.2 LTS

### Console error output:
```
Traceback (most recent call last):
  File "core.commands.commit in /home/joelinux/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 133, in <lambda>
  File "core.commands.commit in /home/joelinux/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 153, in run_async
  File "core.git_command in /home/joelinux/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 149, in git
  File "core.git_command in /home/joelinux/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 112, in raise_error
GitSavvy.core.exceptions.GitSavvyError: `/usr/bin/git commit -q -F -` failed with following output:

Command-line tool 'sprintly' not found. Please ensure it is installed and on your path.
#0 - Proceed without Sprint.ly item number.


Error occurred. Commit aborted.
```

### A description of the problem:
I use [Sprint.ly](https://sprint.ly) for managing tickets. They provide a `commit-msg` git hook for repositories to automatically reference tickets within their database. However, even though `which sprintly` returns just fine from the command line, GitSavvy doesn't appear to find the command in my `$PATH`. The command is located on my system at `/usr/local/bin/sprintly`, and is properly located in `$PATH` for both my user and the root user. I'm not sure why it's not being found (or the error message is incorrect).

### Steps to reproduce, if possible:
If not already using Sprint.ly:
- Install [Sprintly-GitHub](https://github.com/sprintly/Sprintly-GitHub)
- Install the git hook by running `sprintly --install-hook` in the project directory (or just copy `commit-msg` into `.git/hooks/`)
- Attempt to commit _anything_ using GitSavvy

If the error message is correct, then I'm guessing this might be true of any custom git hook installed in the project, but *my* specific situation involves Sprint.ly, so I specified those steps.

**Comment by stoivo** [comment]
Great issue report!

Seems like you are having the same issue as many Mac users, [this package](https://packagecontrol.io/packages/Fix%20Mac%20Path) fixes it for mac users.  Can you check if you have this issue by checking if sprintly is in your PATH inside sublime. 
First find the path to where sprintly binaries are, open a terminal and past `which sprintly`;
Check if that path is the $PATH inside sublime. To do that open the sublime console and past `from os import environ; environ['PATH']`

**Comment by asfaltboy** [comment]
This makes me feel we should add a FAQ section in docs; this particular section could go under "Other tools / PATH issues", what do you think @stoivo ?

**Comment by stoivo** [comment]
hmm, how much of it?

**Comment by asfaltboy** [comment]
Sorry, I meant this section in [your comment][1], we could refactor it as below:

> Please check the tool is in your PATH inside sublime.
> First find the path to where the tool binaries are, open a system terminal/shell and paste:
>
>     which <tool_name>;
>
> Check if that path is the $PATH inside sublime. To do that open the sublime console and paste in:
>
>     from os import environ; environ['PATH']
>
> If the tool path is missing from your sublime environment's `PATH` variable, you need to look into correcting the env variables available to sublime on launch. The unofficial docs mention how to set it globally for windows and mac in [the "Troubleshooting Build Systems" page][2]. Alternatively, you may want to look at the packages ["Environment Settings"][3] and ["Fix Mac Path"][4].
>
> If, however, the path is in your sublime environment, please open an issue and include these values in an issue.

[1]: https://github.com/divmain/GitSavvy/issues/684#issuecomment-323579850
[2]: http://docs.sublimetext.info/en/latest/reference/build_systems/troubleshooting.html
[3]: https://packagecontrol.io/packages/Environment%20Settings
[4]: https://packagecontrol.io/packages/Fix%20Mac%20Path

**Comment by stoivo** [comment]
Yes, we should add that.

**Comment by stoivo** [comment]
Feel free to reopen
