### ISSUE TITLE
So how does one actually use it?

### ISSUE THREAD

**Issue by geoidesic** [divmain/GitSavvy#686]
This looks great but nothing in any of the documentation actually tells one how to use this package. It tells you what it can do but not how to do it.

There are no key-bindings, no menus... so I can't figure out how to even get a simple "git status" to work. Looking in the documentation all it says is "git status: status.md" whatever that means.

A little help?

**Comment by geoidesic** [comment]
Ok never mind. I found it: https://github.com/divmain/GitSavvy/blob/master/docs/status.md

Hope this helps some other n00b :)

**Comment by stoivo** [comment]
What would we do to make it clearer?

**Comment by geoidesic** [comment]
I think on the main readme file which shows on the code's git home page you could just summarise how it is used in general so that one does not have to infer it. A single line such as:

"GitSavvy" does not add any menus or key-bindings to Sublime Text. Instead the way it works is by typing commands into the Command Palette (see Tools > Command Palette). The list of available commands can be found here: https://github.com/divmain/GitSavvy/tree/master/docs"

**Comment by divmain** [comment]
@geoidesic, GitSavvy does add key-bindings to Sublime.  It adds key-bindings, interactive dashboards, panels that give contextual information, etc.  It's pretty comprehensive, and it may be hard to summarize with something other than `Full git and GitHub integration with Sublime Text 3.`, which is the repo description now.

If you get a chance to read through the docs and explore the various features that are provided, we'd love to hear back about how you'd recommend summarizing the feature set.
