### ISSUE TITLE
push command in git status tab

### ISSUE THREAD

**Issue by hanoii** [divmain/GitSavvy#69]
Might be nice to have a push action in the status screen.

**Comment by flip4bytes** [comment]
Yeah, I was wondering about this as well. I assumed there was probably a reason as to why you chose to not include it though? Would love to see it in there as like "shift+P" or something because it's more of a big deal than just an accidental button press.

**Comment by divmain** [comment]
The primary reason is that I tried to restrict status dashboard actions to those that interact directly with the index (or stashes).  If enough people would like to see push/pull from the dashboard, I'm happy putting it in.  I just want to avoid the dashboard getting too bloated or doing too many things.

**Comment by hanoii** [comment]
They are just too frequently used that I would expect it to see it there. They are primary buttons in SourceTree, not that this is any similar, but it's really into my workflow.

Anyway, as sublime is all about configuration, this could just also be another configuration entry in which you can have extra actions on the status page :)

I am really enjoying using GitSavvy, good work!

**Comment by divmain** [comment]
@hanoii - do you envision it would directly do `git push`, or would it prompt for remote/branch like `git: push to branch name` does now?

**Comment by hanoii** [comment]
@divmain I'd say a straightforward push/pull, at least that's what's most common on my workflow.

**Comment by hanoii** [comment]
@divmain hey, it seems that this was added to the git branch dashboard, right?

I do have a question, why is it asking where to push, I'd expect hitting p or P to do the same as git: push from the command pallet but instead is asking for the remote.

**Comment by flip4bytes** [comment]
I'm seeing it on the Branch dashboard too. It was expecting push would be in the status dashboard though? I have no reason to keep open the branch dashboard but I always keep the status dashboard open.

**Comment by divmain** [comment]
Alrighty, I'll add this to status dashboard.  Push in the branch dashboard was a separate effort and unrelated.  Should be able to get this in for the next release.

**Comment by divmain** [comment]
Sorry for the delay - this keybinding has been added to the status dashboard.
