### ISSUE TITLE
Update docs for new blame walk features

### ISSUE THREAD

**Issue by divmain** [divmain/GitSavvy#702]

**Comment by stoivo** [comment]
Where?

**Comment by asfaltboy** [comment]
@stoivo I suggest adding it in [History][1], either under the [current git: blame][2] docs, or maybe in it's  own sub-section.

[1]: https://github.com/divmain/GitSavvy/blob/master/docs/history.md
[2]: https://github.com/divmain/GitSavvy/blob/master/docs/history.md#git-blame-current-file

**Comment by stoivo** [comment]
Isn't this what you are looking for just a bit miss formed?https://github.com/divmain/GitSavvy/blob/master/docs/history.md#action-in-blame-view

**Comment by stoivo** [comment]
Here better formed https://github.com/divmain/GitSavvy/blob/blame_doc/docs/history.md
