### ISSUE TITLE
Error when pushing/pulling

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#71]
Got this error when trying to push a new branch to a remote:

```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\core\commands\push.py", line 86, in deferred_panel
    selected_index=pre_selected_index
  File "C:\Program Files\Sublime Text 3\sublime.py", line 370, in show_quick_panel
    items_per_row, on_select, on_highlight, flags, selected_index)
TypeError: an integer is required
```

I also saw something similar when trying to pull from a secondary remote, but I can't say for certain what was the causing factor.

**Comment by p3lim** [comment]
Not 100% sure what is causing this, if you need me to test I'll get a test case going tomorrow.

**Comment by divmain** [comment]
There was a change in the accepted parameters for this method from one ST3 version to the next.  It can be overcome using keyword args instead.  I'll fix this tonight.
