### ISSUE TITLE
Pushing a tag to remote no longer working

### ISSUE THREAD

**Issue by mnieber** [divmain/GitSavvy#715]
When I create a new tag and press `p` to push it, nothing happens (also, the status bar is not responding in any way). I've used this functionality succesfully many times in the past, did something break?

**Comment by randy3k** [comment]
It is working for me. Would you try upgrading to the latest GitSavvy?

**Comment by mnieber** [comment]
Thanks for the quick reply. I upgraded but it's still not working. By the way, when I upgraded with Package Control I got this message (probably harmless but I wanted to mention it just in case): 

Error loading syntax file "Packages/GitSavvy/syntax/show_commit.sublime-syntax": Unable to read Packages/GitSavvy/syntax/show_commit.sublime-syntax

**Comment by randy3k** [comment]
This syntax was upgrade a month ago. It is unclear why the error was shown and how the error is related to the syntax. Although obvious, did you try restarting sublime text?

**Comment by mnieber** [comment]
Thanks, after restarting it works!
