### ISSUE TITLE
Unable to commit changes to via the plugin anymore

### ISSUE THREAD

**Issue by harshal-gajare** [divmain/GitSavvy#716]
I am unable to commit changes via the plugin anymore. I am able to Stage, unstage changes , change branches but when I try to commit the changes I get an error " Unable to determine Git repo path."

**Comment by harshal-gajare** [comment]
```
[
  {
    "type": "git", 
    "secounds": 0.043879032135009766, 
    "stderr": "", 
    "command": [
      "status", 
      "--porcelain", 
      "-z"
    ], 
    "stdin": null, 
    "stdout": "M  src/approvalProcesses/Order_Index__c.Sample_Order_Single_Approver_Level_US.approvalProcess\u0000"
  }, 
  {
    "type": "git", 
    "secounds": 0.026094913482666016, 
    "stderr": "", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stdin": null, 
    "stdout": "## fix-inactive-user-approval-process...origin/fix-inactive-user-approval-process\nM  src/approvalProcesses/Order_Index__c.Sample_Order_Single_Approver_Level_US.approvalProcess\n"
  }, 
  {
    "type": "git", 
    "secounds": 0.010597944259643555, 
    "stderr": "", 
    "command": [
      "log", 
      "-n 1", 
      "--pretty=format:%h %s", 
      "--abbrev-commit"
    ], 
    "stdin": null, 
    "stdout": "0028a14c Merged in SFDC-2089-build-dior-email-page4 (pull request #899)"
  }, 
  {
    "type": "git", 
    "secounds": 0.06950616836547852, 
    "stderr": "", 
    "command": [
      "stash", 
      "list"
    ], 
    "stdin": null, 
    "stdout": ""
  }, 
  {
    "type": "git", 
    "secounds": 0.048963069915771484, 
    "stderr": "", 
    "command": [
      "status", 
      "--porcelain", 
      "-z"
    ], 
    "stdin": null, 
    "stdout": "M  src/approvalProcesses/Order_Index__c.Sample_Order_Single_Approver_Level_US.approvalProcess\u0000"
  }, 
  {
    "type": "git", 
    "secounds": 0.030784130096435547, 
    "stderr": "", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stdin": null, 
    "stdout": "## fix-inactive-user-approval-process...origin/fix-inactive-user-approval-process\nM  src/approvalProcesses/Order_Index__c.Sample_Order_Single_Approver_Level_US.approvalProcess\n"
  }, 
  {
    "type": "git", 
    "secounds": 0.015290021896362305, 
    "stderr": "", 
    "command": [
      "log", 
      "-n 1", 
      "--pretty=format:%h %s", 
      "--abbrev-commit"
    ], 
    "stdin": null, 
    "stdout": "0028a14c Merged in SFDC-2089-build-dior-email-page4 (pull request #899)"
  }, 
  {
    "type": "git", 
    "secounds": 0.07985901832580566, 
    "stderr": "", 
    "command": [
      "stash", 
      "list"
    ], 
    "stdin": null, 
    "stdout": ""
  }, 
  {
    "type": "git", 
    "secounds": 0.018252134323120117, 
    "stderr": "", 
    "command": [
      "diff", 
      "--stat", 
      "--no-color", 
      "--cached", 
      null
    ], 
    "stdin": null, 
    "stdout": " ...der_Index__c.Sample_Order_Single_Approver_Level_US.approvalProcess | 4 ----\n 1 file changed, 4 deletions(-)\n"
  }, 
  {
    "type": "git", 
    "secounds": 0.046473026275634766, 
    "stderr": "", 
    "command": [
      "status", 
      "--porcelain", 
      "-z"
    ], 
    "stdin": null, 
    "stdout": "M  src/approvalProcesses/Order_Index__c.Sample_Order_Single_Approver_Level_US.approvalProcess\u0000"
  }, 
  {
    "type": "git", 
    "secounds": 0.030153989791870117, 
    "stderr": "", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stdin": null, 
    "stdout": "## fix-inactive-user-approval-process...origin/fix-inactive-user-approval-process\nM  src/approvalProcesses/Order_Index__c.Sample_Order_Single_Approver_Level_US.approvalProcess\n"
  }, 
  {
    "type": "git", 
    "secounds": 0.012295007705688477, 
    "stderr": "", 
    "command": [
      "log", 
      "-n 1", 
      "--pretty=format:%h %s", 
      "--abbrev-commit"
    ], 
    "stdin": null, 
    "stdout": "0028a14c Merged in SFDC-2089-build-dior-email-page4 (pull request #899)"
  }, 
  {
    "type": "git", 
    "secounds": 0.07545614242553711, 
    "stderr": "", 
    "command": [
      "stash", 
      "list"
    ], 
    "stdin": null, 
    "stdout": ""
  }, 
  {
    "type": "error", 
    "error": "ValueError('Unable to determine Git repo path.',)"
  }, 
  {
    "type": "git", 
    "secounds": 0.010843038558959961, 
    "stderr": "", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdin": null, 
    "stdout": "/Users/lm97580/Documents/Workspace/MavensMate/SFDHG\n"
  }, 
  {
    "type": "git", 
    "secounds": 0.010999202728271484, 
    "stderr": "", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdin": null, 
    "stdout": "/Users/lm97580/Documents/Workspace/MavensMate/SFDHG\n"
  }
]
```

**Comment by harshal-gajare** [comment]
Other thing I noticed that has changed is on the commit page I see the below

![image](https://user-images.githubusercontent.com/5017173/28480325-1b590952-6e2e-11e7-97fb-b7ed673713ec.png)

**Comment by randy3k** [comment]
I cannot reproduce it. Would you try updating to the newest GitSavvy? More information will help.

**Comment by harshal-gajare** [comment]
Here is the info that I get in the console 

**which git: /usr/bin/git
os: darwin
sublime version: 3126
GitSavvy git:** 

I have tried uninstalling and reinstalling the plugin but I run into the same issue.

**Comment by harshal-gajare** [comment]
Traceback (most recent call last):
  File "core.git_command in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 127, in git
  File "core.git_command in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 234, in repo_path
  File "core.git_command in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 262, in _repo_path
  File "core.git_command in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 251, in invalid_repo
ValueError: Unable to determine Git repo path.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.git_command in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 137, in git
  File "core.git_command in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 112, in raise_error
GitSavvy.core.exceptions.GitSavvyError: Unable to determine Git repo path.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.commands.commit in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 142, in <lambda>
  File "core.commands.commit in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 162, in run_async
  File "core.git_command in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 141, in git
UnboundLocalError: local variable 'end' referenced before assignment
Traceback (most recent call last):
  File "core.commands.status_bar in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 57, in run_async
  File "core.git_command in /Users/lm97580/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 276, in _repo_path
TypeError: argument of type 'NoneType' is not iterable

**Comment by randy3k** [comment]
It is still unclear how it happened, but I hope that #719 will address this.

**Comment by mnieber** [comment]
I'm getting a possibly related error (in the sublime text console) when trying to open the git status screen:

    `/usr/bin/git rev-parse --show-toplevel` failed with following output:
    fatal: Not a git repository (or any of the parent directories): .git

However, it happens for a repo that lives on a mounted NTFS partition. For a different repo that lives on my main (ext4) drive, it works fine.

**Comment by harshal-gajare** [comment]
@randy3k  I upgraded the package and tested and all looks good again . Thanks for the quick turn around !!
