### ISSUE TITLE
"github: open file on remote" doesn't necessarily resolve the correct URL

### ISSUE THREAD

**Issue by allen-zeng** [divmain/GitSavvy#723]
This is a great feature. But it resolves an incorrect URL for a file when the local branch is ahead, because the SHA that is plugged into the URL doesn't exist on a remote yet.

Can we use the latest SHA of the file on that remote instead?

**Comment by allen-zeng** [comment]
Good point. We could have two options:
- open latest file on remote
- open file at base on remote

"Open latest file on remote" will involve a `fetch` and simply opening the file at the latest remote SHA. "Open file at base on remote", on the other hand, will open the latest locally known commit on the remote.

**Comment by randy3k** [comment]
I am working on this, it seems the easier solution might be prompting to push to remote rather than trying to determine the hash to be used.
