### ISSUE TITLE
pull --rebase broken

### ISSUE THREAD

**Issue by m-messiah** [divmain/GitSavvy#729]
Hello, I have got a bug with pull/rebase - it is not working after last update.

- Sublime: 3126
- git version 2.13.4
- MacOS Sierra 10.12.6

Status:

```
BRANCH:  On branch `testing` tracking `origin/testing`.
           You're ahead by 1 and behind by 4.
  ROOT:    ~/test_repo
  HEAD:    6864c4b35 Test it

    Your working directory is clean.
```

Git pull console:
```
`/usr/bin/git pull origin testing:testing` failed with following output:

From git+ssh://git.example.com/test_repo
 ! [rejected]            testing    -> testing  (non-fast-forward)
```

Reproduce:
- Get repository, with tracking branch
- Configure git for pull --rebase
- Commit to repo (without push)
- Commit to repo from another machine and push
- Shift+Command+P git pull
- Error

In debug log interesting moment same:

```
{
    "stdout": "", 
    "command": [
      "pull", 
      "origin", 
      "testing:testing"
    ], 
    "stderr": "From git+ssh://git.example.com/test_repo\n ! [rejected]            testing    -> testing  (non-fast-forward)\n", 
    "stdin": null, 
    "secounds": 1.0345990657806396, 
    "type": "git"
  }, 
  {
    "error": "'`/usr/bin/git pull origin testing:testing` failed with following output:\\n\\nFrom git+ssh://git.example.com/test_repo\\n ! [rejected]            testing    -> testing  (non-fast-forward)\\n'", 
    "type": "error"
  }, 
```

P.S. Hostname rewritten

**Comment by randy3k** [comment]
Ah, it is because the git pull command explicitly pull from the remote tracking to the current branch rather than just `git pull`. The rebase option is only honored if the remote and branch are omitted.

My suggestion is to add another command `git: pull and rebase` rather fixing the existing command.

**Comment by randy3k** [comment]
Actually the exiting `git: pull` should be renamed as `git: pull from remote branch`.

I suggestion the followings

1. `git: pull`, explicitly pull from the remote tracking branch
2. `git: pull and rebase`, just like 1 with the rebase option
3. `git: pull from remote branch`
4. `git: pull and rebase from remote branch`

**Comment by m-messiah** [comment]
Hey, @randy3k said earlier, 

> The rebase option is only honored if the remote and branch are omitted.

But in #730 they are not omitted, so this MR not working. 

I have just upgraded to last version of GitSavvy, and pull with rebase not work.

**Comment by randy3k** [comment]
So the new command does not rebase?

**Comment by m-messiah** [comment]
Yep, Cmd+Shift+P: `git: pull with rebase` just generates the same command with explicit remote, so it fails same:

```bash
`/usr/local/bin/git pull --rebase origin stable:stable` failed with following output:

From git+ssh://git.example.com/test_repo
 ! [rejected]            stable     -> stable  (non-fast-forward)
   3036db037..6e98ccfca  stable     -> origin/stable
```

**Comment by m-messiah** [comment]
I think, you need to omit some arguments, when pull-rebase called.

**Comment by stoivo** [comment]
When you run `/usr/local/bin/git pull --rebase origin stable:stable` from the command line does it work?

**Comment by m-messiah** [comment]
Nope:
```bash
$ git pull --rebase origin stable:stable
From git+ssh://git.example.com/test_repo
 ! [rejected]            stable     -> stable  (non-fast-forward)
```

**Comment by m-messiah** [comment]
I promote you this code:

```python
if rebase:
    self.git("pull", "--rebase")
else:
    self.git(
        "pull",
        remote,
        branch if not remote_branch else "{}:{}".format(remote_branch, branch)
        )
```

Is it breaks your line about explicity? Do you apply it, or I need to create PR and we can disscuss it there?

**Comment by randy3k** [comment]
It seems the syntax of the pull command is: `git pull --rebase origin branch` without `:localbranch`.

**Comment by randy3k** [comment]
Yap, we want it to be explicit for easier troubleshooting.

**Comment by m-messiah** [comment]
You're right: it works without `:localbranch`

**Comment by stoivo** [comment]
Should be change to https://github.com/divmain/GitSavvy/blob/c655130d43f02ab79a48be53ca603a6d52d6021b/core/git_mixins/remotes.py#L50-L55
```
        self.git(
            "pull",
            "--rebase" if rebase else None,
            remote,
            branch
)
```

**Comment by stoivo** [comment]
This command runs perfectly on my mac 
```
$ git pull --rebase divmain randy3k/checkout:randy3k/checkout
Already up-to-date.
Current branch randy3k/checkout is up to date.
```

**Comment by randy3k** [comment]
Obviously, there is a bug.

from https://git-scm.com/docs/git-pull

> When git fetch is used with <rbranch>:<lbranch> refspec, it refuses to update the local branch <lbranch> unless the remote branch <rbranch> it fetches is a descendant of <lbranch>. This option overrides that check.

I guess that's the issue. When running with `--rebase`, the remote branch is mostly likely not a descendant of the local branch (i.e., there are some un-pushed commits).

**Comment by randy3k** [comment]
I have prepared a PR which only pull to the active branch: https://github.com/divmain/GitSavvy/pull/736

**Comment by randy3k** [comment]
@m-messiah 
Just want to let you know that the behavior of `git: pull` has changed. It will honor `pull.rebase` 
after this PR https://github.com/divmain/GitSavvy/pull/833/files
