### ISSUE TITLE
git: revert

### ISSUE THREAD

**Issue by hanoii** [divmain/GitSavvy#732]
I didn't find a way..  I'd guess it  could be done from the graph window.

**Comment by asfaltboy** [comment]
I don't believe we support it, and I don't use it personally.

However this is a nice feature request, to add a `git: revert` command, should be easy to implement if you want to give it a go and submit a Pull Request we'll be happy to assist.

Meanwhile, as a workaround I can suggest using [custom commands][1].

[1]: https://github.com/divmain/GitSavvy/blob/master/docs/README.md#custom-commands
