### ISSUE TITLE
git add(edit) to git add

### ISSUE THREAD

**Issue by AJgotBeard** [divmain/GitSavvy#734]
I think the git add option is changed to git add(edit). I need to add current file to the repo, not open a new file.

**Comment by asfaltboy** [comment]
Hi @AJgotBeard thank you for reporting the issue. However, I couldn't find a matching `git: add` command in the history, and the `git: add (edit)` command was added about 2 years ago.

Normally, myself I use the `git: status` dashboard, go to the file and press the <kbd>s</kbd> (stage) shortcut.

If that doesn't fit your use case, until we address this feature request, you can [add a custom command][2] in your own User.sublime-commands like so:

```json
{
    "caption": "git: add",
    "command": "gs_custom",
    "args": {
        "output_to_panel": false,
        "args": ["add", "{FILE_PATH}"],
    }
}
```

[1]: https://github.com/divmain/GitSavvy/commit/40cdf58a3f0b61d301d4c7222b4c078584a9f304
[2]: https://github.com/divmain/GitSavvy/blob/master/docs/README.md#custom-commands

**Comment by AJgotBeard** [comment]
Really?? Because I used it somewhat a week ago. I don't usually do github. I recently started.
And since the git : add is not available I used the same git:status as you suggested.
ThankYou for the Reply. 
Should I just paste the above command or the FILE_PATH should be changed to something?

I tried adding the command as it is, but it didn't show in the Command Palette

**Comment by asfaltboy** [comment]
Maybe someone added it and removed it straight after ? I failed at "grep"-ing for it anyway.

{FILE_PATH} should be passed as is.  I added the same command to my own `User.sublime-commands` and it works fine. Mind you that I had to press <kbd>🔼</kbd> on my keyboard since the new command appeared above the `git: add (edit)` command

**Comment by AJgotBeard** [comment]
Where is this `User.sublime-commands` located?
I added the command in GitSavvy setting. May be thats what I am doing wrong.

**Comment by AJgotBeard** [comment]
I got it;
Created the `User.sublime-commands` file in `~.config/sublime-text-3/Packages/User` and added above 

> code 
and got it to work. Thanks for everything.

**Comment by asfaltboy** [comment]
Yes @AJgotBeard exactly! Sorry for delay, was just going to say it needs to be in the Packages/User directory.

**Comment by stoivo** [comment]
`git add(edit)` is giving you the opportunity to edit the patch before applying it to staged.
Maybe `git quick stage` is what you are looking for.

Feel free to reopen if there are any other questions.

**Comment by asfaltboy** [comment]
I forgot about that command @stoivo , I gotta say the two commands have confusing names.
