### ISSUE TITLE
Create pull request for unpushed branches should push them

### ISSUE THREAD

**Issue by sheldon** [divmain/GitSavvy#738]
Hey

Thanks for the excellent git integration, definitely the best I've seen for Sublime. As the co-author of a competitor, you've won me over and I've fully switched a while back. :)

At the moment if you try create a pull request for an unpushed local branch, it asks to set an upstream from existing remote branches. This means my workflow for upstreaming changes involves 4 steps: create local branch, make changes, push, create pull request.

I believe those last 2 steps can be streamlined by defaulting to the same as a push command when trying to create a pull request with an unpushed local branch. This would allow you to create a new remote branch (by default) matching your local branch name, and create a new pull request, all in 1 command.

**Comment by randy3k** [comment]
Um, `create pull request` now asks for configuring tracking remote if there is tracking remote. Instead, it may be more reasonable to prompt and pull to a remote.
