### ISSUE TITLE
"Checkout remote branch as local" action is lost

### ISSUE THREAD

**Issue by pokidovea** [divmain/GitSavvy#749]
Now, I can't find such action in branch management sheet.
https://github.com/divmain/GitSavvy/blob/master/docs/branch_mgmt.md#checkout-remote-branch-as-local-o
![2017-08-21 10-42-51](https://user-images.githubusercontent.com/2443005/29508549-a0d9e26c-865d-11e7-8dfb-6ba763d29968.png)

Sublime Text 3, build 3126

**Comment by stoivo** [comment]
Please read https://github.com/divmain/GitSavvy/blob/master/messages/2.15.0.txt

I have forgotten to update the view and docs. I will do it today.

**Comment by pokidovea** [comment]
So, how to create a new branch from develop, e.g, now? Strange changes...
