### ISSUE TITLE
Get Pull Request Link for Given Push

### ISSUE THREAD

**Issue by jaybyrrd** [divmain/GitSavvy#758]
When you push in the console, git gives you a link that you can go to in order to start a pull request. Is it possible to prompt to open such a link, or display it?

**Comment by stoivo** [comment]
I think you are looking for this setting
https://github.com/divmain/GitSavvy/blob/1443bcf6ff935c63c8b97802361d46774d981a1f/GitSavvy.sublime-settings#L93-L97

it will open an output panel with the output.

**Comment by randy3k** [comment]
There is a command `github: create pull request` to open a pull request page on github.

**Comment by jaybyrrd** [comment]
Hey guys,
I think stoivo's comment actually helps me here. This is mostly so we can see the output for when we aren't on github (IE bitbucket or gitlab) and want to get the pull request link through the command output.

**Comment by stoivo** [comment]
Cool, i use that myself when working with gitlab.
Feel free to reopen if there are any other questions.
