### ISSUE TITLE
AttributeError: 'GsPushToBranchCommand' object has no attribute 'selected_remote' on push to existing branch

### ISSUE THREAD

**Issue by niosus** [divmain/GitSavvy#759]
This has started happening recently, but I am not sure if this is a configuration issue.

## How to reproduce
1. create a branch
2. push it to remote from `BRANCHES` tab pressing <kbd>p</kbd>
3. do a commit to this branch
4. pick `git: push to existing branch` from command pallet and pick the branch

## What happens
Nothing visible happens. Console contains a message:
```
AttributeError: 'GsPushToBranchCommand' object has no attribute 'selected_remote'
```

## Expected behavior
- make user aware of the error (???)
- ask the user to set remote (???)

**Comment by randy3k** [comment]
It has been fixed, please upgrade to the latest release. Thank you.

**Comment by niosus** [comment]
Ok, great to know. Thanks!

By the way, something seems to be wrong with the messages for this release. Console:
```
Package Control: Error parsing messages.json for GitSavvy
Package Control: Upgraded GitSavvy to 2.16.1
```

**Comment by randy3k** [comment]
Thanks for the report.

**Comment by niosus** [comment]
@randy3k no problem! I love using your plugins :+1: They always deliver.
