### ISSUE TITLE
Missing output when encountering error trying to run external merge utility

### ISSUE THREAD

**Issue by niosus** [divmain/GitSavvy#761]
No error visible in output when trying to use the external merge tool. When trying to run it form GitSavvy I get the following in the output pane and console:
```
GitSavvy.core.exceptions.GitSavvyError: `/usr/bin/git config merge.tool` failed with following output:
```
The actual message is missing.

**Comment by randy3k** [comment]
`/usr/bin/git config merge.tool` returns exit code 1 without stderr output if it cannot find the config. Therefore you were not seeing any output here.

**Comment by niosus** [comment]
You are right. Thanks.

**Comment by randy3k** [comment]
Anyway, #762 is address this. Thanks for the report.

**Comment by niosus** [comment]
Thanks for addressing this. It makes sense.
