### ISSUE TITLE
git graph dashboard doesn't handle selection changed events

### ISSUE THREAD

**Issue by deathaxe** [divmain/GitSavvy#774]
Running "git: graph" from command panel opens a view with the list of commits. At the same time the "show_commit" output panel with information of the first selected commit is displayed at the bottom of the window.

#### Now the issue:

Navigating through the commits doesn't trigger an update of the output panel, but only the next on_activate event. I need to leave the view displaying the graph and activate it again to get the output panel updated.

**Comment by stoivo** [comment]
https://github.com/divmain/GitSavvy/blob/master/docs/history.md#git-graph use `,` and `.` to navigate like everywhere else in GitSavvy. 
Also, check out `?` when you are on the graph.

**Comment by deathaxe** [comment]
Oh. Was never aware of those key bindings. 😨 Was always wondering whether it was possible to create good navigation experience in the dashboards as navigating to each character using the cursor might not always make sense.

**Comment by stoivo** [comment]
You should be able to use `,` and `.` to navigate anywhere, in any view.

**Comment by deathaxe** [comment]
Yes I am. It works well. I was just not aware of those key bindings and expected `Up` and `Down` to be used for navigation there. Had a short look into GitSavvy's keymap file and was amazed about its size. Just crazy much stuff in there.

**Comment by stoivo** [comment]
We have decided that navigating with arrows in interrupt the common flow of arrows. If you want to navigate with `up` and `down` you can. Just have a look at https://github.com/divmain/GitSavvy/blob/1f334e9a0c850f8c5bf9dce34ec0a3c9fc8ed48a/GitSavvy.sublime-settings#L315-L319

The size, yeah, it was grown over the years... when you have 3 different ways to navigate at 10 different location is grows.

**Comment by deathaxe** [comment]
Cool. Exactly what I was looking for. I have been using GitSavvy for a long time now. Looks like it's worth to have a deeper look into the changes from time to time.

Thank you very much for your help and the awesome piece of software.

**Comment by deathaxe** [comment]
I close this issue as it was raised due to lack of knowledge only.
