### ISSUE TITLE
Slow at Tags page

### ISSUE THREAD

**Issue by rerime** [divmain/GitSavvy#780]
When change mode by hiting TAB from rebase to tags, it slows. I have in my repo 1,5k tags.
Reproduced on latest version of Sublime 3143 (Windows, Mac)

**Comment by stoivo** [comment]
Did it work faster before?
When you sat slow, what are we talking about, 1 sec or 2 min?
What hardware are you on? SSD?

**Comment by randy3k** [comment]
You could opt out the tags dashboard in the tab cycle by using one of the settings, sth like tab_order. (On a mobile now, cannot check)

**Comment by stoivo** [comment]
https://github.com/divmain/GitSavvy/blob/686d40f87074e22efafe5954768401b6844a7544/GitSavvy.sublime-settings#L281-L299

**Comment by randy3k** [comment]
There is also a setting for the number of items shown in tag dashboard.

https://github.com/divmain/GitSavvy/blob/9bc0743b2fd0ec91751baf13cc9dc6e874c3f8d2/GitSavvy.sublime-settings#L166-L171

**Comment by stoivo** [comment]
Feel free to reopen
