### ISSUE TITLE
diff file inline - not working in Sublime 3?

### ISSUE THREAD

**Issue by HatStephens** [divmain/GitSavvy#782]
`[l] diff file inline`
Doesn't seem to be working after an upgrade to Sublime 3. Just opens a blank page in a new tab.

Anyone else experienced this issue or know a solution?

Thanks!

git version: 2.12.2
have also tried to uninstall an reinstall package

**Comment by stoivo** [comment]
Do you have console errors?

We had the same issue in the gitter chat, try running "Package Control: Satisfying Dependencies", then restart sublime.

**Comment by HatStephens** [comment]
Thanks @stoivo 
This didn't work.
However, I found this https://github.com/DougTy/sublime-compare-side-by-side/issues/31

I commented out my color_scheme ("Packages/Color Scheme - Default/iPlastic.tmTheme") and it worked again.

Hopefully this might help others! 

Thanks for the reply though.
