### ISSUE TITLE
can't stage file: complain about the path

### ISSUE THREAD

**Issue by nimafazeli** [divmain/GitSavvy#783]
I recently changed the structure of folders in my project. It also involved moving my `.git` folder one level. I did the changes inside git bash and everything works from there. 

But git savvy cannot stage the file and return the complain from git that 
````
`C:/Program Files/Git/cmd/git.exe add --all -- tex/23_quality_setting_subgame.tex` failed with following output:

fatal: pathspec 'tex/23_quality_setting_subgame.tex' did not match any files
````

**Comment by stoivo** [comment]
Is tex one of the til level folders?
Did you restart sublime?

**Comment by nimafazeli** [comment]
>Is tex one of the til level folders?

Yes. The folder structure is like this
````
paper
    .git
    tex
    notebook
    output
````
The `.git` used to be in `tex` before the change in folder structure.
>Did you restart sublime?

Yes

Also this top folder along with several other higher level folders (some of them with git) are in a `sublime-project.`

**Comment by stoivo** [comment]
I managed to move my .git folder without any problems.
Can you make test senary with a public repo?

**Comment by nimafazeli** [comment]
for the past few days I was using git bash . Today, after the update of gitsavvy I tried and the issue is resolved. It was either the update or something got resolved by itself.
anyways cool extension and thanks.
