### ISSUE TITLE
Untracked files causes rebase not to work

### ISSUE THREAD

**Issue by 3v1n0** [divmain/GitSavvy#789]
The error "Unable to manipulate commits while repo is in unclean state" is shown even when in the repo there are files that are untracked, while this should not happen.

- Sublime Text version number: 3148
- Git version number: 1.9.1
- OS type and version: Ubuntu 14.04

1. `touch foo.bar` in the repo dir
2. enter in GitSavvy rebase mode
3. Try to do any action

The command will fail since with the said error.

**Comment by stoivo** [comment]
The reason for this because some action does not allow untracked files.

**Comment by 3v1n0** [comment]
Well, using `git rebase` from command line correctly works so, untracked files might not stop sublime to delete or reorder a commit for example.

**Comment by randy3k** [comment]
@stoivo Maybe untracked files do not cause any issues?

**Comment by stoivo** [comment]
@randy3k, should we close this issue?

**Comment by randy3k** [comment]
On your preference. It will get closed when #826 gets merged to master anyway.

**Comment by stoivo** [comment]
This is merged into dev and will be released in the next release. 
Feel free to reopen if it is't solved.
