### ISSUE TITLE
Git log doesn't open until hitting another key (windows)

### ISSUE THREAD

**Issue by ethanbustad** [divmain/GitSavvy#79]
Just tried `git: log` for the first time.

At first I thought it didn't do anything. When I hit ctrl+shift+p again to see if I could get it to work the second time, I briefly saw the command palette, then the `git: log` menu showed up. Seems like it isn't a timing problem - the `git: log` menu just doesn't come up until I open up the command palette again.

This isn't the intended behavior, right? I expect it should work like Package Control, where the menu opens up right after you select the action you'd like to perform.

The workaround is really easy now that I know what to do. But it seemed like the feature just didn't work at first.

(P.S. I'm assuming this is only a problem on Windows.)

Edit: Apparently it just requires some keypress.... doesn't necessarily have to be the command palette.

**Comment by ethanbustad** [comment]
Screen capture:
![issue79](https://cloud.githubusercontent.com/assets/2229593/6609903/6c7daeb2-c815-11e4-81b0-b9a58998e1f6.gif)

**Comment by divmain** [comment]
Hmm... this sounds like a Sublime bug.  Can you put a `print` statement in your local version, right before [this code block](https://github.com/divmain/GitSavvy/blob/f90d409835e228f0a6cc89de39b4f13f57071373/core/commands/log.py#L50-L55)?  You'll either have to restart Sublime or run `GitSavvy: reload modules (debug)` (if you have `debug_mode` set to true in `User/GitSavvy.sublime-settings`.

**Comment by divmain** [comment]
Hmm just realizing that if you're in the GitSavvy repo, you should be anywhere near the limit, so that's not going to help.

**Comment by divmain** [comment]
Should be fixed in the next release.
