### ISSUE TITLE
Unstage doesn't work for newly added files

### ISSUE THREAD

**Issue by 3v1n0** [divmain/GitSavvy#797]
1. Stage a folder containing some files
2. See in the staged area the files and unstage one of them

Error returned
```
`/usr/bin/git reset HEAD snap/.snapcraft/state` failed with following output:

fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

In fact to unstage it, in this case the command `git rm --cached <file>` should be used

**Comment by asfaltboy** [comment]
I believe this one was already reported, by yours truly, in #557 , I even added a failing test PR in #680, but never got around to fixing it 🐌 .

Contributions are welcome 😄 !

If I'm mistaken about the scenario, kindly reopen.
