### ISSUE TITLE
`git: branch` view

### ISSUE THREAD

**Issue by divmain** [divmain/GitSavvy#8]
- [x] syntax-highlighted view
- [x] show all local branches
- [x] checkout branch
- [x] delete branch (--force)
- [x] merge branch

**Comment by divmain** [comment]
@ethanbustad - If you have some time, would you mind test driving this feature for me?

**Comment by p3lim** [comment]
If a remote branch is deleted from somewhere else than the current system, it will still show up in the list, and the user will be unable to delete it because the remote ref doesn't exist.

**Comment by ethanbustad** [comment]
@divmain will do

**Comment by ethanbustad** [comment]
@divmain Tried `checkout`, `create new branch (from HEAD)`, `delete`, and `delete (force)`, and it all seems to work great on my Windows machine. I'll test the other commands as the need arises and let you know if I have any problems.

**Comment by ethanbustad** [comment]
@divmain One thing to consider.... I have a lot of remote branches in one repo (over 1000), so I have to scroll way down to see the possible actions I can take. Would it make sense to show the actions at the top of the branch page, and then list the branches below that? That'd probably affect several other places as well if the UI is to be consistent.... Just a thought. Let me know what you think.

**Comment by p3lim** [comment]
@ethanbustad What about having an option to show the keybindings text in a panel that could be hidden, and add a keybinding (I suggest `h` for help) to show it again. Would be great for power users.

**Comment by divmain** [comment]
@ethanbustad @p3lim, I've just added a key-binding to toggle display of remote branches.  Let me know if it helps.

**Comment by p3lim** [comment]
Nice addition, I'd love to see that in the tags view as well!

**Comment by divmain** [comment]
It'll be necessary to go back and refactor status and tags view using this new abstraction, to get some of the benefits.  Once done, ideally, it should be trivial to update pieces of the UI (it adds regions for partial sections of the rendered template), or implement uni-directional flow of data for rendering depending on which works best in context.
