### ISSUE TITLE
rm/mv commands

### ISSUE THREAD

**Issue by ehuss** [divmain/GitSavvy#801]
I'd like to be able to remove or move files with GitSavvy.  Is there an existing way to do this?  If not, would you be interested in a PR to add them?

**Comment by stoivo** [comment]
There are no existing way of removing or moving. A PR is allways welcome.

**Comment by gogobd** [comment]
I just came across the same issue, it would be great if GitSavvy could support 'Rename...' or 'Move...' commands even though I don't know if those commands only exist if SideBarEnhancements are installed. Also a 'git: mv' command would be awesome.
PS.: GitSavvy is really cool imho. Thanks for all the good work!

**Comment by randy3k** [comment]
closed by  17f6fb2
