### ISSUE TITLE
local variable 'stdout' referenced before assignment

### ISSUE THREAD

**Issue by alextegelid** [divmain/GitSavvy#81]
Appears in console when a new window is opened since updating to ver 1.2.0

**Comment by divmain** [comment]
@alextegelid - sorry about that, 1.2.1 will fix the issue once its picked up by package control.

**Comment by alextegelid** [comment]
Thanks, I'll pull it from GitHub right away!

**Comment by divmain** [comment]
There was a typo, so use 1.2.2.  Thanks for giving me the heads-up.

**Comment by alextegelid** [comment]
Will do, thanks!
