### ISSUE TITLE
Show hook output during commit, push, etc.

### ISSUE THREAD

**Issue by tomv564** [divmain/GitSavvy#812]
Thanks for this plugin, especially the interactive staging support is a huge win.

Unfortunately I lose a lot of time due to pre-commit hooks running a full lint and test suite (not my choice). When I press `ctrl+enter`, all GitSavvy shows is `GitSavvy Make Commit` in the status bar for a half minute until this hook completes - there is no UI to show what work is being done in the background. (I do get the output at the end when the commit completes or fails).

I did some work capturing `stdout` or `stderr` output into the output panel while the hook is running. Is this something you would be interested in? I'll add a demo gif in about a day.

**Comment by asfaltboy** [comment]
Thank you for the kind words @tombv564 ! I would say that if there's a use case, we can always add a toggle to enable the stream, or even default to it if there's little to no performance hit.

Please submit a PR and we can discuss the details.

**Comment by tomv564** [comment]
Added some screen recordings to PR #813

**Comment by randy3k** [comment]
#813 is merged.
