### ISSUE TITLE
GitSavvy hangs when using ControlMasters for SSH

### ISSUE THREAD

**Issue by cdloh** [divmain/GitSavvy#814]
So I've managed to track down an issue that causes GitSavvy to hang after any SSH use.

Steps to reproduce

1. Have a SSH config that uses ControlMasters
eg
```
ControlMaster auto
ControlPath ~/.ssh/master-%r@%h:%p
ControlPersist 120s
```

2. Commit and push changes using GitSavvy on a repo that uses SSH
3. GitSavvy will then hang on any next actions. Eg trying to bring the DIFF screen up will not happen until the ControlMaster times out. Then all of the actions that you asked will happen at once. Ie multiple diff windows.

Sublime Version: Build 3143
Git Version: 2.13.0
OS: OS X El Capitan
Plugin Version: 2.16.5

**Comment by stoivo** [comment]
You are writing SublimeGit, this is GitSavvy. Are you sure you are in the correct repo?
If you are on the correct repo, what's your os and version?

**Comment by cdloh** [comment]
Gah sorry. Long day. I am indeed using GitSavvy. I'll fix my original issue.

OS: OS X El Capitan
Plugin Version: 2.16.5

**Comment by stoivo** [comment]
Can you explain more about your setup?
how do you use ControlMaster to send git commands?

**Comment by stoivo** [comment]
Feel free to reopen
