### ISSUE TITLE
Show diff view also when when committing unstaged files

### ISSUE THREAD

**Issue by m-sostero** [divmain/GitSavvy#815]
When files are staged before they are committed, the `COMMIT` tab shows a complete diff commit view.

GitSavvy should allow to show the same view when doing ` [C] commit, including unstaged`; at the moment this action makes it look like nothing is being committed, and makes it harder to see what the commit diffs are.

**Comment by stoivo** [comment]
Thanks for reporting, is was an issue and will be fixed in #816

**Comment by stoivo** [comment]
it is merged and will be released in the next release.
