### ISSUE TITLE
command-enter won't work

### ISSUE THREAD

**Issue by lewisl** [divmain/GitSavvy#819]
The default key mapping of sublime text assigns command-enter (SUPER-enter) so I can never commit anything.  It is very hard to remove a mapping--provision is only made for reassigning a key, but in this case I think command-enter needs to be "free".

This is very bizarre.  If this happened to everyone no one could use gitsavvy.  But, it is only happening to me.  I have a completely stock sublime text with some packages installed.

Flummoxed.  gitsavvy is useless to me.

If you encounter a bug, please check for an open issue that already captures the problem you've run into.  If it doesn't exist yet, create it!

Please include the following information when filing a bug:

- Sublime Text version number
- Git version number
- OS type and version
- Console error output
- A description of the problem.
- Steps to reproduce, if possible
- If the bug is caused by a failing command, [include a debug log](docs/debug.md#providing-a-debug-log).

**Comment by lewisl** [comment]
So, the problem is simple, but I am not sure how to get around how I work.

I always have a terminal open to the current working directory of the project for testing and experimentation with the Julia repl running. 

But, gitsavvy wants a terminal, too--it starts using the same one, and tries to do git commands in Julia--doesn't work so well.

It's a wonder any part of gitsavvy works in this context, but lots of it does.  I was able to do a quick commit with a single line message.

Any suggestions on how to keep gitsavvy from colliding with the terminal instance I am using for testing?

there are a lot of datafiles used with the program so I don't want to run at some other directory level because then every file reference would need a complete path.

**Comment by lewisl** [comment]
I installed "fix Mac path" thinking that would help--it didn't.

I've uninstalled "terminal" package because I don't use it.  But, had no effect.  Reinstalled it.

So, I am stumped.

**Comment by stoivo** [comment]
Please submit this with the issue 

Please include the following information when filing a bug:

- Sublime Text version number
- Git version number
- OS type and version
- Console error output
- A description of the problem.
- Steps to reproduce, if possible
- If the bug is caused by a failing command, [include a debug log](docs/debug.md#providing-a-debug-log).

**Comment by randy3k** [comment]
I am lost, why it has anything to do with Julia? A set of reproducible steps would be helpful

**Comment by lewisl** [comment]
Here you go:  resubmitted:

Sublime Text version number: Version 3 build 3143
Git version number: 2.8.0
OS type and version: MacOS High Sierra 10.13.1
Console error output: none
A description of the problem: below
Steps to reproduce, if possible: modify a file; stage it; commit it
If the bug is caused by a failing command, include a debug log.

The default key mapping of sublime text assigns command-enter (SUPER-enter) so I can never commit anything. It is very hard to remove a mapping--provision is only made for reassigning a key, but in this case I think command-enter needs to be "free".

This is very bizarre. If this happened to everyone no one could use gitsavvy. But, it is only happening to me. I have a completely stock sublime text with some packages installed.

Flummoxed. gitsavvy is useless to me.

If you encounter a bug, please check for an open issue that already captures the problem you've run into. If it doesn't exist yet, create it!

Why mention Julia:  it is not the language at all.  I run the Julia repl in terminal opened in the same directory as the code project. I noticed that many git commands had been attempted to be run in the Julia repl (clearly that could not work).  I assumed that gitsavvy was opening a terminal instance to pass command strings to git.

Thanks.

**Comment by randy3k** [comment]
Do you hit `SUPER-Enter` in the Commit View like this?
![screen shot 2017-11-30 at 1 53 21 pm](https://user-images.githubusercontent.com/1690993/33449129-dc8383aa-d5d5-11e7-9583-54ad5848df22.png)

What I don't understand is that you are saying that GitSavvy is sending git commands to the REPL, which GitSavvy never does. GitSavvy runs git commands in the background via `subprocess.Popen`.

**Comment by lewisl** [comment]
Yes.  I think the problem is that sublime's default key mapping is preventing gitsavvy from receiving the SUPER-enter.

The confusion with Julia repl being opened was resolved.  Contrary to above poster, a bunch of git commands were sent to the open terminal.  I think this was caused by installed gitsavvy and using it without restarting sublime text.

After restarting sublime text that has never happened again.

**Comment by randy3k** [comment]
TBH, I still don't understand your issue. Could we consider your issue be resolved?

**Comment by lewisl** [comment]
No.  It is not resolved.  It is impossible to commit by pressing SUPER-enter.

What is hard to understand?  I have a default keymap and nearly default settings. 

Something is blocking gitsavvy.  I can only commit with "quick commit."

**Comment by randy3k** [comment]
Did you map any commands to `SUPER-enter`? Could we report the result in the console after running `sublime.log_commands(True)` in the console and hitting `SUPER-enter`?

**Comment by lewisl** [comment]
I have default key bindings, but sublime maps SUPER-enter to run a macro:
{ "keys": ["super+enter"], "command": "run_macro_file", "args": {"file": "res://Packages/Default/Add Line.sublime-macro"} },

It turns out you can't make any changes to default keybindings--you can only override with them.  I need to remove this keybinding.

Here is the console after pressing command-enter:

command: run_macro_file {"file": "res://Packages/Default/Add Line.sublime-macro"}

Sure looks like run a macro.

Does gitsavvy provide its own keybindings that override the defaults?  That seems like it would solve the problem.

Thanks for keeping at it. It will turn out to be simple and something stupid that is certainly my fault.

**Comment by randy3k** [comment]
Did you hit the "SUPER+enter" in the commit view? It should trigger [`gs_commit_view_do_commit`](https://github.com/divmain/GitSavvy/blob/dd8e962d9db5e3454931a871064b033877485d66/Default%20(OSX).sublime-keymap#L9). I see no reason why it is not triggered.

**Comment by lewisl** [comment]
Here is the console output when pressing command-enter while on the commit tab generated by gitsavvy:

>>> sublime.log_commands(True)
command: run_macro_file {"file": "res://Packages/Default/Add Line.sublime-macro"}

**Comment by randy3k** [comment]
How about the value of [`commit_on_close`](https://github.com/divmain/GitSavvy/blob/dd8e962d9db5e3454931a871064b033877485d66/GitSavvy.sublime-settings#L253)? Did you ever change it?

**Comment by lewisl** [comment]
I did not change it so "commit_on_close": false

Maybe I should just change it to true and forget about command-enter.  This would match how sublimegit works.  Not as nice as gitsavvy but this particular operation is fine as done by sublimegit.

I am happy to make this change; I have no attachment to command-enter.  I am just surprised that more Mac users haven't encountered this with the default key mapping of sublime text 3.

If no one has anything else to suggest, I'll change commit_on_close and we can resolve this as it really seems to be a sublime key mapping issue.

**Comment by randy3k** [comment]
It is really odd that it didn't trigger `gs_commit_view_do_commit`

A solution to try is to define GitSavvy command manually (though I don't understand why it is necessary unless another package has override this).
```
    {
        "keys": ["super+enter"],
        "command": "gs_commit_view_do_commit",
        "context": [
            { "key": "setting.command_mode", "operator": "equal", "operand": false },
            { "key": "setting.git_savvy.get_long_text_view", "operator": "equal", "operand": true },
            { "key": "setting.git_savvy.commit_on_close", "operator": "equal", "operand": false }
        ]
    }
```

**Comment by lewisl** [comment]
So, here is something really stupid.  In looking up with Super-enter is on macOS, I am told that it is command-enter.  Is this wrong?  I tried lots of combinations:

I installed Bound Keys package which lists all bound keys for all installed packages and identifies conflicts.

Below are the relevant key bindings it lists for gitsavvy (there are more but don't involve super-enter)

Note that SendText overrides super-enter.  This could be why random commands were sent to terminal.

WOW--that was it.  I disabled SendText and super-enter worked in gitsavvy.

**_Sheepish apologies_**.  It's been months and months since I've used send text.  really isn't very helpful over copy/paste.  Guess I'll uninstall it.

Call this resolved.  I apologize for bothering everyone.  At least this explains all the symptoms I saw.

GitSavvy key bindings - …ion Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package (Default (OSX).sublime-keymap) |
 ________________________________________________________________________________________________________________________________
|super+enter              |gs_commit_view_do_commit |                         |Default, *SendText*                               |
|super+s                  |gs_commit_view_sign      |                         |Default                                           |
|super+enter              |gs_diff_stage_or_reset_h…|                         |Default, *SendText*                               |
|super+backspace          |gs_diff_stage_or_reset_h…|reset: True              |Default                                           |
|super+enter              |gs_add_edit_commit       |                         |Default, *SendText*                               |
|super+enter              |gs_help_goto_link        |                         |Default, *SendText*                               |
|super+backspace          |gs_help_goto_previous    |                         |Default                                           |
|super+z                  |gs_inline_diff_undo      |                         |Default                                           |
|super+enter              |gs_edit_view_complete    |                         |Default, *SendText*                               |

**Comment by randy3k** [comment]
Try SendCode https://github.com/randy3k/SendCode instead.

**Comment by randy3k** [comment]
However, if it is caused by SendText, we should see SUPER-Enter triggered send text command, not the add line macro.

**Comment by lewisl** [comment]
I have 2 different machines with different packages installed.  Sorry about that.  But, I fixed it on both.

To close this out, I just wanted to say this is a great app.  

Thanks very much.
