### ISSUE TITLE
Duplicate cursor created after viewing stash

### ISSUE THREAD

**Issue by ddevlin** [divmain/GitSavvy#82]
After viewing a stash, when returning to the status view, a duplicate cursor is created at line 1 column 1. This interferes with further line based actions like reopening the stash. GitSavvy 1.2.0 / Sublime Text Build 3075.

![2015-03-12 11_24_29](https://cloud.githubusercontent.com/assets/912471/6616851/8ba7244a-c8aa-11e4-951c-249c21bcc8b6.gif)

**Comment by divmain** [comment]
Let me try to reproduce this - definitely a bit strange!

**Comment by divmain** [comment]
Thanks @ddevlin, this will be fixed in the next release.
