### ISSUE TITLE
quick amend

### ISSUE THREAD

**Issue by reagle** [divmain/GitSavvy#822]
I'd like amends to be a bit quicker. This could be done with a `quick stage and amend`, or an amend option in the popup following a quick stage.

**Comment by randy3k** [comment]
Agree, it would be useful. For the comment, use `quick stage and fixup` alternative. (Although `fixup` doesn't work if there are unstaged files).

**Comment by stoivo** [comment]
merged into dev. 
This is merged into dev and will be released in the next release. 
Feel free to reopen if it is solved.
