### ISSUE TITLE
Custom commands

### ISSUE THREAD

**Issue by sentience** [divmain/GitSavvy#83]
I frequently want to pull the latest upstream changes to a branch and then re-apply my own unpushed changes. This is done from the command prompt using `git pull --with-rebase`.

I’m able to do this with the SublimeGit package using its support for [custom commands](https://docs.sublimegit.net/customizations.html#customizations-commands).

**Comment by divmain** [comment]
- [ ] take an array of args like `GitCommand#git`
- [ ] support string interpolation for arguments for `{FILE_PATH}` and `{REPO_PATH}`
- [ ] support non-git commands (that nonetheless rely on running in project's root dir)
- [ ] support output to panel or new scratch view
- [ ] accept flag to run as shell command, to support basic sh capabilities

**Comment by yyyc514** [comment]
What is the advantage of an array of args (in this context) vs just a command string?

**Comment by divmain** [comment]
@yyyc514, what comes to mind:

1. Consistency across the app.
2. More explicit arguments without needing to escape spaces and other characters, and having to know how Python, Sublime settings parser, and/or the OS would treat it.
3. Simpler implementation for special keyword interpolation like `REPO_PATH` and `FILE_PATH`.
4. Only a slight hit to UX.

**Comment by yyyc514** [comment]
Why not allow both for simplify and maximum configurability? :-)  Actually I don't think you can stop that... since all you're doing (in the simple case) is simplest case is string concat. :-)  So n/m. :-)

**Comment by max-mykhailenko** [comment]
Will I have ability to run sublime shortcut command (actually another plugin) on every commit view? I have plugin that count coding time in Sublime and I want write it to every commit (https://github.com/max-mykhailenko/memTask)

**Comment by yyyc514** [comment]
Regarding the command class structure I'm thinking:

- ExternalCommand
- GitCommand (ExternalCommand)
- GsSomeRandomViewCommand (GitCommand, RepoPathMixin)
- GsSomeRandomViewCommand (ExternalCommand, CurrentPathMixin)

The thought being you could use ExternalCommand or GitCommand stand-alone (from globals, utils, etc)... and then if you wanted to use them from a view you'd lay in RepoPathMixin or CurrentPathMixin to set the paths properly based on the file you are currently viewing.  Though really GitCommand and ExternalCommand are mixins the way we're using them so perhaps the names should also change to reflect that?

Thoughts?

**Comment by yyyc514** [comment]
Here is what I've written and started using until we have something better built-in:

https://github.com/yyyc514/Tint

It opens a virtual terminal inside a Sublime tab.  Similar to Glue (https://packagecontrol.io/packages/Glue) but a little different opinion on UX and trying to appear more like a real console than a command bar at the bottom and an editor window. Not saying we should include anything like this (it's a bit too ambitious I think), but just if any one is looking for a solution that works right now.

I did provide an option to configure a custom command and add it to a menu and then launch it in a Tint terminal window.

**Comment by divmain** [comment]
@yyyc514 Tint looks really neat!  For inspiration, you could also look at [SublimeREPL](https://github.com/wuub/SublimeREPL), which does some really interesting things.  I like the idea of a programmable terminal for Sublime though, beyond what the built-in terminal will do.

@max-mykhailenko - it may be possible to expose certain functionality via specific injection points.  This will be unrelated to this ticket, however, so you could open a new issue with a full explanation of what you'd be looking for?
