### ISSUE TITLE
Missing support for the new sublime-color-scheme format crashes GitSavvy

### ISSUE THREAD

**Issue by deathaxe** [divmain/GitSavvy#834]
Sublime Text 3154+ introduces a new JSON based `*.sublime-color-scheme` format. All default color schemes were converted to this new format. This seems to be the reason for GitSavvy's ThemeGenerator to crash if the inline diff command is called from the git status dashboard, if such a new color scheme is selected.

GitSavvy must check the file format of the active color scheme and decide how to create the inline diff theme. The new format makes things even easier as you just need to create a `*.hidden-sublime-color-scheme` with only the rules needed for inline diff. It is no longer required to duplicate the whole color scheme and apply that to the view.

### Specs

- Sublime Text 3156
- Git 2.15.1
- Windows 10 x64 1703

### Console log

```
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
Traceback (most recent call last):
  File "C:\Apps\Sublime\Data\Packages\GitSavvy\core\commands\inline_diff.py", line 38, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(**kwargs), 0)
  File "C:\Apps\Sublime\Data\Packages\GitSavvy\core\commands\inline_diff.py", line 63, in run_async
    self.augment_color_scheme(diff_view, file_ext)
  File "C:\Apps\Sublime\Data\Packages\GitSavvy\core\commands\inline_diff.py", line 98, in augment_color_scheme
    themeGenerator = ThemeGenerator(original_color_scheme)
  File "C:\Apps\Sublime\Data\Packages\GitSavvy\common\theme_generator.py", line 46, in __init__
    self.plist = ElementTree.XML(color_scheme_xml)
  File "./python3.3/xml/etree/ElementTree.py", line 1356, in XML
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```

**Comment by stoivo** [comment]
It is already in dev branch. 
https://github.com/divmain/GitSavvy/pull/830

**Comment by deathaxe** [comment]
Ah, cool. Just checked the issues and PRs here and therefore didn't see it.
