### ISSUE TITLE
Refresh status page on `git checkout`

### ISSUE THREAD

**Issue by gwenzek** [divmain/GitSavvy#835]
Feature request: Refresh status page on `git checkout`

Note: it works if you're running the checkout from the git status page but not from another tab. 

I usually have the status page open in a pane and I'm working in another pane.
Every time I'm checking out a branch (from the command palette), I have to select the status page to refresh it.
Could we refresh it automatically after a `git checkout` ?

Looking at the [CheckoutCommand](https://github.com/divmain/GitSavvy/blob/f87e7eefc0f81b5c04604c20906fa50cda87c740/core/commands/checkout.py#L40)
`util.view.refresh_gitsavvy(self.window.active_view(), refresh_sidebar=True)`
it seems we only refresh the active view. 
We should hunt for GitSavvy views (at least visible views in the current window) and refresh them.
Maybe we should modify `refresh_gitsavvy` to refresh all views or create a `refresh_all` method.
Other commands (pull, ...) could benefit from this.

WDYT ?

**Comment by randy3k** [comment]
Alternatively, we would refresh the status dashboard when it is focused.
