### ISSUE TITLE
Yubikey/ GPG Card support

### ISSUE THREAD

**Issue by ChainsawBaby** [divmain/GitSavvy#847]
I have recently acquired a Yubikey 4 and only use it for ssh authentication, this seems to cause an issue with GitSavvy, as I use the gpg-agent ssh auth sock
`export SSH_AUTH_SOCK=${HOME}/.gnupg/S.gpg-agent.ssh`

It would be nice of GitSavvy could work with this

- GitSavvy version: 2.16.7
- Sublime Text version number: 3156
- Git version number: 2.16.1
- OS type and version: macos 10.13.2
- Console error output:

> `/usr/local/bin/git push origin master:master` failed with following output:
> 
> ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
> Permission denied, please try again.
> ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
> Permission denied, please try again.
> ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
> git@gitserver.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by stoivo** [comment]
Hei Nordman!

Is the SSH_AUTH_SOCK set in sublime ENV. To check it open the sublime console and run this 
```python
from os import environ; environ
```

**Comment by ChainsawBaby** [comment]
Yeah, it is set in sublime ENV, but to the default MacOS ssh socket
`/private/tmp/com.apple.launchd.wwJJwk261V/Listeners`

**Comment by stoivo** [comment]
So not a direct issue from GitSavvy but rather Sublime's loading of the environment. 


Checkout https://packagecontrol.io/packages/Environment%20Settings

**Comment by ChainsawBaby** [comment]
I tried to set the SSH_AUTH_SOCK env variable, but it still defaults to the default...

**Comment by stoivo** [comment]
Create your own little plugin which does 

```
from os import environ
environ['SSH_AUTH_SOCK'] = '/User/name/.gnupg/S.gpg-agent.ssh'
```

http://robdodson.me/hacking-the-path-variable-in-sublime-text/

**Comment by stoivo** [comment]
Any update?

**Comment by ChainsawBaby** [comment]
@stoivo I think it worked, I will keep testing

**Comment by stoivo** [comment]
Reopen if it don't doesn't
