### ISSUE TITLE
Graph syntax doesn't highlight branches

### ISSUE THREAD

**Issue by revyh** [divmain/GitSavvy#848]
- Sublime Text version number: **ST3  Build 3143**
- Git version number: **2.14.1**
- OS type and version: **Xubuntu 17.10** 
- Theme and Color scheme: **Material-Theme**

Branch (`%d` in `--pretty`) highlight support was added in the https://github.com/divmain/GitSavvy/pull/483. But it doesn't work for me.

![image](https://user-images.githubusercontent.com/668565/35770326-6971a03c-094b-11e8-88d5-e758c0ce4083.png)

**Comment by stoivo** [comment]
Please check if it gets the correct scope with moving the cursor the place and run the command `show scope name`. If it did, then the scope is missing in Material-Theme

Was this ever working for you?  if it did, did you use the same theme?

**Comment by revyh** [comment]
Thx for reply. It's seems that scope is correct
```
git-savvy.graph meta.graph.branch.git-savvy constant.other.git.branch.git-savvy
```
