### ISSUE TITLE
support force push

### ISSUE THREAD

**Issue by jdoconnor** [divmain/GitSavvy#85]
Maybe I missed this, but if there's a way to rebase and and amend commits, force push should also be a valid option.

**Comment by p3lim** [comment]
:+1:

**Comment by 3v1n0** [comment]
Mabe it would be the case to add this also to the status page?

**Comment by stoivo** [comment]
You can add these lines to a sublime-keymap file in sublime's user folder
```json
    {
        "keys": ["P"],
        "command": "gs_push",
        "args": {"force": true}
        "context": [
            { "key": "setting.command_mode", "operator": "equal", "operand": false },
            { "key": "setting.git_savvy.status_view", "operator": "equal", "operand": true },
        ]
    },
```

I don't think we want to add it to the standard keybinding.
