### ISSUE TITLE
[Question] Custom interactive mode commands

### ISSUE THREAD

**Issue by Kristinita** [divmain/GitSavvy#854]
### 1. Briefly

I don't understand, how I can run commands with interactive mode use GitSavvy.

For example, I don't understand, how I can use [**commitizen**](https://www.npmjs.com/package/commitizen).

#### 2.1. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Sublime Text Build 3143,
+ git 2.16.1.windows.4,
+ Commitizen 2.9.6,
+ GitSavvy 2.16.7.

#### 2.2. sublime-commands

my example `Default.sublime-commands` file:

```json
[
    {
        "caption": "Git Commitizen",
        "command": "gs_custom",
        "args": {
            "output_to_panel": true,
            "args": ["cz"],
        }
    },
]
```

### 3. Steps to reproduce

[**I install and set**](https://www.npmjs.com/package/commitizen#conventional-commit-messages-as-a-global-utility) commitizen → I make changes in any file in of my git repository → `git add .` → <kbd>Ctrl+Shift+P</kbd> (<kbd>⌘⇧p</kbd> for Mac) → `Git Commitizen`.

### 4. Expected behavior

If I run `git cz` in any terminal:

```batch
D:\SashaBranchReleaseIt>git cz
cz-cli@2.9.6, cz-conventional-changelog@1.2.0


Line 1 will be cropped at 100 characters. All other lines will be wrapped after 100 characters.

? Select the type of change that you're committing: test:     Adding missing tests or correcting existing tests
? Denote the scope of this change ($location, $browser, $compile, etc.):
 gitsavvy
? Write a short, imperative tense description of the change:
 Demonstration for GitSavvy issue
? Provide a longer description of the change:
 Commitizen works in interactive mode
? List any breaking changes or issues closed by this change:

[master 06e16ab] test(gitsavvy): Demonstration for GitSavvy issue
 2 files changed, 8 insertions(+), 1 deletion(-)
 create mode 100644 messages/2.0.22.txt
```

Commitizen ask question → I input text in console → <kbd>Enter</kbd> → I input text for next question → <kbd>Enter</kbd> → and so on.

### 5. Actual behavior

If I run `Git Commitizen` via command palette, I see panel, but I can't select type of committing change in panel.

![GitSavvy Panel](https://i.imgur.com/WLK0r3q.png)

### 6. Did not help

1. I try to use [**command arguments**](https://github.com/divmain/GitSavvy/blob/master/docs/custom.md#command-arguments), include `{PROMPT_ARG}`, but them doesn't help for me.

Thanks.

**Comment by stoivo** [comment]
Custom commands don't support interactive commands. I would recommend you check out https://packagecontrol.io/packages/TerminalView .

**Comment by Kristinita** [comment]
@stoivo , it Linux/macOS plugin, doesn't support Windows.

Thanks.

**Comment by stoivo** [comment]
You can use this one, and just open a terminal ehennyou want to use it

**Comment by asfaltboy** [comment]
I was just wondering, do you think we can use the code added in githook PR
for something like two-way interactive output?

Though, how would we know that we're promoted for input?

**Comment by stoivo** [comment]
Possibly we could but it's a hard problem by itself. Just at how many different terminals apps which is out there thing to make it interactive. 

With the new live feed you would see that you are propted, but nowhere to enter new inputs. We could open an input panel for input but then the output would disappear. 

I would invert by time in sublimeREPL to run the command.
Something in the lines of this 
```json
  {
    "command": "repl_open",
    "caption": "SublimeREPL: git cz - commitizen",
    "id": "repl_commitizen",
    "args": {
      "type": "subprocess",
      "cmd": [
        "git",
        "cz"
      ],
      "cwd": "$file_path",
      "external_id": "commitizen"
    }
  }
```

**Comment by divmain** [comment]
Poking my nose in here - we decided long ago not to support interactive Git commands.  This was for two reasons:

1. Most use cases where it would be useful would be better solved by adding the feature natively to GitSavvy.
2. It would make the code-base really gnarly and much harder to understand.

With `asyncio` coming to fuller maturity, it should be possible for core functionality would be built on top of async functions.  But this would be a massive refactor, verging on a re-write.  Barring that, I think it will be difficult to support interactivity with any elegance.

**Comment by stoivo** [comment]
I am sorry @Kristinita, 

GitSavvy does not support this interactive prosess. I would recommend you to use wbonds Terminal plugin. Add a custom command which opens your terminal at the project directory and runs you command  `git commitizen`
