### ISSUE TITLE
Is it possible to have clickable links in showed panel?

### ISSUE THREAD

**Issue by kiddick** [divmain/GitSavvy#855]
I am talking about panel invoked via `"show_panel_for"`. Currently panel shows on push to newly created branch so it will be cool to have clickable link for new PR (I am using bitbucket)

**Comment by stoivo** [comment]
GitSavvy won't do it.

Check out these to projects [Open URL](https://packagecontrol.io/packages/Open%20URL) [Clickable URLs](https://packagecontrol.io/packages/Clickable%20URLs)

**Comment by asfaltboy** [comment]
I'd love to get that as well, but I think that under current SublimeText API this behaviour is not yet possible

**Comment by kiddick** [comment]
I think we could use minihtml popup to render output from git.. Though it requires some coding

**Comment by stoivo** [comment]
I have installed Open URL. I click the link and hit `ctrl+u` and it opens. I think that should bee good enough.

**Comment by stoivo** [comment]
Checkout [Clickable URLs](https://packagecontrol.io/packages/Clickable%20URLs)
