### ISSUE TITLE
Add keybindings to switch to cached diff and back

### ISSUE THREAD

**Issue by 3v1n0** [divmain/GitSavvy#856]
When un diff mode to stage lines it could happen that you wrongly (un)stage something you didn't want, and then you need to go back to status and open the (un)cached version of the same diff.

It would be convenient to have keybindings to quickly switch views.

**Comment by stoivo** [comment]
Agree, do you use the diff of the inline diff?
I think this should exist for both but It is interesting to know what you are using the most.

**Comment by 3v1n0** [comment]
I use them both... And, yes. It should be added to the two :)
