### ISSUE TITLE
Automatically determine the target commit for fixup

### ISSUE THREAD

**Issue by mnieber** [divmain/GitSavvy#859]
If you find a mistake in a previous commit, and you correct it in the editor, then it would be convenient to automatically determine which commit must be corrected by fixup. This would work by finding the commit that introduced one or more of the lines you are correcting. If there are multiple candidates, it should allow you to choose.

For example, if your commit history looks like this:

706e64a add introduction of foo.txt report
86d9830 add conclusion of foo.txt report

and you stage a few lines that correct the introduction and run "create fixup",  then the new history should be:

706e64a add introduction of foo.txt report
86d9830 add conclusion of foo.txt report
98b5be8 fixup: add introduction of foo.txt report

**Comment by mnieber** [comment]
I just realized that "it should allow you to choose" doesn't make complete sense. For example, a commit that fixes up both "add introduction of foo.txt report" and "add conclusion of foo.txt report" should never be squashed into "add introduction of foo.txt report". 

On the other hand, it's still informative to see the list of commits that are "corrected" by the staged lines. So maybe we can allow the user to choose the commit to fix up, but also add an "abort" option to this list (in most cases, this is what the user would choose). I suppose pressing `Esc` would also abort.

**Comment by randy3k** [comment]
Maybe it is useful to mark those commits which have modified the staged files.

**Comment by mnieber** [comment]
@randy3k I'm not sure whether I would use that particular variation of this feature much. I do have experience with using a script such as the one I described above (but unfortunately I no longer have access to it), and it saved me quite a lot of time and mental cpu cycles. I would often just stage whatever has changed, knowing that it should all go into 1 and only 1 of the previous commits, run "create fixup" and - if it succeeds - move on. Especially this "blindly committing" allowed for a very smooth workflow.

**Comment by randy3k** [comment]
It is possible that it may fix up an commit which has been pushed, some precaution has to be made to ensure the commit history integrity.

**Comment by randy3k** [comment]
I found this [script](https://github.com/chrisarcand/dotfiles/blob/master/bin/git-autofixup). You could create a [custom command](https://github.com/divmain/GitSavvy/blob/master/docs/custom.md#custom-commands) to invoke this script.

**Comment by mnieber** [comment]
@randy3k Thanks, it kinda works! However, it's lacking in one major aspect: if there are multiple commits that are corrected by the staged changes, then it just picks the first one, instead of aborting with a warning. This means you cannot use this script blindly, and this makes it much less of a time saver (and worse: forces you to think again).

**Comment by randy3k** [comment]
True, you'll need to write your own script then.

**Comment by mnieber** [comment]
Yes, I will :-). The script you posted will be a good starting point, I will post a link here if it's done.

**Comment by mnieber** [comment]
Still very fresh, but it seems to work

https://gist.github.com/mnieber/b88a2f3136aa1f733d96314507935c8d
