### ISSUE TITLE
Stage and commit selected text (hunk) in a file

### ISSUE THREAD

**Issue by irhs** [divmain/GitSavvy#86]
I frequently find that I want to commit certain parts of my modified file, leaving the rest of the changes in working tree. Equivalent of 'git add -p'. With the sublime text2 git plugin I could select text from a file and stage and commit those. 

This feature would be a good addition.

**Comment by alextegelid** [comment]
Try the inline diff view in GitSavvy, that’s what you’re looking for.


—
Alexander Tegelid
070-508 49 90
alex@tegelid.se
—

**Comment by irhs** [comment]
Ah. I missed that. Thanks for pointing out.
