### ISSUE TITLE
How I can checkout a remote branch like a local one

### ISSUE THREAD

**Issue by ellipticaldoor** [divmain/GitSavvy#870]
If I press [e] to toggle display of remote branches and checkout one that is remote it checks it but in detached mode

![image](https://user-images.githubusercontent.com/3449006/36603580-1736ff16-18b3-11e8-85b6-08e402aef494.png)

But if I do it local just works fine

**Comment by randy3k** [comment]
use `create from selected branch` instead of `checkout`.

**Comment by ellipticaldoor** [comment]
Thanks! :)
