### ISSUE TITLE
Allow to unstage changes when amending a commit

### ISSUE THREAD

**Issue by mnieber** [divmain/GitSavvy#876]
In git gui, when you amend a commit, you can unstage some of the changes. This is very handy and would be a good feature for GitSavvy :-). When you amend a commit X, you basically move to the state just before committing X. You see the staged changes for X, are able to unstage them, and commit the new index.

**Comment by stoivo** [comment]
You can do that today.

1. Copy the commit message
2. Run git reset to ref and select the last commit, and select mixed.
3. Commit as usual, past the previous commit

**Comment by mnieber** [comment]
Yes, you're right, I would just have to make a shortcut for it.
