### ISSUE TITLE
Tags view improvements

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#88]
Continuation of #80.

- Suffix remote tags to the local tags section when they exist locally
- Give the same treatment to the remote section(s), only having one section instead of a section for each remote.

**Comment by p3lim** [comment]
Since this is the most related issue already open; did you want me to port the tags view to the new interface paradigm, or are you taking on that task yourself?

**Comment by divmain** [comment]
If you'd like to do it, feel free. Otherwise, I'll pick it up in the next couple of days.

**Comment by divmain** [comment]
TODO:
- [ ] transition `git: tags` view to interface paradigm
- [ ] include tags dashboard in dashboard `TAB` functionality
- [ ] toggle display of remote flags similar to how it works in the Branch dashboard
