### ISSUE TITLE
GitHub Integration 

### ISSUE THREAD

**Issue by hnbeck** [divmain/GitSavvy#882]
Hi, 

I use Sublime 3 Build 3143 on Win10 (all Updates in), installed GitSavvy last Summer (don't find any version number). 
I want to access my repo on https://github.com . I started from a fresh clone of my remote repo (branch origin/master and local master)

I changed a file and staged and commit it, that worked. Then I want to push it and got

> `c:\program files\git\cmd\git.EXE push` failed with following output:
> 
> bash: /dev/tty: No such device or address
> error: failed to execute prompt script (exit code 1)
> fatal: could not read Username for 'https://github.com': Invalid argument
> 

Then after googeling a little bit I added in user config the api token
_{
	"api_tokens": {
         "github.com": "HERE IS MY TOKEN GENERATED FROM GITHUB"
    }
}_

but the error message remains. I think I do something wrong... Thanks for any help :)

Cheers

Hans

**Comment by stoivo** [comment]
Thanks, 

So the setting you set is for api calls. It is used for fetching issues when your repository is private. 

What you need to do is to setup git to save your credentials 
https://help.github.com/articles/caching-your-github-password-in-git/#platform-windows

**Comment by hnbeck** [comment]
Thank you very much. Problem solved :)
