### ISSUE TITLE
Shortcuts / commands to edit keymaps

### ISSUE THREAD

**Issue by bcalik** [divmain/GitSavvy#884]
I'm coming from SublimeGit and shortcuts on status page is a bit different. I could not get used to it.

For example "d" is "diff" in SublimeGit, but in GitSavvy its "discard" shortcut. Everytime I mispress "d" key.

Is there any way to customize shortcuts?

**Comment by randy3k** [comment]
Just look at the sublime-keymap file. You just need to override the keybinding for diff. However, I do suggest you to re-train your muscle memory.

**Comment by bcalik** [comment]
Ok I created [this](https://raw.githubusercontent.com/divmain/GitSavvy/master/Default.sublime-keymap) file on `.../Sublime Text 3/Packages/GitSavvy` path. Then I modified.

It works well, but it still shows the old shortcut in status page. It's not important anyway.

**Comment by stoivo** [comment]
We can add a command to the command panel like `Preferences: gitsavvy Settings`

**Comment by randy3k** [comment]
It is a bit more complex because there are more than one file specifying keybinds, `Default ($platform).sublime-keymap` and `Default.sublime-keymap`.
