### ISSUE TITLE
Ignore custom NeoVintageous escape sequence

### ISSUE THREAD

**Issue by mbger** [divmain/GitSavvy#887]
Hi, 

the `vintageous_friendly` option already does a great job of making NeoVintageous and GitSavvy play well together. However when I define a [custom key mapping to exit the insert mode](https://github.com/guillermooo/Vintageous/wiki/Using-jj-instead-of-Esc) like this

```
{
	"keys": ["k", "j"],
	"command": "_enter_normal_mode",
	"args": {
		"mode": "mode_insert"
	},
	"context": [{"key": "vi_insert_mode_aware"}]
}
```
I run into problems when navigating in GitSavvy dashboards (using `j` and `k` to go to previous / next hunk for example) because this will inevitably throw me out of insert mode. 

Is there a way to prevent GitSavvy to go back to normal mode or to ignore the keymapping when in a GitSavvy dashboard?

**Comment by randy3k** [comment]
You may consider the context key
```
            { "key": "setting.git_savvy.status_view", "operator": "not_equal", "operand": true }
```

i.e.,
```
[
    {
        "keys": ["k", "j"],
        "command": "_enter_normal_mode",
        "args": {
            "mode": "mode_insert"
        },
        "context": [
            {"key": "vi_insert_mode_aware"},
            {"key": "setting.git_savvy.status_view", "operator": "not_equal", "operand": true}
        ]
    }
]
```

**Comment by mbger** [comment]
@randy3k Nice, that did the trick. 👍
