### ISSUE TITLE
Feature Request: Bind q to close the GitSavvy Window

### ISSUE THREAD

**Issue by varmanishant** [divmain/GitSavvy#890]
Would it be possible to bind the key q to quit the `GitSavvy` window? Btw this is a nice plugin!

**Comment by stoivo** [comment]
TLDR; not as a default. 

If you want it you can add this your keybindings
```js
  {
    "keys": ["q"],
    "command": "close",
    "context": [
      { "key": "setting.git_savvy.status_view", "operator": "equal", "operand": true },
    ]
  },
  {
    "keys": ["q"],
    "command": "close",
    "context": [
      { "key": "setting.git_savvy.branch_view", "operator": "equal", "operand": true }
    ]
  },
```
This is for  branch interface and for status. There are currently no way to do this call all GitSavvy views.

Hope this helps
