### ISSUE TITLE
Feature Request: Highlight the lines?

### ISSUE THREAD

**Issue by varmanishant** [divmain/GitSavvy#891]
This is just a cosmetic thing from `Emacs`'s `Magit`. Would it be possible to highlight the cursor line/blocks when you are hovering over files/headings (`staged`, `unstaged`) etc? Mapping `s` to stage/unstage the block would be even more nice! That would make it more obvious and beautiful than the simple cursor. 

If this is not too hard, I would like to see if I can do this!

**Comment by stoivo** [comment]
hovering? with the mouse?

Give it a try 👍  just open the PR when you have something WIP so we can comment and work it out together. 

We LOVE💓💖💗💘 contributions

**Comment by asfaltboy** [comment]
Meanwhile, if you would like to highlight a line a caret is on, it's possible by enabling the following in your Sublime Text preferences:

    "highlight_line": true

Source: http://wesbos.com/sublime-text-5-visual-tweaks/

**Comment by asfaltboy** [comment]
@varmanishant did the above resolve your request? If so, please close the ticket.

Or if not, could you kindly clarify to which GitSavvy view/command should the highlight & shortcut be added?

**Comment by varmanishant** [comment]
Ok, I will close this know.

**Comment by 3v1n0** [comment]
I've this parameter set for my sublime text and works fine, but it doesn't for Gitsavvy views (such as graph, where it's quite important).

Is this related to #552?

**Comment by stoivo** [comment]
Try so set in in the graph settings specifically. Go to teh graph and hit `ctrl/super + ,`

**Comment by 3v1n0** [comment]
Nope, no difference...

**Comment by stoivo** [comment]
Please open a new issue and add some platform details and some screenshots

**Comment by kaste** [comment]
Thanks @asfaltboy 

I think `"highlight_line": true` should be the default for the `graph view`. I currently use 

```
    "highlight_line": true,
    "gutter": true,
    "margin": -20,
```

![image](https://user-images.githubusercontent.com/8558/48573947-2a1a9800-e90e-11e8-9022-b0378954bd76.png)

Feels almost like norton commander 🚶

**Comment by 3v1n0** [comment]
Ok, this works for me... `Preferences -> Settings - Syntax Specific` plus your snippet works for me, only `highlight_line` wasn't working here.

**Comment by kaste** [comment]
Yeah, highlight_line without gutter is no thing in Sublime. But then you need a negative margin to make it look better. 🙄

**Comment by stoivo** [comment]
@kaste, looks better then the default. @asfaltboy @randy3k  should we change the default
