### ISSUE TITLE
Log panel for push prints binary string representation

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#897]
I just pulled latest `dev` branch locally, and `live_panel_output` is turned off for me.

On commit 7a0a38f in dev, output of push command is this:

```
> /usr/bin/git push --set-upstream asfaltboy test-me:test-me
b'Branch test-me set up to track remote branch test-me from asfaltboy.\n'
b'To github.com:asfaltboy/GitSavvy.git\n * [new branch]      test-me -> test-me\n'
```

However on master it is:

```
> /usr/bin/git push --set-upstream asfaltboy test-master:test-master
Branch test-master set up to track remote branch test-master from asfaltboy.

To github.com:asfaltboy/GitSavvy.git
 * [new branch]      test-master -> test-master
```

I have a feeling the regression is due to the [_"live panel"_ related changes in **git_command.py**][1] and the newly defined function [`panel_append` in **log.py**][2].

I would probably consider this a blocker for #893 

[1]: https://github.com/divmain/GitSavvy/blob/dev/core/git_command.py#L202-L218
[2]: https://github.com/divmain/GitSavvy/blob/dev/common/util/log.py#L9-L11

**Comment by stoivo** [comment]
a blocker!

**Comment by randy3k** [comment]
> I would probably consider this a blocker for #893

:+1

**Comment by randy3k** [comment]
#898 still has some bug

When I do `review pull request`, the output is out of sync

```
> /usr/local/bin/git fetch https://github.com/ydsdsa/AlignTab.git patch-1

[Done in 0.36s]From https://github.com/ydsdsa/AlignTab
 * branch            patch-1    -> FETCH_HEAD

```

Relevant settings
```
    "show_panel_for": [
        "commit",
        "apply",
        "fetch",
        "pull",
        "push"
    ],
    "live_panel_output": true
```

**Comment by randy3k** [comment]
Let me close this issue and open a new one.
