### ISSUE TITLE
File status in gutter

### ISSUE THREAD

**Issue by divmain** [divmain/GitSavvy#9]
- [ ] icons for inserted, modified lines
- [ ] icon between lines for removed lines
- [ ] gray out icons when changes are staged

**Comment by p3lim** [comment]
So basically [GitGutter](https://packagecontrol.io/packages/GitGutter)?

**Comment by divmain** [comment]
Ha - pretty much, although I don't think GitGutter disambiguates between stated and unstaged changes in a file.  But perhaps that'd work better as a PR for GitGutter.  I'll close and revisit if necessary.
