### ISSUE TITLE
Unable to delete or push tag

### ISSUE THREAD

**Issue by steventen** [divmain/GitSavvy#905]
- Sublime Text version number: Build 3159 (happens under previous versions also)
- Git version number: 2.14.2
- OS type and version: MacOS 10.13.3
- Console error output:
```
`/usr/local/bin/git tag -d 7 v1.77` failed with following output:

error: tag '7 v1.77' not found.
```
- A description of the problem:
I found the `[d] delete` and `[p] push to remote` commands cannot properly parse the tag. For tags displayed as below in TAGS view:
```
  LOCAL:
    1160e4b17 v1.77
    4a719e149 v1.73
    ... ...
```
`delete` and `push` commands will always grab the last character of the commit id + the tag id (e.g. `7 v1.77`,  `9 v1.73`), but `[l] view commit` command can correct parse and display the tag

**Comment by randy3k** [comment]
It seems that the commands in the tag dashboard have assumed 8-digit hashes. A workaround for you at the moment is to force `core.abbrev` to be 8

```
git config --local core.abbrev 8
```
