### ISSUE TITLE
Windows cmd.exe console pops up

### ISSUE THREAD

**Issue by kaste** [divmain/GitSavvy#909]
Hi 👋 

the most recent version (checked via a fresh install) pops up the famous and annoying Windows console window. This only happens on startup, right after that GitSavvy shows the current branch etc in the status bar. 

I could not get a log, bc it is a startup problem I could not figure out how to enable actual logging fast enough. 

I saw that you don't set `startupinfo.wShowWindow = subprocess.SW_HIDE`. 

https://github.com/divmain/GitSavvy/blob/d7fd1b33e798e3873f384c33f4fed2c8b40fac92/core/git_command.py#L180-L182

I always thought that this is necessary when you set STARTF_USESHOWWINDOW. (I always read that as *I* use SHOWWINDOW so *I* must also provide it.)

On the other hand, that's probably super old code.

**Comment by randy3k** [comment]
We appreciate any contributions. If you can confirm the additional flag fixes the issues, please consider making a pull request. It is the quickest way to have the issue resolved.

**Comment by kaste** [comment]
```
5cd1651527cb4fb882b33c9e5dbed760ba7acb27 is the first bad commit
commit 5cd1651527cb4fb882b33c9e5dbed760ba7acb27
Author: Randy Lai <randy.cs.lai@gmail.com>
Date:   Sat Feb 17 21:01:50 2018 -0500

    Enhancement: check git version

:040000 040000 19c9ae91dc3ba0196c52dbf8bb29a674ccd7321b 839b403bbd0cde79e2be35167f498424797d61e5 M  core
```

https://github.com/divmain/GitSavvy/commit/5cd1651527cb4fb882b33c9e5dbed760ba7acb27

https://github.com/divmain/GitSavvy/blob/5cd1651527cb4fb882b33c9e5dbed760ba7acb27/core/git_command.py#L224

**Comment by randy3k** [comment]
Thanks for pin pointing the issue.

**Comment by kaste** [comment]
I'll do the PR for the credits

**Comment by kaste** [comment]
🤘
