### ISSUE TITLE
Checkout current file commit

### ISSUE THREAD

**Issue by mercurykd** [divmain/GitSavvy#914]
Like git blame current file, git show current file with choice commit

**Comment by mercurykd** [comment]
Command "checkout current file" in git : git checkout HEAD -- file
Need choice commit, example in git : git checkout COMMIT -- file

**Comment by stoivo** [comment]
Use `git: log current file`

**Comment by mercurykd** [comment]
> Use git: log current file

And checkout commit in menu?
This deattached HEAD for all files

git checkout COMMIT -- file 
leads the state of a particular file at the time of the commit, and this file becomes a modified(staged), HEAD NOT deattach

**Comment by stoivo** [comment]
I was thinking `Show file at commit` then copy the section you want

**Comment by stoivo** [comment]
What about one more option in the select?  `git: log current file` -> `Checkout file at commit`

**Comment by mercurykd** [comment]
> What about one more option in the select? git: log current file -> Checkout file at commit

you god damn right (с)

**Comment by randy3k** [comment]
I thing it is also beneficial to enhance the command `git: checkout current file`.

**Comment by stoivo** [comment]
Will be in next release
