### ISSUE TITLE
git: status no longer updating - l, tab, shift+tab don't work

### ISSUE THREAD

**Issue by Chovin** [divmain/GitSavvy#916]
## System Info
- Sublime Text version number: 3143
- Git version number: 2.14.1
- OS type and version: Mac OSx 10.13.3 + Windows 7
- Console error output: none
## A description of the problem.
`git: status` seems to have stopped updating on my windows and mac workstations.
Pressing any button doesn't update the GUI, so I'm not able to use `l` inline diffs, `tab` switch between dashboards, etc.
When I press `s` to stage a file, I see in the footer that it is staged, but the status page doesn't update to show that.

## Steps to reproduce, if possible
1. `cmd+shift+p` > `git: status`
2. press any button

**Comment by randy3k** [comment]
I cannot reproduce it on my computer. Could you try to restart Sublime Text first? We have recently released an update, so your Sublime Text may need a restart.

**Comment by Chovin** [comment]
The update seems to have fixed it! Thank you!
