### ISSUE TITLE
Checkout current file

### ISSUE THREAD

**Issue by NicoSantangelo** [divmain/GitSavvy#92]
Hello!

The only feature I miss from SublimeGit it's the ability to checkout the current active file to HEAD without having to go to the status view.

I've implemented this in GitSavvy like this:

````python
class GsCheckoutCurrentFileCommand(WindowCommand, GitCommand):

    """
    Reset the current active file to HEAD.
    """

    def run(self):
        view_file_name = self.window.active_view().file_name()
        if view_file_name:
            self.checkout_file(view_file_name)
            sublime.status_message("Successfully checked out %s from HEAD." % view_file_name)

````

and in Default.sublime-commands:

````json
{
     "caption": "git: checkout current file",
     "command": "gs_checkout_current_file"
},
````

I didn't add `@util.actions.destructive(description="discard a file")` because it's a direct action against the file.

I don't know if this really is useful or in the roadmap, I didn't make a proper PR because I couldn't decide where to put the command and documentation (my best guess was in `checkout.py`, but I'm not sure).

Great package!

**Comment by divmain** [comment]
Hey @NicoSantangelo, I'm happy to add this myself but would also welcome a PR if you want your name on it.  `core/commands/checkout.py` looks good for the palette command.

One additional note, you can reference `self.file_path` to get the file name, which should normalize the path relative to the repository root, and also allow this to work in inline-diff views.

**Comment by NicoSantangelo** [comment]
Great! I didn't realized that I could use `self.file_path`.
I'll send the PR today (adding the docs).

Thanks
