### ISSUE TITLE
Commit syntax has weird highlighting

### ISSUE THREAD

**Issue by rchl** [divmain/GitSavvy#920]
I see weird violet highlight of first comment line when committing. It shows up when there is something written on first (empty) line and there is no line break between it and the comment.

See the image:
<img width="601" alt="git-commit-highlight" src="https://user-images.githubusercontent.com/153197/38490025-397ed4c4-3be8-11e8-9cef-4e37b8c8c434.png">

S3 b3161
git version 2.15.1 (Apple Git-101)
macOs 10.13

BTW. New S3 builds include syntax for commit messages and other git files. I wonder if it makes sense to use those instead.

**Comment by rchl** [comment]
I found `use_syntax_for_commit_editmsg` to switch to native syntax but it doesn't work exactly as expected. I'll file new bug for that.
Also, regardless of that setting, this bug should still be valid.

**Comment by randy3k** [comment]
the highlight is related to git style guide https://github.com/divmain/GitSavvy/blob/b64a9fccc3e709e7d3b4ffe1c31e94422c8de3b4/GitSavvy.sublime-settings#L127

**Comment by rchl** [comment]
OK, but it's too overzealous in saying there is an problem.

When starting to type the subject there is no empty line added yet so it shouldn't indicate a problem at that point. It only should do that when there are at least two lines of text added at the start of the document, without line break in between.

That would also fix the case when there is only commit summary without any message in the body - I think that is equally valid and shouldn't indicate any problem.

**Comment by stoivo** [comment]
When I wrote it I did think there will comment on the 2. line.

**Comment by rchl** [comment]
I've looked at the pull request and I'm not sure it addresses the problem the way I would humbly expect.

The comments themselves are from git and and are not included in the final commit message. So IMO they should be treated more like not being there at all instead of ignoring first comment line specifically. Basically handle the commit view as if the comment would not be there at all. Then we would have rules like:
a) if there is only one line of message (summary) - OK
b) if there is summary + empty line - WRONG - highlight second line
c) if there is one line of summary + empty line + line with commit message - OK

**Comment by rchl** [comment]
Seems to work OK.

Small, a bit contrived problem found - after removing all the commented out lines, highlighting no longer triggers when there are two lines with text without empty line in between.

**Comment by stoivo** [comment]
Ok. That will be fixed in the next release :) 
Thanks  for testing and reporting
