### ISSUE TITLE
Visual Studio Code aka VSCode

### ISSUE THREAD

**Issue by franciscolourenco** [divmain/GitSavvy#930]
An issue to assess interest / viability of VSCode support. 
Leave a thumbs up if you are interested.

**Comment by braver** [comment]
Seriously? That makes no sense at all. A plugin like this leans heavily on the API's provided by the editor it runs in. You'll also noticed it's 97.1% Python.

**Comment by franciscolourenco** [comment]
@braver you can call it a VSCode port if it makes more sense to you.

**Comment by braver** [comment]
- Doesn't VS Code already have most of the features of GitSavvy built in + it has GitLens.
- Still doesn't make sense to "port" it. What would you be porting?

**Comment by franciscolourenco** [comment]
> Doesn't VS Code already have most of the features of GitSavvy built in + it has GitLens.

No

> Still doesn't make sense to "port" it. What would you be porting?

The functionality and great UI

**Comment by braver** [comment]
> No

I think for this to  make sense you should specify what you're missing because basically the correct answer here is "yes".

> The functionality and great UI

Neither exists without the SublimeText API's. You going to port them too?

**Comment by franciscolourenco** [comment]
> I think for this to make sense you should specify what you're missing because basically the correct answer here is "yes".

There are so many features missing that listing only a few is not fair, but here are some:

- Status panel in editor
- Hunk staging
- Undo staging
- Interactive rebase in editor
- Commands / Keyboard shortcuts for basic things
- ...

> Neither exists without the SublimeText API's. You going to port them too?

VSCode has an API too. Is there any fundamental API functionality missing?

**Comment by braver** [comment]
Ok, that clears something up for me. Doesn’t VS Code have a forum to discuss creating new plugins? This issue tracker is a weird place for that.

**Comment by franciscolourenco** [comment]
Feel free to suggest a better place

**Comment by franciscolourenco** [comment]
For people migrating to VSCode, some open issues with the intention of bringing VSCode closer to gitsavvy in terms of usability:
https://github.com/Microsoft/vscode/issues/48964
https://github.com/Microsoft/vscode/issues/48965

**Comment by 3v1n0** [comment]
Probably a way to get this working in vscode and any $EDITOR, could be to transform this into a command line tool, with an API that could be used by external editors and by this extension too

**Comment by stoivo** [comment]
That is an interesting idea but id requires work.

**Comment by stoivo** [comment]
If the plan is to make it run in a terminal 100% we need to implement everything in asci. We could take advantace of built in panes.

**Comment by 3v1n0** [comment]
Well since there's nothing great as Gitsavvy is that can be used in cli, it would be cool to have such interface too... So the idea is to create a library that performs the actual operations in python, reusing what is possible of the current codebase + a UI that is different for CLI, sublime, vscode or $ANYEDITOR

**Comment by asfaltboy** [comment]
While I would love to see support for similar features in VS Code, I down-voted this ticket simply because GitSavvy is a smaller project managed by volunteers, as opposed to the multiple teams that VS Code has at their disposal. If this proposal should be filed anywhere it's at a VS Code git plugin (or core repo, wherever their VCS code is hosted).

**Comment by stevage** [comment]
Just a (pointless) vote here. GitSavvy is so good that even though I migrated to VS Code a while ago, I basically use Sublime+GitSavvy as my Git tool. I really love the keyboard driven workflow, staging hunks with keyboard, opening pull requests etc.

I wonder if a KickStarter would be appropriate?

**Comment by franciscolourenco** [comment]
@stevage I'm currently doing the same. It's not as fast though, I find myself accidentally using sublime for editing instead of VSCode.

**Comment by rpbaptist** [comment]
I jumped ship to VS Code just recently, since Sublime Text with LPS and Elixir LS, GitGutter ended up using 10GB RAM within 30 minutes and 20GB RAM by the end of the day.

I was searching for something like GitSavvy. Turns out there's nothing like it. I understand the application is entirely different, but wanted to voice support for such an integration and am willing to pay for it. GitSavvy is just so good.

**Comment by franciscolourenco** [comment]
@rpbaptist have tried edamagit? How good is it compared to GitSavvy?

**Comment by rpbaptist** [comment]
I've been using it today. It's missing a lot of features compared to GitSavyy. I'm mostly missing staging hunks visually and the git panels don't appear to be refreshing.

Inspired by @stevage I disabled the language server in Sublime and using it purely as a git tool now.

**Comment by franciscolourenco** [comment]
@rpbaptist disabled the linguage server? What do you mean and achieve with that? I've also been using Sublime as a glorified git interface for the past couple of years..

**Comment by rpbaptist** [comment]
The LSP package in combination with LS Elixir in a big repo caused major memory leakage or bloat.

I just disabled the packages in Sublime to make it learner now. I really wished I could stick with it, but it's untenable.

So I disabled a bunch of packages via package manager and I can keep it running in the background for GitSavvy.

**Comment by lewisl** [comment]
Assume this won't happen.  It may be too much work, and not worth it, to do in VS Code.  The beauty of magit (emacs) and GitSavvy are that the full UI and results display are done in edit windows.  It makes everything super obvious and very convenient.  But, everyone has other work to do and there are plenty of satisfactory ways to use git these days.  Just wanted to give pat on the back to GitSavvy authors:  I love it in SublimeText.

**Comment by kaste** [comment]
Thanks man!  💕

**Comment by mercurykd** [comment]
definitely need to make a separate product, with subsequent integration into code editors via api
