### ISSUE TITLE
Bad call flags in PyCFunction_Call

### ISSUE THREAD

**Issue by dufferzafar** [divmain/GitSavvy#931]
If you encounter a bug, please check for an open issue that already captures the problem you've run into.  If it doesn't exist yet, create it!

Please include the following information when filing a bug:

- Sublime Text version number
`3161`

- Git version number
`2.17.0`

- OS type and version
`Linux dufferZafar-Dell 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

- Console error output

```
Please report this error to GitSavvy:

Bad call flags in PyCFunction_Call. METH_OLDARGS is no longer supported!
```

**Comment by asfaltboy** [comment]
3161 seems to be [a sublime dev build](http://www.sublimetext.com/3dev). Possibly regression introduced in it that breaks some python APIs on Linux?

@dufferzafar could you try [the stable sublime release from here](http://www.sublimetext.com/3)?

**Comment by stoivo** [comment]
ping @dufferzafar

**Comment by dufferzafar** [comment]
Sorry. Pretty busy right now, but the semester ends tomorrow, so I'll look into this at this weekend. Promise!

**Comment by dufferzafar** [comment]
I'm now using build 3164. Haven't received this bug ever again. I think you could close this as "couldn't reproduce" or something.

If it occurs again, I'll make sure I attach a debug log.
