### ISSUE TITLE
Option to disable length check in commit message

### ISSUE THREAD

**Issue by tobia** [divmain/GitSavvy#938]
Is it possible to disable the length highlighting in the commit message view?

![git_message](https://user-images.githubusercontent.com/48756/39587656-51caac18-4efa-11e8-8f43-0be8b777c4ac.png)

Is there an option to do so? Can I override a syntax file in my User folder?

**Comment by stoivo** [comment]
It is called pedantic
Check this
https://github.com/divmain/GitSavvy/blob/1196f7819ebbc2b8de71222481c23ea58b4553ec/GitSavvy.sublime-settings#L127-L142

I would encourage you yo use it. Maybe you want to loosen on some of them.

**Comment by tobia** [comment]
No way, how did I miss it!? Sorry for the noise and thanks a bunch for the plugin.

**Comment by stoivo** [comment]
No problem, sometimes it's nice with some issues which don't require more than a reference to docs and settings.
