### ISSUE TITLE
(Github) pagination stops after 2nd page

### ISSUE THREAD

**Issue by asfaltboy** [divmain/GitSavvy#944]
- Sublime Text: dev.15184e3
- Git version: 2.16.2
- OS: MacOS High Sierra 10.13.4 (17E202)
- Console error output: -

When iterating over many Github repository forks, in a popular repo, the 2nd page ">>> next page" link leads to an empty quick panel with the "<<< last page" choice.

- Steps to reproduce:
  * clone https://github.com/django/django
  * open in sublime text and run "github: add fork as remote"
  * iterate over the first two page using the ">>> next page" (last quick panel option)

The issue seems to be with the next link header regex parser:
```python
page1_link_header = '<https://api.github.com/repositories/4164482/forks?per_page=100&page=2>; rel="next", <https://api.github.com/repositories/4164482/forks?per_page=100&page=141>; rel="last"'

page_2_link_header = '<https://api.github.com/repositories/4164482/forks?per_page=100&page=1>; rel="prev", <https://api.github.com/repositories/4164482/forks?per_page=100&page=3>; rel="next", <https://api.github.com/repositories/4164482/forks?per_page=100&page=141>; rel="last", <https://api.github.com/repositories/4164482/forks?per_page=100&page=1>; rel="first"'
```

**Comment by stoivo** [comment]
Close because it's merged into dev
