### ISSUE TITLE
Ability to pull remote branch on branches page

### ISSUE THREAD

**Issue by cdloh** [divmain/GitSavvy#949]
Presently if your local branch tracks a remote branch you can check it out on the branches page but then you have to manually run the pull command outside of the branches page or do a fetch and then merge into the active branch.

It'd be great if there could be a keyboard shortcut to do a git pull

**Comment by cdloh** [comment]
Is there a way to add it to that view?

**Comment by cdloh** [comment]
Ah great I just add the context to it. Thanks mate!

**Comment by stoivo** [comment]
Great awesome I could help!
