### ISSUE TITLE
Show reverse diff for 'checkout file at commit'

### ISSUE THREAD

**Issue by kaste** [divmain/GitSavvy#955]
For the new command `GsCheckoutCurrentFileAtCommitCommand` you currently show the standard commit info in the bottom panel. I think it would be nicer to show the reverse patch here. 

This is esp. obvious comparing HEAD to workspace. E.g. you would see which lines will be removed if you checkout that commit. (Basically `git diff -R <commit> -- <file>`.) Without the '-R' it's a bit confusing. 

Would you consider a PR here?

**Comment by stoivo** [comment]
Yes, but only for the checkout command.

All you need to do is to define on_highlight on GsCheckoutCurrentFileAtCommitCommand. Can call some async this methos like GsShowCommitInfoCommand.

PR will be appreciated!

**Comment by asfaltboy** [comment]
I'm going to close this ticket, as the PR has been merged. Feel free to reopen if there are any remaining tasks
