### ISSUE TITLE
Cannot clone a repository from within Sublime Text 3

### ISSUE THREAD

**Issue by liszca** [divmain/GitSavvy#973]
Hi,
I Cannot clone a repository from within Sublime Text 3, from the PowerShell cloning works fine, what could be missing in my Sublime Text configuration? And I looked into the GitSavvy help, but there isn't a command like "git clone", what am I doing wrong?

Greetings
liszca

**Comment by asfaltboy** [comment]
Hi @liszca thank you for reporting the issue; to help narrow it down, kindly provide more info:

- Sublime Text version number
- Git version number
- OS type and version
- A description of the problem.
- Steps to reproduce, if possible
- Do you see any error alerts?
- Any sublime text console errors (hit <kbd>ctrl+~</kbd>)?
- Please provide [a GitSavvy debug log][1]


[1]: https://github.com/divmain/GitSavvy/blob/master/docs/debug.md#providing-a-debug-log

**Comment by liszca** [comment]
Your hint with the console helped, the directory wasn't empty.
