### ISSUE TITLE
AttributeError: 'module' object has no attribute 'log_error'

### ISSUE THREAD

**Issue by oerp-odoo** [divmain/GitSavvy#986]
I tried to use command ` github: open repo`

Please include the following information when filing a bug:

- Console error output:
```python
Traceback (most recent call last):
  File "/home/oerp/.config/sublime-text-3/Packages/GitSavvy/github/commands/open_on_remote.py", line 114, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(remote))
  File "/home/oerp/.config/sublime-text-3/Packages/GitSavvy/github/commands/open_on_remote.py", line 123, in run_async
    open_repo(self.remotes[remote])
  File "/home/oerp/.config/sublime-text-3/Packages/GitSavvy/github/github.py", line 104, in open_repo
    github_repo = parse_remote(remote)
  File "/home/oerp/.config/sublime-text-3/Packages/GitSavvy/github/github.py", line 69, in parse_remote
    util.log_error('Invalid github url: %s' % url)
AttributeError: 'module' object has no attribute 'log_error'
```
- A description of the problem.
When I try to open repository on github with command `github: open repo`, it silently throws error in console, without any indication (in interface) if something went wrong.
- Steps to reproduce, if possible
I had this repo URL set as remote: `git@github.com:/oerp-odoo/oerp-odoo.git`
It seems GitSavvy does not recognize first slash `/ ` after `:`. Though I can push to remote with such URL just fine (even using GitSavvy).

I would say this is two fold problem. First it does not recognize correct URL and when it does not recognize it, its logging functionality (that is supposed to catch incorrect URL) is not working, as seen from traceback.

P.S. Now I modified my URL by removing extra slash, so it is working without problems, but I think logging would fail if someone would write really incorrect URL (they would not see anything unless they would open sublime console).

**Comment by randy3k** [comment]
Thanks for bringing it up.

I think it is a better idea to keep the remote url standardized (who knows how many variations could be here). A fix to the log_error has been pushed through.

**Comment by oerp-odoo** [comment]
Yes I agree. I usually use remote without slash. But this time I
accidentally left it😀
