### ISSUE TITLE
Where is `git stash` command?

### ISSUE THREAD

**Issue by oerp-odoo** [divmain/GitSavvy#992]
I wanted to stash changes, but I don't see  just `git stash` (or equivalent `git stash push`) command as available. Is it named differently or it is missing?
![screenshot from 2018-08-21 10-21-58](https://user-images.githubusercontent.com/7812986/44386790-38822f00-a52c-11e8-934e-bb94ec6af2c8.png)

**Comment by randy3k** [comment]
it seems that `git stash save` has been deprecated in favor of `git stash push` though.

**Comment by oerp-odoo** [comment]
OK thanks. Though did you use command names by following some git documentation with those commands as a reference? Cause I find some differences compared to `git-scm.com` documentation. Like this one (In that site I don't even see command named `save` for `stash`). 

I also noticed that with `stage`. I was expecting to use command `add`, but did not find one. Usually I more frequently see command used `add` instead of `stage` (though they are aliases).

**Comment by randy3k** [comment]
we try to make commands more identifiable while
trying to keep the original name as much as possible. for the case of `git stash`, `save` is now deprecated, it was the subcommand to create stashes. For `add`, i personally find that `stage` is less ambiguous. Of course, we are welcome to any suggestions and PRs on better ways of naming commands.

**Comment by oerp-odoo** [comment]
I agree, that `stage` command was introduced as alias for `add` to make it more clear for people who were confused by command `add`. Though It can backfire, because if you read documentation about git, main command is still `add`, and people might expect that one. But yes we need to stay with one command I guess and be consistent.

Maybe it is possible to add some helper text near command, so it would explain like `git stash save` (same as `apply`) or `git stage` (same as `add`) or something? If it won't cluster interface too much :)
