### ISSUE TITLE
Diff editors get included in the global search results

### ISSUE THREAD

**Issue by franciscolourenco** [divmain/GitSavvy#999]
Would it be possible to automatically exclude the diff buffers from global search results?

**Comment by randy3k** [comment]
I don’t think it is possible unfortunately.

**Comment by asfaltboy** [comment]
I don't think there's a way either, opened [a question in the forums][1]. I'm going to close this ticket for now. If there are any updates, please update back here.

[1]: https://forum.sublimetext.com/t/exclude-a-view-with-a-given-name-from-search-results/39173?u=asfaltboy
